### ISSUE TITLE
仓颉五代无法输入「迟」字

### ISSUE THREAD

**Issue by facaiy** [rime/squirrel#100]
仓颉 [迟： 卜尸人 YSO](http://zidian.911cha.com/bnRp.html)

**Comment by jakwings** [comment]
能上傳你的輸入法配置和所用的倉頡碼表看看嗎？

**Comment by ningchi** [comment]
我是使用的默认码表，请问应该在哪看到码表呢？

**Comment by jakwings** [comment]
這幾個文件：
`~/Library/Rime/installation.yaml`
`~/Library/Rime/default.custom.yaml`
`~/Library/Rime/cangjie5.custom.yaml`
`/Library/Input Methods/Squirrel.app/Contents/SharedSupport/cangjie5.dict.yaml`
`/Library/Input Methods/Squirrel.app/Contents/SharedSupport/cangjie5.schema.yaml`

**Comment by ningchi** [comment]
### 数据
修改后缀为txt才可上传，
[cangjie5.dict.txt](https://github.com/rime/squirrel/files/211058/cangjie5.dict.txt)
[cangjie5.schema.txt](https://github.com/rime/squirrel/files/211060/cangjie5.schema.txt)
[installation.txt](https://github.com/rime/squirrel/files/211059/installation.txt)
这俩文件没有：
~/Library/Rime/default.custom.yaml
~/Library/Rime/cangjie5.custom.yaml

### 效果
![码表上有「迟」字](https://cloud.githubusercontent.com/assets/1112263/14401040/b4130954-fe36-11e5-8442-c6395dc1f22a.png)
![实际录入只有词组](https://cloud.githubusercontent.com/assets/1112263/14401047/ea78957c-fe36-11e5-802c-fe80e39165e0.png)


另外,
我可以关闭词组，只输出单字么？
谢谢。

**Comment by jakwings** [comment]
看來你用的不是官網上提供的最新版本 0.9.26.2，也不是自行編譯的。你可以先到 rime.im 下載最新版試試。安裝前可清除以下文件夾避免之前自動生成的用戶詞典的副作用：
`~/Library/Rime/cangjie5.userdb`

重碼的單字會自動調整，由 `cangjie5.schema.yaml` 中的 `enable_user_dict` 開啓。

不要詞組的話可以自行創建輸入方案解決，主要是把 `cangjie5.dict.yaml` 中的 `use_preset_vocabulary` 設爲 false，或 `max_phrase_length` 設爲 1。
我預制了一個方案，解壓 yaml 文件到 `~/Library/Rime` 再重新部署再選「DIY倉頡五代」即可。
[cj5.zip](https://github.com/rime/squirrel/files/211143/cj5.zip.txt)

**Comment by ningchi** [comment]
@jakwings 谢谢，我使用`brew cask install squirrel`。

手动去官方下载后，问题同样存在。

**Comment by ningchi** [comment]
改为你给的单字方案后就正常了，可录入「迟」。
我应该以前也遇到过类似词组覆盖单字的问题。

总之，谢谢了。

**Comment by ningchi** [comment]
另外，
`cangjie5.schema.yaml`没有找到`enable_user_dict`，是默认值么？

**Comment by jakwings** [comment]
看來我之前看錯文件，總之把 `enable_user_dict` 加到 `translator:` 那一節就好。是默認啓用的。
這裏有大致說明：https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md#%E4%B8%89translator

我用自編譯版本無法復現，官方包的話安裝時要重新登入系統，目前我的電腦長期開着一堆窗口，暫時不方便親測。
你翻頁後能找到單字嗎？

**Comment by ningchi** [comment]
从前到后翻到底，没有找到「迟」。
但先后翻一页，再前翻回去，「迟」就正常显示在第一个位置。

看来可能是显示的问题。

![screen shot 2016-04-10 at 6 23 12 am](https://cloud.githubusercontent.com/assets/1112263/14406769/e6e9d688-fee4-11e5-84cd-5a1a146efcaf.png)
![screen shot 2016-04-10 at 6 23 03 am](https://cloud.githubusercontent.com/assets/1112263/14406770/e6ee7d0a-fee4-11e5-8953-4ddd039d0a80.png)
![screen shot 2016-04-10 at 6 22 47 am](https://cloud.githubusercontent.com/assets/1112263/14406768/e6e9bce8-fee4-11e5-8852-a543458cf1e1.png)

**Comment by jakwings** [comment]
那操作系統的版本呢？

**Comment by jakwings** [comment]
先做個記錄：不曉得是不是 librime 在 squirrel 0.9.26.2 發佈之後加入的 SingleCharFirstTranslation 解決了問題。

**Comment by ningchi** [comment]
~ ❯❯❯ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11.4
BuildVersion:   15E65

希望这些信息有用。

**Comment by lotem** [comment]
先做個記錄。
主幹版本尚未觀察到這個錯誤，但願已經修好了。
