### ISSUE TITLE
[Bug] 點擊"重新部署"後，"用戶設定"中所做更改會復原

### ISSUE THREAD

**Issue by manao29** [rime/squirrel#1003]
**簡要描述 Bug：**
 - 之前在另一台电脑安裝的嘸蝦米輸入方案，在這台新Mac上，进行相同配置且點擊"重新部署"後，"用戶設定"中所做的更改會被復原。即原配置文件10KB，經過設定後變為14KB，點擊"重新部署"想要讓其生效，但會還原成原來的10KB文件，不清楚是否是新版本對配置文件有讀寫保護的原因。

**示例如下**

![CleanShot 2024-12-09 at 12 36 25@2x](https://github.com/user-attachments/assets/d7953fac-8362-493d-a4a5-b6fb851286fb)

**環境**
 - 系統版本： (macOS 15.1)
 - 鼠鬚管版本： (1.0.2)
 - 方案： (嘸蝦米輸入方案，在另一台MacBook可以保存我的所有個性化配置。MacBook的版本也和此Mac一致)

**我試過：**
  - [ ] 更改好之後，不點擊重新部署，Restart電腦，配置好的文件依然會被還原。
  - [ ] 這是個新 Bug，以前真的沒有
  - [ ] 在 Issues（包括已關閉的 Issue） 中未找到相關的報告
  - [ ] 煩情您幫忙查看此問題之具體原因，先在此謝過啦！

**Comment by manao29** [comment]
問題已解決，在每個配置文件的前幾行有一個時間戳的信息，每次替換內容前，需要將這些信息保留一致，修改配置之後保存，不要點擊重新部署，而是退出登錄，再進入桌面即可生效新配置了，謝謝！

**Comment by manao29** [comment]
問題已解決，在每個配置文件的前幾行有一個時間戳的信息，每次替換內容前，需要將這些信息保留一致，修改配置之後保存，不要點擊重新部署，而是退出登錄，再進入桌面即可生效新配置了，謝謝！

**Comment by haoweicrushu** [comment]
@manao29 hello, 想問一下你的嘸蝦米是怎麼配置的呢，我試很久 但沒辦法成功

**Comment by lotem** [comment]
應將修改保存到 [用戶文件夾](https://github.com/rime/home/wiki/UserData) 而非 `build` 子文件夾。

輸入法提供的配置文件如 `squirrel.yaml` 最好以打補丁的方式自定義：
https://github.com/rime/home/wiki/CustomizationGuide#定製指南
