### ISSUE TITLE
[Bug] 在有些机器上，候选会无视`horizental: true`，强行竖向排列

### ISSUE THREAD

**Issue by AlseinX** [rime/squirrel#1004]
**簡要描述 Bug：**
macOS 15.2版本，候选会无视`horizental: true`，强行竖向排列

**預期行爲：**
在设置`horizental: true`后，正常横向排列

**實際行爲：**
无论设置`horizental: true`还是`horizental: false`，都是竖向排列

**環境**
 - 系統版本： (macOS 15.2)
 - 鼠鬚管版本： (1.0.2)
 - 方案： 小鹤音形(如果你用的是自定義或第三方的方案，且該 Bug 可能與方案有關，請提供方案鏈接)
 - [ ] 使用了 Lua： (用了甚麼 Lua 腳本？)
 - [ ] 與其它 App 有關： (哪個 App？)

**我試過：**
  - [ ] 我換了內置的方案（如`朙月拼音`）後問題仍存在
  - [x] 我找到了導致問題出現的具體設置： 可能跟屏幕分辨率有关，问题发生在mac mini m4接显示器（物理分辨率3840x2160，逻辑分辨率1920x1080）时。我在macbook pro 16寸 m1 max上使用同样版本的操作系统，同样版本的鼠须管，用户目录下的配置完全一致（直接拷贝而来），不会触发该bug，候选项会正常横向排列
  - [x] 這是個新 Bug，以前真的沒有
  - [x] 我對原因有一些猜想： (你的寳貴想法)
  - [x] 在 Issues（包括已關閉的 Issue） 中未找到相關的報告

**Comment by LEOYoon-Tsaw** [comment]
horizontal已經無效了，
