### ISSUE TITLE
[feature] 可以配置mac下的显示层次吗？

### ISSUE THREAD

**Issue by Nioy** [rime/squirrel#1006]
**簡要描述 Bug：**
~~我其實沒有遇到Bug~~

**預期行爲：**
使用ishot pro截图时，想在图中添加文字，显示候选字体
**實際行爲：**
使用ishot pro截图时，想在图中添加文字，但是不显示候选字体
**環境**
 - 系統版本： (macOS 14.5)
 - 鼠鬚管版本： (1.0.0)
 - 方案： (如果你用的是自定義或第三方的方案，且該 Bug 可能與方案有關，請提供方案鏈接)
 - [ ] 使用了 Lua： (用了甚麼 Lua 腳本？)
 - [ ] 與其它 App 有關： (哪個 App？)

**我試過：**
  - [ ] 我換了內置的方案（如`朙月拼音`）後問題仍存在
  - [ ] 我找到了導致問題出現的具體設置： (何設置？)
  - [ ] 這是個新 Bug，以前真的沒有
  - [ ] 我對原因有一些猜想： (你的寳貴想法)
  - [ ] 在 Issues（包括已關閉的 Issue） 中未找到相關的報告
  
  
![20241220-112147](https://github.com/user-attachments/assets/d2324bea-11d7-4f9d-b269-5894cf0ac19d)

**Comment by LEOYoon-Tsaw** [comment]
鼠鬚管使用的level已經很高了：

https://github.com/rime/squirrel/blob/master/sources/SquirrelPanel.swift#L41

系統快捷鍵截屏也沒有問題，我不覺得是鼠鬚管方面的問題
