### ISSUE TITLE
使用倉頡輸入法時如何使單字優先顯示

### ISSUE THREAD

**Issue by HongTao628** [rime/squirrel#107]
我在用倉頡時，打出三四個字母，候選欄中詞組優先，然後才是單字，有時要打全碼，單字才能出來，我希望單字先顯示，然後才是詞組，請問如何設置。

**Comment by lotem** [comment]
需要使用 librime 1.2.9 提供的 `single_char_filter` 組件。
https://github.com/rime/brise/blob/master/preset/cangjie5.schema.yaml#L53

**Comment by HongTao628** [comment]
沒用啊，我的cangjie5.schema.yaml 中有這一行，依然不是單字優先。具體應如何設置呢？

**Comment by lotem** [comment]
你用的是什麼版本？公開發行的版本沒有這個組件。

**Comment by HongTao628** [comment]
distribution_code_name: Squirrel
distribution_name: "鼠鬚管"
distribution_version: 0.9.26.1
你的意思是要我自己去編譯嗎？

**Comment by lotem** [comment]
是的，这个功能尚未发布。

**Comment by HongTao628** [comment]
那麼有把這個功能加入新版的計畫嗎？

**Comment by lotem** [comment]
下次發佈會有。

**Comment by Justsoos** [comment]
请问，其他输入法，比如 luna_pinyin_simp.custom 中如此修改配置，是否也有 “单字优先” ？
```lua
patch:
  engine:
    filters:
      - single_char_filter
```
鼠须管敲入“这实际上” 这四个字，竟然要翻7-8页以上才能找到匹配单字，相当累人且可怕 :p

**Comment by lotem** [comment]
Al necrobumper:
拼音裏面多音節詞和單字構成重碼的情況十分罕見，只有 `tuan = 團, 圖案` 等類似情況。因此通常無須使用這個過濾器。

需要翻很多頁才能找到常用字，可能是方案的設置或者詞典出了問題。
用簡化字方案，檢索常用字不需要大量翻頁。
