### ISSUE TITLE
有没有可能使用CapsLock切换中英文时, 让中文状态下Caps灯亮, 英文状态下Caps灯灭?

### ISSUE THREAD

**Issue by blahgeek** [rime/squirrel#109]
按照如下代码配置后, 使用CapsLock切换中英文时, 中文状态下Caps灯灭, 英文状态下Caps灯亮, 有没有可能反过来?

```
  ascii_composer/good_old_caps_lock: false
  ascii_composer/switch_key:
    Caps_Lock: commit_code
```

**Comment by zofari** [comment]
同问。
多数是在英文状态，灯总是亮着很让人抓狂……
其实如果灯一直暗着我也是可以接受的……

**Comment by lotem** [comment]
一樓所求理論上可以做到，然而需要改動大量程序代碼或配置，比如把輸入方案配置爲接受大寫輸入。

二樓所求無法做到。本品不能控制鍵盤的Caps Lock狀態。
您可以使用系統支持的「使用大寫鎖定鍵在輸入方式之間切換」：
在「輸入方式」面板中選取「使用大寫鎖定鍵來在⋯之間切換」選項。選擇「蘋果」選單  >「系統偏好設定⋯」，按一下「鍵盤」，然後按一下「輸入方式」。

**Comment by hiuwo** [comment]
我也覺得這個功能必須啊 大寫時打中文小寫是打英文

> 同问。
> 多数是在英文状态，灯总是亮着很让人抓狂。
> 其实如果灯坏掉一直不亮我也是可以接受的……
> 试过用 Control 或 Shift，但这俩太常用了，很容易误触。
> 也试过 Shift+space，有两个问题：1. 我想要`commit_code`，这个好像无法设置；2. 在 iterm2 可以用，但是会输入空格……
