### ISSUE TITLE
spotlight 如何自动切换到英文？

### ISSUE THREAD

**Issue by tangshi** [rime/squirrel#112]
通常的应用如Terminal alfred可以通过Bundle Identity 来设置，但是spotlight好像就没办法了

**Comment by nelsonlho** [comment]
System Preferences ==> Keyboard ==> Shortcuts 
Choose "Spotlight" on the left
Uncheck "Show Spotlight search"

**Comment by lotem** [comment]
macOS 版本是多少，難道不是 `com.apple.Spotlight` 了？ 
在 Console.app 按 `Squirrel` 關鍵字過濾可以看到正在輸入應用的 Bundle identifier

**Comment by tangshi** [comment]
谢谢 @lotem ，我因为不知道去哪儿找Spotlight的Bundle identifier所以来提了个Issue，根据指点，现在已经找到了，就是com.apple.Spotlight，哈哈
