### ISSUE TITLE
中英文切换能不能使用组合键？

### ISSUE THREAD

**Issue by gatspy** [rime/squirrel#113]
现在用shift切换中英文,但是shift键使用频率太高了啊，特别是在终端下面以及vim里面。现在都是切换系统英文输入和squirrel，感觉这样切换特别麻烦。想输入中文的时候切输入的是字母，想输入英文的时候输入的却是汉字.最好就是能在squirrel中可以设置组合键来实现中英文切换,ctrl+space cmd+space等等
求解决之道。

**Comment by lotem** [comment]
可以用 `Control+Shift+2` 或 `Control+@`。定義在這裏：
https://github.com/rime/brise/blob/master/default.yaml#L127
https://github.com/rime/brise/blob/master/default.yaml#L132

**Comment by gatspy** [comment]
谢谢了。虽然这个组合键有点难按，还是比单shift强多了。适合CAPS改为Ctrl。
这个key_binder可以在custom中patch吗

**Comment by lotem** [comment]
可以自定義。

**Comment by gatspy** [comment]
@lotem 谢谢拉啊。可以关闭了，现在我已经使用的太爽了。

**Comment by jtr109** [comment]
@lotem 你好, 链接已经失效了, 这个文件夹好像已经不存在了. 能烦请你再发个链接吗? 或者 gist 也行. 我希望把中英文切换改成 <kbd>shift</kbd>+<kbd>space</kbd>. 非常感谢!

**Comment by Voleking** [comment]
@jtr109 参照下面在 `default.custom.yaml` 中加入设置
```yaml
patch:
  key_binder／bindings:
    # hotkey switch
    - { when: always, accept: Shift+space, toggle: ascii_mode }
    # - { when: always, accept: Control+Shift+1, select: .next }
    # - { when: always, accept: Control+Shift+2, toggle: ascii_mode }
    # - { when: always, accept: Control+Shift+3, toggle: full_shape }
    # - { when: always, accept: Control+Shift+4, toggle: simplification }
    # - { when: always, accept: Control+Shift+5, toggle: extended_charset }
    # - { when: always, accept: Control+Shift+exclam, select: .next }
    # - { when: always, accept: Control+Shift+at, toggle: ascii_mode }
    # - { when: always, accept: Control+Shift+numbersign, toggle: full_shape }
    # - { when: always, accept: Control+Shift+dollar, toggle: simplification }
    # - { when: always, accept: Control+Shift+percent, toggle: extended_charset }
    # - { when: always, accept: Shift+space, toggle: full_shape }
    # - { when: always, accept: Control+period, toggle: ascii_punct }
```

**Comment by jtr109** [comment]
@Voleking 感谢你的回复, 不过我尝试这样操作好像没有达到预期的效果. 这是[我的配置](https://gist.github.com/jtr109/4d7766839fb6ae3669f34d9f7ca87d73). 另外, 在ascii_composer/switch_key 下也尝试过加入 Shift+space 好像也没有效果.

**Comment by Voleking** [comment]
@jtr109 我试了下，很是奇怪，Control+Shift+space 正常，Shift+space 就会出现你那样的问题，你试下换成其他快捷键试试？

**Comment by jtr109** [comment]
@Voleking 谢谢, 会不会是和全半角切换冲突导致的? 我晚点再尝试一下, 非常感谢!

**Comment by lotem** [comment]
我來認領 `Shift+space` 的問題

**Comment by jtr109** [comment]
谢谢, 期待您的消息! @lotem

**Comment by Voleking** [comment]
对，在 iTerm2 和 Terminal 下不能用组合按键切换

**Comment by xuhdev** [comment]
我在fcitx下也有同樣的問題 “shift+space”

**Comment by lotem** [comment]
似乎把這件事遺忘了

**Comment by Rhonin1220** [comment]
其实还有个小问题，能否把inline_ascii模式和ascii_mode这两个区分开呢？现在全都绑在shift上比较难受，用vim的时候shift很容易误触切换到中文，但是平常用的是时候inline_ascii又十分方便

**Comment by bigogithub** [comment]
在Sublime Text 3中，如果配置了Shift_L: inline_ascii，输入Shift+Tab组合键时，输入Tab的同时也切换中英文，这是目前最烦恼的问题

**Comment by lotem** [comment]
Fixed via http://github.com/rime/librime/commit/707738900168336a75219ae5fc69fa08cc71a4b8
