### ISSUE TITLE
再次遇到编译错误，环境：11.11.6

### ISSUE THREAD

**Issue by 1900forever** [rime/squirrel#115]
已经执行过brew update && brew upgrade
在执行make deps的时候，遇到如下报错：

> ln -fs libleveldb.dylib.1.18 libleveldb.dylib
> ln -fs libleveldb.dylib.1.18 libleveldb.dylib.1
> rm -f libleveldb.a
> ar -rs libleveldb.a db/builder.o db/c.o db/db_impl.o db/db_iter.o db/dbformat.o db/dumpfile.o db/filename.o db/log_reader.o db/log_writer.o db/memtable.o db/repair.o db/table_cache.o db/version_edit.o db/version_set.o db/write_batch.o table/block.o table/block_builder.o table/filter_block.o table/format.o table/iterator.o table/merger.o table/table.o table/table_builder.o table/two_level_iterator.o util/arena.o util/bloom.o util/cache.o util/coding.o util/comparator.o util/crc32c.o util/env.o util/env_posix.o util/filter_policy.o util/hash.o util/histogram.o util/logging.o util/options.o util/status.o port/port_posix.o
> ar: creating archive libleveldb.a
> cp -R thirdparty/src/leveldb/include/leveldb thirdparty/include/
> cp thirdparty/src/leveldb/libleveldb.a thirdparty/lib/
> make[1]: **\* [thirdparty] Error 2
> make: **\* [librime/thirdparty/lib/libopencc.a] Error 2
> ln -fs libleveldb.dylib.1.18 libleveldb.dylib
> ln -fs libleveldb.dylib.1.18 libleveldb.dylib.1
> rm -f libleveldb.a
> ar -rs libleveldb.a db/builder.o db/c.o db/db_impl.o db/db_iter.o db/dbformat.o db/dumpfile.o db/filename.o db/log_reader.o db/log_writer.o db/memtable.o db/repair.o db/table_cache.o db/version_edit.o db/version_set.o db/write_batch.o table/block.o table/block_builder.o table/filter_block.o table/format.o table/iterator.o table/merger.o table/table.o table/table_builder.o table/two_level_iterator.o util/arena.o util/bloom.o util/cache.o util/coding.o util/comparator.o util/crc32c.o util/env.o util/env_posix.o util/filter_policy.o util/hash.o util/histogram.o util/logging.o util/options.o util/status.o port/port_posix.o
> ar: creating archive libleveldb.a
> cp -R thirdparty/src/leveldb/include/leveldb thirdparty/include/
> cp thirdparty/src/leveldb/libleveldb.a thirdparty/lib/
> make[1]: **\* [thirdparty] Error 2
> make: **\* [librime/thirdparty/lib/libleveldb.a] Error 2

**Comment by lotem** [comment]
蘭州沒有貼出錯誤信息

**Comment by 1900forever** [comment]
> 
ld: warning: directory not found for option '-L/usr/local/lib/Release'
ld: warning: directory not found for option '-L/Users/yan/src/squirrel/librime/thirdparty/lib/Release'
Undefined symbols for architecture x86_64:
  "snappy::RawCompress(char const*, unsigned long, char*, unsigned long*)", referenced from:
      leveldb::TableBuilder::WriteBlock(leveldb::BlockBuilder*, leveldb::BlockHandle*) in libleveldb.a(table_builder.o)
  "snappy::RawUncompress(char const*, unsigned long, char*)", referenced from:
      leveldb::ReadBlock(leveldb::RandomAccessFile*, leveldb::ReadOptions const&, leveldb::BlockHandle const&, leveldb::BlockContents*) in libleveldb.a(format.o)
  "snappy::MaxCompressedLength(unsigned long)", referenced from:
      leveldb::TableBuilder::WriteBlock(leveldb::BlockBuilder*, leveldb::BlockHandle*) in libleveldb.a(table_builder.o)
  "snappy::GetUncompressedLength(char const*, unsigned long, unsigned long*)", referenced from:
      leveldb::ReadBlock(leveldb::RandomAccessFile*, leveldb::ReadOptions const&, leveldb::BlockHandle const&, leveldb::BlockContents*) in libleveldb.a(format.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

cp -L librime/xbuild/lib/Release/librime.1.dylib lib/librime.1.dylib
cp: librime/xbuild/lib/Release/librime.1.dylib: No such file or directory
make: *** [librime] Error 1

**Comment by jakwings** [comment]
我觉得你可以再一下看上次的 issue： [#99](https://github.com/rime/squirrel/issues/99#issuecomment-202678218)

**Comment by 1900forever** [comment]
> 
brew unlink snappy
make clean
make deps
make
sudo make install


解决问题，谢谢两位。不知道这个snappy是哪里来的
