### ISSUE TITLE
自行编译版本稳定性问题

### ISSUE THREAD

**Issue by oscargong** [rime/squirrel#127]
自行编译的鼠须管经常有在部署的时候 crash 掉的情况。还常常只有 deploying 的提示没有 deploy complete 的提示…

系统为 macOS 10.12

**Comment by OscarGong** [comment]
具体 crash 时的情形如图
https://cloud.githubusercontent.com/assets/3164826/11433988/89878b4c-9482-11e5-9fa0-4c04b8f92673.png

**Comment by OscarGong** [comment]
https://cl.ly/i09i
https://cl.ly/i0k6
这里是 Crash Report

**Comment by lotem** [comment]
崩潰在第三方庫 libmarisa 裏面，不太好分析。大概知道問題出在反查字典。當時所部署的字典文件有什麼特別之處嘛？比如候選文字那一欄包含某些特殊（控制）字符。
