### ISSUE TITLE
squirrel如何在mac上Debug？

### ISSUE THREAD

**Issue by shz2050** [rime/squirrel#128]
请问squirrel源码如何在mac上Debug，工程在XCode运行成功了，但是无论在哪里打字都唤不起输入法的panel。

是不是输入法的Debug方式有点特殊？求教~

**Comment by lotem** [comment]
調試哪部分呢？
如果是調試輸入方案和算法，可以用 librime 裏面的命令行工具 `rime_api_console`

輸入法的 App 運行起來並不能自動接收到任何文本框裏的鍵盤輸入。首先要把輸入法註冊到系統，然後在系統設置裏啓用，這樣才能用來打字。
然而我沒有辦法在真實環境中調試，因爲輸入法進程一旦不及時響應就會被系統終止。

**Comment by shz2050** [comment]
我本是想调试squirrel与rime库的交互过程，加深理解rime的调用过程。通过阅读squirrel的源码还是学到了好多~谢谢
