### ISSUE TITLE
如何更改menu bar上的輸入法icon？

### ISSUE THREAD

**Issue by tcczz** [rime/squirrel#130]
本人想更換成國旗，已嘗試使用Ukulele進行輸入法拷貝，但不行，謝謝解答！

**Comment by lotem** [comment]
這個不建議您修改。
不過呢，能開心就好。該圖案在源碼中是這個圖形文件：
https://github.com/rime/squirrel/blob/develop/rime.pdf

**Comment by tcczz** [comment]
謝謝，所以我要如何找到源碼的文件夾？Library/Input Methods裏面是空的。
還有，為什麼不建議修改？～

**Comment by OscarGong** [comment]
@tcczz git clone 后修改自行编译

**Comment by StayTherapy** [comment]
在 `/Library/Input Methods/Squirrel.app/Contents/Resources` 路徑下有兩個文件 `rime.pdf` & `RimeIcon.icns`， 保持文件名然後替換文件內容也能生效，很久以前這樣改過，換成毛筆圖案之類的，挺有意思。
但我在想這樣的方法會不會有點 hardcore，下一次 App 更新可能就被覆蓋了，所以找到了這個 Issue，想看看有沒有配置參數可以修改圖標？

**Comment by lotem** [comment]
在輸入法程序執行之前，系統設置界面已經顯示該圖標了。我由此推知沒有辦法在運行時更換，只可以在輸入法應用的資源裏指定。
