### ISSUE TITLE
无法打开方案选单

### ISSUE THREAD

**Issue by blueset** [rime/squirrel#131]
尝试过包括默认的 <kbd>Ctrl+`</kbd> 在内的多种按键组合，但是始终不能调出方案选单。

如果需要提供日志等信息，我会尽力协助。

OS X El Capitan 10.11.6  
Squirrel 0.9.26.1

**Comment by jixiuf** [comment]
一般出现菜单栏后再按吧

**Comment by lotem** [comment]
輸入正常麼

**Comment by blueset** [comment]
@lotem 目前打字沒有問題，只不過只是知道是繁體字拼音，不知道是什麼方案。
@jixiuf 你指的是什么菜单栏？

**Comment by jixiuf** [comment]
选字的那个菜单。

**Comment by blueset** [comment]
@jixiuf 打开选字菜单之后也不能调出方案选单界面。

**Comment by lotem** [comment]
如果美式鍵盤能正常輸入，又沒有改過配置，打不開方案選單那可能是快捷鍵被系統或軟件佔用了。比如 Emacs 就用了這個快捷鍵。

**Comment by coolbreezeqf** [comment]
@lotem 請問有沒有方法修改切換選方案選單的快捷鍵

**Comment by Voleking** [comment]
@coolbreezeqf  这种问题搜一下都有的没必要在 issue 里提吧。

**Comment by coolbreezeqf** [comment]
@Voleking 我已經搜到了。 我在這裏提，是因爲我剛好遇到了同樣的問題。

**Comment by Voleking** [comment]
@coolbreezeqf 没看懂你想表达的意思，抱歉
