### ISSUE TITLE
不能切换输入法，没有上屏的字母会有黄色底色

### ISSUE THREAD

**Issue by xalexec** [rime/squirrel#132]
如下图，不能切换，快捷键有时可切换，有时不能显示
切换出输入法后，除了底色外输入正常。

环境 MacBook Pro (Retina, 15-inch, Mid 2015) 10.12.1 (16B2657)
rime 0.9.26.2

![wechatimg355](https://cloud.githubusercontent.com/assets/3349091/20591834/8189cb60-b265-11e6-928b-a80240d9c150.jpeg)

![wechatimg357](https://cloud.githubusercontent.com/assets/3349091/20591840/8776aa20-b265-11e6-8d24-b0f29335ae38.jpeg)

<img width="464" alt="2016-11-24 4 47 08" src="https://cloud.githubusercontent.com/assets/3349091/20591887/c93d784e-b265-11e6-9b15-727b53caf1a3.png">

**Comment by lotem** [comment]
黃色背景是該文本框自定義的效果嘛？給這段文字設的屬性，按系統的定義應該是下劃線。
這不是重點，重點是「鼠鬚管」處於灰掉的狀態，按理這時候就切換不出來了。現在還能打字，這；狀態已經混亂。從 OS X 的某個版本後，鼠鬚管剛安裝完沒有重啓/註銷可能會這樣不能用。升級系統也可能有關係。有時候需要到系統設置裏去掉這個輸入法，再加回來。
內嵌編碼的背景色，真的沒做控制。

**Comment by xalexec** [comment]
正常情况下是下划线，某些情况下会变为黄色。
并伴随着变为灰色状态，不可切换。

现在用了刚编译的版本，有问题的话再来反馈。
