### ISSUE TITLE
10.12.2编译源码出错

### ISSUE THREAD

**Issue by bms3-33** [rime/squirrel#133]
以下是报错信息
cp -R thirdparty/src/gtest/include/gtest thirdparty/include/
cp thirdparty/src/gtest/build/libgtest*.a thirdparty/lib/
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C librime -f Makefile.xcode release
mkdir -p xbuild
cd xbuild; cmake -G Xcode .. -DBUILD_STATIC=ON -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON
-- The C compiler identification is AppleClang 8.0.0.8000038
-- The CXX compiler identification is AppleClang 8.0.0.8000038
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /opt/local/share/cmake-3.7/Modules/FindBoost.cmake:1793 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.59.0

  Boost include path: /opt/local/include

  Could not find the following static Boost libraries:

          boost_filesystem
          boost_regex
          boost_signals
          boost_locale

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:42 (find_package)

-- Found glog: /Users/read/squirrel/librime/thirdparty/lib/libglog.a
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found yaml-cpp: /Users/read/squirrel/librime/thirdparty/lib/libyaml-cpp.a
-- Found leveldb: /Users/read/squirrel/librime/thirdparty/lib/libleveldb.a
-- Found marisa: /Users/read/squirrel/librime/thirdparty/lib/libmarisa.a
-- Found opencc: /Users/read/squirrel/librime/thirdparty/lib/libopencc.a
-- Found X11/keysym.h at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/Tk.framework/Headers
-- Configuring incomplete, errors occurred!
See also "/Users/read/squirrel/librime/xbuild/CMakeFiles/CMakeOutput.log".
make[1]: *** [release] Error 1
make: *** [librime] Error 2

**Comment by Prcuvu** [comment]
请安装或自行编译boost。

**Comment by bms3-33** [comment]
谢谢，重新安装boost后安装成功
