### ISSUE TITLE
deploy 之后，内存占用会上升至 780 兆

### ISSUE THREAD

**Issue by pupboss** [rime/squirrel#134]
很无耻的做一回伸手党....

正常使用情况下 squirrel 内存占用非常稳定，在 20 兆左右，每次 deploy 之后，就会上升到 780 兆左右，是不是哪个部位发生了 memory leak

安装的版本是 brew cask 里面最新的，14 年 12 月份那个版本

词库是前段时间 V2EX 网友分享的词库 https://www.v2ex.com/t/286896#reply88 

每次部署大概几十秒的样子

**Comment by lotem** [comment]
我也瞭解這個情況。但是測不出來內存泄漏。
轉換詞典時申請了大量內存，都是用 stl 容器操作的。可能和 stl 的內存分配策略有關？
我希望把部署操作拿到一個獨立進程來做，就像「小狼毫」那樣的。

**Comment by lotem** [comment]
如果介意大的內存示數，可以執行以下命令重啓一次輸入法進程。
```sh
/Library/Input\ Methods/Squirrel.app/Contents/MacOS/Squirrel --quit
```

**Comment by pupboss** [comment]
对的，我也是采用了类似的方法，在活动监视器里面 kill 掉这个进程

关于您说的「把部署操作拿到一個獨立進程來做」，我还没有研究过这个方向，等明白这部分内容之后，我发一个 pull request (如果那个时候仍然没有修复的话，哈哈)
