### ISSUE TITLE
squirrel 静默模式 自动英文 无效

### ISSUE THREAD

**Issue by Geng-G-Razor** [rime/squirrel#136]
mac 下大多数输入法都有自动英文的功能。
squirrel 也有这个功能。我也学会了自己加app配置项。
但是，我从来没有体验过自动英文的功能。

我对自动英文的理解是这样的：
我在 iTerm2 下切到中文，然后我切到 chrome，什么都不做，再切到 iTerm2 下，这时候应该是英文的。
像 QQ，百度，搜狗都是这样的模式。
可是在 squirrel 中却不是这样，它还是中文。

我在别人的电脑上安装过 squirrel，载入的就是默认配置，会有几项自动英文的app，也是不能自动英文。

所以，我想问下，squirrel 的自动英文到底是什么个情况。
是我配置文件错了，还是它本来工作方式就是这样？

**Comment by lotem** [comment]
所設置的是每個應用窗口裏的默認輸入狀態。
macOS 輸入法框架會爲每個應用窗口保持一個到輸入法程序的連接，切換窗口時不斷開。根據這個設計，鼠鬚管會記住切換前的狀態。我認爲這個策略是恰當的。

依愚見，切換窗口並不意味着輸入結束，繼續剛纔的工作時，預期應該是保持在該窗口內前一刻的輸入法狀態。比方說敲一行 `echo 你好世界`，用到了中文，之後何時切會英文只能靠操作員手動完成，輸入法無從知曉當前這串文字是否已結束輸入（也許還有很長），他也不知道一行「命令」爲何物。諸如打完一個命令就切回默認輸入狀態，這與該應用的業務相關，目前輸入法還無法做到對應用場景的智能感知。

**Comment by Geng-G-Razor** [comment]
感谢回复。
squirrel的策略和其它输入法，如搜狗，百度的自动英文，不太一致。
导致我理解上一直有问题。
关于你的输入策略的思考，其实我并没有想法，当然也不会反对。
只是现在的问题是，squirrel 用户中，大多是比较喜欢折腾的，而喜欢折腾的人，往往容易对 vim 感兴趣。
而vim用户，最大的希望就是，在自己切换到一个app时，输入状态是英文。
要不然，为了搞清楚自己是什么状态，不停的按shift真的好累。
这是我的一点点的想法，是实实在在的，使用中存在的困难。

**Comment by lotem** [comment]
在 vim 裏面輸入中文比較難辦。只要不用中文編程，靜默模式就是很有幫助的。如果用 vim 大量輸入中文，則理想爲：輸入法的狀態跟着 vim 的模式走，其實這跟切換窗口不太相關。
比如在 vim 的 INSERT 模式輸入中文時切換窗口，回來仍處於 INSERT 模式，保持中文狀態似乎沒什麼不好。真正需要自動切換爲英文的是回到命令模式後。
於是鼠鬚管針對 macvim 做了一個特殊處理，即在 MacVim 中按 `^C` 或 `^[` 退出插入模式時，輸入法會自動切換爲英文狀態。然而在終端裏用 vim，就沒辦法檢測到模式轉換了。

**Comment by Geng-G-Razor** [comment]
是的，MacVim 退出编辑模式，切换成英文是非常伟大的一项功能。
以前用 MacVim + Squirrel 编程是非常流畅的体验。
如果我一直用 MacVim， 我是不会提这个 issue 的.
只是现在我的主力编辑器，已经变成了 webStorm，安装了 vim 插件。
想必还有很多人用 Atom, sublime, VS Code 等等安装了 vim 插件。
这样的福利，我们就享受不到了。
如果这个功能比较容易添加的话，能不能指点下代码在哪里改，我倒是想自己改造下。
如果比较复杂的话，那就恐怕力不能及了。

**Comment by lotem** [comment]
這裏現在寫死了 MacVim。看來有必要把「vim 模式」加爲 `app_options` 的一個選項。
https://github.com/rime/squirrel/blob/master/SquirrelInputController.m#L169

**Comment by Geng-G-Razor** [comment]
谢谢。
感谢作者开发出这么伟大的输入法

**Comment by Geng-G-Razor** [comment]
尝试自己修改代码，构建过程报错。
ld: library not found for -lrime.1
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by KenChv** [comment]
这个问题这么多年没有人回答，我来回答一下。目前本人只在MacOS下配置使用，而且能满足这种要求。具体如下：
1. 用vim等文本编辑器打开squirrel.custom.yaml；
2. 具体配置：
"app_options/com.runningwithcrayons.Alfred-3/ascii_mode": true
  "app_options/com.sublimetext.3/ascii_mode": true
  "app_options/com.google.Chrome/ascii_mode": true
  "app_options/org.gnu.Emacs/ascii_mode": true
  "app_options/com.googlecode.iterm2/ascii_mode": true

**Comment by KenChv** [comment]
这个问题这么多年没有人回答，我来回答一下。目前本人只在MacOS下配置使用，而且能满足这种要求。具体如下：
1. 用vim等文本编辑器打开squirrel.custom.yaml；
2. 具体配置：
"app_options/com.runningwithcrayons.Alfred-3/ascii_mode": true
  "app_options/com.sublimetext.3/ascii_mode": true
  "app_options/com.google.Chrome/ascii_mode": true
  "app_options/org.gnu.Emacs/ascii_mode": true
  "app_options/com.googlecode.iterm2/ascii_mode": true

**Comment by dbthinking** [comment]
补充一下获取App包名（path）的方法：
终端命令: osascript -e 'id of app "alfred"'
输出: com.runningwithcrayons.Alfred
