### ISSUE TITLE
make deps failed

### ISSUE THREAD

**Issue by Bambooin** [rime/squirrel#138]
Is someone failed with the build. I already have build the product
a months ago, but this time I have this problem after try to "make clean"
and try a lot time.

The error log:

xcodebuild[32305:33268529] [MT] PluginLoading: Required plug-in compatibility UUID DA4FDFD8-C509-4D8B-8B55-84A7B66AE701 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/KSHObjcUML.xcplugin' not present in DVTPlugInCompatibilityUUIDs

and

/** BUILD FAILED **

The following build commands failed:
	Ld xbuild/lib/Release/librime.1.2.9.dylib normal x86_64
(1 failure)
Users/someone/github/squirrel/librime/src/translation.cc -o /Users/someone/github/squirrel/librime/xbuild/src/rime.build/Release/rime.build/Objects-normal/x86_64/translation.o

Ld xbuild/lib/Release/librime.1.2.9.dylib normal x86_64
    cd /Users/someone/github/squirrel/librime
    export MACOSX_DEPLOYMENT_TARGET=10.12
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -L/Users/someone/github/squirrel/librime/xbuild/lib/Release -L/usr/local/Cellar/boost/1.62.0/lib/Release -L/usr/local/Cellar/boost/1.62.0/lib -L/Users/someone/github/squirrel/librime/thirdparty/lib/Release -L/Users/someone/github/squirrel/librime/thirdparty/lib -F/Users/someone/github/squirrel/librime/xbuild/lib/Release -filelist /Users/someone/github/squirrel/librime/xbuild/src/rime.build/Release/rime.build/Objects-normal/x86_64/rime.1.2.9.LinkFileList -install_name /librime.1.2.9.dylib -mmacosx-version-min=10.12 -dynamiclib -Wl,-headerpad_max_install_names -install_name @rpath/librime.1.dylib /usr/local/Cellar/boost/1.62.0/lib/libboost_filesystem-mt.a /usr/local/Cellar/boost/1.62.0/lib/libboost_regex-mt.a /usr/local/Cellar/boost/1.62.0/lib/libboost_signals-mt.a /usr/local/Cellar/boost/1.62.0/lib/libboost_system-mt.a /usr/local/Cellar/boost/1.62.0/lib/libboost_locale-mt.a /Users/someone/github/squirrel/librime/thirdparty/lib/libglog.a /Users/someone/github/squirrel/librime/thirdparty/lib/libyaml-cpp.a /usr/lib/libiconv.dylib /Users/someone/github/squirrel/librime/thirdparty/lib/libleveldb.a /Users/someone/github/squirrel/librime/thirdparty/lib/libmarisa.a /Users/someone/github/squirrel/librime/thirdparty/lib/libopencc.a -single_module -compatibility_version 1.0.0 -current_version 1.2.9 -Xlinker -dependency_info -Xlinker /Users/someone/github/squirrel/librime/xbuild/src/rime.build/Release/rime.build/Objects-normal/x86_64/rime.1.2.9_dependency_info.dat -o /Users/someone/github/squirrel/librime/xbuild/lib/Release/librime.1.2.9.dylib
ld: warning: directory not found for option '-L/usr/local/Cellar/boost/1.62.0/lib/Release'
Undefined symbols for architecture x86_64:
  "snappy::RawCompress(char const*, unsigned long, char*, unsigned long*)", referenced from:
      leveldb::TableBuilder::WriteBlock(leveldb::BlockBuilder*, leveldb::BlockHandle*) in libleveldb.a(table_builder.o)
  "snappy::RawUncompress(char const*, unsigned long, char*)", referenced from:
      leveldb::ReadBlock(leveldb::RandomAccessFile*, leveldb::ReadOptions const&, leveldb::BlockHandle const&, leveldb::BlockContents*) in libleveldb.a(format.o)
  "snappy::MaxCompressedLength(unsigned long)", referenced from:
      leveldb::TableBuilder::WriteBlock(leveldb::BlockBuilder*, leveldb::BlockHandle*) in libleveldb.a(table_builder.o)
  "snappy::GetUncompressedLength(char const*, unsigned long, unsigned long*)", referenced from:
      leveldb::ReadBlock(leveldb::RandomAccessFile*, leveldb::ReadOptions const&, leveldb::BlockHandle const&, leveldb::BlockContents*) in libleveldb.a(format.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

cp -L librime/xbuild/lib/Release/librime.1.dylib lib/librime.1.dylib
cp: cannot stat 'librime/xbuild/lib/Release/librime.1.dylib': No such file or directory
make: *** [librime] Error 1

**Comment by lotem** [comment]
大意是：編譯 leveldb 的時候檢測到了可選的 libsnappy 因而連接到這個庫，而這個庫沒有安裝 x86_64 架構的二進制文件。所以鏈接 libsnappy 失敗了。
有可能是安裝其他軟件時作爲依賴安裝了 libsnappy 。如果用 Homebrew，可以查看這個軟件包是否已安裝：
`brew info snappy`

**Comment by Bambooin** [comment]
Thanks, I install the snappy last week for the trime.

**Comment by osfans** [comment]
要不要snappy呢？要不我也取消？

**Comment by Bambooin** [comment]
I am learning the make and camke, unfamiliar with the C++ library.
Now I can uninstall snappy to compile squirrel and reinstall it again after it.
As I seldom compile squirrel, but do trime a lot of time.
If snappy is useful for the compression, why do we depart it from trime?

**Comment by lotem** [comment]
@osfans Please think twice. If you remove the snappy library from newer builds, your client won't be able to read existing user dictionary entries that have been compressed by previous versions.
