### ISSUE TITLE
新版本编译安装后，部署时候出现`source file 'pinyin_simp.dict.yaml' does not exist.`错误

### ISSUE THREAD

**Issue by pzgz** [rime/squirrel#139]
在新版本安装以后，部署的时候，报告错误，日志里面出现`source file 'pinyin_simp.dict.yaml' does not exist.`。

看了一下，之前的版本在安装以后，在`~/Library/Rime/`里面会有几个文件alias到`/Library/Input Methods/Squirrel.app/Contents/SharedSupport/`中的几个文件，但是新的这个安装里面，这几个符号连接没了，是需要自己加上吗？

**Comment by pzgz** [comment]
请忽略这个问题，应该是我在`~/Library/Rime/`历史遗留的文件造成的，我删除了对应的几个文件，就ok了。

**Comment by lotem** [comment]
不是你弄錯了，是打包的文件少了。
我希望能減少預裝的輸入方案，與之配套的是一套輸入法包管理機制。初步成果： 
http://git.io/brise
還沒有集成到鼠鬚管。

這樣取得缺少的文件（包）：
```sh
curl -fsSL https://git.io/v13uY | bash -s -- pinyin-simp
```

**Comment by pzgz** [comment]
非常感谢，搞定了
