### ISSUE TITLE
在配置小鹤双拼之后无法打出一些ae开头词组

### ISSUE THREAD

**Issue by TomatoFryEggs** [rime/squirrel#140]
如：
ali=阿里
ele=饿了

**Comment by lotem** [comment]
不僅打不出 a、e 開頭的，也打不出 sh 開頭的和 uang 結尾的。因爲是雙拼：每個音節都用兩鍵輸入。

**Comment by TomatoFryEggs** [comment]
那该怎么解决呢？

**Comment by lotem** [comment]
解決：

或者切換到全拼，按原題的方式輸入；或者改用雙拼的拼法輸入。

我打不開小鶴雙拼的官網，所以從 https://zh.wikipedia.org/wiki/双拼 摘抄一段：

> 双拼方案：单声母键位不变，主要是韵母键位的设计方案，即把三个双声母 zh、ch、sh 和 35 个韵母安排到键盘的 26 个字母键位上的设计方案，具体请参阅后面流行双拼方案键位图。
> 零声母方案：指全拼中无声母的音节在双拼中的处理方案，即全拼中有几个音节没有声母，双拼中需要把这个零声母实质化，于是就有了零声母方案。
> 固定一个字母做零声母 + 韵母所在键，如微软双拼、智能ABC、紫光双拼
> 以韵母首字母为零声母 + 韵母所在键，如拼音加加注：拼音加加实际上兼容两种零声母方案。[1]
> 单韵母、三韵母为韵母首字母 + 韵母所在键，双韵母为韵母首字母 + 韵母末字母，如自然码、小鹤双拼

**Comment by TomatoFryEggs** [comment]
@lotem 谢谢了，那我分享一个毒瘤的解决方案把。
其实正常情况下那样的词汇也不多，把常用的那几个加入custom_phrase.txt。
