### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Voleking** [rime/squirrel#142]
輸入法中西文切換的形式可否加入一種新的切換策略:當前為中文模式則已輸入的編碼字符上屏並切換至西文輸入模式,為西文輸入模式則不變.

如果能告知如何在源碼中改也是極好的.

**Comment by lotem** [comment]
這樣豈不是，切不回中文模式了？……

**Comment by Voleking** [comment]
額，尷尬，靠其他切換模式咯，其實我本來是想着平常用 vim 寫 md 的時候用 ⇪+c 切換到 normal 如果把 capslock 幫到上面那個模式可以不用頻繁的切換中英文（我自己試着使用 commit_code 模式發現有時是英文是反而會切換回中文）。現在感覺這個方案沒有充分考慮，close 了，抱歉。由  #136 #124 不過還是可見 vim 自動中英文轉換需求是特別大的。

**Comment by jixiuf** [comment]
#123 看看有没有用

**Comment by Voleking** [comment]
@jixiuf 好的，感谢
