### ISSUE TITLE
如何配置 key_biner 切换时候的 Hint

### ISSUE THREAD

**Issue by alswl** [rime/squirrel#143]
在使用系统默认的 Control+Shift+2 时候，会出现一个 Hint：「中」/「A」。
我目前在使用开发版本的 `charset_filter` 功能，也期望能够出现一个提示信息，
告诉我当前处在哪个 `charset`。

请问这个功能目前支持么？该如何配置。

我使用的版本是 master 分支，git hash：b3df748

**Comment by alswl** [comment]
是否和这个 Issue 相关联 https://github.com/rime/home/issues/38

**Comment by lotem** [comment]
沒有關聯。
現在這些提示語是在 macOS 前端寫定的。
要想靈活些，大概改成從配置加載比較好。
