### ISSUE TITLE
数字键盘输入的数字，不会将数字之后的 ：/。 转换为 :/.

### ISSUE THREAD

**Issue by alswl** [rime/squirrel#144]
我使用的版本是 master 分支，git hash：b3df748

使用 Stable 版本时候，数字键盘输入的数字，会将数字之后的 ：/。 转换为 :/. 。
而开发版会将普通数字输入正确转换，但是如果使用数字键盘（小键盘）输入时候，就无法自动转换了。

**Comment by lotem** [comment]
由於缺少相關設備，數字鍵盤的問題，近期可能無法着手解決。

Rime 一直是對數字鍵盤不做處理的，即透過輸入法、數字直達應用。
因此數字鍵盤的字符無法參與判斷是否匹配到 9.9、9:9 等模式。
除非在 key_binder/bindings 配置部分將數字鍵盤的虛擬按鍵碼 KP_9 等一一映射到主鍵盤數字的按鍵碼。
我猜原來爲 default.yaml 或輸入方案打過這個補丁，才能行的。
