### ISSUE TITLE
怎样既排除生僻字 又能输入不完全简化的汉字？

### ISSUE THREAD

**Issue by xjkdev** [rime/squirrel#147]
例如 书法家 赵孟頫 的 “頫” 字，通常情况下都用不完全简化的頫字，然而，如果排除了生僻字，这个字就会变为 “𫖯” 字，由于我又开启了生僻字过滤，这个字就打不出来了。而且用“𫖯”字的话，搜索引擎基本检索不到正确的结果，所以必须要使用未完全简化的 “頫” 字。

另外不开启生僻字过滤会出现“𫔭”这样没人用的奇怪的字，所以开启生僻字过滤是必要的。
（我是通过添加GBK过滤开关达到这个功能的）

请问在这个版本的鼠须管（开发版约一星期前自编译）下能否让頫字在简体字模式下出现呢，或者说能否让简体字和繁体字并存？

**Comment by lotem** [comment]
得改 opencc 字典。
https://github.com/rime/librime/blob/master/thirdparty/src/opencc/data/dictionary/TSCharacters.txt
現在看來只能重做一個繁→簡轉換表。
