### ISSUE TITLE
鼠须管在MacOS Sierra 10.12的分享界面无法输入

### ISSUE THREAD

**Issue by gujiaxi** [rime/squirrel#149]
鼠须管在Sierra的分享界面无法输入，相同的情况也会出现在通知中心的分享输入框。

不管是自行编译的版本（a4e5241）还是brew cask上的版本（0.9.26.2），都存在这个bug。

MacOS Sierra Version 10.12.3 (16D32)

![](http://i.imgur.com/ue9cKWQ.png)

![](http://i.imgur.com/6OzQb4R.png)

**Comment by gujiaxi** [comment]
在我这里微博和Messages也有一样的问题，难道是我编译的问题。

**Comment by gujiaxi** [comment]
我最近发现这个问题是由中英文切换引起的，经过测试，在分享界面无法通过Shift来切换输入源（中/英）。

比如：一旦设置了首选英文输入 (`"switches/@0/reset": 1`)，那么在分享界面就无法通过Shift按键来切换至中文输入法，从而导致无法输入中文。

**Comment by lotem** [comment]
是的，沒法用 `Shift` 鍵切換。可以臨時用 `Control+Shift+2` 替代。

**Comment by gujiaxi** [comment]
`Control+Shift+2`是内置的按键组合吗？测试了一下没有成功。

**Comment by lotem** [comment]
預設方案裏面引用了這項設置
https://github.com/rime/rime-prelude/blob/master/default.yaml#L130
也可以自定義一個包含字符鍵的快捷鍵。

**Comment by gujiaxi** [comment]
可以了，感谢。
