### ISSUE TITLE
中文状态下反引号如何设定

### ISSUE THREAD

**Issue by jtr109** [rime/squirrel#151]
中文状态下输入反引号 -- "\`", 会出现笔画反查功能以及备选框. 我希望设定所有的符号都直接输出正常的键盘输入. 已经设定默认西文符号, 其他的符号问题都解决了, 比如句号 ".", 但是反引号无法解决.

特请教一下, 谢谢!

**Comment by Prcuvu** [comment]
把`reverse_lookup`部分全部删除即可。

**Comment by lotem** [comment]
```yaml
patch:
  recognizer/patterns/reverse_lookup: {}
```

**Comment by jtr109** [comment]
thanks a lot! @lotem

**Comment by jtr109** [comment]
Tip for others:
After trying. I thought the patch from lotem may works only in the scheme, such as `double_pinyin_flypy.custom.yaml`, not the `default.custom.yaml`.

**Comment by wanglongbiao** [comment]
感谢，问题解决了，rime 配置好，用起来真方便！
