### ISSUE TITLE
怎么编译鼠须管？

### ISSUE THREAD

**Issue by AndyChen2005121** [rime/squirrel#157]
对，上一次打包好的 release 已经是两年前的事了，所以我想从源码编译。
问题来了，怎么弄？

**Comment by zijung** [comment]
https://github.com/rime/squirrel/blob/master/INSTALL.md

**Comment by LuciusChen** [comment]
参见 #152 。另外不知道为什么最近 Xcode 不会自动选择已经安装的 Command Line Tools，如果编译报错的话，可以在如下地方选择一下。
![screen shot 2017-04-20 at 8 47 25 pm](https://cloud.githubusercontent.com/assets/4947981/25231541/cf94ac94-260a-11e7-9f8f-1206e28053fd.png)

**Comment by lzxin1** [comment]
手动编译安装需要安装`Xcode`, 并且打开运行一次

如果没有安装`Xcode`, 在`make deps`时会报错:
```
cmake error:
    Xcode 1.5 not supported
```

如果没有打开`Xcode`运行一次, 在`make`时会报错: `某个image找不到`(当时没有截图, 所有详细报错日志记不清了)

OS: macOS High Sierra 10.13.1
