### ISSUE TITLE
是否考虑增加 Touch Bar 相关支持？

### ISSUE THREAD

**Issue by heruoxin** [rime/squirrel#158]

**Comment by zgr0629** [comment]
现在再touchbar里显示的联想词是英文的，而不是中文

**Comment by aaftio** [comment]
我现在使用的时候，touch bar 是一闪一闪的，显示的是空白

**Comment by LEOYoon-Tsaw** [comment]
等人來做唄

**Comment by aaftio** [comment]
可惜我不是做Mac开发的，而且还是最近几个月才开始用OSX。不过，现在也还在用linux ibus版本的，感觉linux ibus做得已经很不错了！非常感谢这个项目

**Comment by ksqsf** [comment]
Touch Bar 功能很有用阿，想用來切換輸入方案、簡繁。

**Comment by LEOYoon-Tsaw** [comment]
TouchBar已死🪦

**Comment by hayden-pan** [comment]
> TouchBar已死🪦

是啊，当年没有做也是对的🤣
