### ISSUE TITLE
xcode-select 升级之后，无法编译

### ISSUE THREAD

**Issue by foisonocean** [rime/squirrel#159]
提示找不到 CMAKE_C_COMPILER 和 CMAKE_CXX_COMPILER

**Comment by LuciusChen** [comment]
Preferences ==> Location ==> Command Line Tools 手动选择一下。

**Comment by foisonocean** [comment]
@LuciusChen 
不好意思，这个是在系统的偏好设置里面改吗？我没有找到相关的选项呢

**Comment by foisonocean** [comment]
原來是在 xcode 的偏好设置去更改，现在已经编译成功了

**Comment by RandomLive** [comment]
谢谢。
