### ISSUE TITLE
看到经常有询问获取最新编译的安装包的请求，我是否可以在每次的源码更新后上传自己最新编译的版本

### ISSUE THREAD

**Issue by Cavolo** [rime/squirrel#167]
[Squirrel.app.zip](https://github.com/rime/squirrel/files/1329189/Squirrel.app.zip)

**Comment by songxing10000** [comment]
头像很漂亮啊

**Comment by lotem** [comment]
還沒準備好更新。

**Comment by Cavolo** [comment]
呃现在的情况是慕名而来的人通过搜索引擎检索到rime的官网下载发现最新的版本是14年的，所以很多人会认为这是一个已经放弃了的项目，大佬能提供定期官方编译我觉得可能会给这个项目带来更大的活力，毕竟有个编译的包会给很多新手降低入门的门槛，他们只需要按照网上的教程自己配置就行了

**Comment by ThinkCats** [comment]
贊一個

**Comment by Cavolo** [comment]
d4574f0
[Squirrel.app.zip](https://github.com/rime/squirrel/files/1668418/Squirrel.app.zip)

**Comment by songxing10000** [comment]
跟着这个https://github.com/rime/squirrel/blob/master/INSTALL.md，就能编译安装上新包
