### ISSUE TITLE
更新完，成了完全不可用状态，只能用系统自带中文拼音 😀

### ISSUE THREAD

**Issue by yakirChen** [rime/squirrel#168]
I0927 01:41:51.830325 2585146176 deployment_tasks.cc:33] updating rime installation info.
W0927 01:41:51.830359 2585146176 config_data.cc:59] nonexistent config file '/Users/yakir/Library/Rime/installation.yaml'.
I0927 01:41:51.830391 2585146176 deployment_tasks.cc:76] creating installation info.
I0927 01:41:51.835793 2585146176 deployment_tasks.cc:83] generated installation id: 2baf6c85-3a3b-4ec5-9b77-e005332428bd
I0927 01:41:51.835808 2585146176 config_data.cc:238] write: installation_id
I0927 01:41:51.835817 2585146176 config_data.cc:238] write: install_time
I0927 01:41:51.835824 2585146176 config_data.cc:238] write: distribution_name
I0927 01:41:51.835829 2585146176 deployment_tasks.cc:94] distribution: 鼠鬚管
I0927 01:41:51.835832 2585146176 config_data.cc:238] write: distribution_code_name
I0927 01:41:51.835837 2585146176 deployment_tasks.cc:99] distribution code name: Squirrel
I0927 01:41:51.835840 2585146176 config_data.cc:238] write: distribution_version
I0927 01:41:51.835845 2585146176 deployment_tasks.cc:105] distribution version: 0.9.27
I0927 01:41:51.835850 2585146176 config_data.cc:238] write: rime_version
I0927 01:41:51.835855 2585146176 deployment_tasks.cc:108] Rime version: 1.2.9
I0927 01:41:51.835857 2585146176 config_data.cc:82] saving config file '/Users/yakir/Library/Rime/installation.yaml'.
E0927 01:41:51.835902 2585146176 config_data.cc:38] failed to save config to stream.
I0927 01:41:51.835997 2585146176 config_data.cc:62] loading config file '/Library/Input Methods/Squirrel.app/Contents/SharedSupport/squirrel.yaml'.
I0927 01:41:51.838165 2585146176 config_compiler.cc:451] all dependencies resolved.
I0927 01:42:10.111068 2585146176 deployer.cc:114] starting work thread for 3 tasks.
I0927 01:42:10.111145 245690368 deployer.cc:83] running deployment tasks:
I0927 01:42:10.111464 245690368 deployment_tasks.cc:33] updating rime installation info.
W0927 01:42:10.111605 245690368 config_data.cc:59] nonexistent config file '/Users/yakir/Library/Rime/installation.yaml'.
I0927 01:42:10.111667 245690368 deployment_tasks.cc:76] creating installation info.
I0927 01:42:10.117897 245690368 deployment_tasks.cc:83] generated installation id: 436e9fca-7bbb-48ad-b91f-ad04d5787b38
I0927 01:42:10.117914 245690368 config_data.cc:238] write: installation_id
I0927 01:42:10.117924 245690368 config_data.cc:238] write: install_time
I0927 01:42:10.117930 245690368 config_data.cc:238] write: distribution_name
I0927 01:42:10.117935 245690368 deployment_tasks.cc:94] distribution: 鼠鬚管
I0927 01:42:10.117938 245690368 config_data.cc:238] write: distribution_code_name
I0927 01:42:10.117944 245690368 deployment_tasks.cc:99] distribution code name: Squirrel
I0927 01:42:10.117947 245690368 config_data.cc:238] write: distribution_version
I0927 01:42:10.117952 245690368 deployment_tasks.cc:105] distribution version: 0.9.27
I0927 01:42:10.117955 245690368 config_data.cc:238] write: rime_version
I0927 01:42:10.117960 245690368 deployment_tasks.cc:108] Rime version: 1.2.9
I0927 01:42:10.117964 245690368 config_data.cc:82] saving config file '/Users/yakir/Library/Rime/installation.yaml'.
E0927 01:42:10.118016 245690368 config_data.cc:38] failed to save config to stream.
I0927 01:42:10.118074 245690368 deployment_tasks.cc:421] backing up config files.
E0927 01:42:10.118119 245690368 deployment_tasks.cc:429] error creating directory 'sync/436e9fca-7bbb-48ad-b91f-ad04d5787b38'.
I0927 01:42:10.118217 245690368 user_dict_manager.cc:226] synchronizing 1 user dicts.
I0927 01:42:10.118223 245690368 user_dict_manager.cc:191] synchronize user dict 'luna_pinyin'.
E0927 01:42:10.118248 245690368 user_dict_manager.cc:197] error creating directory 'sync'.
E0927 01:42:10.118274 245690368 user_dict_manager.cc:233] failed synchronizing 1/1 user dicts.
I0927 01:42:10.118296 245690368 deployer.cc:95] 3 tasks ran: 0 success, 3 failure.
I0927 01:42:12.778296 2585146176 config_data.cc:62] loading config file '/Users/yakir/Library/Rime/default.yaml'.
I0927 01:42:12.780618 2585146176 config_compiler.cc:451] all dependencies resolved.
I0927 01:42:12.780642 2585146176 engine.cc:70] starting engine.
W0927 01:42:12.780695 2585146176 config_data.cc:59] nonexistent config file '/Users/yakir/Library/Rime/user.yaml'.
E0927 01:42:12.780730 2585146176 config_component.cc:171] error loading config from: user
I0927 01:42:12.780926 2585146176 config_data.cc:62] loading config file '/Users/yakir/Library/Rime/luna_pinyin.schema.yaml'.
I0927 01:42:12.781590 2585146176 config_compiler.cc:451] all dependencies resolved.
I0927 01:42:12.781826 2585146176 config_data.cc:62] loading config file '/Users/yakir/Library/Rime/symbols.yaml'.
I0927 01:42:12.801635 2585146176 config_compiler.cc:451] all dependencies resolved.
I0927 01:42:12.802114 2585146176 engine.cc:121] updated option: _auto_commit
I0927 01:42:12.802209 2585146176 config_data.cc:62] loading config file '/Users/yakir/Library/Rime/symbols.yaml'.
I0927 01:42:12.821612 2585146176 config_compiler.cc:451] all dependencies resolved.
I0927 01:42:12.822085 2585146176 config_data.cc:62] loading config file '/Users/yakir/Library/Rime/symbols.yaml'.
I0927 01:42:12.842103 2585146176 config_compiler.cc:451] all dependencies resolved.
I0927 01:42:12.842190 2585146176 table_db.cc:80] stabledb 'custom_phrase.txt' does not exist.
I0927 01:42:12.842239 2585146176 dictionary.cc:264] loading dictionary 'luna_pinyin'.
I0927 01:42:12.842244 2585146176 table.cc:318] loading table file: /Users/yakir/Library/Rime/luna_pinyin.table.bin
E0927 01:42:12.842255 2585146176 mapped_file.cc:112] attempt to open non-existent file '/Users/yakir/Library/Rime/luna_pinyin.table.bin'.
E0927 01:42:12.842305 2585146176 table.cc:324] Error opening table file '/Users/yakir/Library/Rime/luna_pinyin.table.bin'.
E0927 01:42:12.842330 2585146176 dictionary.cc:266] Error loading table for dictionary 'luna_pinyin'.
I0927 01:42:12.852334 2585146176 engine.cc:121] updated option: ascii_mode
I0927 01:43:20.741734 2585146176 engine.cc:87] engine disposed.

**Comment by yakirChen** [comment]
這個版本可以用 check回這個版本了 88e77ac8e932067a886fbfa88071b0e9f9106751

**Comment by Cavolo** [comment]
更新完注销过吗

**Comment by lotem** [comment]
Fixed via 66948afe6c50ef1a72a55abd505d2c8ceae4fe37

以安裝包或 sudo 方式安裝後有此問題的，還須更改用戶目錄的所有者：
```sh
sudo chown -R $USER  ~/Library/Rime
```
