### ISSUE TITLE
vim怎样设置按下esc时自动切换成英文输入模式

### ISSUE THREAD

**Issue by 3xp10it** [rime/squirrel#169]
之前一直用的zsh+squirrel+macOS sierra+macvim(用的是非gui的终端mvim),
按照https://raw.githubusercontent.com/3xp10it/AutoIM/master/default.custom.yaml
设置可按一次esc实现如题的功能,但是后来升级了macOS系统和换成fish shell后发现在macvim中在中文输入状态时要按2次esc才会切换到英文输入下的normal模式,按1次esc时由中文输入模式切换成英文输入模式,按第2次esc时由英文输入状态切换成vim的normal模式.

也即现在在mvim中输入esc时,这个esc会被squirrel先捕获到,然后才被mvim捕获到,从而导致第1次按下esc时由当前状态[中文输入和insert模式]切换成英文输入的insert模式,而不是被mvim捕获到变成normal状态.

env:
iterm2
squirrel最新版
macvim
fish shell

**Comment by Voleking** [comment]
可以考虑下用 fcitx。
[fcitx-vim-osx](https://github.com/CodeFalling/fcitx-vim-osx) 
or [fcitx.vim](https://github.com/lilydjwg/fcitx.vim)

**Comment by 3xp10it** [comment]
fcitx切换比较慢吧.

**Comment by Voleking** [comment]
个人感觉还好。

**Comment by 3xp10it** [comment]
刚刚试了下fcitx-vim-oxs，效果很好，十分感谢推荐。

**Comment by Voleking** [comment]
不客气:smile:

**Comment by jostyee** [comment]
Mac的话试试 https://github.com/ybian/smartim

**Comment by bao3** [comment]
楼上的方法是可行的，也是我一直在用。

**Comment by lzxin1** [comment]
@jostyee 只能在不同的输入法间切换, 不能直接切换`Squirrel`的中英文

**Comment by lotem** [comment]
Refer to https://github.com/rime/squirrel/issues/124
Fixed by https://github.com/rime/squirrel/commit/08ed4f4590e17c969f1536b347bbe1f05737d4aa
