### ISSUE TITLE
在IntelliJ IDEA中輸入漢字的時候光標顯示位置不對

### ISSUE THREAD

**Issue by ethanfu** [rime/squirrel#17]
當在IntelliJ IDEA中輸入漢字的時候，當回車出現新行的時候光標可能定格在某個位置，假設當我輸入wo的時候，會在光標的位置出現w並且在行首的位置出現“我”的漢字

**Comment by loong1992** [comment]
这么多年过去了, 这个问题现在可以关闭了吧, 我这里没有这种问题.
