### ISSUE TITLE
如何实现五笔“一至三码空格上屏，四码无重自动上屏，第五码顶字上屏”

### ISSUE THREAD

**Issue by linchen2chris** [rime/squirrel#174]
如何在五笔下实现
1）一至三码空格上屏，
2）四码无重自动上屏，
3）第五码顶字上屏

**Comment by lotem** [comment]
https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md#%E4%B8%80speller
用
max_code_length: 形碼最大碼長，超過則頂字上屛〔number〕
auto_select: 自動上屛〔true或false〕
