### ISSUE TITLE
macOS Visual Studio Community 输入不了中文

### ISSUE THREAD

**Issue by yakirChen** [rime/squirrel#179]
如标题:
macOS Visual Studio Community 输入不了中文 😔
切换到中文模式，输入的还是英文 

`macOS` 10.13.2 
`Visual Studio Community` 7.3
`鼠鬚管` clone倉庫編譯的`0.9.27`版

發現只在`Visual Studio Community`中有這個問題存在

**Comment by lotem** [comment]
是這個軟件嘛？我找不到 macOS 的 Community 版本。
https://www.visualstudio.com/vs/visual-studio-mac/

**Comment by yakirChen** [comment]
[https://www.visualstudio.com/zh-hans/downloads/](https://www.visualstudio.com/zh-hans/downloads/)
我在这个链接下载的, 因为我只有`Community`版本,不晓得其他版本有没有这个输不上中文的问题
```proprties
=== Visual Studio Community 2017 for Mac ===

Version 7.3 (build 799)
Installation UUID: 8a0996c3-6265-4692-97d3-a45a38b4dabd
Runtime:
	Mono 5.4.1.7 (2017-06/e66d9abbb27) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504010007

=== NuGet ===

版本: 4.3.1.4445

=== .NET Core ===

运行时: /usr/local/share/dotnet/dotnet
运行时版本: 2.0.0
SDK: /usr/local/share/dotnet/sdk/2.0.0/Sdks
SDK 版本: 2.0.0
MSBuild SDK: /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

版本: 1.6.0
位置:/Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.iOS ===

Xamarin.iOS not installed.
Can't find mtouch or the Version file at /Library/Frameworks/Xamarin.iOS.framework/Versions/Current.

=== Xamarin.Android ===

未安装

=== Xamarin Inspector ===

Version: 1.3.2
Hash: 461f09a
Branch: 1.3-release
Build date: Tue, 03 Oct 2017 18:26:57 GMT
Client compatibility: 1

=== Xamarin.Mac ===

Version: 4.0.0.214 (Visual Studio Community)

=== Build Information ===

Release ID: 703000799
Git revision: df590420ea5bc681994baefff2eabdaad889fba9
Build date: 2017-12-05 09:23:45-05
Xamarin addins: 51068d6eaf3b6fb4fbc72b33cb869b0ebff04ec5
Build lane: monodevelop-lion-d15-5

=== Operating System ===

Mac OS X 10.13.2
Darwin 17.3.0 Darwin Kernel Version 17.3.0
    Thu Nov  9 18:09:22 PST 2017
    root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1
```

**Comment by jiangyoucai** [comment]
https://code.visualstudio.com/
vscode里也无法输入中文，sublime和其他软件正常

**Comment by lotem** [comment]
@jiangyoucai 
試了這個版本，可以正常輸入 vscode version 1.14.2 (macOS)

**Comment by jiangyoucai** [comment]
谢谢@lotem
默认是关闭的，我加了自定义squirrel.custom.yaml后，可以了
```
# Squirrel settings
# encoding: utf-8

patch:
  app_options:
    com.microsoft.VSCode:
      ascii_mode: false
```

**Comment by yakirChen** [comment]
@lotem  `vscode` 和`Visual Studio Community`应该是不一样的两个 app .  vscode 一直是可以正常输入的. `Visual Studio Community` 当前是 **7.3.3(build 12)**  版本, 尝试切换中文 还是不能输入
下面是两个app的对比图, 左图是 `Visual Studio Code`, 右图是 `Visual Studio Community`

![vsCode_vsStudio](http://yakirchen.com/imgs/tmp/vsCode_vsStudio.png)

**Comment by aajijifujiji** [comment]
谢谢你！
大概是我之前在default.custom.yaml这个文件改的，好像没有成功。
在这个文件改之后可以使用了

**Comment by wanglongbiao** [comment]
为啥要在 vs code 里面默认英文呢。。。😮‍💨

**Comment by hiking93** [comment]
> 谢谢@lotem 默认是关闭的，我加了自定义squirrel.custom.yaml后，可以了
> 
> ```
> # Squirrel settings
> # encoding: utf-8
> 
> patch:
>   app_options:
>     com.microsoft.VSCode:
>       ascii_mode: false
> ```

實測有用，但為什麼預設不讓輸入中文呢？
