### ISSUE TITLE
在很多全屏模式的游戏里无法显示候选菜单

### ISSUE THREAD

**Issue by LambdaXIII** [rime/squirrel#181]
有一些游戏可以，有一些不行。
无法显示的游戏如果设置成“最大化窗口”模式的话就可以显示。但是这样的话性能太低了。

**Comment by lotem** [comment]
没办法咯。
有一些游戏可以，有一些不行——大概是有些特别之处。

**Comment by LambdaXIII** [comment]
我尝试着修改了一下 panel 的_window.level 好像可以了，我怎么提交？
还是说我贴到这里？
我不太会用这些协作方式……

**Comment by Prcuvu** [comment]
@LambdaXIII 网页右上角点Fork，用Git把你的Fork仓库pull到本地，修改后在本地commit，然后push回GitHub上的Fork仓库，最后在GitHub上提Pull Request。

**Comment by lotem** [comment]
Fixed by https://github.com/rime/squirrel/pull/182
