### ISSUE TITLE
如何選擇安裝輸入法語言

### ISSUE THREAD

**Issue by DrakeWong** [rime/squirrel#185]
我是使用繁體中文版的MacOS，MacOS 的office會「自作聰明」偵測輸入法語言，並預設相應的字體（這樣構成我的困擾）。

請問有沒有方法可以改動輸入法語言的歸類，由「簡體中文」改到歸類到「繁體中文」之下呢？

![snip20180123_2](https://user-images.githubusercontent.com/12155059/35263320-4503a728-0053-11e8-805a-d0f6a9155635.png)

![snip20180123_1](https://user-images.githubusercontent.com/12155059/35263386-814d04cc-0053-11e8-96b5-82f6dbd9dd68.png)

**Comment by lotem** [comment]
列入繁體中文的輸入法，需要將此處的語言代碼修改爲 `zh-Hant`
https://github.com/rime/squirrel/blob/master/Info.plist#L32
再重新向系統註冊輸入法
```shell
open "/Library/Input Methods/Squirrel.app/Contents/Info.plist"  # 編輯
"/Library/Input Methods/Squirrel.app/Contents/MacOS/Squirrel" --install
```
我不確定「偵測輸入法語言」的行爲是否跟該文件中「tsInputModeCharacterRepertoireKey」聲明的語言列表有關。如果以上修改無效，可嘗試刪除列表中定義爲「zh-Hans」的值。

**Comment by DrakeWong** [comment]
問題解決！！！！！

萬分感謝！！！！

**Comment by momofish325** [comment]
也遇到一樣的情況，但是照著上面的方式操作，將語言代碼修改爲zh-Hant之後，在word裡沒辦法打出中文，怎麼打都是英文；刪除定義爲zh-Hans的值，整個輸入法就從切換的選項中消失了......

跪求幫助，它真的很好用啊Q_Q
