### ISSUE TITLE
候选栏能否设置字符垂直居中？

### ISSUE THREAD

**Issue by mpco** [rime/squirrel#193]
![screen shot 2018-03-09 at 4 59 54 pm](https://user-images.githubusercontent.com/3690653/37199172-ce4de210-23bb-11e8-8899-8de6b01ef2ca.png)

如图，字符上方的空间有些大，请问能否调节。

**Comment by lotem** [comment]
文字是居中的。不需要設置。
<img width="666" alt="screen shot 2018-03-09 at 7 07 27 pm" src="https://user-images.githubusercontent.com/151157/37204792-3dee57c4-23cd-11e8-9af9-7d0e52a0c6d1.png">
題主試試換個字體。
