### ISSUE TITLE
又遇到编译错误

### ISSUE THREAD

**Issue by 1900forever** [rime/squirrel#194]
`     
 typeinfo for YAML::TypedBadConversion<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > in config_data.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	Ld xbuild/lib/Release/librime.1.3.0.dylib normal x86_64
(1 failure)
make[1]: *** [release] Error 65
make: *** [librime] Error 2

`
10.13.4，Xcode9.2环境

**Comment by lotem** [comment]
> 我比較關心項目的代碼有沒有出問題，並不太關心使用該代碼時個體的遭遇。

**Comment by Prcuvu** [comment]
无法重现问题。

**Comment by LuciusChen** [comment]
![image](https://user-images.githubusercontent.com/4947981/51455946-be79fe80-1d86-11e9-89dc-c1c57f197f6f.png)
再次出现。。。
