### ISSUE TITLE
Font issue: Pingfang SC and .Pingfang SC

### ISSUE THREAD

**Issue by skksdd** [rime/squirrel#196]
When deploying my squirrel input method, the issue below occurred.

![artboard 1](https://user-images.githubusercontent.com/19769650/38120540-19d10f8c-33fc-11e8-9f81-af550bce3095.jpg)

The only difference is the font-face difference in squirrel.custom.yaml
Left image: `font_face: ".Pingfang SC" `
Right image: `font_face: "Pingfang SC"`

Besides `font-face`, all the other settings are all the same.

1. The font `.Pingfang SC` can't be found in Font Book.app or other apps such as Photoshop.app
2. The font `.Pingfang SC` can only be found in Pages.app

- Is this problem caused by squirrel ?
- Is there a way to remove `.Pingfang SC` and get the fonts consolidated?

**Comment by lotem** [comment]
`PingFang SC` looks like the one on the right.
I don't have the `.` prefixed font. When that name is specified, maybe it just falls back to the default font.

**Comment by skksdd** [comment]
@lotem 
Thx for your explanation.
I agree that the `.` font is a fallback.
Thanks again for all your significant contribution to such a great input method.
Have a nice day 😁.
