### ISSUE TITLE
鼠鬚管設置問題

### ISSUE THREAD

**Issue by asphoa** [rime/squirrel#198]
我剛下載了 0.9.26.1 版本，在 HIGH SIERRA 10.13.4中，設置 cangjie5.schema.custom.yaml 無效：
patch:
  translator：
    enable_sentence: false
    max_phrase_length: 1
    enable_sentence: false
  
  abc_segmentor:
    extra_tags: {}
文件名改成 cangjie5.custom.yaml 也是一樣。

在 installation.yaml 加了兩行：
installation_id: "asphoa"
sync_dir: "/Users/asphodelos/Library/Mobile/Documents/com~apple~CloudDocs/Squirrel"
 也沒有作用。

但在 squirrel.custom.yaml 中設置卻見效了：
patch:
  style:
    font_point: 20
    color_scheme: native
    font_face: 'Noto Sans CJK KR'

我的目的是：
1）倉頡打單字，不要拼音混打，不要生成詞組和句子，僅靠「`」來查詢不會打的字的倉頡碼；
2）想讓 icloud 同步用戶設置文件；
3）最好能實現目前 macOs 上單按一下 Caps Lock 轉囘到 ABC 擴展鍵盤。

不知目前錯在哪裡， 希望幫助，先謝了！

**Comment by lotem** [comment]
把 patch 寫在 `cangjie5.custom.yaml`

**Comment by asphoa** [comment]
感謝囘復！

我試成功 installation.yaml 中的雲同步設置了。

但將 patch 寫入 `cangjie5.custom.yaml`、無論是否刪除`cangjie5.schema.custom.yaml`、重新部署後仍不見效。

我的「用戶設定」文件夾中幷沒有一個`cangjie5.yaml`。

也試了將`cangjie5.schema.yaml`改名爲`cangjie5.yaml`，重新部署，程序又自動生成了一個`cangjie5.schema.yaml`，`cangjie5.custom.yaml`的設置也仍不見效。

我的「用戶設定」文件夾：
<img width="238" alt="captura de pantalla 2018-04-11 a las 13 50 51" src="https://user-images.githubusercontent.com/6508806/38604909-6f7ca58a-3d8f-11e8-908a-6123450767cc.png">

`cangjie5.custom.yaml`中的設置（格式都是照介紹中所寫）：
patch:
  translator：
    enable_sentence: false
    max_phrase_length: 1
    enable_sentence: false
  abc_segmentor：
    extra_tags: {}

我將所有用戶設置文件都放在了 Dropbox 上： https://goo.gl/Nw8v1h

如有空，還請再幫我看看。

**Comment by Icermli** [comment]
我想问一下菜单里的`Sync user data`是在干什么？往哪里sync？

**Comment by yakirChen** [comment]
> 我想问一下菜单里的`Sync user data`是在干什么？往哪里sync？

$HOME/Library/Rime

可以修改`installation.yml`
```yaml
installation_id: "xxx"
sync_dir: "/a/b/c"
```
完整路径 `/a/b/c/xxx`

**Comment by lotem** [comment]
參考文檔：

@asphoa 
https://github.com/rime/home/wiki/CustomizationGuide#%E5%AE%9A%E8%A3%BD%E6%8C%87%E5%8D%97
YAML map 的 key 不可重複

@yakirChen 
https://github.com/rime/home/wiki/UserGuide#%E5%90%8C%E6%AD%A5%E7%94%A8%E6%88%B6%E8%B3%87%E6%96%99
