### ISSUE TITLE
高内存占用

### ISSUE THREAD

**Issue by 1900forever** [rime/squirrel#202]
![screen shot 2018-04-15 at 11 01 11](https://user-images.githubusercontent.com/3516677/38774495-14c81a50-409d-11e8-8f0c-87594233cf02.jpg)
最新源码自行编译的

**Comment by lotem** [comment]
疑似問題：  https://github.com/rime/squirrel/issues/134

**Comment by summear** [comment]
我也遇到了同样的问题，结束进程重启后恢复正常，过段时间又会涨到250-300M左右的占用

**Comment by lotem** [comment]
偶现。
没有测出内存泄漏。
发现重现条件再研究。
