### ISSUE TITLE
关于生成bin文件的问题

### ISSUE THREAD

**Issue by capoeira-7** [rime/squirrel#204]
前几天看文章介绍，下载了小狼毫和鼠须管。
输入法默认是不带五笔输入方案的，在折腾了几天后有点要放弃了（文档很长，而且对于有初步程序基础的人来说都看起来挺吃力的），后来windows版本升级，可以有用户界面选择来安装五笔输入了，解决了小狼毫的五笔输入问题。

那么鼠须管要怎么安装五笔输入方案呢？
文档中给的解释是修改配置文件，然后重新部署。
所以下载了wubi86相关的4个yaml文件放在了/user/username/Library/Rime/目录下
wubi86.dict.yaml
wubi86.schema.yaml
wubi_pinyin.schema.yaml
wubi_trad.schema.yaml

修改default.yaml中schema_list段
添加了“- schema: wubi86”
重新部署
但始终没有生成任何wubi相关的bin文件，也就是通过部署wubi86.dict.yaml并没有编译成bin文件

请教一下大家到底问题是出在哪里呢，bin文件不是通过重新部署生成的吗？

**Comment by capoeira-7** [comment]
或者是缺少什么库或软件的支持吗？比如必须要安装某些C语言程序包？

**Comment by lotem** [comment]
tooold
无法重现
先关闭了
