### ISSUE TITLE
自己编译的话，难道没法切换五笔输入法？

### ISSUE THREAD

**Issue by amdth** [rime/squirrel#207]
<img width="548" alt="2018-04-22 8 13 37" src="https://user-images.githubusercontent.com/12285129/39089977-185f2786-4605-11e8-925d-806e2151807d.png">

**Comment by amdth** [comment]
@mxclover  编辑default.custom.yaml文件，重新部署，接下来就和你一样的问题了：能切换但是无法打出五笔。
<img width="566" alt="2018-04-22 8 23 58" src="https://user-images.githubusercontent.com/12285129/39090056-bf2d6220-4606-11e8-9cef-bb0a6ece9db3.png">
<img width="627" alt="2018-04-22 8 25 48" src="https://user-images.githubusercontent.com/12285129/39090058-ccc3424c-4606-11e8-8f25-5569412ceaa2.png">

**Comment by mxclover** [comment]
@amdth 去 `default.yaml` 里看看，我的 `schema_list` 添加了 `double_pinyin`（自然码双拼） `luna_pinyin_simp`（明月简体中文）

![](https://ws2.sinaimg.cn/large/006tKfTcgy1fql83llmbnj30cq0g13yu.jpg)

**Comment by amdth** [comment]
添加过后有错误
<img width="325" alt="2018-04-22 10 37 50" src="https://user-images.githubusercontent.com/12285129/39090721-4f9bac88-4619-11e8-997d-4013c58a58c0.png">
接下来就是切换到五笔，但是只能打出英文。

**Comment by mxclover** [comment]
@amdth 为什么邮件里你写的这段（标红框）的在github 里没显示... 没同步过来？
 
![](https://ws1.sinaimg.cn/large/006tKfTcgy1fql8haer9nj30vp0g5q48.jpg)

**Comment by mxclover** [comment]
@amdth 那我们的情况是类似的，切换 五笔 or 双拼，都只能打出英文...

@lotem 老师，能否帮我们看一下这个问题，是否是最新版的 鼠须管 的 `BUG` ?

**Comment by amdth** [comment]
@mxclover 觉得表达的不妥，就修改了一下。
我觉得是build里面没有相关的文件的原因

**Comment by lotem** [comment]
有錯誤 請查看日誌

**Comment by amdth** [comment]
日志无法查看
<img width="571" alt="2018-04-24 12 34 54" src="https://user-images.githubusercontent.com/12285129/39140526-6e5809ca-4757-11e8-964a-41ac16de4029.png">

**Comment by yakirChen** [comment]
@amdth  请问下贵配置的是什么字体呀 很好看 😝

**Comment by amdth** [comment]
@yakir 终于有人说外观好看了，真的很感动。字体没动，就修改了一下颜色。

在 2018年4月24日週二 上午9:32，yakir <notifications@github.com> 寫道：

**Comment by nameoverflow** [comment]
日志的文件名是 `rime.squirrel.INFO` + 一串序号。

**Comment by amdth** [comment]
@nameoverflow na 你好 能具体说明一下吗？还是不知道怎么查看日志。

**Comment by lotem** [comment]
我試過了，可以切換到五筆。那就沒有 BUG 啦。至於怎麼用怎麼配置。那是另一番討論。

**Comment by amdth** [comment]
那样的话，大佬能不能告诉该怎么切换到五笔呢？找了好多资料，无果

在 2018年4月24日週二 下午8:28，佛振 <notifications@github.com> 寫道：
