### ISSUE TITLE
Squirrel输入法自动打开VoiceOver

### ISSUE THREAD

**Issue by john-shine** [rime/squirrel#208]
安装adobe creative cloud之后，就会自动打开voice over快速入门，突然念一段文字，吓死人。
控制台查看日志是Squirrel启动的，难道是Squirrel触发的？

Apr 22 16:48:57 Squirrel[523]: createSession: com.apple.VoiceOverQuickstart
Apr 22 16:48:57 Squirrel[523]: setAppOptions: com.apple.VoiceOverQuickstart

**Comment by lotem** [comment]
日誌是說在 `com.apple.VoiceOverQuickstart` 這個程序裏打開了輸入法。

**Comment by john-shine** [comment]
好的，谢谢
