### ISSUE TITLE
最新编译版，中文状态下开启大小写再关闭后无法输入中文

### ISSUE THREAD

**Issue by yai-dev** [rime/squirrel#209]
### 背景：  
中文状态下开启大小写再关闭后无法输入中文，除非重新切换到鼠须管输入法才行。  

### 环境：  
macOS 10.13.4  
鼠须管最新master分支编译版

**Comment by lotem** [comment]
疑似 https://github.com/rime/weasel/issues/167
但不符合「除非重新切换到鼠须管输入法才行」

**Comment by sunzhenyucn** [comment]
谢谢老大的回复，我会尝试先自行解决。
