### ISSUE TITLE
鼠须管在添加输入方案时会出现错误

### ISSUE THREAD

**Issue by amdth** [rime/squirrel#210]
[鼠须管日志.zip](https://github.com/rime/squirrel/files/1945217/default.zip)

**Comment by lotem** [comment]
你要用五筆吧？我猜測現在應該已經能用了。

要讓部署不報錯的話得把依賴的簡化字拼音方案一起裝上。參考
https://github.com/rime/rime-wubi

**Comment by lotem** [comment]
暂时还不能自动安装依赖项。
https://github.com/rime/plum/issues/1

**Comment by amdth** [comment]
太谢谢您了，现在已经不会报错了。
