### ISSUE TITLE
如何手动编辑词库

### ISSUE THREAD

**Issue by john-shine** [rime/squirrel#212]
请问如何编辑（修改/删除) 用户词库，我自己使用文本编辑器编辑xxx.userdb.txt文件，删除了一些错误的词条，但是选择同步用户词库之后，删除的词条又出来了。。

该如何操作呢

**Comment by john-shine** [comment]
非常感谢您的回答，这个链接我阅读过了。但是我要编辑的词条有十几二十条，而且有的编码记录很长，例如：
a a a a a a a a a a a a a a a a a a a b b b b b b bu
显然上述的方法是行不通的

**Comment by john-shine** [comment]
本地词库是 ~/Library/Rime/luna_pinyin.userdb/xxx.ldb 这个文件吗？

**Comment by lotem** [comment]
不支持手動編輯用戶詞典的內容。

----

原題中，同步會將用戶詞典及其所有備份中的內容合併。因此只刪除一份備份中的相關記錄不影響合併後的結果。

通過輸入法刪除後，纔會在用戶詞典中留下刪除該詞條的記錄。
「沒有輸入過的記錄」和「已手動刪除」是不同的。特別是在詞典同步的時候。

**Comment by john-shine** [comment]
不喜欢这个答案……准备看代码，自己搞了 /bye

**Comment by QiangF** [comment]
大师考虑把这个功能加到
https://gitlab.com/liberime/liberime

**Comment by lotem** [comment]
沒有直接編輯用戶詞典的方法。
對文本文件的編輯，最終會在導入時與用戶詞典的內容合併，因此不能有效地刪除詞條。

可以增設一個不自動上屏的輸入模式用來刪除用戶詞，最簡單的辦法是複製一份方案並禁用自動上屏。

**Comment by ooopscc** [comment]
@lotem 但是这样可能还会有另一个问题，我删除完下次输入还是会自动合成么？我在另一个repo提了这个问题，烦请看一下 https://github.com/rime/librime/issues/303

**Comment by Hermittttt** [comment]
您好，我最近遇到了类似的问题，即通过shift+del删除的词汇无法将删除同步到其他设备上。
输出的词典快照中，利用shift+del删除的自造词词条会被保留，词频降为-1，即无法出现在候选词中。但是同步功能被描述为

> 你不必擔心來自快照的詞條已存在於用戶詞典的情況；詞頻更新爲二者的較大值，其他參數亦會按照合理的算法疊加。

如果按照这样的同步规则，那么被删除的词条永远无法被更新到其他设备上，一些测试证实了实际情况下确实无法同步，不知能否添加“同步时如果词频为正则取较大值，词频为负则取较小值”的策略。

**Comment by lotem** [comment]
> 您好，我最近遇到了类似的问题，即通过shift+del删除的词汇无法将删除同步到其他设备上。
> 输出的词典快照中，利用shift+del删除的自造词词条会被保留，词频降为-1，即无法出现在候选词中。但是同步功能被描述为
> 
> > 你不必擔心來自快照的詞條已存在於用戶詞典的情況；詞頻更新爲二者的較大值，其他參數亦會按照合理的算法疊加。
> 
> 如果按照这样的同步规则，那么被删除的词条永远无法被更新到其他设备上，一些测试证实了实际情况下确实无法同步，不知能否添加“同步时如果词频为正则取较大值，词频为负则取较小值”的策略。

不用管技术上怎样处理被删除的词。
用户把他删除了，从逻辑上讲用户词典里就不再有这个词。不存在的词自然不需要同步到其他设备。

**Comment by snowman** [comment]
如何获取所有曾经输入的词?

**Comment by tristone13th** [comment]
> 輸入編碼，選字光標置於要刪除的選項上，然後按 `Shift+Delete` 或 `Control+k` 刪除。
> 
> [rime/home/wiki/UserGuide#%E5%88%AA%E9%99%A4%E8%AA%A4%E4%B8%8A%E5%B1%8F%E7%9A%84%E9%8C%AF%E8%A9%9E](https://github.com/rime/home/wiki/UserGuide#%E5%88%AA%E9%99%A4%E8%AA%A4%E4%B8%8A%E5%B1%8F%E7%9A%84%E9%8C%AF%E8%A9%9E)

请问这个快捷键可以更改嘛

**Comment by babesun** [comment]
> > > 您好，我最近遇到了类似的问题，即通过shift+del删除的词汇无法将删除同步到其他设备上。
> > > 输出的词典快照中，利用shift+del删除的自造词词条会被保留，词频降为-1，即无法出现在候选词中。但是同步功能被描述为
> > > > 你不必擔心來自快照的詞條已存在於用戶詞典的情況；詞頻更新爲二者的較大值，其他參數亦會按照合理的算法疊加。
> > > 
> > > 
> > > 如果按照这样的同步规则，那么被删除的词条永远无法被更新到其他设备上，一些测试证实了实际情况下确实无法同步，不知能否添加“同步时如果词频为正则取较大值，词频为负则取较小值”的策略。
> > 
> > 
> > 不用管技术上怎样处理被删除的词。 用户把他删除了，从逻辑上讲用户词典里就不再有这个词。不存在的词自然不需要同步到其他设备。
> 
> 可是不同步的话，其他设备输出的候选就还存在这个被删除的词，无法做到双向同步。测试了现在的rime还是这样的设计。

是的，所以目前看起来只能每个设备都去删除一次了。。。

**Comment by lotem** [comment]
又挖墳。。。

不是簡單地不同步刪除，是數據可能衝突的情況下，不同步刪除。

在已經在同步中領先的電腦上刪除，可以同步到落後的電腦。
