### ISSUE TITLE
macOS 10.13.4 , Xcode 9.3.1 编译出错

### ISSUE THREAD

**Issue by zinwalin** [rime/squirrel#215]
自己的MacBook Air编译通过, 公司的MacBook Pro失败.

RMBP➜ squirrel git:(master) >make deps
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C librime -f Makefile.xcode thirdparty
make[1]: Makefile.xcode: No such file or directory
make[1]: *** No rule to make target `Makefile.xcode'. Stop.
make: *** [librime/thirdparty/lib/libmarisa.a] Error 2

**Comment by Aben** [comment]
submodule下載了碼？

    git submodule init && git submodule update

**Comment by zinwalin** [comment]
解决了，git clone时忘记加上--recursive

**Comment by Aben** [comment]
@zinwalin 那可以关闭本issue了

**Comment by zinwalin** [comment]
Done.
