### ISSUE TITLE
[preset_color_schemes]製作了一款新皮膚，供大家選用

### ISSUE THREAD

**Issue by Aben** [rime/squirrel#217]
配置如下

    batman:
       author: "Rango <tntaben@gmail.com>"
       back_color: 0x282724
       candidate_text_color: 0x828282
       comment_text_color: 0x5F6260
       hilited_back_color: 0xFFFFFF
       hilited_candidate_back_color: 0x5F6260
       hilited_candidate_text_color: 0x03EFFD
       hilited_text_color: 0x5F6260
       name: "蝙蝠俠／batman"
       text_color: 0x828282

**Comment by Aben** [comment]
@yakirChen 這就弄
![image](https://github.com/Aben/share/blob/master/15277362038653.jpg)

**Comment by yakirChen** [comment]
配色好看的 
我也分享个😋
![鼠须管皮肤](http://yakirchen.com/imgs/squirrel-screenshot/rime_black.png)

**Comment by Aben** [comment]
感觉把issue当论坛不好，是不是应该去reddit创建一个讨论区呢？
