### ISSUE TITLE
关于鼠须管部署失败的问题

### ISSUE THREAD

**Issue by WenAlexy** [rime/squirrel#219]
要我查看日志，我也找到了地方，可无奈，点查看原身也没用，这是我的default.custom.yaml的文件，我用的是星空一道方案，项目是这个https://github.com/dzyht/rime_xkyd， 由于直接覆盖default.yaml文件会在部署后把文件放到trash文件夹中，因此我创建了default.custom.yaml文件，可创建后还是没用，依旧报错，由于看不了日志，因此来问一下。
![2018-06-24 7 57 01](https://user-images.githubusercontent.com/36525505/41814610-2fbf9a58-7785-11e8-9ecd-786514868b9f.png)
![2018-06-24 7 57 56](https://user-images.githubusercontent.com/36525505/41814615-3a27533c-7785-11e8-8935-80ded4083fac.png)
![2018-06-24 7 59 20](https://user-images.githubusercontent.com/36525505/41814618-4397ae1c-7785-11e8-972d-bf15f46563dd.png)

**Comment by WenAlexy** [comment]
之前在部署五笔的时候也遇到过同样地问题

**Comment by lotem** [comment]
有提示表示部署時發生錯誤。具體是什麼錯誤寫在日誌文件裏。

**Comment by loricheung** [comment]
把错误日志文件删除, 重启, 再部署一次. 删除时记得清空回收站

**Comment by nameoverflow** [comment]
YAML 格式错了，schema_list 后面的列表行前要再加两个空格

**Comment by lotem** [comment]
錯誤信息不詳，無復現步驟，不再跟進。
