### ISSUE TITLE
如何删除 鼠须管 的英文模式？

### ISSUE THREAD

**Issue by binlucky** [rime/squirrel#221]
一直困扰的三种状态： 鼠须管中文、鼠须管英文、macABC
鉴于mac abc 无法删除。
希望有配置文件 禁用 鼠须管英文状态。
这样也解决了部分希望在 右上角图标显示当前中英文状态的 意愿

**Comment by jixiuf** [comment]
https://github.com/rime/squirrel/wiki/实现Shift_L-按下时切换输入法即Shift_L-代替Ctrl_Space-切换系统输入法
可以实验一下，不知道最终效果如果

如 wubi_pinyin.schema.yaml
```
switches:
  - name: ascii_mode
    reset: 0
    states: [ 中文] #只保留中文输入法，避免无意间切到英文输入状态，因为我使用系统的英文输入法，还不是rime的
#   states: [ 中文, 西文 ]
#或者使用下面这种语法来打patch
# switches/@0/states:  [ 中文]
```

或者以打补丁的方式wubi_pinyin.schema.custom.yaml
```
 patch:
# switches:
#   - name: ascii_mode
#     reset: 0
#     states: [ 中文, 西文 ]
  
# wubi_pinyin.schema.yaml. 里有个reset: 奖0 改成1 就变成默认英文输入状态
# 設輸入方案裏 {name: ascii_mode} 在 switches: 列表中爲第一項，即下標 0
# 默认中文状态
  switches/@0/reset: 0
  # 默认英文状态
  # switches/@0/reset: 1

  # 只保留中文输入法，避免无意间切到英文输入状态，因为我使用系统的英文输入法，还不是rime的
  # states: [ 中文, 西文 ]
  switches/@0/states:  [ 中文]
```

**Comment by lotem** [comment]
從輸入方案 `engine/processor` 列表裏刪除 `ascii_composer`

**Comment by binlucky** [comment]
谢谢 @jixiuf @lotem

**Comment by osaso** [comment]
这样之后，就不能设置进入某APP，自动默认ENGLISH了哟

**Comment by twlz0ne** [comment]
[**@jixiuf**](https://github.com/jixiuf) commented on [Jul 1, 2018, 12:10 AM GMT+8](https://github.com/rime/squirrel/issues/221#issuecomment-401550162 "2018-06-30T16:10:53Z - Replied by Github Reply Comments"):
> [https://github.com/rime/squirrel/wiki/实现Shift\_L-按下时切换输入法即Shift\_L-代替Ctrl\_Space-切换系统输入法](https://github.com/rime/squirrel/wiki/%E5%AE%9E%E7%8E%B0Shift_L-%E6%8C%89%E4%B8%8B%E6%97%B6%E5%88%87%E6%8D%A2%E8%BE%93%E5%85%A5%E6%B3%95%E5%8D%B3Shift_L-%E4%BB%A3%E6%9B%BFCtrl_Space-%E5%88%87%E6%8D%A2%E7%B3%BB%E7%BB%9F%E8%BE%93%E5%85%A5%E6%B3%95)  
> 可以实验一下，不知道最终效果如果
> 
> 如 wubi\_pinyin.schema.yaml
> 
> ```
> switches:
>   - name: ascii_mode
>     reset: 0
>     states: [ 中文] #只保留中文输入法，避免无意间切到英文输入状态，因为我使用系统的英文输入法，还不是rime的
> #   states: [ 中文, 西文 ]
> #或者使用下面这种语法来打patch
> # switches/@0/states:  [ 中文]
> ```
> 
> 或者以打补丁的方式wubi\_pinyin.schema.custom.yaml
> 
> ```
>  patch:
> # switches:
> #   - name: ascii_mode
> #     reset: 0
> #     states: [ 中文, 西文 ]
>   
> # wubi_pinyin.schema.yaml. 里有个reset: 奖0 改成1 就变成默认英文输入状态
> # 設輸入方案裏 {name: ascii_mode} 在 switches: 列表中爲第一項，即下標 0
> # 默认中文状态
>   switches/@0/reset: 0
>   # 默认英文状态
>   # switches/@0/reset: 1
> 
>   # 只保留中文输入法，避免无意间切到英文输入状态，因为我使用系统的英文输入法，还不是rime的
>   # states: [ 中文, 西文 ]
>   switches/@0/states:  [ 中文]
> ```
> 

无论我把这段配置放在 `default.custom.yaml` 还是 `luna_pinyin.schema.custom.yaml` 它都不生效，也没有提示部署出错，不知什么原因。

[**@lotem**](https://github.com/lotem) commented on [Jul 2, 2018, 10:04 AM GMT+8](https://github.com/rime/squirrel/issues/221#issuecomment-401652387 "2018-07-02T02:04:10Z - Replied by Github Reply Comments"):
> 從輸入方案 `engine/processor` 列表裏刪除 `ascii_composer`

当我从 `luna_pinyin.schema.yaml` 的 `engine/processor` 列表裏刪除 `ascii_composer` 之后，就无法显示中文候选字了：

![rime-squirrel-chinese-candidates-disappear](https://user-images.githubusercontent.com/2653486/132486761-d0861e47-dd99-453e-a54e-f2167bd2a4f9.png)

系统&版本：

- macOS 10.12.6
- squirrel 0.15.2 + luna_pinyin

**Comment by chenba0** [comment]
> 不过似乎把ascii_composer从processors移除效果更好， 只是不知道会不会有负作用，待验证

这个方法能做到 只有中文输入, 目前还没发现什么毛病.

**Comment by MiyamoriGithub** [comment]
> 不过似乎把ascii_composer从processors移除效果更好， 只是不知道会不会有负作用，待验证

使用这个方法确实屏蔽了英文模式，不过需要注意配置文件中设置了部分app(如Spotlight，VSCode)默认使用acsii_mode，导致无法在其中输入中文，需要在squirrel.customer.yaml中给这些app打补丁
`patch:
  com.apple.Spotlight:
    inline: true`

**Comment by yzlnew** [comment]
> patch: com.apple.Spotlight: inline: true

似乎没有效果，有完整的用例吗？

**Comment by haoburongyi** [comment]
> 不过似乎把ascii_composer从processors移除效果更好， 只是不知道会不会有负作用，待验证
default.custom.yaml的Shift_L: noop#commit_code

**Comment by haoburongyi** [comment]
> [https://github.com/rime/squirrel/wiki/实现Shift_L-按下时切换输入法即Shift_L-代替Ctrl_Space-切换系统输入法](https://github.com/rime/squirrel/wiki/%E5%AE%9E%E7%8E%B0Shift_L-%E6%8C%89%E4%B8%8B%E6%97%B6%E5%88%87%E6%8D%A2%E8%BE%93%E5%85%A5%E6%B3%95%E5%8D%B3Shift_L-%E4%BB%A3%E6%9B%BFCtrl_Space-%E5%88%87%E6%8D%A2%E7%B3%BB%E7%BB%9F%E8%BE%93%E5%85%A5%E6%B3%95) 可以实验一下，不知道最终效果如果
> 
> 如 wubi_pinyin.schema.yaml
> 
> ```
> switches:
>   - name: ascii_mode
>     reset: 0
>     states: [ 中文] #只保留中文输入法，避免无意间切到英文输入状态，因为我使用系统的英文输入法，还不是rime的
> #   states: [ 中文, 西文 ]
> #或者使用下面这种语法来打patch
> # switches/@0/states:  [ 中文]
> ```
> 
> 或者以打补丁的方式wubi_pinyin.schema.custom.yaml
> 
> ```
>  patch:
> # switches:
> #   - name: ascii_mode
> #     reset: 0
> #     states: [ 中文, 西文 ]
>   
> # wubi_pinyin.schema.yaml. 里有个reset: 奖0 改成1 就变成默认英文输入状态
> # 設輸入方案裏 {name: ascii_mode} 在 switches: 列表中爲第一項，即下標 0
> # 默认中文状态
>   switches/@0/reset: 0
>   # 默认英文状态
>   # switches/@0/reset: 1
> 
>   # 只保留中文输入法，避免无意间切到英文输入状态，因为我使用系统的英文输入法，还不是rime的
>   # states: [ 中文, 西文 ]
>   switches/@0/states:  [ 中文]
> ```
> 
> 不过似乎把ascii_composer从processors移除效果更好， 只是不知道会不会有负作用，待验证
不过似乎把ascii_composer从processors移除效果更好， 只是不知道会不会有负作用，待验证
删除了之后是要打补丁，不打补丁的办法如下：
default.custom.yaml的Shift_L: commit_code改为Shift_L: noop，我是完全用不到shift所以禁用就好了，无其他副作用

**Comment by haoburongyi** [comment]
> > patch: com.apple.Spotlight: inline: true
> 
> 似乎没有效果，有完整的用例吗？

最终的解决方案在这里 https://github.com/rime/squirrel/issues/584

**Comment by ryancui92** [comment]
1. 删掉/注释掉 `luna_pinyin_simp.schema.yaml` 的 `engine/processors/ascii_composer`
2. 删掉/注释掉 `squirrel.yaml` 里的所有 `app_options`. 因为你已经不使用 Rime 的英文模式了。这样 VSCode Alfred 之类的都能输入中文了

如果有需要可以另外加一个自动切换输入法的软件。

**Comment by haoburongyi** [comment]
感谢

ryancui ***@***.***> 于2023年2月20日周一 16:48写道：

**Comment by hyec** [comment]
探索出来一个用patch、不需要修改共享配置的方法：
luna_pinyin.custom.yaml：
```yaml
patch:
  engine/processors/@0:
  switches/@0:
```

**Comment by jiangyv1718** [comment]
> 这样之后，就不能设置进入某APP，自动默认ENGLISH了哟

正好符合我的要求

**Comment by jokerhoneyyeah** [comment]
# Rime schema
# encoding: utf-8
patch:
  schema/name: 自然码
  switches:
   # - name: ascii_mode
      reset: 0
      states: [ 中文, 西文 ]

在double_pinyin.custom.yaml 目前测试结果是可以关闭英文模式，还在不知道有没有副作用

**Comment by reorx** [comment]
> 如果有需要可以另外加一个自动切换输入法的软件。

https://inputsource.pro/ 配合完美

**Comment by siropkin** [comment]
I know guys, maybe it's not the best place to put my message in, but I don't know where. I'm writing an IntelliJ plugin called Kursor that detects and displays the keyboard layout near the cursor in the IDE, and one of the layouts is Squirrel. I know how to detect it when it's in "Chinese" mode, but when the user switches it to "English" mode, I don't know how to detect it. Any help would be great https://github.com/siropkin/kursor
