### ISSUE TITLE
调用 Google IME api 来输入拼音

### ISSUE THREAD

**Issue by wjp2013** [rime/squirrel#225]
词库一直都是大问题，能否考虑像这里的做法一样，调用 Google IME api 来输入拼音呢。

https://github.com/dongyuwei/hallelujahIM/issues/24

**Comment by dongyuwei** [comment]
Android 上有 Google 拼音离线词库，词频比较精准，采用Apache License(Version 2.0)：https://android.googlesource.com/platform/packages/inputmethods/PinyinIME/+/refs/heads/master/jni/data/rawdict_utf16_65105_freq.txt

我有个web 版拼音输入法项目使用了这个词库： https://github.com/dongyuwei/web-pinyin-ime

**Comment by lotem** [comment]
@wjp2013 請創作一個單獨的項目，以 [Rime插件](https://github.com/rime/librime/tree/master/sample) 形式實現該功能。

**Comment by lotem** [comment]
相同問題 https://github.com/rime/home/issues/44 https://github.com/rime/weasel/issues/3
