### ISSUE TITLE
Changing IME by using Caps Lock

### ISSUE THREAD

**Issue by lifehome** [rime/squirrel#228]
Since macOS Sierra, users can switch to non-latin input method using Caps Lock. However after installing Squirrel, I cannot do so, nor the Caps Lock IM switch option appeared in the system preferences....

So I am hoping there can be such feature, to cater the IME switching use case.

**Comment by DbArl** [comment]
I hope so. and hope add long click Cpas custom.

**Comment by hellotanuky** [comment]
You can use Karabiner-Elements( https://github.com/tekezo/Karabiner-Elements ) to modify Caps Lock to `F18` then change `System Preferences - Keyboard - Input Sources - Select blabla` to F18.
If you don't want to install a third party software, you can use internal command `hidutil` to do the same thing. See https://apple.stackexchange.com/questions/256342/use-caps-lock-to-switch-to-and-from-languages-on-sierra

**Comment by yycking** [comment]
[just add flow to info.plist](https://developer.apple.com/documentation/bundleresources/information_property_list/ticapslocklanguageswitchcapable?language=objc)
`<key>TICapsLockLanguageSwitchCapable</key> <true/>`

**Comment by DbArl** [comment]
> [just add flow to info.plist](https://developer.apple.com/documentation/bundleresources/information_property_list/ticapslocklanguageswitchcapable?language=objc)
> `<key>TICapsLockLanguageSwitchCapable</key> <true/>`
> 
> I did a test on my mac
> [#375 (comment)](https://github.com/rime/squirrel/issues/375#issuecomment-552323087)

Tx.

**Comment by lotem** [comment]
同 https://github.com/rime/squirrel/issues/375
