### ISSUE TITLE
希望有能够获取中英文状态的接口之类的。

### ISSUE THREAD

**Issue by mpco** [rime/squirrel#229]
看到开发者不喜欢中英文状态栏标识。
但是希望有能够获取中英文状态的接口之类的。
或者能否在 Squirrel 切换中英文状态时，运行一个自定义命令、将状态写入某文件或发送一个http请求之类的。
然后，让用户自己根据需要进行配置。

**Comment by jixiuf** [comment]
https://github.com/jixiuf/squirrel/releases

**Comment by nameoverflow** [comment]
@jixiuf 这个不错啊
cc @lotem

**Comment by songxing10000** [comment]
@jixiuf 厉害啊
