### ISSUE TITLE
Wiki：禁用 Squirrel 英文模式，使用左侧 Shift 切换 Squirrel 与系统英文输入法。

### ISSUE THREAD

**Issue by mpco** [rime/squirrel#230]
配置前：Squirrel 中英，系统英文输入法等三个状态，很混乱。
配置后：Squirrel 中文，系统英文输入，左侧 Shift 切换。

[禁用 Squirrel 英文模式，使用左侧 Shift 切换中英 · rime/squirrel Wiki](https://github.com/rime/squirrel/wiki/%E7%A6%81%E7%94%A8-Squirrel-%E8%8B%B1%E6%96%87%E6%A8%A1%E5%BC%8F%EF%BC%8C%E4%BD%BF%E7%94%A8%E5%B7%A6%E4%BE%A7-Shift-%E5%88%87%E6%8D%A2%E4%B8%AD%E8%8B%B1)

Wiki 没啥人看，放在这里让更多人知道。
一个月后关闭。

**Comment by ruolis** [comment]
好像关闭之后，就不能使用：切换 app 自动切换英文/中文了

**Comment by runapp** [comment]
能问一下怎么解决小狼毫图标左侧有个“中”字导致中英文切换的时候任务栏伸缩的问题吗？
