### ISSUE TITLE
首次启动都需要部署

### ISSUE THREAD

**Issue by Sihan001** [rime/squirrel#232]
每次开机后，首次启动提示部署。所以首次都需要等待2秒左右。

**Comment by Sihan001** [comment]
虽然影响不大，在加入plum处理输入方案前的版本是没有此问题。

**Comment by lotem** [comment]
如果是全新安裝（用戶文件夾沒有舊版本生成的文件）後的表現，可能原因是
https://github.com/rime/librime/commit/68c8a344739c70978a0de0fc47e0f13988c0340e

**Comment by lotem** [comment]
同 https://github.com/rime/squirrel/issues/271

通過 https://bintray.com/rime/squirrel/testing/0.11.0%2Bgit2d387d0 驗證已修復
