### ISSUE TITLE
有一个方言汉字打不出来

### ISSUE THREAD

**Issue by snowxuyu** [rime/squirrel#235]
在mac OS 上面试用鼠须管输入法 “剋” 这个字 打不出来，拼音是kei

**Comment by zhouyisu** [comment]
我可以打出来，繁体就有。

**Comment by songxing10000** [comment]
五笔可以 打出来
![image](https://user-images.githubusercontent.com/10040131/44791356-0465d880-abd4-11e8-990c-12f2f2e7d4a1.png)

**Comment by yakirChen** [comment]
![image](https://user-images.githubusercontent.com/22702893/44824932-a6b8a700-ac3a-11e8-87d1-072e6b983673.png)
繁體可以

**Comment by Prcuvu** [comment]
朙月拼音、地球拼音和袖珍简化字拼音方案全部兼收了“剋”的 kè、kēi 二音。

**Comment by lotem** [comment]
被繁簡轉換消除了
