### ISSUE TITLE
Mac 版QQ，微信无法上屏

### ISSUE THREAD

**Issue by northleafup** [rime/squirrel#238]
Mac os 升级到最新的mojava版后，在切换到QQ或者微信时，输入汉字时无法上屏，需要点击重新部署后才能将汉字上屏，这个是什么情况。

**Comment by xiehuc** [comment]
我这边貌似没问题，用的是最新编译版本。官网的包的确太老了，感觉需要重新打包下。

**Comment by northleafup** [comment]
我这边是只有QQ 和微信有这个问题，别的软件就没有问题

**Comment by Voleking** [comment]
你也没提供 Squirrel 版本信息啊 @northleafup

**Comment by northleafup** [comment]
@xiehuc
@Voleking
我刚才再一次测试发现，我安装系统自带的五笔型输入法，在QQ 及微信上也会偶尔出现这个问题，所以应该不是鼠须管的问题
我电脑的版本是： Mac的最新版，鼠须管是0.9.26.2(最新版）

**Comment by northleafup** [comment]
@xiehuc
@Voleking
我刚才再一次测试发现，我安装系统自带的五笔型输入法，在QQ 及微信上也会偶尔出现这个问题，所以应该不是鼠须管的问题
我电脑的版本是： Mac的最新版，鼠须管是0.9.26.2(最新版）

**Comment by jasonlam-swatow** [comment]
我也有這個問題。是更新 Mojave 之後。鼠鬚管 0.9.26.1（「檢查新版本」說是最新版）。

**Comment by northleafup** [comment]
我无法舍弃鼠须管，鉴于我的电脑还有一些其它的问题，严重影响到了我，所以我把系统重装了，还原到了10.13（10.13上鼠须管无问题），还希望各位能帮忙解决一下此问题。
谢谢。

**Comment by Voleking** [comment]
我清盘升的 macOS Mojave，没遇到什么问题

**Comment by kenmjlee** [comment]
我也是只有微信和QQ 才有。
Mac的最新版，鼠须管是0.9.26.2（但check for update依然显示是0.9.26.1）

**Comment by nyaapass** [comment]
应该不是输入法的问题 (我用系统自带输入法和搜狗也有相同的问题), 是 QQ 和微信没有适配新版本.

现在若是通过从屏幕上方点击 QQ 和微信的图标的方式来打开应用, 就无法正常输入中文.

但若是通过 `tab + command` 或者是下方程序坞来打开, 则可以正常输入中文.

**Comment by northleafup** [comment]
@nyaapass 
 等QQ和微信彻底解决了这个问题我再考虑升系统版本

**Comment by rainplus** [comment]
这个问题应该不是鼠須管的问题,因为我使用了其他的输入法也遇到了
