### ISSUE TITLE
MacBook Pro 遇到编译错误问题

### ISSUE THREAD

**Issue by sef7uba** [rime/squirrel#244]
/Library/Developer/CommandLineTools/usr/bin/make -C librime -f Makefile.xcode release
cmake . -Bxbuild -GXcode -DBUILD_STATIC=ON -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON
CMake Error:
  Xcode 1.5 not supported.

CMake Error: Could not create named generator Xcode

Generators
  Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  Xcode                        = Generate Xcode project files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.

make[1]: *** [release] Error 1
make: *** [librime] Error 2

---------------------
cmake version 3.12.2
CMake suite maintained and supported by Kitware (kitware.com/cmake).

xcode-select version 2349.

**Comment by lotem** [comment]
Via google search:
https://wiki.vcmi.eu/How_to_build_VCMI_(macOS)#Setting_Xcode_version_Xcode
