### ISSUE TITLE
同时使用大词典和小词典的时候部署过慢

### ISSUE THREAD

**Issue by Oyami-Srk** [rime/squirrel#246]
一个输入法只能使用一个词典，所以通过`import_tables`的方法挂载了多个词典
但是存在一个用户自定义的user_phrase.dict.yaml词典可能需要经常更新
但是部署就需要从头将导入的外部大词典（这些是一般不会出现改动）和用户自定义的小词典一起重新编译，就十分花时间
有没有其他方法来导入用户词典呢？

P.S. 利用custom_phrase会让用户定义的词汇会出现在首位候选，需要的就是单纯能联想出用户定义过的词汇就可以了。

**Comment by lotem** [comment]
把需要經常更新的詞典分開也可以。只是這些詞不能參與造句。

**Comment by Oyami-Srk** [comment]
感谢@lotem 的帮助，Rime是我用过最棒的输入工具了！

**Comment by ksqsf** [comment]
@faywong 使用 https://github.com/rime/home/wiki/DictionaryPack 功能

把对应的 dictionary 写到 translator/packs 下即可。
