### ISSUE TITLE
请问鼠须管如何删除自定义词组？

### ISSUE THREAD

**Issue by sungnix** [rime/squirrel#248]
想要删掉不小心输入的错误词组，
类似于搜狗输入法的「快捷删词」快捷键：
https://jingyan.baidu.com/album/636f38bb4276e6d6b84610c1.html?picindex=4

**Comment by songxing10000** [comment]
/Users/mac/Library/Rime/sync/ff6b4aa9-a787-4e13-918a-12399d3d1975/wubi86.userdb.txt
这个文件里有自动造的词语

**Comment by sungnix** [comment]
删除里面的自定义词组并Depoy后，
还是可以打出被删除的词组，
这个方法还想没有效果。

**Comment by martinmts** [comment]
请问这个问题有解决掉吗？我也碰到这样的问题。已经从用户词典里删除了那个词组，而且已经重新布署过，但是这个词组仍然出现在候选框中。

我看到手册中有提到：
>刪除誤上屏的錯詞
不慎上屏了錯誤的詞組，再打同樣的編碼時，那錯詞出現在候選欄，令有潔癖的同學十分不爽。這時候可以：
>
>先把選字光標（用上、下鍵）移到要刪除的用戶詞組上，再按下 Shift+Delete 或 Control+Delete（蘋果鍵盤用 Shift+Fn+Delete）。

这个说明让人有些困惑。什么叫做 `先把選字光標（用上、下鍵）移到要刪除的用戶詞組上`？假设词组由三个字组成，把光标移到哪里才算是移到用户词组上？我用的是 Mac，`Shift+Fn+Delete`是删除光标后的一个字。我试过把光标移动到词组最前面，中间，或者把词组选中后再删除，这些操作都只能正常删除光标之后的字，似乎和输入法本身并没有关系。

我不太明白的是：为什么已经从用户词典文档里删除了那个词组，并且重新布署过了，这个词组还是会出现在候选框中？输入法又是从哪里调用到这个词组的，难道不是从用户词典文档中调用的吗？
