### ISSUE TITLE
EXCEL输入中文时会带出英文字符

### ISSUE THREAD

**Issue by stone222** [rime/squirrel#249]
MacOs 10.14.1
Excel 16.13.1

输入法方案为wubi_pinyin

只要配置了
 style/inline_preedit: false

输入中文时会带出英文字符

举个例子
输入工作，五笔输入是aawt，实际输出字符为“工作wt”
输入明天，五笔输入是jegd，实际输出字符为“明天gd”

**Comment by zqjimlove** [comment]
+1 word 也会

**Comment by PCanyi** [comment]
+1，我发现，如果打得特别快就不会带出来，一旦有停顿就会带出来。我是在excel上测的。

**Comment by LEOYoon-Tsaw** [comment]
用最新的Excel(16.72)沒有發現這個問題
