### ISSUE TITLE
Dark 模式下输入框的黑边

### ISSUE THREAD

**Issue by kuoruan** [rime/squirrel#250]
OSX 10.14 引入了深色模式，在该模式下，主题的边框颜色不起作用了。
浅色模式：
![2018-11-14 13 32 53](https://user-images.githubusercontent.com/8685618/48462298-92844f00-e812-11e8-95c1-4ea7514f7e3b.png)
深色模式：
![2018-11-14 13 34 23](https://user-images.githubusercontent.com/8685618/48462317-a2039800-e812-11e8-9233-d746f31e6d38.png)

**Comment by xiehuc** [comment]
这个貌似系统加的黑边。自带输入法也有的，其它窗口也有的。改不掉

**Comment by lotem** [comment]
如果是系统绘制的阴影区域，那确实去不掉。这时候应该响应系统设置，搭配暗色的背景。比如就用默认的配色，可以自动适配系统主题色。

**Comment by nekolab** [comment]
同样在系统的Dark Mode下，0.9.26是没有这个黑边的，同时系统自带的输入法（白色底色）也没有这个黑边

我倾向于认为这个黑边是由 @xiehuc 贡献的代码引入的，但苦于不会写Obj-C，不知可否烦请 @xiehuc 和 @lotem 再研究一下

感谢

**Comment by kuoruan** [comment]
这里有许多讨论：

https://github.com/electron/electron/issues/13164

主要是由于 ```NSRequiresAquaSystemAppearance``` 这个 Key

VSCode 的解决方案：

https://github.com/Microsoft/vscode/pull/59742

https://github.com/electron/electron/pull/14755

**Comment by lotem** [comment]
Opted out dark mode according to
https://developer.apple.com/documentation/appkit/nsappearancecustomization/choosing_a_specific_appearance_for_your_app

**Comment by xiehuc** [comment]
黑边跟我那代码没关系，你darkmode下app都加黑边。

可以尝试用https://github.com/zenangst/Gray
这个软件可以为每个app指定主题，把rime设置成亮色主题就没黑边了，应该 @nekolab

**Comment by lotem** [comment]
可能在輸入法裏完全禁用 dark mode 是最好的。

---

根據配色方案動態設置 appearance
https://github.com/rime/squirrel/tree/dark-mode
只讓 `native` 配色方案支持適配明、暗色，而且做的過程中發現取系統默認顏色的代碼很亂，需要大幅重構才能支持用戶切換明、暗色後立即生效。我打算先擱置這個解決方案。

**Comment by xiehuc** [comment]
是, 因为会有需求:
配色随系统变化而变化
系统亮色主题下用黑色主题
系统黑色主题下用亮色主题

能代码里面标识不需要darkmode最好的了.

**Comment by nekolab** [comment]
@xiehuc 那为什么0.9.26在Dark Mode下是没有黑边的啊？

**Comment by xiehuc** [comment]
我猜的是, 编译的xcode太老了, 或者target os太老了. 所以启用了系统的兼容方案, 就是认为旧APP只有白色模式.

**Comment by lotem** [comment]
所以，讓讓輸入法默認配色永遠是亮色，沒問題吧？

**Comment by xiehuc** [comment]
同感，没问题????
________________________________

**Comment by lovelock** [comment]
我做了兩個配色方案，基本和原生的輸入法一樣，截圖放在這裏

<img width="309" alt="image" src="https://user-images.githubusercontent.com/2208731/71305795-c36e8480-2413-11ea-8ec4-5bfe6668640c.png">

<img width="302" alt="image" src="https://user-images.githubusercontent.com/2208731/71305805-db460880-2413-11ea-88c3-66a892415f09.png">

希望能有一個開關能識別到當前的App是在哪種模式下，然後在已經設定的兩個方案內自動切換。

**Comment by lotem** [comment]
已由 https://github.com/rime/squirrel/pull/449 解決
