### ISSUE TITLE
在某些应用中无法退格或使用方向键

### ISSUE THREAD

**Issue by CRH6F-A-0464** [rime/squirrel#252]
在某些应用中（如Chrome的搜索栏）一旦点按退格（backspace）和方向键将会导致输入法消失。

![screenflow](https://user-images.githubusercontent.com/22784008/48980220-46ce8100-f101-11e8-90a8-7d358babd2fb.gif)

**Comment by trainchou** [comment]
![bug](https://user-images.githubusercontent.com/3922020/49064435-e43ac980-f255-11e8-8c5d-e461190d7b72.gif)
Same here.

**Comment by songxing10000** [comment]
的确，输入时按方向键会有问题。不过对于打五笔的人来说问题不大，几乎不按方向键，偶尔有重名字，顶多按下 `1` 、 `2`

**Comment by AndyChen2005121** [comment]
@songxing10000 是的，但有时候却不会出现这个问题（比如Github的issues回复框）。所以我怀疑这是bug。

**Comment by burning** [comment]
同样得bug，主要实在chrome地址栏出现

**Comment by Wujidadi** [comment]
目前鼠鬚管仍有此問題，主要發生在 Chrome 地址欄，Safari、Firefox 均不見此情況
若按照[此篇](https://github.com/rime/home/issues/267)中 lanjuzi 提到的：設定 `inline_preedit` 為 `true`，的確可以避免此問題，但不知是否治標不治本

**Comment by ballII** [comment]
目前鼠鬚管（0.14.0）在Chrome（80.0.3987.149）地址欄仍有此問題。在 squirrel.custom.yaml 中設定 `inline_preedit` 為 `true`，仍無法避免此問題。

（Mac版本：10.10.5）

**Comment by lotem** [comment]
同 https://github.com/rime/home/issues/267
