### ISSUE TITLE
MacOS系统 Sublime Text 3 全屏状态下，输入不上屏

### ISSUE THREAD

**Issue by iahu** [rime/squirrel#253]
进入 Sublime 的全屏状态（View->Full Screen那个，非系统那的），输入不上屏。退出全屏后在整个 Sublime 任一 Tab 下依然如此。

另外，鼠须管的系统图标状态是这样的
![image](https://user-images.githubusercontent.com/1704588/49139253-3f3ef000-f32c-11e8-87f4-31fced867008.png)

**Comment by tiglog** [comment]
这应该是输入法崩溃了，自己换字体后会经常发生。

**Comment by oldcai** [comment]
Duplicate of #317
