### ISSUE TITLE
最新源码编译失败

### ISSUE THREAD

**Issue by Howard-00** [rime/squirrel#254]
如题，10.14.1，按照GitHub上教程编译的，安装相关开发工具用的Macports，编译后提示错误：
Ld /Users/hc/Library/Developer/Xcode/DerivedData/Squirrel-dvesowfsoeeylkbrlmlewsycceui/Build/Products/Debug/Squirrel.app/Contents/MacOS/Squirrel normal x86_64 (in target: Squirrel)
    cd /Users/hc/tmp/squirrel
    export MACOSX_DEPLOYMENT_TARGET=10.7
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -L/Users/hc/Library/Developer/Xcode/DerivedData/Squirrel-dvesowfsoeeylkbrlmlewsycceui/Build/Products/Debug -L/Users/hc/tmp/squirrel/lib -F/Users/hc/Library/Developer/Xcode/DerivedData/Squirrel-dvesowfsoeeylkbrlmlewsycceui/Build/Products/Debug -F/Users/hc/tmp/squirrel -F/Users/hc/tmp/squirrel -F/Users/hc/tmp/squirrel -filelist /Users/hc/Library/Developer/Xcode/DerivedData/Squirrel-dvesowfsoeeylkbrlmlewsycceui/Build/Intermediates.noindex/Squirrel.build/Debug/Squirrel.build/Objects-normal/x86_64/Squirrel.LinkFileList -Xlinker -rpath -Xlinker @loader_path/../Frameworks -Xlinker -rpath -Xlinker @loader_path/../Library/OpenSource -Xlinker -rpath -Xlinker @loader_path/../Library/Frameworks -Xlinker -rpath -Xlinker /usr/lib -Xlinker -rpath -Xlinker /usr/local/lib -mmacosx-version-min=10.7 -Xlinker -object_path_lto -Xlinker /Users/hc/Library/Developer/Xcode/DerivedData/Squirrel-dvesowfsoeeylkbrlmlewsycceui/Build/Intermediates.noindex/Squirrel.build/Debug/Squirrel.build/Objects-normal/x86_64/Squirrel_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -lrime.1 -framework Cocoa -framework InputMethodKit -framework Carbon -framework Sparkle -Xlinker -dependency_info -Xlinker /Users/hc/Library/Developer/Xcode/DerivedData/Squirrel-dvesowfsoeeylkbrlmlewsycceui/Build/Intermediates.noindex/Squirrel.build/Debug/Squirrel.build/Objects-normal/x86_64/Squirrel_dependency_info.dat -o /Users/hc/Library/Developer/Xcode/DerivedData/Squirrel-dvesowfsoeeylkbrlmlewsycceui/Build/Products/Debug/Squirrel.app/Contents/MacOS/Squirrel

ld: library not found for -lrime.1
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by lotem** [comment]
按照 https://github.com/rime/squirrel/blob/master/INSTALL.md 操作，沒有重現以上結果。題主可能採取了不同的操作步驟。
