### ISSUE TITLE
最新这次代码安装成功却显示报错

### ISSUE THREAD

**Issue by yanhuacuo** [rime/squirrel#262]
编译无报错，打包没问题，最后取得的「zip」包解压出PKG文件安装时提示「安装失败」，但实际上，安装是成功的（ 现在就在用着 ）

![安装失败](https://raw.githubusercontent.com/yanhuacuo/98WB/master/issues/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-12-29%20%E4%B8%8B%E5%8D%886.21.19.png)

**Comment by yanhuacuo** [comment]
删除下面这行新添的代码后，实测再打包的 PKG 包即可消除这个不实的「报错」。

**Comment by lotem** [comment]
@yanhuacuo 幫幫忙，貼出來這兩條命令的輸出。

```bash
git --version
ls $HOME/Library/Rime
```

**Comment by lotem** [comment]
沒有研究具體的失敗原因，不過因爲要把輸入法安裝到 `/Library`，pkg 安裝器是在高權限下執行，而且安裝程序的執行環境也比較特別。而下載的配方包以及 `plum` 代碼庫都可以重用，留在用戶目錄下比較好。我看可以在輸入法首次運行的時候執行，能滿足多用戶的場景。

**Comment by Secbone** [comment]
了解了，这样的话，可以在安装时默认为用户安装上 /plum/ 命令行工具，第一次运行时使用 /plum/ 安装默认配置，之后用户再可以用 /plum/ 命令行加载个性配置。

**Comment by yanhuacuo** [comment]
> 了解了，这样的话，可以在安装时默认为用户安装上 /plum/ 命令行工具，第一次运行时使用 /plum/ 安装默认配置，之后用户再可以用 /plum/ 命令行加载个性配置。

希望不要使 RIME 一开始就默认下载各种方案啊，真的完全不需要一安装完毕就**静默去联网**下载一堆根本不可能用得到的方案啊。

**Comment by lotem** [comment]
將來可以做個小號的初始設置介面吧，提示用戶選方案，或者指定自己維護的配方列表。
