### ISSUE TITLE
升级 Squirrel 版本 0.10.0 后 VSCode 中无法输入中文

### ISSUE THREAD

**Issue by nonoroazoro** [rime/squirrel#264]
升级 Squirrel 版本 0.10.0 之后，无法在 VSCode 中输入中文，在浏览器等地方可以输入。

另外，请教如何回滚 Squirrel 版本?

**Comment by alex-the-man** [comment]
Rollback: https://bintray.com/lotem/rime/Squirrel/0.9.26.2

**Comment by nonoroazoro** [comment]
感谢！

**Comment by lotem** [comment]
未重現報告中的問題：
Squirrel 0.10.0
Visual Studio Code Version 1.30.1 (1.30.1)
macOS 10.14.2 Beta (18C38b)

**Comment by lotem** [comment]
題主是否未注意到這項功能：
https://github.com/rime/home/wiki/CustomizationGuide#%E5%9C%A8%E7%89%B9%E5%AE%9A%E7%A8%8B%E5%BA%8F%E8%A3%8F%E9%97%9C%E9%96%89%E4%B8%AD%E6%96%87%E8%BC%B8%E5%85%A5

**Comment by nonoroazoro** [comment]
@lotem 这个我确实检查过配置了，相同的配置文件，我回滚到老版本就好了，新版本就不能用。

**Comment by nonoroazoro** [comment]
@lotem 稍后我编辑这个回复，给你列个步骤~

**Comment by nonoroazoro** [comment]
@lotem 不好意思，最近有点忙，就把这事给忘记了。具体步骤如下：

1. 原本是 0.9.26.2 版本（经测试在 VSCode 下正常，其他应用下也正常，其实这个版本我已经用了很久了，没遇到过任何问题）。
2. 直接安装 0.10.0 升级，重新部署后在 VSCode（版本 1.30.2） 下尝试输入中文时，出来的都是英文字母，并且候选框也不会出现，但是在 Firefox 下面却能正常输入中文。
3. 然后，我直接把 @alex-the-man 给我的版本替换掉 0.10.0 再重新部署后就能正常使用了。

**Comment by lotem** [comment]
怎樣“尝试输入中文”？切換到中文模式了嘛？

**Comment by nonoroazoro** [comment]
@lotem 对的，先切换输入法到 Squirrel，然后尝试输入，但是在 VSCode 下面就是不出现中文候选框，只会直接输入英文字母。

**Comment by Lursun** [comment]
@nonoroazoro 
com.github.electron
![image](https://user-images.githubusercontent.com/11616295/58500765-67ad8700-81b5-11e9-988a-ff30a2e81204.png)

**Comment by icaibird** [comment]
这个问题我也遇到了，不是100%不出现的，可能开始正常，但是不知道什么时候就出问题了，怎么都不出中文框。最开始出现问题，配置文件里加了这个  "com.microsoft.VSCode:ascii_mode": false，重新同步用户文件后好用了，第二天下午不知道怎么又不能输入中文了。

**Comment by icaibird** [comment]
"com.microsoft.VSCode/ascii_mode": false 好用了，之前配置写的有问题。

**Comment by williampan** [comment]
`com.microsoft.VSCode` 沒錯，若要找別的程式的 bundle identifier 可在 Terminal 打 `osascript -e 'id of app "程式名稱"'`。
https://robservatory.com/easily-see-any-apps-bundle-identifier/

**Comment by CodeDreamfy** [comment]
我也有同样的问题：
鼠须管: 0.16.2
vscode：1.80.0 
MacOS：13.4.1
其他软件都可以，除了在vscode中，鼠须管完全什么都不起作用，不论中文英文，除非tab切换到美国键盘
![image](https://github.com/rime/squirrel/assets/7604937/ca5d386c-e9db-45b9-958a-9d8f19359968)
![image](https://github.com/rime/squirrel/assets/7604937/ca26172e-025e-4567-94f3-5154b36c5071)
