### ISSUE TITLE
更新到 0.10.0 后报错

### ISSUE THREAD

**Issue by zhangao0086** [rime/squirrel#266]
更新之后 Deploy 报错：
![image](https://user-images.githubusercontent.com/7742344/50622647-c7c33880-0f49-11e9-817b-a99ffddbe013.png)

下载 pkg 重新安装也不行，附上 `rime.squirrel.ERROR` 文件：
https://gist.github.com/zhangao0086/457165385fe77a60b4a0c6be05c0475f

**Comment by nashxk** [comment]
相同的错误，我是重新安装了上个版本了。

**Comment by arking7** [comment]
配置文件路径变了，自定义码表要放在 /Library/Input Methods/Squirrel.app/Contents/SharedSupport 下

**Comment by lotem** [comment]
> 配置文件路径变了，自定义码表要放在 /Library/Input Methods/Squirrel.app/Contents/SharedSupport 下

不是這樣的。用戶自定義文件請放在 `~/Library/Rime` 文件夾。詳見 https://github.com/rime/home/wiki/UserData

**Comment by lotem** [comment]
題主遇到的問題，是因為這個版本裏五筆輸入方案不再預裝：
> 精簡安裝包預裝的輸入方案，更多方案可由 [東風破](https://github.com/rime/plum) 取得

安裝命令：
```sh
curl -fsSL https://git.io/rime-install | bash -s -- wubi pinyin-simp
```

**Comment by zhangao0086** [comment]
> 題主遇到的問題，是因為這個版本裏五筆輸入方案不再預裝：
> 
> > 精簡安裝包預裝的輸入方案，更多方案可由 [東風破](https://github.com/rime/plum) 取得
> 
> 安裝命令：
> 
> ```shell
> curl -fsSL https://git.io/rime-install | bash -s -- wubi pinyin-simp
> ```

确实有用

**Comment by lotem** [comment]
@Ironaki 我查了一下，確實 `pinyin-simp` 依賴於 `stroke` 做反查。不過依賴項不存在時只輸出一條警告 LOG，不會導致部署失敗報錯吧？

**Comment by lotem** [comment]
呃……果然會報錯的。
因爲 /plum/ 不會自動安裝依賴的配方包，而預裝的數據是最精簡的版本。依賴管理是個複雜的問題。我再考慮一下。

**Comment by Ironaki** [comment]
> @Ironaki 求證一下，缺少 `stroke` 是否報錯（部署結束顯示有錯誤）。
> 
> 我又實驗了一次，全新安裝後啓用 `wubi_pinyin`，只須安裝 `wubi pinyin_simp` 兩則配方即可通過部署。
> 也對照了代碼，啓用的方案（如 `wubi_pinyin`）的直接依賴（`pinyin_simp`）未安裝時，部署會失敗，而依賴項（`pinyin_simp`）的依賴（`stroke`）不需要安裝。
> 
> 如果 `stroke` 阻礙部署成功，是否在 `schema_list` 直接裏啓用了 `pinyin_simp` 或其他直接依賴於 `stroke` 的方案？

可能是因为我使用了小鹤双拼和 `pinyin_simp`，需要 `stroke`？
