### ISSUE TITLE
0.10.0 缺少用户自定义文件的存放目录

### ISSUE THREAD

**Issue by arking7** [rime/squirrel#267]
抱歉，是我搞錯了，應該是默認打包的輸入方案變了造成的。

**Comment by lotem** [comment]
沒有改變。
用戶自定義文件請放在 `~/Library/Rime`

**Comment by arking7** [comment]
抱歉，是我搞錯了，應該是默認打包的輸入方案變了造成的。

**Comment by arking7** [comment]
又尝试了一下从旧版本升级，原配置文件都被移动到了 trash 下，请问究竟应该怎么迁移旧版本的自定义输入方案？
