### ISSUE TITLE
0.10版本五笔输入法错误

### ISSUE THREAD

**Issue by imshenshen** [rime/squirrel#268]
0.10版本五笔输入法错误
之前可以使用z反查，现在不行了
好多词也打不出来了

**Comment by duguyipiao** [comment]
同样的问题，退回到了之前的版本。

**Comment by lotem** [comment]
安裝包裏面沒有預裝 [五筆](https://github.com/rime/rime-wubi) 輸入法。
詳見 [更新日誌](https://rime.im/release/squirrel/)。

**Comment by imshenshen** [comment]
回滚后重新update到0.10，然后用plum装了wubi86，还是不行。

我把[wubi86.custom.yaml](https://github.com/imshenshen/dotfiles/blob/master/rime/wubi86.custom.yaml) rename后部署，再把名字改回来再部署，就可以了。

目前看工作正常。

PS： 之前还把*.bin文件都删了，不确定有没有影响。
PS： 几年没更新突然弹出update，好感慨，感谢 @lotem的贡献 ~ ￥100已支付宝送出

**Comment by 0-o-0** [comment]
只安装五笔还不行。wubi86有对pinyin_simp的dependency。需要把[拼音](https://github.com/rime/rime-pinyin-simp)输入法也装上。

**Comment by cyio** [comment]
我这里没有成功用上`bash rime-install`
发现我的 rime 目录下缺少一个文件`pinyin_simp.dict.yaml`
手动下载
```
wget https://raw.githubusercontent.com/rime/rime-pinyin-simp/master/pinyin_simp.dict.yaml
```
然后重新部署就可以反查了。

**Comment by iblogc** [comment]
@cyio 我这边这样之后可以用反查，但是第一个候选词永远没有五笔编码提示
![image](https://user-images.githubusercontent.com/3283023/52783750-cf6c1600-308d-11e9-82cb-32eb108a86a5.png)
