### ISSUE TITLE
通过 homebrew 升级到 0.10.0 之后，重新部署时报错

### ISSUE THREAD

**Issue by chrisyue** [rime/squirrel#269]
报错日志的主要信息就是说有以下几个文件不存在

```
/Users/xxx/Library/Rime/stroke.reverse.bin
/Users/xxx/Library/Rime/luna_pinyin_simp.prism.bin
/Users/xxx/Library/Rime/luna_pinyin_tw.prism.bin
/Users/xxx/Library/Rime/stroke.table.bin
/Users/xxx/Library/Rime/stroke.prism.bin
/Users/xxx/Library/Rime/luna_pinyin.table.bin
/Users/xxx/Library/Rime/luna_pinyin.prism.bin
/Users/xxx/Library/Rime/luna_pinyin.reverse.bin
/Users/xxx/Library/Rime/luna_pinyin_fluency.prism.bin
/Users/xxx/Library/Rime/stroke.dict.yaml
```

`/Users/xxx/Library` 就是『用户设定』打开的那个目录。

不过居然还是能用的（配置的自然码双拼），而且我是重启了操作系统后尝试的，应该加载的是新版本了。

请问作者我先在应该怎么解决这个问题？

我也看了一些其他人问的类似问题，比如要使用东风破来安装自己的编码方法，但既然我现在还能用，应该是另外一个问题？

**Comment by lotem** [comment]
這裏面有兩個問題。

其中一個我已記錄在 https://github.com/rime/librime/issues/241。這是個 BUG。

那些名爲 `*.bin` 的符號鏈接是舊版本創建的，因爲同名的 `.bin` 文件已經安裝到共享文件夾，部署時就直接鏈接到用戶文件夾以節省時間。
這個操作在新版本里不需要了，程序會依次到兩個文件夾找文件，因此升級後會刪除這些鏈接。——不幸的是刪除操作發生異常，因爲這些方案都不再預裝，鏈接失效了，程序多餘地讀了一次鏈接，檢查他是否指向用戶目錄下的文件。

修復程序之前，可以手動刪除這些符號鏈接：
```sh
rm ~/Library/Rime/*.bin
```

**Comment by libhappy** [comment]
旧版本中的输入方案都是通过软链接指向程序包中自带的文件，新版本中这些输入方案文件被删除了，所以报错。从1.0.0版本开始，输入方案不再自带，需要手动通过[plum](https://github.com/rime/plum)安装。如果安装后依然不存在该输入方案(如 emoji输入)，可以在配置文件中删除该输入方案。

**Comment by lotem** [comment]
@slgray 不會吧… 鼠鬚管版本是 0.10.0 ？
可以查看一下本尊
`ls -l /Library/Input Methods/Squirrel.app/Contents/SharedSupport/luna_pinyin_fluency.prism.bin`

**Comment by lotem** [comment]
呃，我還沒說第二個問題。
`stroke` 也不再預裝了，他可能是已啓用的某個方案的依賴項，所以部署時需要。
對了，本來也要用 `stroke` 做筆畫反查的拼音等方案，預裝版本都精簡掉了。
所以推測應該還有其他方案用他，比如雙拼。

安裝依賴的問題我正在研究，一些初步結論：
https://github.com/rime/squirrel/issues/266#issuecomment-451129747

**Comment by lotem** [comment]
呃……
Homebrew cask 才剛剛更新到 0.10.0 版。
https://github.com/Homebrew/homebrew-cask/pull/56864
……
那麼請問題主 @chrisyue 怎麼提前做到了「通过 homebrew 升级到 0.10.0」？

**Comment by chrisyue** [comment]
@lotem 這我就不清楚了，不過我確實是通過 brew cask upgrade 升級的，大概北京時間下午 4 點左右

**Comment by slgray** [comment]
> @slgray 不會吧… 鼠鬚管版本是 0.10.0 ？
> 可以查看一下本尊
> `ls -l "/Library/Input Methods/Squirrel.app/Contents/SharedSupport/luna_pinyin_fluency.prism.bin"`

 我通过重新配置来解决这个问题了。
