### ISSUE TITLE
更新0.10.0后user.yaml保存失败，导致每次rime重新部署后，简体繁体转换须重新设置。

### ISSUE THREAD

**Issue by saintaugustinus** [rime/squirrel#271]
INFO文件下报错如下：
`I0103 22:23:57.037120 117608448 config_data.cc:85] saving config file '/Library/Input Methods/Squirrel.app/Contents/SharedSupport/user.yaml'.`
`E0103 22:23:57.037140 117608448 config_data.cc:41] failed to save config to stream.`
发现系统rime配置目录下的user.xml未更新(怀疑权限问题，给了磁盘完全访问权后user.xml更新成功)
以前的user.xml好像是在用户设定目录下的没有权限问题
请问除了除了给磁盘完全访问权之外有其它办法解决吗？

**Comment by lotem** [comment]
是程序的錯誤。應讀寫 `~/Library/Rime/user.yaml` 而非共享文件夾那份。共享文件夾只有安裝時可以寫入。

軟件修復前，可手動建立該文件以避免該錯誤：
```bash
killall Squirrel; touch ~/Library/Rime/user.yaml
```
