### ISSUE TITLE
0.10.0输入框的文字没有0.9.20清晰

### ISSUE THREAD

**Issue by sungnix** [rime/squirrel#278]
▼环境
・macOS 10.13.6
・Squirrel 0.10.0

▼问题
同样的外观配置0.10.0下看起来没有0.9.20清晰。
![](https://s.macboke.com/font-diff.png)

**Comment by lotem** [comment]
0.9.20 版本以後字體渲染部分的實現沒有改動。
只有 https://github.com/rime/squirrel/commit/6b9290de684803659334aedcf234272ab7e92c50 最有可能導致這個偏差——嚴格地說是舊版本有錯誤，沒有用對設置的字號。看上去兩張圖字的確是不一樣大。
主觀地說，0.10.0 這幅圖看起來清晰度並不遜色。似乎只是字重不同，筆畫比上面稍細。

**Comment by sungnix** [comment]
感谢确认，
确实是字体看起来要细一些，
那只能多使用新版本来适应下了。

**Comment by lotem** [comment]
字體字號可以設置的，也許能調成舊版的效果。
因爲差異是舊版本的BUG造成，就此關閉工單。
