### ISSUE TITLE
安裝完畢宜退出並重新登錄，以保證輸入法的安裝／更新生效

### ISSUE THREAD

**Issue by lotem** [rime/squirrel#281]
如 [更新日誌](https://rime.im/release/squirrel/) 所言，需要重新登錄，輸入法更新纔會生效。

後續版本的安裝包將恢復這一要求：
https://github.com/rime/squirrel/commit/c84001ea4348b902543938d89d68306b1ea86b3f ：安裝完成後要求退出登錄

根據目前收到的反饋，安裝完畢後，可能出現以下情況：

  - [键盘布局不可用](https://github.com/rime/squirrel/issues/277)
    輸入法菜單大概是灰色的「……」
  - [調用了升級安裝前的版本](https://github.com/rime/home/issues/303)
    輸入法可能是活了，然而數據文件對不上，也是不能工作的狀態

## macOS Mojave  管理輸入法的機制或有改變
（也許版本之間一直在變）
我在開發和調試的時候注意到在 Mojave 這版 macOS 上，更新輸入法並覆寫程序文件之後，系統仍會調用更新前版本的程序。
我推測，系統保持了可執行文件的引用並在輸入法進程結束後利用保存的環境繼續調用，這可能是某種「安全優化」。

這確實給調試帶來不少麻煩。
爲了測試本地構建的新版本，只好手動從控制檯啓動輸入法進程，這樣能執行到新版本的程序包括 `librime.1.dylib`。

```sh
cd squirrel
make deps && make && make install
/Library/Input\ Methods/Squirrel.app/Contents/MacOS/Squirrel --quit; /Library/Input\ Methods/Squirrel.app/Contents/MacOS/Squirrel
```
從控制檯結束這個進程後，系統仍會自動喚起舊版本的輸入法…

**Comment by snovey** [comment]
呃……我是通过首页的 Mac 安装包安装的
想问下这个 squirrel 是在哪个路径下？
或者是否有卸载重装的办法，我在应用程序中没有找到输入法的 app

**Comment by lotem** [comment]
@snovey `"/Library/Input Methods/Squirrel.app"`

**Comment by snovey** [comment]
<img width="585" alt="image" src="https://user-images.githubusercontent.com/15171147/50734102-4501de00-11d4-11e9-9ce5-92110a109bf1.png">
呃，还是没懂，求指点
（现在输入法是部分可用的，打字可以，emoji 不行

**Comment by Cee** [comment]
第二个问题可以通过重启电脑解决。

**Comment by LEOYoon-Tsaw** [comment]
重啓之後如果輸入法沒有自動添加，請前往設定-鍵盤-文字輸入手動添加

**Comment by SnowOnion** [comment]
我通過 Squirrel-1.1.2.pkg 安裝後，會**自動**退出並重新登錄。
建議先詢問用戶，再退出並重新登錄。您認為呢？

**Comment by lotem** [comment]
> 我通過 Squirrel-1.1.2.pkg 安裝後，會**自動**退出並重新登錄。 建議先詢問用戶，再退出並重新登錄。您認為呢？

我記得最後一步的確認按鈕是「退出登錄」，用戶確認了纔會退出。

**Comment by SnowOnion** [comment]
啊，確實。😂

<img width="732" height="560" alt="Image" src="https://github.com/user-attachments/assets/f96e2e55-be0f-4e59-b0a7-651b0c9d6475" />
