### ISSUE TITLE
遇到编译错误， macOS  10.14.2

### ISSUE THREAD

**Issue by dawnray** [rime/squirrel#282]
In file included from port/port_posix.cc:5:
In file included from ./port/port_posix.h:41:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/pthread.h:232:66: error: 
      unknown type name 'size_t'
int pthread_attr_getguardsize(const pthread_attr_t * __restrict, size_t * __restrict);
                                                                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/pthread.h:249:43: error: 
      unknown type name 'size_t'
                void * _Nullable * _Nonnull __restrict, size_t * __restrict);
                                                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/pthread.h:256:66: error: 
      unknown type name 'size_t'
int pthread_attr_getstacksize(const pthread_attr_t * __restrict, size_t * __restrict);
                                                                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/pthread.h:265:49: error: 
      unknown type name 'size_t'
int pthread_attr_setguardsize(pthread_attr_t *, size_t);
                                                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/pthread.h:281:53: error: 
      unknown type name 'size_t'
int pthread_attr_setstack(pthread_attr_t *, void *, size_t);
                                                    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/pthread.h:287:49: error: 
      unknown type name 'size_t'
int pthread_attr_setstacksize(pthread_attr_t *, size_t);
                                                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/pthread.h:510:40: error: 
      unknown type name 'size_t'
int     pthread_getname_np(pthread_t,char*,size_t);
                                           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/pthread.h:524:1: error: 
      unknown type name 'size_t'
size_t pthread_get_stacksize_np(pthread_t);
^
In file included from port/port_posix.cc:5:
In file included from ./port/port_posix.h:47:
./port/atomic_pointer.h:55:3: warning: 'OSMemoryBarrier' is deprecated: first deprecated in macOS
      10.12 - Use std::atomic_thread_fence() from <atomic> instead [-Wdeprecated-declarations]
  OSMemoryBarrier();
  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/libkern/OSAtomicDeprecated.h:749:9: note: 
      'OSMemoryBarrier' has been explicitly marked deprecated here
void    OSMemoryBarrier( void );
        ^
1 warning and 8 errors generated.
make[3]: *** [libleveldb.dylib.1.18] Error 1
make[2]: *** [leveldb] Error 2
make[1]: *** [thirdparty] Error 2
make: *** [librime/thirdparty/lib/libmarisa.a] Error 2

**Comment by lotem** [comment]
代碼可以編譯。不知道如何重現這個問題。
