### ISSUE TITLE
沒有朙月拼音*臺灣正體的選項

### ISSUE THREAD

**Issue by Enig123** [rime/squirrel#283]
由於臺灣正體與香港正體有一些差異，希望能夠加入臺灣正體選項。

或者能夠告知如何操作以顯示朙月拼音*臺灣正體選項？

**Comment by lotem** [comment]
有：
https://github.com/rime/rime-luna-pinyin/blob/master/luna_pinyin_tw.schema.yaml

**Comment by lotem** [comment]
問題不明確：使用的軟件不明

**Comment by Enig123** [comment]
對新版本不熟，可否告知如何加入臺灣正體的配置。我是在mac os Mojave上升級之後遇到了臺灣正體不出來的情況，在其它windows 8.1, windows 10中使用，升級之後保留有臺灣正體選項。

檢察mac os Majove的輸入法配置文件，其中有你所說的luna_pinyin_tw.schema.yaml，日期爲2015年，可能是以前版本留下來的文檔。

**Comment by lotem** [comment]
噢。那就是新版本不再發行這個文件了。[更新日誌](https://rime.im/release/squirrel/) 有說明。
https://github.com/rime/squirrel/issues/279

這個文件的新版本在這裏：
https://raw.githubusercontent.com/rime/rime-luna-pinyin/master/luna_pinyin_tw.schema.yaml

不過從 https://github.com/rime/squirrel/issues/283#issuecomment-459521731 的描述，有這個文件在，可能僅僅是 `luna_pinyin_tw` 沒有加入到配置裏的輸入方案列表？
https://github.com/rime/home/wiki/CustomizationGuide#%E4%B8%80%E4%BE%8B%E5%AE%9A%E8%A3%BD%E6%96%B9%E6%A1%88%E9%81%B8%E5%96%AE

**Comment by iblis17** [comment]
default.yml 以前有 `luna_pinyin_tw` ，現在不見了。爲何拿掉？

**Comment by imper0502** [comment]
我的做法是開兩個opencc 轉換：

switches:
  - name: ascii_mode
    reset: 0
    states: [ "中", "En" ]
  - name: full_shape
    reset: 0
    states: [ "半形", "全形" ]
  - name: ascii_punct
    reset: 0
    states: [ "。，", "．，" ]
  - name: s2tw                  # 簡繁轉換
    reset: 1
#    states: [ "簡化字", "標準字" ]
  - name: t2tw                  # 正繁轉換
#    states: [ "傳承字", "標準字" ]
    reset: 1
    
engine/filters:
    - simplifier@s2tw  # 簡繁轉換
    - simplifier@t2tw  # 正繁轉換
    - uniquifier  　　　# 過濾重複的候選字，有可能來自正繁簡轉換
    - cjk_minifier

s2tw: # 簡繁轉換
  option_name: s2tw
  opencc_config: s2tw.json
  tips: none
t2tw: # 正繁轉換
  option_name: t2tw
  opencc_config: t2tw.json
  tips: none

**Comment by lotem** [comment]
> default.yml 以前有 `luna_pinyin_tw` ，現在不見了。爲何拿掉？

因爲該方案所需的資源（用於輸出zh-Hant-TW字形的opencc字典）不是統一預裝的。
受限於發行渠道，一些平臺只預裝了基本的繁簡轉換表，不包含香港、臺灣變體。
預設配置（`default.yaml`）要支持所有平臺，因此默認只激活全平臺可用的輸入模式。
