### ISSUE TITLE
鼠须管自动升级到0.10后wubi86完全废掉

### ISSUE THREAD

**Issue by missdeer** [rime/squirrel#286]
从0.9.26.1自动升级到0.10，原本一直正常使用的wubi86方案不见了，这是问题一。
好不容易加回来，也不正常了，貌似只能出一级简码了，这是问题二。
只好手动退回0.9.26.1，全部恢复正常。
两台机器都出现了，不敢在其他机器试了。

**Comment by lotem** [comment]
自動升級？讀過 [更新日誌](https://rime.im/release/squirrel/) 嗎？

**Comment by lotem** [comment]
併入 https://github.com/rime/squirrel/issues/279
