### ISSUE TITLE
使用花园明朝字体后，候选词生僻字部分不显示

### ISSUE THREAD

**Issue by UniqueSimon** [rime/squirrel#287]
生僻字显示为方块，所以安装了花园明朝A和B
```
patch:
  "style/color_scheme": psionics #主题
  "style/horizontal": false #横竖排
  "style/font_point": 14 #字号14
  "style/font_face": ".PingFang SC,HanaMinA,HanaMinB"
  "translator/spelling_hints": "4"
```
但是，生僻字部分仅仅是方块消失了，并没有出现字，选择后能输出，如下图。
<img width="79" alt="snipaste_2019-01-11_14-42-13" src="https://user-images.githubusercontent.com/26346635/51017620-a4366880-15af-11e9-9a08-f268693657f8.png">

**Comment by lotem** [comment]
未能重現，可能跟系統或軟件版本有關。也許得重新登錄一次。

**Comment by UniqueSimon** [comment]
> 未能重現，可能跟系統或軟件版本有關。也許得重新登錄一次。

重启后正常了，感谢。
