### ISSUE TITLE
0.10.0版中如何使用郑码呢？

### ISSUE THREAD

**Issue by dalton-chiou** [rime/squirrel#288]
想看看别人是怎么做的。我轻易不敢升级，因为怕装不好，在MAC下没的可用（我只用郑码），就麻烦了。
这里有人使用郑码吗？

**Comment by tiglog** [comment]
我用，有问题可以找我。

**Comment by lotem** [comment]
因爲軟件版權限制，本品不包含鄭碼輸入法。事實上這個版本只包含一組經過刪減的拼音輸入方案以保證開箱即用體驗，輸入方案需要另行安裝或用戶自己提供，參見 https://github.com/rime/squirrel/issues/279
