### ISSUE TITLE
横排时，字体有点下蹲

### ISSUE THREAD

**Issue by yanhuacuo** [rime/squirrel#289]
如图：

![pic](https://raw.githubusercontent.com/yanhuacuo/98WB/master/issues/12.jpg)

**Comment by yanhuacuo** [comment]
> 我这貌似没有问题
> <img alt="screenshot 2019-01-17 at 12 00 16 am" width="488" src="https://user-images.githubusercontent.com/13161779/51261460-42c92c00-19eb-11e9-9c84-7e555d3e7b7a.png">

我用的是默认样式，你这个配色是改过的吧。

**Comment by lotem** [comment]
默認樣式沒測出這個問題。樓主這個字體是改過的吧。

**Comment by Voleking** [comment]
> > 我这貌似没有问题
> > <img alt="screenshot 2019-01-17 at 12 00 16 am" width="488" src="https://user-images.githubusercontent.com/13161779/51261460-42c92c00-19eb-11e9-9c84-7e555d3e7b7a.png">
> 
> 我用的是默认样式，你这个配色是改过的吧。

这是是 native 的配色，只不过我系统是 Dark mode，所以就是这个样子

**Comment by yanhuacuo** [comment]
> 默認樣式沒測出這個問題。樓主這個字體是改過的吧。

「思源黑体2.0」

**Comment by lotem** [comment]
相關討論 https://github.com/rime/squirrel/issues/196
