### ISSUE TITLE
更小的安裝包

### ISSUE THREAD

**Issue by LEOYoon-Tsaw** [rime/squirrel#29]
用fp8 (fast paq) 壓縮程序文件 (Squirrel.app，字典尚未佈署)，可以壓縮到4.54MB (現在的安裝包是7.80MB，大小是現在的58%)。不過這個壓縮率的代價是較長的壓縮時間，在我的電腦上需356.10 sec壓縮 (解壓與壓縮耗時相等)。
該壓縮算法源代碼在此：http://dhost.info/paq8/fp8_v3.zip

**Comment by lotem** [comment]
已開發完成。

下一次發佈時，輸入方案不再以預裝形式提供。
輸入法安裝包僅保留一個內容縮減的拼音輸入方案，以示輸入法程序能夠正常工作。
輸入方案 由用家選擇安裝。
試試 一句話安裝指令
