### ISSUE TITLE
请问现版本的小狼毫如何支持注音并击？

### ISSUE THREAD

**Issue by Old-Pussy** [rime/squirrel#290]
https://github.com/rime/squirrel/issues/78
这个issue都是三年前的了

**Comment by Old-Pussy** [comment]
……不小心发到鼠须管这边来了

**Comment by lotem** [comment]
支持。

**Comment by lotem** [comment]
> 你不输入声调的话，你当前输入的两个音在某些情况下可能会被认成两个汉字。
> 这也与 RIME 不绝对强制确认声调的特性有关。

這取決於輸入方案設計中的功能取捨。
若非在配置中明確定義，RIME只會匹配碼表中的完整拼式。
