### ISSUE TITLE
小鶴雙拼方案切換至簡體後仍然輸出繁體

### ISSUE THREAD

**Issue by leeiivy** [rime/squirrel#291]
鼠鬚管 0.10.0 版本

**Comment by Voleking** [comment]
比方说什么字？

**Comment by leethom** [comment]
> 比方说什么字？

切換至簡體後和繁體輸出沒區別

**Comment by Voleking** [comment]
倾向是你配置问题
![screen shot 2019-01-18 at 11 17 16](https://user-images.githubusercontent.com/13161779/51363368-9edaa000-1b12-11e9-8892-bcaa602cb184.png)
![screen shot 2019-01-18 at 11 17 07](https://user-images.githubusercontent.com/13161779/51363395-ba45ab00-1b12-11e9-85d7-a1512fa10004.png)
