### ISSUE TITLE
用程序方式切换后，始终为英文状态，需要切换其他窗口再切换回来

### ISSUE THREAD

**Issue by tenhow** [rime/squirrel#292]
用程序方式切换后，始终为英文状态，需要切换其他窗口再切换回来。
这一个bug不知道源于什么地方，但是真的很蛋疼！！！
比如我用vim模式，设定insert为鼠须管，normal为 U.S.英文键盘，
用选择im.rime.inputmethod.Squirrel.Rime的方式 切换键盘
之后状态栏的图标是变了，但是rime始终却不切换，仍为英文输入，所有快捷键无效，无法使用快捷键切换中英状态。只能切换到另外一个窗口再回来才可以正常使用。

**Comment by tenhow** [comment]
P.S. 切换用的这套程序，https://github.com/minoki/InputSourceSelector

**Comment by vinurs** [comment]
你这个是在mac下面的微信或者QQ里面才会出现这种情况吗？

**Comment by tenhow** [comment]
不是哦，是在所有程序下都是这样的

**Comment by tenhow** [comment]
首先测试终端就能发现这个问题，然后其他程序都测试过，一样的哈。

**Comment by ikey4u** [comment]
我也遇到这个问题了, 我再把问题描述一下:

插入模式下, 你是输入法的中文状态, 然后你回到了正常模式, 于是输入法自动切换到英文模式.

这个时候, 你把窗口的焦点聚焦到另外一个应用程序上, 然后再回到 vim,
再进入插入模式, 也切换到了中文状态(就是rime打图标), 但是你发现你无法输入中文了,
还是处于中文状态, 你不得不手动调用切换输入法的快捷键, 将其调整到中文模式.

我用的系统是 mac os 10.13.6, vim 8.1 版本, vim 中输入法自动切换使用的是 fcitx-remote-osx 插件.

**Comment by lotem** [comment]
鑑於題中描述的出現問題的操作是由第三方軟件實現的，超出了本品開發的關注範圍，因此關閉工單。

**Comment by ikey4u** [comment]
> 鑑於題中描述的出現問題的操作是由第三方軟件實現的，超出了本品開發的關注範圍，因此關閉工單。
您好, 请不要关闭这个 issue, 在同样地环境下, 我使用其他输入法, 比如搜狗输入法, 是没有任何问题的, 我是在换了 rime 输入法之后才出现这种问题的.  @lotem

**Comment by tenhow** [comment]
目前看反正没有很完美的解决方式
