### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by winduser** [rime/squirrel#293]
I experienced the error shown as follows:

** BUILD FAILED **

The following build commands failed:
	Ld xbuild/lib/Release/librime.1.4.0.dylib normal x86_64
(1 failure)
make[1]: *** [release] Error 65
make: *** [librime] Error 2

------

I've searched all the relevant issues in the past, and tried what the comments suggest. However, the error still exists.

**Comment by lotem** [comment]
It's the same issue with https://github.com/rime/librime/issues/247
Comments in that thread provide a solution.
