### ISSUE TITLE
更新 0.11.0 后，郑码输入方案失效了

### ISSUE THREAD

**Issue by ichenyonghua** [rime/squirrel#296]
更新 0.11.0 后，郑码输入方案失效了，重新登录，重启系统都无法恢复。系统版本：10.14.2，看配置文件目录结构似乎有变化，而未找到最新的配置说明文档。请给予支持，多谢！

**Comment by ichenyonghua** [comment]
感谢，使用“东方破”重新配置，重新添加输入方案，已解决问题！

发自我的 iPhone

在 2019年1月28日，22:15，佛振 <notifications@github.com<mailto:notifications@github.com>> 写道：


出廠沒有這個輸入方案。怎樣配置的？
有錯誤日誌嘛？
變化的部分是輸入法生產的文件。用戶配置沒有變化。
文檔入口： https://rime.im/docs

**Comment by dalton-chiou** [comment]
我也用郑码。暂时没敢更新。主要是最近没时间折腾，有时间了仔细配置一遍。
