### ISSUE TITLE
统一鼠须管、中州韵和小狼毫橫排模式方向键↓↑→←的功能

### ISSUE THREAD

**Issue by waterml** [rime/squirrel#298]
鼠须管的方向键↓↑默认是翻页，而最近几版的中州韵(fcitx-rime)和小狼毫中↓↑默认是移动（选择）高亮。
因为经常在win/linux/mac间切换，有时就有点迷惑了。
Ps. 个人认为翻页的默认快捷键已经够多了
这算是个无伤大雅的小问题，不知当不当提出来。

**Comment by lotem** [comment]
不是的。↓↑默認動作是移動選字光標。
當候選詞介面設置爲橫向排列時，↓↑綁定的動作爲翻頁，而→←爲移動選字光標。

**Comment by waterml** [comment]
@lotem 我用的词没有描述清楚，在横排（竖排也一样）候选项介面的情况下，中州韵和小狼毫↓↑默认是移动候选字光标，→←是移动拼音串（而且似乎仅限拼音串）中的光标。
鼠须管在竖排候选项的条件下，↓↑与中州韵和小狼毫中基本无异；但是横排候选项的情况下，↓↑是 `翻页`，→←是移动拼音串`以及`候选项中的光标。
我想表达的是在横排候选项情况下，统一鼠须管的↓↑和→←与中州韵和小狼毫的一致。

**Comment by lotem** [comment]
不能改了
這是個“feature”

**Comment by gcell** [comment]
我晕，原来是这个问题，这几天我也被这个同样的方向键问题搞晕了，linux和mac来回折腾跟倒时差一样。
