### ISSUE TITLE
在chrome和office中極其嚴重的bug

### ISSUE THREAD

**Issue by HongTao628** [rime/squirrel#299]
MAC：10.14.2
excel：16.16.6
chrome：72.03626.81
squirrel：0.11.0
我使用倉頡輸法，默認配置。
在chrome的地址欄輸入時，左右鍵和esc鍵的効果一樣，刪除鍵不是刪一個字符而是刪除我全部輸入的果西。
在excel裡，輸入時會留下英文字母，例如「發」（nonhe），輸入後成了「發nhe」，總會有字母在後面，以致於我沒一次不得不手動去刪，致使在excel中無法使用倉頡輸入法。

**Comment by wuzhaojun** [comment]
我在Mac OS 10.14 上 用0.11.0也遇到了同样的问题。
这个问题好像只是出现在Chrome的地址栏。在Chrome别的区域（比如页面的编辑框）里不会出现。
在Chrome的地址栏里，比如我在输入栏输入“nig"，想改成"nih"的时候，如果我一按delete键，就会把"nig"全部删掉。而不是只是删除前面的一个“g”。
我用的Chrome版本是Version 72.0.3626.96

**Comment by wuzhaojun** [comment]
试过在启动Chrome时加上 --disable-extensions 也会出现同样的问题。

**Comment by flaming** [comment]
我用五笔输入法，chrome的地址栏遇到同样的问题。

**Comment by groverlynn** [comment]
在chrome中有同样的情况。
但是使用chromium内核的opera则完全无恙

**Comment by lotem** [comment]
題目所描述的不是本品的操作。
請聯繫相關軟件的開發商。

**Comment by mathgo** [comment]
问题描述：

> 在Chrome的地址栏。在Chrome别的区域（比如页面的编辑框）里不会出现。
在Chrome的地址栏里，比如我在输入栏输入“nig"，想改成"nih"的时候，如果我一按delete键，就会把"nig"全部删掉。而不是只是删除前面的一个“g”。

复现步骤：

在 squirrel.custom.yaml 中加入以下配置时会复现问题

```
patch:
  style/inline_preedit: false
```

而当`inline_preedit`为true时，问题不存在。

烦请 @lotem 再确认下。

**Comment by CrazyWisdom** [comment]
@mathgo 的方法可以，可以临时救急下，谢谢。
