### ISSUE TITLE
0.11.0版*.custom.yaml和自製*.dict.yaml重新佈署沒有作用

### ISSUE THREAD

**Issue by iPopper** [rime/squirrel#300]
我碰到的情況是，無論`0.10.0`或`0.11.0`，重新佈署`0.9.26.2`版使用的`自定custom.yaml和dict.yaml`都沒起作用。

為了測試，我用完全乾淨的外接硬碟安裝`macOS 10.14.3`版測試`0.11.0`版，只安裝系統和東風破要用的`Command Line Tools`。
測試了三次，每次測試前都完全清除`rime`和`squirrel`相關檔案，只保留`自定的custom.yaml和dict.yaml`。

如果在設定的檔案夾（`~/Library/Rime/`）裡沒有`自定的custom.yaml和dict.yaml`檔案，用東風破安裝基本輸入方案（`:preset`），重新布署後輸入方案的相關檔案會在 `~/Library/Rime/build/` 裡。然後把`自定的custom.yaml和dict.yaml`檔案放到設定檔案夾，再重新布署並不起作用。

還沒安裝`squirrel`前，先把`自定的custom.yaml和dict.yaml`檔案放在設定檔案夾（`~/Library/Rime/`）裡，安裝`squirrel`後，用東風破安裝基本輸入方案，這時重新佈署只對`luna_pinyin`有用，只有：`default.yaml`、`luna_pinyin.prism.bin`、`luna_pinyin.reverse.bin`、`luna_pinyin.table.bin`、`squirrel.yaml`，五個檔案在 `~/Library/Rime/bulid/` 裡，倉頡和其他幾個輸入方案都沒有。

也再測試`0.9.26.2`版，`自定的custom.yaml和dict.yaml`重新佈署是可用的。
目前先退回`0.9.26.2`版。

下面是ERROR log的內容。

```
E0127 19:45:31.643276 136372224 config_data.cc:172] copy on write failed; incompatible node type: commit
E0127 19:45:31.643528 136372224 config_compiler.cc:140] error merging branch commit
E0127 19:45:31.643549 136372224 config_compiler.cc:140] error merging branch {
E0127 19:45:31.643568 136372224 config_compiler.cc:140] error merging branch full_shape
E0127 19:45:31.643586 136372224 config_compiler.cc:71] failed to merge tree: default:punctuator
E0127 19:45:31.643605 136372224 legacy_preset_config_plugin.cc:56] failed to include section default:punctuator
E0127 19:45:31.643625 136372224 config_component.cc:250] error building config: cangjie5.schema
E0127 19:45:31.659209 136372224 config_data.cc:172] copy on write failed; incompatible node type: commit
E0127 19:45:31.659237 136372224 config_compiler.cc:140] error merging branch commit
E0127 19:45:31.659256 136372224 config_compiler.cc:140] error merging branch {
E0127 19:45:31.659276 136372224 config_compiler.cc:140] error merging branch full_shape
E0127 19:45:31.659293 136372224 config_compiler.cc:71] failed to merge tree: default:punctuator
E0127 19:45:31.659312 136372224 legacy_preset_config_plugin.cc:56] failed to include section default:punctuator
E0127 19:45:31.659330 136372224 config_component.cc:250] error building config: luna_pinyin.schema

```

**Comment by lotem** [comment]
配置文件解析錯誤。
新版本有更嚴格的檢查。出問題的代碼可能位於 `default.custom.yaml`
可能用到有別於 https://github.com/rime/home/wiki/CustomizationGuide#%E4%B8%80%E4%BE%8B%E5%AE%9A%E8%A3%BD%E6%A8%99%E9%BB%9E%E7%AC%A6%E8%99%9F 的自定義方法。

**Comment by iPopper** [comment]
感謝！
問題似乎解決了。
