### ISSUE TITLE
有些候选词显示不出来

### ISSUE THREAD

**Issue by linchen2chris** [rime/squirrel#304]
用五笔, 选了增广, 有些候选词显示不出来, 不知道是不是字体的问题
![image](https://user-images.githubusercontent.com/3970087/53221886-719b8780-36a6-11e9-8380-215f9f9b2cfd.png)
字体用的是
    font_face: "PingFangSC-Regular,Noto Sans CJK TC" # "Lucida Grande"

**Comment by loong1992** [comment]
我用了 月拼音.简化字 方案, 有些候选词也是显示不出来(显示问号), 例如输入 kai这三个字母时, 部分候选字显示不出
![候选字](https://user-images.githubusercontent.com/32151839/57983827-c6258780-7a88-11e9-81f4-433e76c64b77.png)

**Comment by KyleBing** [comment]
一些用不到的生僻字而已，不用管，这个到死也不会用到的。
我的处理方式是打开码表，搜索并删除相应的字。

**Comment by loong1992** [comment]
安装字体能解决显示问题吗? 或者能批量删除这些生僻字吗?

**Comment by yakirChen** [comment]
> 安装字体能解决显示问题吗? 或者能批量删除这些生僻字吗?
花园明朝
http://fonts.jp/hanazono/

**Comment by yakirChen** [comment]
> 安装字体能解决显示问题吗? 或者能批量删除这些生僻字吗?

花园明朝
http://fonts.jp/hanazono/

**Comment by KyleBing** [comment]
> 安装字体能解决显示问题吗? 或者能批量删除这些生僻字吗?

个人感觉删除为好，删除就是用正则表达式替换呗，也可以发给我我帮你删。 kylebing@163.com

**Comment by loong1992** [comment]
> > 安装字体能解决显示问题吗? 或者能批量删除这些生僻字吗?
> 
> 花园明朝
> http://fonts.jp/hanazono/
> 
> ![image](https://user-images.githubusercontent.com/22702893/59817071-02caf400-9351-11e9-998b-d4c51a57af7e.png)

谢谢, 下载了hanazono-20170904.zip, 解压后, 装了HanaMinB.ttf 字体解决了问题
![字体预览](https://user-images.githubusercontent.com/32151839/59818139-2abc5680-9355-11e9-82f0-9ddf53c0844a.png)

**Comment by loong1992** [comment]
> > 安装字体能解决显示问题吗? 或者能批量删除这些生僻字吗?
> 
> 个人感觉删除为好，删除就是用正则表达式替换呗，也可以发给我我帮你删。 [kylebing@163.com](mailto:kylebing@163.com)

我就不删除了, 留着做生僻字输入吧, 谢谢你了
