### ISSUE TITLE
update 11 fail 

### ISSUE THREAD

**Issue by ElizRitchie** [rime/squirrel#305]
I know nothing about coding.  I had been happily using squirrel for jyutping input and I stupidly accepted an update notice.  Now when I switch to squirrel and start typing the window of character choices doesn't pop up.  Also when I hit deploy I got an error message. 
I tried reinstalling from the blog I had originally gotten it from and following the instructions for getting and installing the jyutping.yaml file.  No luck.  I've restarted my computer too.  

Please help me!  

Elizabeth :(

**Comment by lotem** [comment]
Probably the same issue:
https://github.com/rime/squirrel/issues/279
Check the error logs to be sure.
