### ISSUE TITLE
[鼠须管] 在状态栏面板中，不支持按键 `shift` 切换中英文

### ISSUE THREAD

**Issue by KyleBing** [rime/squirrel#306]
如下图：在状态栏面板中输入文字的时候不支持 `shift` 按键切换中英文。

### 重现方式：

1. 右侧打开状态栏面板
2. 编辑世界时钟
3. 输入文本，不响应 `shift` 按键

<img width="345" alt="screen shot 2019-03-04 at 13 20 07" src="https://user-images.githubusercontent.com/12215982/53712146-8afbbb00-3e80-11e9-884a-11bc5e0e9c47.png">

**Comment by lotem** [comment]
同 https://github.com/rime/squirrel/issues/85

**Comment by lotem** [comment]
关闭相同问题
