### ISSUE TITLE
默認發行文件有誤

### ISSUE THREAD

**Issue by Phecda** [rime/squirrel#308]
預設的配色方案中有一行是重複的。
https://github.com/rime/squirrel/blob/46b6b985441e32dcf350fee224b78d5c3f0bd313/data/squirrel.yaml#L237
https://github.com/rime/squirrel/blob/46b6b985441e32dcf350fee224b78d5c3f0bd313/data/squirrel.yaml#L242

這個重複使得我無法用另外的工具解析這個 yaml 文件。

**Comment by lotem** [comment]
Fixed via https://github.com/rime/squirrel/commit/44a4d7ee3cad94c170616b7c8d9415a4f92c86d5
