### ISSUE TITLE
macOS Mojave鼠鬚管0.11.0版 句号键无法翻页，输出英文句点

### ISSUE THREAD

**Issue by boomker** [rime/squirrel#313]
相关配置如下:
    - {accept: "Shift+Tab", send: Page_Up, when: composing}
    - {accept: Tab, send: Page_Down, when: composing}
    - { when: paging, accept: comma, send: Page_Up }
    - {accept: period, send: Page_Down, when: has_menu}

    - { when: has_menu, accept: bracketleft, send: Page_Down }
    - { when: has_menu, accept: bracketright, send: Page_Down }

**Comment by lotem** [comment]
原裝配置沒有問題。應該是自定義配置引入的。
