### ISSUE TITLE
Spanish mac keyboard 

### ISSUE THREAD

**Issue by N214** [rime/squirrel#315]
Hello, I'm having some config issues, I can't use those two keys with my current config. 

![main-qimg-1f0b29c5375b130d2ac132e350efcba4-c](https://user-images.githubusercontent.com/34739662/40583879-617bd1fa-6197-11e8-8170-2136c4df9e59.jpeg)

**Comment by KyleBing** [comment]
复现步骤：

1. 输入法中添加 `Spanish-ISO` 输入法
2. 切换到 `Spanish-ISO` 再切回 `鼠须管` 输入法输入
3. 输入法使用的键盘布局还是 `Spanish-ISO` 的布局，按正常键盘上的 <kbd>~</kbd> 会出现 `《`

4. 切换英文输入法，再切换成 `鼠须管` 输入法就不会出现这问题了。

感觉应该是输入法没有自己的默认布局，而使用了上一次系统输入法的键盘布局导致的。


<img width="780" alt="Screen Shot 2020-12-09 at 16 33 27" src="https://user-images.githubusercontent.com/12215982/101604736-4aa97380-3a3c-11eb-8b9d-a9a41f9b6551.png">
<img width="780" alt="Screen Shot 2020-12-09 at 16 33 24" src="https://user-images.githubusercontent.com/12215982/101604748-4ed59100-3a3c-11eb-8e91-ad58be9ebf05.png">

**Comment by naked89** [comment]
> > 输入法没有自己的默认布局，而使用了上一次系统输入法的键盘布局
> 
> 这是符合设计的。

您好，这个问题有没有好的解决方案，每次用完西语后必须切换英文键盘再到中文，确实有点不方便。

**Comment by KyleBing** [comment]
> > > 输入法没有自己的默认布局，而使用了上一次系统输入法的键盘布局
> > 
> > 
> > 这是符合设计的。
> 
> 您好，这个问题有没有好的解决方案，每次用完西语后必须切换英文键盘再到中文，确实有点不方便。

Okay

**Comment by lotem** [comment]
默认行为保证了输入的文字与键盘上的键位一致。

如果要用其他语言的键盘输入中文时改用美式键盘布局，请修改这个选项：
https://github.com/rime/squirrel/blob/master/data/squirrel.yaml#L6

**Comment by naked89** [comment]
> > > > 输入法没有自己的默认布局，而使用了上一次系统输入法的键盘布局
> > > 
> > > 
> > > 这是符合设计的。
> > 
> > 
> > 您好，这个问题有没有好的解决方案，每次用完西语后必须切换英文键盘再到中文，确实有点不方便。
> 
> Okay

Okay ？？看不懂。。。。
