### ISSUE TITLE
鼠须管的重新部署是否有命令行具体用法？

### ISSUE THREAD

**Issue by xingezhang** [rime/squirrel#320]
因为有一套自己的配置，git clone下来后，都要点击重新部署，重新部署这个命令是否有命令行的具体用法介绍？
谢谢

**Comment by lotem** [comment]
有

`Squirrel --reload`

**Comment by xingezhang** [comment]
谢谢，那么同步用户数据应该也有命令了？

**Comment by KyleBing** [comment]
重新布署也有快捷键  `control` + `option` + `  很方便

**Comment by sundevilyang** [comment]
@lotem
我运行 `Squirrel --reload` 得到：
`zsh: command not found: Squirrel`

运行`bash rime-install luna-pinyin` 得到：
`bash: rime-install: No such file or directory`

**Comment by xingezhang** [comment]
@sundevilyang 应该是这个：
/Library/Input\ Methods/Squirrel.app/Contents/MacOS/Squirrel --reload

**Comment by jiutianhuanpei** [comment]
结合了另一个神器 Hammerspoon ，想在每次更新词库之后都自动部署，但是Squirrel的路径有空格，所以不能正确执行，写成 ‘/Library/Input\\ Methods/Squirrel.app/Contents/MacOS/Squirrel --reload’ 也不行，所以有什么方法可以解决吗？

**Comment by Voleking** [comment]
@jiutianhuanpei hammerspoon 文档中有写：
+ If you need to execute commands that have spaces in their paths, use a form like: hs.execute [["/Some/Path To/An/Executable" "--first-arg" "second-arg"]]

so `hs.execute [["/Library/Input Methods/Squirrel.app/Contents/MacOS/Squirrel" "--reload"]]`

**Comment by bosconb** [comment]
@jiutianhuanpei 解决了吗老哥，我也遇到这个问题

**Comment by Voleking** [comment]
@bosconb 我不是写了么，我还试了。。。

**Comment by bosconb** [comment]
> @bosconb 我不是写了么，我还试了。。。

-____-!!  可以了，谢谢！！
之前用老哥的lua不起效果，换了大佬你的也无效。
经你这么一提醒，发现是自己路径配置错了

**Comment by jiutianhuanpei** [comment]
@bosconb 解决了
```
cmd = '/Library/Input\\ Methods/Squirrel.app/Contents/MacOS/Squirrel --reload'
os.execute(cmd)	
```

但有个问题，我更新到 0.14.0 版本之后，再次执行这个命令，右上角没有部署完成的弹窗了，当然，也没有部署成功 @lotem

**Comment by bosconb** [comment]
> cmd = '/Library/Input\\ Methods/Squirrel.app/Contents/MacOS/Squirrel --reload'
> os.execute(cmd)	
> ```
> 但有个问题，我更新到 0.14.0 版本之后，再次执行这个命令，右上角没有部署完成的弹窗了，当然，也没有部署成功 @lotem

是不是开了Mac的【勿扰模式】？
我有提示，用的是楼上的那句命令
```bash
local function reloadMycustomedDict(aaa)

    hs.execute [["/Library/Input Methods/Squirrel.app/Contents/MacOS/Squirrel" "--reload"]]

end
hs.pathwatcher.new("/Users/xxx/Library/Rime/custom_phrase.txt", reloadMycustomedDict):start()
```
但是发现打开和关闭监控文件（不做任何修改）都会自动触发hs.execute，相当于每修改一次用户自定义词典至少要多部署两遍，这怎么解决？@Voleking

**Comment by Voleking** [comment]
@bosconb 简单看了下没看出啥问题，我也好久没折腾了，参考下我这个试试？我这个 hammerspoon 配置文件保存后才会重新加载。（Ps，我觉得如果不是经常修改配置其实是个伪需求）
```lua
return hs.pathwatcher.new(os.getenv("HOME") .. "/.hammerspoon/", function(files)
  local shouldReload = false

  for _, file in pairs(files) do
      if file:sub(-4) == ".lua" then
          shouldReload = true
      end
  end

  if shouldReload then
      hs.reload()
  end
end)
```

**Comment by GJRobert** [comment]
題外話：經過實測，macOS「勿擾模式」真的會影響系統是否跳出「重新部署」的通知訊息……

> > 但有个问题，我更新到 0.14.0 版本之后，再次执行这个命令，右上角没有部署完成的弹窗了，当然，也没有部署成功 @lotem
> > ```
> 
> 是不是开了Mac的【勿扰模式】？
> 我有提示，用的是楼上老哥的那句命令

**Comment by hsuanyi-chou** [comment]
可以參考我的 shell 範本，改成自己的客制化唷！

[shell 原始碼](https://github.com/hsuanyi-chou/rime-liur/blob/master/rime_liur_installer.sh)

此 shell 會做4件事：
1. 檢查鼠鬚管是否存在，不存在則終止執行
2. 使用 plum 初始化輸入法
3. 下載自行製作之輸入法 (本 shell 為嘸蝦米)
4. 自動部署 (即 reload)

嘸蝦米輸入法 blog 原文: [在Mac安裝嘸蝦米，使用鼠鬚管(RIME)並擁有注音模式、讀音反查、中英混輸、動態造詞](https://blog.typeart.cc/rime-liur/guide/)
