### ISSUE TITLE
添加日期等系统变量

### ISSUE THREAD

**Issue by KyleBing** [rime/squirrel#327]
如：在打 `data` 或者  `日期` 的时候输出当前系统时间 `2019-06-13 14:21`
希望添加这个功能。在写日期的时候很有用。

**Comment by bosconb** [comment]
新版本增加的插件librime-lua貌似就能实现这个功能，[librime-lua date](https://github.com/hchunhui/librime-lua/blob/master/sample/lua/date.lua)

**Comment by lotem** [comment]
同 https://github.com/rime/librime/issues/61

**Comment by jdhao** [comment]
这个插件是官方支持的吗，另外有没有不用编译的方式， 增加一个插件就需要编译一次，感觉太繁琐了。

**Comment by KyleBing** [comment]
> 这个插件是官方支持的吗，另外有没有不用编译的方式， 增加一个插件就需要编译一次，感觉太繁琐了。

不需要编译啊，只需要安装输入法程序，添加 rime.lua 并在相应的 skema 中 添加translator，重新布署即可。跟编辑 yaml 配置文件一样。
这里有说明：https://github.com/hchunhui/librime-lua
我自己的配置文件里已经加上了：https://github.com/KyleBing/rime-wubi86-jidian

**Comment by jdhao** [comment]
ok，明白了，谢谢。。我看那个 repo 下面有 build 部分，以为需要 build 才能使用 lua 脚本。
