### ISSUE TITLE
一个多音字的问题。

### ISSUE THREAD

**Issue by Grazee** [rime/squirrel#328]
![image](https://user-images.githubusercontent.com/12786402/59478686-c8fb7880-8e8c-11e9-869e-e1aaf27da526.png)
我打的拼音是“yin xing”，候選詞第一個有點哭笑不得了。

**Comment by lotem** [comment]
無法重現。
「銀行」注音爲`yin hang`。
如果樓主使用自配的詞典文件，請檢查其中多音字的注音。
