### ISSUE TITLE
在什么样的情况下,简拼(输入声母,出现候选词)会失效?

### ISSUE THREAD

**Issue by issuessss** [rime/squirrel#330]
是因为词库太多的原因?我觉得不合理啊?
举个例子,我要打 "什么" 2个字
我现在使用的是明月拼音, 所有使用简拼(通过输入声母,显示候选词)的方式,都不会出现候选词.
输入 sm, 不会出现候选字或词
输入 shm, 不会出现候选字或词
输入 shem, 出现候选字或词
输入 sme, 不会出现候选字或词
输入 shme, 不会出现候选字或词
输入 shenm,出现候选字或词
输入 shenme,出现候选字或词

但是当我切换到 明月拼音的简化字 或者 语句流,这2个没有加词库.
输入 sm, 出现候选字

这是什么原因? 唯一的区别就是我在明月拼音加了词库,难道加词库会有影响?
现在必须要打全拼音才会显示候选词,上面的输入的简拼应该出现候选词但是没出现.

**Comment by lotem** [comment]
無法重現問題。
上列形式原裝方案都可以輸入。

**Comment by issuessss** [comment]
找到原因了
是因为luna_pinyin.custom.yaml里面多了这些东西,我把它注释掉就好了.
这些配置和简拼有冲突
#    - derive/([dtngkhrzcs])o(u|ng)$/$1o/  # zho => zhong|zhou
#    - derive/ong$/on/                  # zhonguo => zhong guo
#    - derive/ao$/oa/                   # hoa => hao
#    - derive/([iu])a(o|ng?)$/a$1$2/    # tain => tian

**Comment by AnLuoRidge** [comment]
模糊音定義先於簡拼定義，方可令簡拼支持模糊音。

**Comment by vcfvct** [comment]
我的情况是因为在`luna_pinyin.extended.dict.yaml` 的 `import_tables`导入了一些自定义词库比如

- luna_pinyin.cn_en.dict.yaml
- luna_pinyin.kaomoji.dict.yaml

这些词库for some reason导致常用字母h/l/x之类的简拼无效, 不导入之后就好了.
