### ISSUE TITLE
地球拼音在 0.12.0 似乎不起作用了

### ISSUE THREAD

**Issue by zhuangya** [rime/squirrel#331]
目前在输入的时候写声调会变成这种情况：

![image](https://user-images.githubusercontent.com/499038/59601919-13545200-9138-11e9-9b1a-d362395e8428.png)

`$HOME/Library/Rime` 我本地有 git 做管理，尝试了

- 重新通过 plum 更新输入方案
- 恢复到之前 `$HOME/Library/Rime` 的版本

都无法恢复地球拼音的功能

**Comment by lotem** [comment]
無法重現問題。
原裝輸入方案不是這樣的結果。

**Comment by zhuangya** [comment]
我找到问题所在了：

```
diff --git a/terra_pinyin.custom.yaml b/terra_pinyin.custom.yaml
index 681de82..c547c6d 100644
--- a/terra_pinyin.custom.yaml
+++ b/terra_pinyin.custom.yaml
@@ -11,8 +11,6 @@ patch:
 
   translator/dictionary: terra_pinyin.custom
 
- #  載入朙月拼音擴充詞庫
-  "translator/dictionary": luna_pinyin.extended
 __patch:
 # Rx: emoji:customize:schema=terra_pinyin {
   - patch/+:
```

看起来我这应该是个例，但是记录一下以备后来也有人遇到 😄️
多谢 @lotem

**Comment by lotem** [comment]
不要混用不同编码的词库
