### ISSUE TITLE
建议增加中/英文，以及拼音串/候选词使用不同字体的功能

### ISSUE THREAD

**Issue by llpub** [rime/squirrel#333]
如题，希望配置里能区分中文和英文的font_face; 
或者区分输入的拼音串和候选词的font_face。例如：等宽字体能让拼音串区分度更高，但是相应的中文间距很难看；
望大神考虑。

**Comment by GJRobert** [comment]
鼠鬚管的 font_face 已經可以用兩個以上的字型來 fallback 了，比方說可以用 Georgia, Songti TC 這樣的，這樣華文和英文就是不同的字型了。

**Comment by lotem** [comment]
試試font fallback能否做到。
目前輸入法並不不支持英文。且「拼音串」也未必是拉丁字母，也可以包含注音符號、倉頡字母等中文字符，以及已經部分選中的中文字。

**Comment by GJRobert** [comment]
呼應佛振，鼠鬚管的 font_face 支援 fallback，真的很感謝。我自己在鼠鬚管就已經用等寬英文字 + 華文字型了。所以在 Squirrel 這裡應該有辦法達到樓主要的效果。

小狼毫可能還沒實做這部分的功能（如果有想必就更方便了），但 Windows 傳統上是可以在系統層面 Registry Editor 中修改字型 fallback 的，我很久以前在 XP 做過，把華文字型設為某英文字型的 fallback。
