### ISSUE TITLE
出现乱码是缺什么字体吗?

### ISSUE THREAD

**Issue by issuessss** [rime/squirrel#335]
<img width="348" alt="image" src="https://user-images.githubusercontent.com/1378332/59959292-f7a9cc80-94e6-11e9-9010-32d18c2564b7.png">

看第8个. 方框里面是个?号

**Comment by bosconb** [comment]
猜测是对生僻字字体支持不到位，装个「 [花园明朝](https://pan.baidu.com/s/1jH56NHW)」字体试试
