### ISSUE TITLE
请问能否记录输入法状态

### ISSUE THREAD

**Issue by Gowa2017** [rime/squirrel#336]
我说描述的正记录输入法状态，可能有点区别。场景是这样的：

我使用 VIM 进行文字的录入，我会在 VIM的 normal 模式和  insert 模式间进行切换。

如果我在 insert 模式，输入完，但是我想要移动的时候，我只能使用  esc 键切换到 normal 模式，但这个时候，输入法中文模式下的，我必须的再来一次 shift 键才能切换到英文模式，能否做到 normal 模式下自动变成英文。

概括一下我在 VIM 中 从 insert 模式 切换到 normal 模式再到 insert 模式的流程：

输入文字 -> ESC（切换到 normal 模式） -> SHIFT（切换英文） -> gg（到首行) -> i (切换到insert模式) -> shift (切换到中文) -> 输入文字。

能否将 shift 这个过程省略掉。

补充：
研究了一下，通过 app_options 选项可以默认设置某应用为英文模式。但是那个是针对 MacOS下的　APP，但是如果是 iterm 内打开 vim 那个是没有 BudleExecuteIdentified 的。这个怎么处理。

**Comment by lotem** [comment]
通過檢測ESC等按鍵完成模式轉換。但沒法限定只在VIM裏有效。
這個版本可以做到在iTerm裏全局生效：
https://github.com/rime/squirrel/pull/166

**Comment by tiglog** [comment]
可以把切换英文模式绑定到 ESC 上。如下：
```
{when: always, accept: Release+Escape, toggle: ascii_mode}
```

**Comment by Gowa2017** [comment]
> 可以把切换英文模式绑定到 ESC 上。如下：
> 
> ```
> {when: always, accept: Release+Escape, toggle: ascii_mode}
> ```

这个，对于个个按键的命名是在哪里有详细的说明么。

Release 是个什么键。
