### ISSUE TITLE
对于使用码表的输入法，如何在候选条中隐藏选项后面的提示码（就是那一串～开头的）？

### ISSUE THREAD

**Issue by semipleno** [rime/squirrel#337]
我希望能够在其他所有功能不变的情况下隐藏掉提示码（如图，那一串～开头的），就正常地、不带别的任何提示地显示选项，请问应该怎么做呢？

我在档案里找了半天也没看到相关资料，也尝试了注释掉schema文档里translator下面的几行，也没有我想要的效果。这是目前的输入法界面：

![75C919274B4F8E57133A40FE657D2B1B](https://user-images.githubusercontent.com/24865709/59991891-b565c400-967b-11e9-9107-458b1fa22692.jpg)

**Comment by semipleno** [comment]
啊啊啊，经过我的各种实验，终于实现啦：在translator中添加
  comment_format:
    - erase/^.*$/
是不是这样

**Comment by lotem** [comment]
無效用例。無法區分編碼完全匹配和部分匹配的候選字。
