### ISSUE TITLE
更新后，密码输入时不会自动转为英文状态

### ISSUE THREAD

**Issue by dalton-chiou** [rime/squirrel#340]
如题。原先0.9.26版本是可以的。需要在哪里设置吗？

**Comment by faynwol** [comment]
0.14同样的问题，网页密码框不会自动变英文
小狼毫是没问题的

**Comment by faynwol** [comment]
@dalton-chiou 请问你解决这个问题了吗？

**Comment by lotem** [comment]
是否切換到密碼鍵盤是由瀏覽器應用和操作系統決定的。

**Comment by faynwol** [comment]
> 是否切換到密碼鍵盤是由瀏覽器應用和操作系統決定的。

@lotem 感谢回复，您的意思是mac下目前不支持吗？

我的各app版本
macOS 10.12.6
鼠须管0.14.0
chrome 79.0.3945

在京东登录页面密码框，鼠须管没有自动切换，win10下小狼毫切换了

**Comment by lotem** [comment]
macOS系統不會在密碼框裏調用輸入法（本品）。
除非網頁沒有正確地定義密碼框，或瀏覽器沒有正確地告訴操作系統光標定位於密碼框。

**Comment by faynwol** [comment]
@lotem 懂了，不过应该是我描述的不对

实际场景是，在登录页面输入用户名有时会处于中文状态，输入后用回车上屏，切换到密码输入框此时仍旧是中文，没有自动切换到英文

**Comment by lotem** [comment]
> @lotem 懂了，不过应该是我描述的不对
> 
> 实际场景是，在登录页面输入用户名有时会处于中文状态，输入后用回车上屏，切换到密码输入框此时仍旧是中文，没有自动切换到英文

这个时候要操作系统把输入法切换到系统键盘。输入法不应该在密码框里激活。因此输入法也不需要处理在密码框里的情形。没有这个使用场景。
