### ISSUE TITLE
Google Doc 中输入时，候选弹窗不跟随光标，而在屏幕顶端

### ISSUE THREAD

**Issue by easy4u** [rime/squirrel#345]
使用的是0.14.0 版本，MAC 系统是 10.14.5，复现概率：必现

<img width="868" alt="Screen Shot 2019-07-17 at 11 35 48 AM" src="https://user-images.githubusercontent.com/6970526/61345300-118cc400-a887-11e9-8c51-8da0451eb168.png">

**Comment by bosconb** [comment]
macOS 10.14.6 Beta ，Squirrel 0.14.0复现，搜了一下，貌似Mac搜狗和mac自带的简体拼音输入法也存在这个问题。
[关于chrome浏览器的bug](http://mse.sogou.com/bbs/forum.php?mod=viewthread&tid=2731390)

**Comment by yangling704** [comment]
暂缓之计
![image](https://user-images.githubusercontent.com/26773794/100913040-3c3ce400-349f-11eb-947e-b8d205997a7c.png)
![image](https://user-images.githubusercontent.com/26773794/100913070-47900f80-349f-11eb-8420-84b66bc619be.png)

**Comment by lotem** [comment]
有待Google修复。

**Comment by benxgh1996** [comment]
@yangling704 在firefox上能解决这个问题吗？在firefox上我没有看到turn on screen magnifier support这个选项。
<img width="520" alt="image" src="https://user-images.githubusercontent.com/15823966/106882162-0d600b80-66a4-11eb-87c9-ba2d99073ed2.png">

**Comment by greatbody** [comment]
> @yangling704 在firefox上能解决这个问题吗？在firefox上我没有看到turn on screen magnifier support这个选项。
> <img alt="image" width="520" src="https://user-images.githubusercontent.com/15823966/106882162-0d600b80-66a4-11eb-87c9-ba2d99073ed2.png">

这个选项是 Google Docs的选项，
![image](https://user-images.githubusercontent.com/6984599/112102851-d9a15c80-8be3-11eb-92c8-59c4c5720497.png)

**Comment by hanksb** [comment]
Turned on screen magnifier support还是看不到词候选框。请问还有什么解决方法么？

**Comment by driventokill** [comment]
> > @yangling704 在firefox上能解决这个问题吗？在firefox上我没有看到turn on screen magnifier support这个选项。
> > <img alt="image" width="520" src="https://user-images.githubusercontent.com/15823966/106882162-0d600b80-66a4-11eb-87c9-ba2d99073ed2.png">
> 
> 这个选项是 Google Docs的选项， ![image](https://user-images.githubusercontent.com/6984599/112102851-d9a15c80-8be3-11eb-92c8-59c4c5720497.png) ![image](https://user-images.githubusercontent.com/6984599/112102919-f5a4fe00-8be3-11eb-9a04-5d1135c6d237.png)

Works for me🎉

**Comment by livesmo** [comment]
> 暂缓之计 ![image](https://user-images.githubusercontent.com/26773794/100913040-3c3ce400-349f-11eb-947e-b8d205997a7c.png) ![image](https://user-images.githubusercontent.com/26773794/100913070-47900f80-349f-11eb-8420-84b66bc619be.png)

赞   尝试了下   问题解决了
