### ISSUE TITLE
在某些应用里候选框的样式与设置的不一样

### ISSUE THREAD

**Issue by zhuxiaoxi** [rime/squirrel#347]
本来设置的是这样的候选框
![photo_2019-07-20_19-34-23](https://user-images.githubusercontent.com/2098464/61578178-7b29fe00-ab25-11e9-8d3b-41472b73f43e.jpg)

唯独终端应用里是这样的双行候选框，其他的第三方输入法可以始终保持一样的样式，Rime不能这样。是BUG吗？
![photo_2019-07-20_19-34-26](https://user-images.githubusercontent.com/2098464/61578192-9ac12680-ab25-11e9-833e-0365045649bd.jpg)

**Comment by lotem** [comment]
不是BUG。特意設置成這樣的。

**Comment by zhuxiaoxi** [comment]
> 不是BUG。特意設置成這樣的。

请问有没有方法调一下？

**Comment by lotem** [comment]
是這項配置控制的：
https://github.com/rime/squirrel/blob/master/data/squirrel.yaml#L289

**Comment by dimosz** [comment]
@lotem 遇到同样的问题，感谢。
