### ISSUE TITLE
在IDEA中，出现重复输入

### ISSUE THREAD

**Issue by bpzhang** [rime/squirrel#348]
在idea中，切换到字母输入状态，如果快速的敲击三个键，会出现重复的问题。例如敲击L、O、G。则会出现oog或者是llg等

**Comment by issuessss** [comment]
是的

**Comment by issuessss** [comment]
类似一种双击，连击。
特别是使用快捷键，非常明显。我以为键盘出问题了，后来切换到自带的输入没问题。

**Comment by issuessss** [comment]
IntelliJ IDEA 2019.2 (Ultimate Edition)
Build #IU-192.5728.98, built on July 23, 2019

**Comment by issuessss** [comment]
在浏览器打字会出现连击情况。和idea无关。

**Comment by yakirChen** [comment]
+ [librime的submodule](https://github.com/rime/librime/tree/master/thirdparty/src)都用最新的commit 
+ boost 用了1.71.0

昨天晚上重新编译了下 没有碰到这个问题了

**Comment by yakirChen** [comment]
+ [librime的submodule](https://github.com/rime/librime/tree/master/thirdparty/src)都用最新的commit 
+ boost 用了1.71.0

昨天晚上重新编译了下 没有碰到这个问题了

**Comment by bpzhang** [comment]
> 在浏览器打字会出现连击情况。和idea无关。

我只是在IDEA中会出现这个问题，其他软件或者是浏览器中都没有

**Comment by spphins** [comment]
这一点,在cpu占有率高的时候,就会特别的明显.

**Comment by bpzhang** [comment]
> 这一点,在cpu占有率高的时候,就会特别的明显.

是的 貌似中文输入软件都有这个问题，现在还不确定是不是第三方的输入法都这样

**Comment by spphins** [comment]
今天试了一下最新版的，貌似修复了这个问题，已经不会出现连陆的情况了。
