### ISSUE TITLE
Shift_L和Shift_R作用不正常

### ISSUE THREAD

**Issue by zhouye** [rime/squirrel#35]
在MacOS 10.9.4下Shift_L和Shift_R都映射到Shift_L

default.custom.yaml片段：

  key_binder/bindings:
- send: 2
  accept: Shift+Shift_L
  when: composing
- send: 3
  accept: Shift+Shift_R
  when: composing

按下左右shift都会输入2

**Comment by xzer** [comment]
分享一个可用的hack方案：

首先，既然输入法不能识别左右shift，那么我们就不用左右shift来区分，设置成shift取第二个，control取第三个：

```yaml
  "key_binder/bindings":
    - { when: has_menu, accept: Shift+Shift_L, send: 2 }
    - { when: has_menu, accept: Control+Control_L, send: 3 }
```

接下来，用karabiner截获右shift按键，转换成control发出去：

```xml
  <item>
    <name>Swap SHIFT_R to CONTROL_L (retain SHIFT_R)</name>
    <identifier>private.my_squirrel_swap_shift_r</identifier>

    <inputsource_only>squirrel</inputsource_only>

    <autogen>__KeyToKey__ KeyCode::SHIFT_R, KeyCode::CONTROL_L, KeyCode::SHIFT_R</autogen>
  </item>
```

上面的配置有一个小问题，右键选择之后会被切换到英文输入状态，有两个解决办法，第一，我因为是用的日本版的mac book，配置的日文键盘，本身有「英数」键可以快捷切换中英文，所以，我简单的将shift切换输入法状态禁用掉了：

```yaml
  ascii_composer:
    switch_key:
      Shift_L: noop
      Shift_R: noop
```

另外一个办法，是将上面的转换，再多送一个shift出来：

```xml
    <autogen>__KeyToKey__ KeyCode::SHIFT_R, KeyCode::CONTROL_L, KeyCode::SHIFT_R, KeyCode::SHIFT_R</autogen>
```

或者，干脆一个shift也不送：

```xml
    <autogen>__KeyToKey__ KeyCode::SHIFT_R, KeyCode::CONTROL_L</autogen>
```

一个shift都不送的时候，偶尔在中文状态下右键shift输入一个大写字母这样的情况可能会有些不便，所以，还是推荐多送一个shift的方案。

多送一个shift的坏处是，每次右shift选字的时候，鼠须管都会有一个小的淡出窗口提示现在切换到中文状态了，多少有些烦扰。@lotem 能够禁止显示那个提示窗口吗？

**Comment by Lluvio** [comment]
@xzer  如果使用上karabiner的话，你这个应该只能适应 10.12以前的版本。现在作者的新项目karabiner-element，可以达到你说的效果。另，现在的配置是json，比xml更加方便.

**Comment by MingzSau** [comment]
不好意思挖坟了，因为最近也在折腾这个。
如果都用键位映射的方案了，直接把左右shift的短按操作映射到数字2、3就好了。

**Comment by dengshenkk** [comment]
```
    - { when: has_menu, accept: Shift+Shift_L, send: 2 }
    - { when: has_menu, accept: Shift+Shift_R, send: 3 }
```

## 鼠须管 0.16.1 是当前的最新版本。
### 用的是小鹤双拼, 这样设置后经过测试是可以区分左右的, 左shift上屏第二候选词, 右shift上屏第三候选词.
