### ISSUE TITLE
请教各位大佬五笔+拼音模式下怎么样实现自动造词功能

### ISSUE THREAD

**Issue by man2018** [rime/squirrel#351]
各位大佬，目前我用的是鼠须管0.14.0版本，新建了一个wubi_pinyin.custom.yaml文件，里面内容如下：
# wubi_pinyin.custom.yaml
# encoding: utf-8

patch:
  switches:
    - name: ascii_mode
      reset: 0
      states: ["中文", "西文"]
    - name: full_shape
      states: ["半角", "全角"]
    - name: extended_charset
      states: [ 常用, 增廣 ]
    - name: simplification
      reset: 0
      states: ["汉字", "漢字"]
    - name: show_emoji
      reset: 1
      states: [ "🈚️️\uFE0E", "🈶️️\uFE0F" ]
    - name: ascii_punct
      states: [ 。，, ．， ]

  simplifier:
      opencc_config: s2t.json  # 简入繁出

  engine/filters:
    - simplifier
    - uniquifier
    - simplifier@emoji_conversion

  emoji_conversion:
    opencc_config: emoji.json
    option_name: show_emoji
    tags: abc

  #"speller/max_code_length": 4 #最长4码
  "speller/auto_select": true #顶字上屏
  "speller/auto_select_unique_candidate": true #无重码自动上屏
  
  "translator/dictionary": wubi86.extended #加载五笔词库
  "reverse_lookup/comment_format/@1": xform/^(\w+).*/$1/
  "translator/enable_encoder": true

#  符号快速输入和部分符号的快速上屏
  punctuator:
    import_preset: symbols
    symbols:
      "/fs": [½, ‰, ¼, ⅓, ⅔, ¾, ⅒ ]
      "/bq": [😂️, 😅️, ☺️, 😱️, 😭️, 😇️, 🙃️, 🤔️, 💊️, 💯️, 👍️, 🙈️, 💩️, 😈️ ]
      "/dn": [⌘, ⌥, ⇧, ⌃, ⎋, ⇪, , ⌫, ⌦, ↩︎, ⏎, ↑, ↓, ←, →, ↖, ↘, ⇟, ⇞]
      "/fh": [ ©, ®, ℗, ℠, ™, ℡, ⓘ, ♂, ♀, ☉, ☊, ☋, ☌, ☍, ☐, ☑︎, ☒, ☜, ☝, ☞, ☟, ✎, ✄, ♲, ♻, ⚐, ⚑, ⚠]
      "/xh": [ ＊, ×, ✱, ★, ☆, ✩, ✧, ❋, ❊, ❉, ❈, ❅, ✿, ✲]
    half_shape:
      "#": "#"
      "*": "*"
      "`": "`"
      "~": "~"
      "@": "@"
      "=": "="
      "/": ["/", "÷"]
      '\': "、"
      "_" : "──"
      "'": {pair: ["「", "」"]}
      "[": ["【", "["]
      "]": ["】", "]"]
      "$": ["¥", "$", "€", "£", "¢", "¤"]
      "<": ["《", "〈", "«", "<"]
      ">": ["》", "〉", "»", ">"]
  recognizer/patterns/punct: "^/([a-z]+|[0-9]0?)$"

# 使用自定义词典 custom_phrase.txt
  custom_phrase:
    dictionary: ""
    user_dict: custom_phrase
    db_class: stabledb
    enable_completion: false
    enable_sentence: false
    initial_quality: 1
  "engine/translators/@4": table_translator@custom_phrase

这样的配置，无法对于输入过的字生成新词。如：输入了“好菜谱”3字，下次不能直接以vayu3个码直接打出来“好菜谱”3字。可有办法解决

**Comment by ooopscc** [comment]
+1，同样的问题，最后无奈只能不用 extended 词库。

**Comment by man2018** [comment]
@ooopscc 我请教了大神，解决方法是：直接把别的词库添加到默认的wubi86.dict.yaml里面就行了

**Comment by lotem** [comment]
請檢查是否定義了詞組編碼的規則。
組詞的規則由 `translator/dictionary` 所定義的詞典指定。即 `wubi86.extended.dict.yaml`。

**Comment by man2018** [comment]
@lotem 直接将其他词库添加到默认的里面就行了 你这个方式我不会搞

**Comment by byujiang** [comment]
也是遇到同样问题，只能不用 extended 词库了。

**Comment by lotem** [comment]
參考 https://github.com/rime/home/issues/534
