### ISSUE TITLE
为什么把小狼毫默认的主题加到鼠须管里面显示效果很差呢 求救

### ISSUE THREAD

**Issue by man2018** [rime/squirrel#354]
如题，我照着小狼毫默认的主题修改了下，但运用到鼠须管上面显示效果很差，有人知道啥情况不

![2019-08-14_18-19-45](https://user-images.githubusercontent.com/18020785/63014173-8243f200-bec0-11e9-988f-486fb9f59493.jpg)
![2019-08-14_18-20-33](https://user-images.githubusercontent.com/18020785/63014174-8243f200-bec0-11e9-9007-ac6c208631f8.jpg)

**Comment by lotem** [comment]
二者不是同一個軟件。

**Comment by man2018** [comment]
@lotem 大佬，能辛苦你给鼠须管搞个小狼毫默认的主题吗？
