### ISSUE TITLE
双拼模式下最后一个字不支持联想

### ISSUE THREAD

**Issue by majie1993** [rime/squirrel#355]
比如用小鹤打 “拼音” 两个字，输入 pby 不能联想出 “拼音”，必须输入完整的 “pbyb” 才行

![image](https://user-images.githubusercontent.com/2177086/63152195-d4f6e880-c03d-11e9-8918-f98e4ff8aa7f.png)

![image](https://user-images.githubusercontent.com/2177086/63152183-cb6d8080-c03d-11e9-92d7-d470ab226267.png)

**Comment by lotem** [comment]
無法重現問題

**Comment by majie1993** [comment]
仔细测试了一下，应该是这个词库导致的问题。
https://github.com/xiaoTaoist/rime-dict
小鹤双拼的 custom yaml 引入 translator/dictionary: luna_pinyin.extended，就会出现上面图上的问题

**Comment by HaiFongPan** [comment]
@majie1993 感谢指名方向，也在用差不多的词库，去掉 luna_pinyin.cn_en.dict.yaml 就没问题了。

**Comment by lotem** [comment]
我在各個場合敬告大家，拼音詞典顧名思義只用拼音編碼。什麼編碼都加進去，那肯定會出問題的。
