### ISSUE TITLE
请问鼠须管地球拼音如何做到中文时全角标点,英文时半角标点

### ISSUE THREAD

**Issue by raysshine** [rime/squirrel#358]
我记得以前是这样的(也可能我记错了).

好几天没开mac,今天用的时候中文状态的标点全是半角的了.
要是切成全角状态的话,英文输入时又是全角了.

来回切换好头疼啊.请问有没有方法能自动中文时全角,英文时半角?
谢谢!

系统:macOS 10.14.6
输入法:鼠须管0.14.0

**Comment by lotem** [comment]
在方案選單裏，依次選中狀態「半角」及「，。」

**Comment by plainee** [comment]
这个确实很乱.我...,,,正在输入...,.??...中文
打开全角后，．．是这样．．．ｄｓｆａｓｆｄｓａ．．．
