### ISSUE TITLE
RIME在VSCode中候选框位置随机漂移

### ISSUE THREAD

**Issue by f1ynng8** [rime/squirrel#359]
OS：MacOS 10.14.6 MoJave
RIME: 0.14

目前仅发现在VSCode中使用Shift切换中英文时的Caption，以及打字的候选框会随机遮挡当前正在输入的行，我录了一个视频供参考：
![vscode 2019-09-08 07_56_08](https://user-images.githubusercontent.com/1539218/64481418-57726280-d20e-11e9-855f-4414a8f7fdd6.gif)

另外在其它程序里都使用正常，我随机找了MacOS自带的text editor录了一段视频，可见切换中英文时的Caption和打字的候选框位置都是正确的。
![text_editor 2019-09-08 07_57_21](https://user-images.githubusercontent.com/1539218/64481433-9d2f2b00-d20e-11e9-8f89-8081d789ec4d.gif)

目前使用配置是这里的：https://github.com/KyleBing/rime-wubi86-jidan

不知道其它人是否也遇到这个问题？

**Comment by dongyuwei** [comment]
VS Code 键盘事件处理可能有问题。我测试10.14.5系统自带的拼音输入法和搜狗输入法，候选词定位都有点问题。

**Comment by lotem** [comment]
這麼說來，應該屬於應用軟件的問題。

**Comment by LuciusChen** [comment]
MacOS 在 emacs 里面出现了候选框始终在屏幕的左下角（贴边）的情况，不知道怎么解决。

**Comment by ksqsf** [comment]
@LuciusChen https://github.com/emacs-mirror/emacs/commit/ceb5a1522270c41d0c9f5e6b52d61e3173f72f1d#diff-f023bf0bfcff23de9af72f520f9b7b33a648a223c2136b32da73da7e4571fae2R7064 请向Emacs报告bug。

**Comment by LuciusChen** [comment]
> @LuciusChen [emacs-mirror/emacs@ceb5a15#diff-f023bf0bfcff23de9af72f520f9b7b33a648a223c2136b32da73da7e4571fae2R7064](https://github.com/emacs-mirror/emacs/commit/ceb5a1522270c41d0c9f5e6b52d61e3173f72f1d#diff-f023bf0bfcff23de9af72f520f9b7b33a648a223c2136b32da73da7e4571fae2R7064) 请向 Emacs 报告 bug。

报了 bug，那边也给了 patch 可以暂时修复这个问题。

```
diff --git a/src/nsterm.m b/src/nsterm.m
index b56c587bc69..b883e605a5b 100644
--- a/src/nsterm.m
+++ b/src/nsterm.m
@@ -7064,7 +7064,7 @@ - (void) setMarkedText: (id) string
 - (NSRect) firstRectForCharacterRange: (NSRange) range
 			  actualRange: (nullable NSRangePointer) actualRange
 {
-  return NSZeroRect;
+  return [self firstRectForCharacterRange: range];
 }
 
 #endif /* NS_IMPL_COCOA */
```

**Comment by LuciusChen** [comment]
修复已经 push 到 master 了
