### ISSUE TITLE
设置其中一个 shift 为 noop，然后另一个 shift 也没作用了

### ISSUE THREAD

**Issue by glacjay** [rime/squirrel#361]
我在 windows 下设置左 shift 为 noop，右 shift 为 commit_code，工作正常；mac 下同样的配置，结果两个 shift 都不起作用了，只有把两个 shift 都设置为 commit_code 才行。

**Comment by lotem** [comment]
同 https://github.com/rime/squirrel/issues/176

**Comment by lotem** [comment]
同 https://github.com/rime/squirrel/issues/35
