### ISSUE TITLE
Squirrel的翻页问题

### ISSUE THREAD

**Issue by Jreen** [rime/squirrel#363]
其实很早就有这样的问题了。但我一直懒得没有排查问题，直到现在：
里面是我的default.custom.yaml关于快捷键的设置
```
  key_binder/bindings:
    __patch:
      - key_bindings:/paging_with_minus_equal
```
按照上面说的，
paging_with_minus_equal:
  __append:
    - { when: has_menu, accept: minus, send: Page_Up }       
    - { when: has_menu, accept: equal, send: Page_Down }

when: has_menu, accept: minus, send: Page_Up  是- 向后翻页
when: has_menu, accept: equal, send: Page_Down 是=向前翻页

可是问题是：=变成了向后翻页，-没有生效的样子。

我的luna里面没有关于key_binder方面的设置。

**Comment by lotem** [comment]
`Page_Up` 是去上一页，`Page_Down` 是去下一页。

**Comment by Jreen** [comment]
可是我按"equal"再按"minus"，本应该是翻上一页，可直接变成了“ - ”了

我这个情况是这样的：
输入拼音 —— 找需要的字—— （翻页）—— 错过需要的字，再翻上一页 —— 不能翻上一页，直接变成“ - ” 这个了

**Comment by lotem** [comment]
原裝軟件無法重現。
`-`鍵可能是被別的處理器處理了。請檢查自定義配置。
