### ISSUE TITLE
配色方案可以單獨寫在一個檔案/文件裡嗎？

### ISSUE THREAD

**Issue by GJRobert** [rime/squirrel#366]
大多數人都是使用 squirrel.custom.yaml 在新增自訂配色方案，把
```
patch:
  ...
  preset_color_schemes/mycolor:
    ...
```
寫在裡頭，然後再用 `style/color_scheme` 來調用 `mycolor`。

我好奇：Rime 的 YAML 整體調用機制，是否允許我們建立一個獨立的 YAML 檔案/文件，來存放這個 mycolor 配色方案，以便模組化維護及佈建？比方說我可以建立一個 squirrel.mycolor.custom.yaml 檔案，讓 Rime 在 build 的時候也可以一併調用嗎？今天嘗試了一下好像不行……

**Comment by lotem** [comment]
可以。
請參考 https://github.com/lotem/rime-theme-windows10

**Comment by GJRobert** [comment]
很感謝您〜
