### ISSUE TITLE
鼠鬚管的 border_color 參數有效嗎？

### ISSUE THREAD

**Issue by GJRobert** [rime/squirrel#367]
我看 [Rime西米](https://bennyyip.github.io/Rime-See-Me/) 的候選框是有邊框效果的，但是我發現鼠鬚管，也就是我們 macOS 上，不管配色主題的 `border_color` 怎麼設定（通常會和 `back_color` 不同），或是 `border_width`、`border_height` 設定多大，或是我調用哪個內建的配色主題，永遠都看不出有邊框。

請問這是鼠鬚管的 feature 或是 bug？

**Comment by lotem** [comment]
「Rime西米」用於設計小狼毫配色方案。兩者界面略有不同。

**Comment by GJRobert** [comment]
我把「Rime 西米」fork 並修改了一個專門用於設計鼠鬚管配色方案的：
[Rime 西米 for Squirrel](https://gjrobert.github.io/Rime-See-Me-squirrel/)

歡迎指教。
（專案原始碼在：[GJRobert/Rime-See-Me-squirrel: Skin editor for Squirrel (Rime frontend on macOS)](https://github.com/GJRobert/Rime-See-Me-squirrel)）
