### ISSUE TITLE
xcode11.1上，编译主程序成功，但是提示签名失败

### ISSUE THREAD

**Issue by 98wb** [rime/squirrel#370]
```
Signing Identity:     "-"

    /usr/bin/codesign --force --sign - --entitlements /Users/pc/Downloads/squirrel-master/build/Squirrel.build/Release/Squirrel.build/Squirrel.app.xcent --timestamp=none /Users/pc/Downloads/squirrel-master/build/Release/Squirrel.app
/Users/pc/Downloads/squirrel-master/build/Release/Squirrel.app: code object is not signed at all
In subcomponent: /Users/pc/Downloads/squirrel-master/build/Release/Squirrel.app/Contents/MacOS/rime-install
Command CodeSign failed with a nonzero exit code
```

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by lotem** [comment]
如何構建的？

**Comment by 98wb** [comment]
手动下载所有源代码及相关依赖，没有升级 xcode 前，编译一切正常。
升级过一次 xcode 到最新版之后，librime 部分，plum 部分，app 打包都通过，仅签名这里反复报错。
编译是按照 install.md 所述步骤来的，并没其它的更改。
虽然提示签名失败，但是手动进入「squirrel/package」下，执行 make_package 脚本，也能正常封包。
所封的包，以恰当权限执行安装，也未见异常。

**Comment by kuoruan** [comment]
+1
手动签名也不行
```
/usr/bin/codesign --force --sign - --entitlements /Users/***/Projects/Github/squirrel/build/Squirrel.build/Release/Squirrel.build/Squirrel.app.xcent --timestamp=none /Users/opera/Projects/Github/squirrel/build/Release/Squirrel.app
/Users/***/Projects/Github/squirrel/build/Release/Squirrel.app: code object is not signed at all
In subcomponent: /Users/***/Projects/Github/squirrel/build/Release/Squirrel.app/Contents/MacOS/rime-install
```

**Comment by kuoruan** [comment]
Fixed:
https://stackoverflow.com/questions/58195914/xcode-11-command-codesign-failed-with-a-nonzero-exit-code

Add ```--deep``` to the "Other Code Signing Flags" in the "Build Settings".

<img width="868" alt="2019-11-29 11:21:25am" src="https://user-images.githubusercontent.com/8685618/69841502-63fcd900-129a-11ea-9630-2ec0675b1149.png">
