### ISSUE TITLE
Failed to brew link --force boost@1.60

### ISSUE THREAD

**Issue by a8568730** [rime/squirrel#371]
Thank you for this great work. :)

I follow the installation instructions in [INSTALL.md](https://github.com/rime/squirrel/blob/master/INSTALL.md), successfully installed the xcode-select and boost@1.6.0.
```
$ xcode-select --install
$ brew install boost@1.60
```
However, I ran into error when brew link: 
```
$ brew link --force boost@1.60

Linking /usr/local/Cellar/boost@1.60/1.60.0... 
Error: Could not symlink include/boost/accumulators/accumulators.hpp
Target /usr/local/include/boost/accumulators/accumulators.hpp
is a symlink belonging to boost. You can unlink it:
  brew unlink boost

To force the link and overwrite all conflicting files:
  brew link --overwrite boost@1.60

To list all files that would be deleted:
  brew link --overwrite --dry-run boost@1.60
```
What did I miss?

**Comment by lotem** [comment]
You probably have brew-installed the latest version of boost already.
In that case you can build a non-portable version (relying on the homebrewed software on your computer)  by editing the Makefile after this line:
https://github.com/rime/squirrel/blob/master/Makefile#L6

**Comment by a8568730** [comment]
I tried your advice and edit the Makefile, and it works. :)

Also, thanks to your point,
> You probably have brew-installed the latest version of boost already.

I tried to reinstall boost@1.6.0, 
```
$ brew uninstall boost
$ brew install boost@1.60
```
Then brew link script run successfully.
```
$ brew link --force boost@1.60
Linking /usr/local/Cellar/boost@1.60/1.60.0... 119 symlinks created
