### ISSUE TITLE
用自定义短语也无法输入「塚」字

### ISSUE THREAD

**Issue by zhouhui-monstar** [rime/squirrel#373]
这个字应该是日文汉字，
添加到自定义短语后显示出来的也是简体的「冢」字。
![](https://s.macboke.com/20191107-1715.gif)

**Comment by lotem** [comment]
簡化字標準裏「冢」是規範的寫法。
選用「朙月拼音·簡化字」方案或在輸入法狀態裏選中簡化字模式，會將非規範字轉換爲對應的簡化字。

**Comment by zhouhui-monstar** [comment]
明白了，感谢解答。
