### ISSUE TITLE
macOS 10.15 開放CapsLock的API

### ISSUE THREAD

**Issue by yycking** [rime/squirrel#375]
我發現[Catalina 可支援第三方輸入法，用 CapsLock 切換中英輸入](https://developer.apple.com/documentation/bundleresources/information_property_list/ticapslocklanguageswitchcapable?language=objc)。

good_old_caps_lock似乎是在librime做處理，那麼鼠鬚管是否有機會實作這個功能？

**Comment by yycking** [comment]
測試結果
![截圖 2019-11-11 下午3 13 15](https://user-images.githubusercontent.com/7345347/68568393-6e476680-0496-11ea-8e93-8843a93ed5b7.png)

新增
`<key>TICapsLockLanguageSwitchCapable</key>
<true/>`
至鼠鬚管的Info.plist

**Comment by hiking93** [comment]
> 新增
> `<key>TICapsLockLanguageSwitchCapable</key> <true/>`
> 至鼠鬚管的Info.plist
> 
> 測試結果
> ![截圖 2019-11-11 下午3 13 15](https://user-images.githubusercontent.com/7345347/68568393-6e476680-0496-11ea-8e93-8843a93ed5b7.png)
> 這個可以避開java application只能大寫的坑。
> 可是會有切換輸入法，燈不亮的問題！

多謝 🙏

我覺得燈不亮倒是合理，macOS 內建輸入法的行為就是這樣；長按 caps lock 依然可以進入大寫模式，這時候燈就會亮起來。

**Comment by lovelock** [comment]
> 新增
> `<key>TICapsLockLanguageSwitchCapable</key> <true/>`
> 至鼠鬚管的Info.plist
> 
> 測試結果
> ![截圖 2019-11-11 下午3 13 15](https://user-images.githubusercontent.com/7345347/68568393-6e476680-0496-11ea-8e93-8843a93ed5b7.png)
> 這個可以避開java application只能大寫的坑。
> 可是會有切換輸入法，燈不亮的問題！

改了`Info.plist`之后还要怎么操作才能生效？是要重新编译吗？我改了之后好像没有什么变化。Rime让我唯一觉得不方便的地方就是这个点了。

**Comment by lovelock** [comment]
修改之后重启你的Java Application，用的最多的大概就是Jetbrains全家桶了吧，就可以生效了。这样的效果就媲美原生的了。我最喜欢的是可以用Emacs的键位，附上我的配置 https://github.com/lovelock/rime

**Comment by casouri** [comment]
加载设置以后似乎要重启别的app才能正常切换。

**Comment by crazyxhz** [comment]
用了这个确实和原生体验更接近了, 只是切换输入法的时候英文能否上屏呢, 现在从中文输入法切换到系统英文输入法, 会带上中文结果

**Comment by PrometheusH** [comment]
@yycking @lovelock @casouri 在你们三个的帮助下完美解决了问题，感你们的分享，世界有你们而更美好

**Comment by PrometheusH** [comment]
@crazyxhz 
1. 点鼠须管用户设定
<img width="238" alt="截屏2021-01-05 下午8 50 48" src="https://user-images.githubusercontent.com/43463393/103649220-0e185b80-4f99-11eb-9965-9029a579e52e.png">
2. 打开default.custom.yaml
<img width="422" alt="截屏2021-01-05 下午8 51 04" src="https://user-images.githubusercontent.com/43463393/103649391-5768ab00-4f99-11eb-9344-c7da9445a5ba.png">
3.将Caps_Lock:设置为commit_code，就可以实现切换输入法时英文上屏
`customization:
  distribution_code_name: Squirrel
  distribution_version: 2019-06-23
  rime_version: 1.5.3
patch:
  schema_list:
    - schema: flypy # 添加小鹤音形

#
# 可用的按键有 Caps_Lock, Shift_L, Shift_R, Control_L, control_R
# Mac 系统上的鼠须管不能区分左、右，因此只有对 Shift_L, Control_L 的设定起作用
#
# 已输入编码时按切换键，可以进一步设定输入法中西文切换的形式
# 可选的临时切换策略有三：
# inline_ascii 在输入法的临时西文编辑区内输入字母、数字、符号、空格等，回车上屏后自动复位到中文
# commit_text 已输入的候选文字上屏并切换至西文输入模式
# commit_code 已输入的编码字符上屏并切换至西文输入模式
# 设为 noop, 屏蔽该切换键
#
# 如果要把Caps Lock 设为只改变字母的大小写而不做中西文切换，可将 Caps_Lock 对应的切换方式设为 noop
# 如果要以Caps Lock 切换到西文模式，默认输出小写字母，请置 ascii_composer/good_old_caps_lock: false
# 如果要以Caps Lock 切换到西文模式，默认输出大写字母，请置 ascii_composer/good_old_caps_lock: true

  ascii_composer/good_old_caps_lock: false
  ascii_composer/switch_key:
    Caps_Lock: commit_code
    Shift_L: noop
    Shift_R: noop
    Control_L: noop
    Control_R: noop

  key_binder/bindings:
    - when: paging
      accept: bracketleft
      send: Page_Up
    - when: has_menu
      accept: bracketright
      send: Page_Down
`

**Comment by gngshn** [comment]
问下有人解决了重启电脑之后输入法就无法输入中文提问题吗?
