### ISSUE TITLE
不想让Rime在Win10命令行中自动切换为英文

### ISSUE THREAD

**Issue by panhaoyu** [rime/squirrel#378]
我的输入方案是，英文采用系统英文输入法，而中文采用Rime的方案。现在，命令行中，切换至Rime，默认是英文输入法，而我希望默认是一个中文输入法。请问有什么好的方案吗？

删除ascii_composer没用，试过了。

小弟在些先感谢各位大佬了。

Hey, everyone.

My input method is, using system English input method and Rime Chinese input method.
My system in Win10, latest.
Now, in a cmd window, when I change my input method from system ENglish method to Rime, it defaults english mode of rime. I hope I can change the default mode to Chinese. In all other programs, it works well, but failed on CMD.

I've tried to delete `ascii_composer`, but it did not work.

**Comment by lotem** [comment]
這個項目是用在macOS上的輸入法。

和Windows命令行有關的配置在這裏：
https://github.com/rime/weasel/blob/master/output/data/weasel.yaml#L7
