### ISSUE TITLE
Macos下浏览器下载路径文件名称选择里面无法切换英文输入

### ISSUE THREAD

**Issue by Likenttt** [rime/squirrel#382]
Safari里面当我点击下载的时候会弹出一个页面让我选择下载的路径以及下载的文件名称,但是在这里面我无法切换成英文输入,有些文件我不喜欢使用中文命名,此时就只能切换到默认的输入法了

**Comment by lotem** [comment]
相關問題 https://github.com/rime/squirrel/issues/381

**Comment by lotem** [comment]
相同
https://github.com/rime/squirrel/issues/85
https://github.com/rime/squirrel/issues/306
