### ISSUE TITLE
squirrel前端请求多字体支持

### ISSUE THREAD

**Issue by yanhuacuo** [rime/squirrel#387]
一个独立的字体，支持的字符数量上限是「65535」个。

目前 unicode 13 草案已经定下了扩展G，全部 unicode 汉字已近十万。

为了正常显示，通用的做法是将它们分成多个字体文件。

但是目前 squirrel 并不支持多字体备选，单个字体名指定，系统会自动将缺失的部分 fallback 给系统默认字体，后果就是显示效果非常混乱。

能否考虑像 vscode 或 Atom 那样，可以接受多个字体，从根源上解决超集显示问题？

当然，通过复杂的操作，也可以修改 MacOS 的 fallback 列表实现字体统一，不过这将会影响到所有软件，整个系统，太痛苦了。

**Comment by lotem** [comment]
配置樣例 https://github.com/rime/squirrel/issues/287
