### ISSUE TITLE
emacs evil-mode 中重进入 insert-mode 时 rime 默认为 asci_mode

### ISSUE THREAD

**Issue by ArchCST** [rime/squirrel#391]
### 系统信息
OS：macOS
版本：鼠须管 0.14.0
输入法切换软件：fcitx-remote

### Bug重现
![CleanShot 2019-12-17 at 21 49 30](https://user-images.githubusercontent.com/41679407/71000963-35468580-2117-11ea-8db1-0b7c82c51c86.gif)

1. 全新安装鼠须管 0.14.0
2. 进入 ~/Library/Rime 建立 squirrel.custom.yaml，写入patch后重新布署
```
patch:
  app_options/org.gnu.Emacs: {}
```
3. 打开emacs，按 i 进入 insert-mode ，切换到 Squirrel ，正常输入中文「啊啊」。
4. 按 esc 进入 normal-mode，fcitx-remote 正确将输入法切换到 English。
5. 按 a 进入 insert-mode，按 「aa」期望输入「啊啊」，此时 `bug` 出现：fcitx-remote正确将输入法切换到 Squirrel，但 Squirrel 为 ascii_mode，无法输入中文。

同样的操作在 IntelliJ IDEA 的 [ideavim_extension](https://github.com/hadix-lin/ideavim_extension) 插件下可正常使用并无此bug。

_Originally posted by @ArchCST in https://github.com/rime/squirrel/issues/389#issuecomment-566550372_

**Comment by lotem** [comment]
>
> 同样的操作在 IntelliJ IDEA 的 [ideavim_extension](https://github.com/hadix-lin/ideavim_extension) 插件下可正常使用并无此bug。
> 
> _Originally posted by @ArchCST in [#389 (comment)](https://github.com/rime/squirrel/issues/389#issuecomment-566550372)_

在另一款軟件裏使用同樣的輸入法可以完成相同操作，可見問題不是出在輸入法上的。
