### ISSUE TITLE
app_options patch 后必需要手动重启输入法

### ISSUE THREAD

**Issue by ArchCST** [rime/squirrel#392]
观察到在 `squirrel.yaml` 中所有设置了 `app_options/ascii_mode: true` 的软件用 `app_options/xxx: {}` patch掉后均出现了 [#391 ](https://github.com/rime/squirrel/issues/391) 提到的 Bug，而其它软件则不会有此问题。

可见 [#391 ](https://github.com/rime/squirrel/issues/391) 提到的 issue 确实存在于 squirrel 中关于 app_options 的代码中。

> 同样的操作在 IntelliJ IDEA 的 [ideavim_extension](https://github.com/hadix-lin/ideavim_extension) 插件下可正常使用并无此bug。
> 
> _Originally posted by @ArchCST in [#389 (comment)](https://github.com/rime/squirrel/issues/389#issuecomment-566550372)_

在另一款軟件裏使用同樣的輸入法可以完成相同操作，可見問題不是出在輸入法上的。

_Originally posted by @lotem in https://github.com/rime/squirrel/issues/391#issuecomment-567320021_

**Comment by lotem** [comment]
請描述一下本帖提出的具體是什麼問題？有沒有簡單的重現步驟？

**Comment by ArchCST** [comment]
### 系统信息
OS：macOS
版本：鼠须管 0.14.0
输入法切换软件：fcitx-remote

### Bug重现
![CleanShot 2019-12-17 at 21 49 30](https://user-images.githubusercontent.com/41679407/71000963-35468580-2117-11ea-8db1-0b7c82c51c86.gif)

1. 全新安装鼠须管 0.14.0
2. 进入 ~/Library/Rime 建立 squirrel.custom.yaml，写入patch后重新布署
```
patch:
  app_options/org.gnu.Emacs: {}
```
3. 打开emacs，按 i 进入 insert-mode ，切换到 Squirrel ，正常输入中文「啊啊」。
4. 按 esc 进入 normal-mode，fcitx-remote 正确将输入法切换到 English。
5. 按 a 进入 insert-mode，按 「aa」期望输入「啊啊」，此时 `bug` 出现：fcitx-remote正确将输入法切换到 Squirrel，但 Squirrel 为 ascii_mode，无法输入中文。

squirrel.yaml 中所有设置了 app_options/ascii_mode: true 的软件用 app_options/xxx: {} patch掉后均出现了此bug。

**Comment by lotem** [comment]
「所有设置了 `app_options/ascii_mode: true` 的软件」是怎麼出現這個BUG的？所有軟件按ESC都能進insert-mode嘛？如果只是VIM這一個軟件有問題，還用了外部切換器的話，我就不研究了。

**Comment by ArchCST** [comment]
同一个bug报了三次，也给了详细的重现步骤，还是希望能解决一下。外部切换器工作没问题，别强行让人在vim中不能用中文。

**Comment by lotem** [comment]
抱歉。我只能儘量保證輸入法在正常的應用裏能工作。
本身就邏輯複雜，對輸入有特殊處理的的應用，我實在力有未逮。
強行讓，簡直是無稽之談。

**Comment by aur3l14no** [comment]
我这边也出现了这个情况...

**Comment by aur3l14no** [comment]
@ArchCST 你现在解决了么？VSCode (用 im-select / fcitx-remote) 和 Emacs (用 fcitx-remote) 都遇到了这个问题。

**Comment by ArchCST** [comment]
> @ArchCST 你现在解决了么？VSCode (用 im-select / fcitx-remote) 和 Emacs (用 fcitx-remote) 都遇到了这个问题。

解决了，换落格

**Comment by aur3l14no** [comment]
@ArchCST 你用的是落格输入法 2 么？我使用 fcitx.el + fcitx-remote 依旧出现了这个问题。
也说明这似乎不是 Squirrel 的问题诶
