### ISSUE TITLE
修改yaml后部分App(VSCode )无法输入中文? 

### ISSUE THREAD

**Issue by nutnutwin** [rime/squirrel#395]
大家好, 我在macOS 下最近安装了Squirrel后

	在明月拼音｢˜/Library/Rimeluna_pinyin.schema.yaml｣中进行了以下修改(Block掉Shift切换中英文)
	```
	  processors:
	    #- ascii_composer
	```
- 现象
	大多数App 下都可按照预想动作(保持在中文模式), VSCode 下一直是英文输入

- 补充
	Windows 下进行如此修改没有发现问题
	macOS 下, VSCode 以外用了几种浏览器(Chrome, Firefox, Safari, Brave), 编辑器(Sublime etc) 都没有这个问题

# 请问
	上述修改正确吗? 是否有其他正规的修改方法, 比如将Shift换成其他按键

求指教, 谢谢

**Comment by lotem** [comment]
設置切換鍵，參考
https://github.com/rime/home/wiki/CustomizationGuide#%E4%BD%BF%E7%94%A8control%E9%8D%B5%E5%88%87%E6%8F%9B%E4%B8%AD%E8%A5%BF%E6%96%87
默認配置 https://github.com/rime/rime-prelude/blob/master/default.yaml#L60

控制 VS Code 中的輸入法默認狀態，參考
https://github.com/rime/home/wiki/CustomizationGuide#%E5%9C%A8%E7%89%B9%E5%AE%9A%E7%A8%8B%E5%BA%8F%E8%A3%8F%E9%97%9C%E9%96%89%E4%B8%AD%E6%96%87%E8%BC%B8%E5%85%A5

**Comment by nutnutwin** [comment]
谢谢, 我试试看

**Comment by nutnutwin** [comment]
昨天测试过可以了, 谢谢!
