### ISSUE TITLE
当我使用 candidate_format 设定候选词高亮的时候有一个 bug。

### ISSUE THREAD

**Issue by DbArl** [rime/squirrel#397]
如果我有多个候选词的时候候选词后的空间明显异常，这在我设定候选词后的空间为 0 时最明显。candidate_format: "\u2005%c\u2004%@" 
<img width="100" alt="image" src="https://user-images.githubusercontent.com/29571915/74928264-22e91080-5414-11ea-8b58-b8a44a48eb3e.png">
<img width="63" alt="image" src="https://user-images.githubusercontent.com/29571915/74928278-2a101e80-5414-11ea-8889-88cdb623213e.png">
可以看到候选词“样”后面的空间比“一”后面的多 1/6 空格左右。

**Comment by LEOYoon-Tsaw** [comment]
<img width="99" alt="image" src="https://user-images.githubusercontent.com/4469383/91235292-42cef900-e703-11ea-88e9-c9feba211817.png">
Will be fixed in next release.

**Comment by DbArl** [comment]
> <img alt="image" width="99" src="https://user-images.githubusercontent.com/4469383/91235292-42cef900-e703-11ea-88e9-c9feba211817.png">
> 
> Will be fixed in next release.

另外希望能加入随系统切换暗色模式。可以自定义亮色和暗色两个外观。

**Comment by LEOYoon-Tsaw** [comment]
> > <img alt="image" width="99" src="https://user-images.githubusercontent.com/4469383/91235292-42cef900-e703-11ea-88e9-c9feba211817.png">
> > Will be fixed in next release.
> 
> 另外希望能加入随系统切换暗色模式。可以自定义亮色和暗色两个外观。

也在下次更新裏了.

**Comment by DbArl** [comment]
> > > <img alt="image" width="99" src="https://user-images.githubusercontent.com/4469383/91235292-42cef900-e703-11ea-88e9-c9feba211817.png">
> > > Will be fixed in next release.
> > 
> > 
> > 另外希望能加入随系统切换暗色模式。可以自定义亮色和暗色两个外观。
> 
> 也在下次更新裏了.

好的，谢谢。非常期待新版本。

**Comment by lotem** [comment]
> > > <img alt="image" width="99" src="https://user-images.githubusercontent.com/4469383/91235292-42cef900-e703-11ea-88e9-c9feba211817.png">
> > > Will be fixed in next release.
> > 
> > 
> > 另外希望能加入随系统切换暗色模式。可以自定义亮色和暗色两个外观。
> 
> 也在下次更新裏了.

我認爲不會
