### ISSUE TITLE
能实现手动造词吗？比如按特定键才学习新词组

### ISSUE THREAD

**Issue by f1ynng8** [rime/squirrel#399]
目前默认的自动学习新词组进入候选，第二次选中固定候选的方式，即使把词组的数量限制为2个或者3具，个人认为仍然存在一些问题，比如我下面这张图里，随着时间的增加，候选里面会出现很多莫名其妙的词组，如果有时候不小心打错编码，就会直接上屏，并且被学习进固定词组。

![WX20200301-093007](https://user-images.githubusercontent.com/1539218/75751178-d3360d80-5d60-11ea-942e-1cfb72009b9c.png)

个人非常喜欢极点五笔那种，必须按特定组合键手动造词。因为造词其实是个小频繁操作，当然如果说完全关闭造词，只能去改词库，这样又太麻烦了。还是按特定组合键手动造词比较合适。

**Comment by lotem** [comment]
能。
五筆86方案用`;`分隔，連續輸入單字碼、上屏即可手動造詞。
具體以輸入方案配置爲準。

**Comment by f1ynng8** [comment]
尝试了一下，确实能够实现。有同样问题的人可以参考。
https://github.com/f1ynng8/rime-wubi86-jidian
