### ISSUE TITLE
Feature Request of SquirrelPanel

### ISSUE THREAD

**Issue by ghost** [rime/squirrel#403]
As shown [here](https://github.com/rime/squirrel/blob/master/SquirrelPanel.m#L578), Squirrel supports a radius adjustment of the highlighted section downside (if in horizontal mode layout) of the panel by passing `style/hilited_corner_radius` in the config, but lacks a little bit of the same to bracing the upper.

May Squirrel be will of adding this feature in the new release?

Thanks o<(=////▽////=)>o.

![Screen Shot 2020-03-19 at 1 18 17 AM](https://user-images.githubusercontent.com/30183249/76992177-caab1d00-6985-11ea-8859-c158e38649f8.png)

**Comment by LEOYoon-Tsaw** [comment]
<img width="248" alt="image" src="https://user-images.githubusercontent.com/4469383/91234772-0222b000-e702-11ea-8c2c-976a2b2f6300.png">
It will come with the next release.
