### ISSUE TITLE
vscode保存新文件时不能切换到中文

### ISSUE THREAD

**Issue by Kurt-Shiwz** [rime/squirrel#408]
在vscode中新建文件并保存时会调用mac系统的对话框，在文件名这里不能切换到中文状态，只能是英文。
version:0.14.0
vscode:1.43.2
os:10.15.4

**Comment by alex-the-man** [comment]
Does it help with you open ~/Library/Rime/build/squirrel.yaml and change the part for vscode to:
```
  com.microsoft.VSCode:
    ascii_mode: false
```

**Comment by driventokill** [comment]
1. Config VSCode as non ascii mode.
![image](https://user-images.githubusercontent.com/360744/81645099-899e2900-945b-11ea-91e7-2e38460d4e0d.png)
2. Won't work. Can't input Chinese with squirrel while saving file.
![image](https://user-images.githubusercontent.com/360744/81645310-f285a100-945b-11ea-8eba-e262fe375eb9.png)

**Comment by Kurt-Shiwz** [comment]
> 1. Config VSCode as non ascii mode.
>    ![image](https://user-images.githubusercontent.com/360744/81645099-899e2900-945b-11ea-91e7-2e38460d4e0d.png)
> 2. Won't work. Can't input Chinese with squirrel while saving file.
>    ![image](https://user-images.githubusercontent.com/360744/81645310-f285a100-945b-11ea-8eba-e262fe375eb9.png)
> 
> vscode: 1.45.0
> squirrel: 0.14.0
> mac os: 10.15.4

你改完重新部署了吗？
改完ascii_mode后我的可以输入中文了。虽然用shift不能切换中英。

**Comment by driventokill** [comment]
> > 1. Config VSCode as non ascii mode.
> >    ![image](https://user-images.githubusercontent.com/360744/81645099-899e2900-945b-11ea-91e7-2e38460d4e0d.png)
> > 2. Won't work. Can't input Chinese with squirrel while saving file.
> >    ![image](https://user-images.githubusercontent.com/360744/81645310-f285a100-945b-11ea-8eba-e262fe375eb9.png)
> > 
> > vscode: 1.45.0
> > squirrel: 0.14.0
> > mac os: 10.15.4
> 
> 你改完重新部署了吗？
> 改完ascii_mode后我的可以输入中文了。虽然用shift不能切换中英。

好了，我自己的锅

**Comment by lotem** [comment]
同 https://github.com/rime/squirrel/issues/85
