### ISSUE TITLE
您好现在显示中英文切换状态的小提示框默认是在光标的右下方 可以换到左上方吗 这样可以不遮挡视线

### ISSUE THREAD

**Issue by ninevcat** [rime/squirrel#409]
如题 可以考虑在scheme里面新增属性吗

**Comment by lotem** [comment]
有趣的想法。
不過現在顯示狀態的位置就是候選框的位置，他實質上就是只放了一個字的候選框。而候選框在一般情況下錨在光標所在文字行的基線以下，這個位置通常是空白的、是相對不會遮擋視線的位置。
不知你所提出的、右下方比左上方更為遮擋視線，具體是什麼情況？

**Comment by ninevcat** [comment]
> 有趣的想法。
> 不過現在顯示狀態的位置就是候選框的位置，他實質上就是只放了一個字的候選框。而候選框在一般情況下錨在光標所在文字行的基線以下，這個位置通常是空白的、是相對不會遮擋視線的位置。
> 不知你所提出的、右下方比左上方更為遮擋視線，具體是什麼情況？

因为阅读习惯是从左到右,从上到下的原因嘛, 虽然实际使用是相对不会遮挡视线的位置, 但是视觉上会有点别扭, 会造成极短暂的阅读障碍.
如果在切换状态后迅速下移光标时可能会遮挡视线, 虽然可能是少数的使用场景,但是如果能考虑到这点的话会非常感谢🙏🏻

**Comment by lotem** [comment]
我仍不明白。
閱讀順序是從左到右、從上到下，則右下角正是遠離上文文字的位置。
絕對不遮擋是無法做到的，光標周圍的任何位置都可能出現文字。只能選擇其中造成干擾機率最小的。如果爲了一個極少數的場景做修改，結果會是更多地感受到不便。
這是我目前對這個問題的理解。您如果發現了可以繼續改進的地方，不妨運用技術力嘗試做出來，實際看效果如何。

**Comment by ninevcat** [comment]
> 我仍不明白。
> 閱讀順序是從左到右、從上到下，則右下角正是遠離上文文字的位置。
> 絕對不遮擋是無法做到的，光標周圍的任何位置都可能出現文字。只能選擇其中造成干擾機率最小的。如果爲了一個極少數的場景做修改，結果會是更多地感受到不便。
> 這是我目前對這個問題的理解。您如果發現了可以繼續改進的地方，不妨運用技術力嘗試做出來，實際看效果如何。

emm, 那考虑减少遮挡块的停留时间呢

**Comment by lotem** [comment]
調節提示框的停留時間值得嘗試。

**Comment by ninevcat** [comment]
> 調節提示框的停留時間值得嘗試。
非常感谢

**Comment by ninevcat** [comment]
> 調節提示框的停留時間值得嘗試。

非常感谢
