### ISSUE TITLE
输入无法切换，无故出现CPU风扇狂转的现象

### ISSUE THREAD

**Issue by dansion** [rime/squirrel#411]
mac 10.15.3 ，MacBook Pro (15-inch, 2018)。
该现象一天好几次出现，无法愉快的使用了～～～

**Comment by StayTherapy** [comment]
@dansion  目前 macOS 已经更新到 `10.15.7 `， Squirrel 也更新到了 `0.14.0 `，风扇狂转的显现还存在吗？
