### ISSUE TITLE
鼠须管中「撤销上次输入」的疑问

### ISSUE THREAD

**Issue by hlwojiv** [rime/squirrel#416]
我在小狼豪的 issues 中知晓「本品未实现该功能。」，也就是说不支持「撤销上次输入字符」的功能。

但我有个疑问就是，我在鼠须管的实践中，是可以重复上次输入的字符；从此处看，能否实现「获取上次输入字符的长度，然后进行 delete 」的动作操作？

**Comment by lotem** [comment]
不支持刪除輸入法緩衝區之外的文字。
