### ISSUE TITLE
是否可以配置不显示候选框

### ISSUE THREAD

**Issue by JoneWang** [rime/squirrel#418]
例如：
在 switches 中可设置 hide_candidate 来确定方案是否显示候选框。

在使用形码输入的使用，大多都无需选字，所以希望能提供此选项。

**Comment by lotem** [comment]
对需求也不太了解。我所知且已经依托Rime实现的形码输入法都有一定量的重码，现实中尚未支持不需要选字的输入方案。

**Comment by JoneWang** [comment]
> 对需求也不太了解。我所知且已经依托Rime实现的形码输入法都有一定量的重码，现实中尚未支持不需要选字的输入方案。

确实是都会有重码，所以我想到的方案并不是不需要选字，而只是隐藏候选框，对于数字键选字依然有效。
例如我在使用的小鹤音形，数字选字是在固定位置，在熟悉到一定程度后，已经可以通过肌肉记忆无需查看候选框选字。

**Comment by lotem** [comment]
這種輸入方式要求用家背誦所有漢字的編碼和重碼順序。本品不支持這種用法。

**Comment by JoneWang** [comment]
并没有要求用户背诵，而是我就是用户，当已经不需要看候选框时，我想隐藏掉，主要是强迫症想让显示的尽量干净。
只是作为我个人想定制输入法的可选配置项而已。

**Comment by lotem** [comment]
可以把這種輸入法當作個人專用的工具。竊以爲沒有普遍應用的價值。

**Comment by JoneWang** [comment]
> 可以把這種輸入法當作個人專用的工具。竊以爲沒有普遍應用的價值。

嗯嗯，我 fork 一份试着修改看看。
打扰了，无需回复。

**Comment by JoneWang** [comment]
已在 [此克隆仓库](https://github.com/JoneWang/squirrel) 实现此功能。
