### ISSUE TITLE
无法通过命令自动同步字典配置

### ISSUE THREAD

**Issue by all4fun** [rime/squirrel#421]
windows 下可以通过 "C:\Program Files\Rime\weasel-0.14.0\WeaselDeployer.exe" /sync
命令来执行词典同步，而Mac OSX 系统中
/Library/Input Methods/Squirrel.app/Contents/MacOS/rime_deployer 
貌似并不支持这样的参数？

**Comment by LEOYoon-Tsaw** [comment]
寫bash腳本唄

**Comment by all4fun** [comment]
> 寫bash腳本唄

就是写脚本没找到支持的命令~

**Comment by lotem** [comment]
> > > 寫bash腳本唄
> > 
> > 
> > 就是写脚本没找到支持的命令~
> 
> rime_dict_manager -s 可以，但是会报一个LOCK文件的IO错误，需要先把LOCK文件更名。不过，bash脚本我不会写，大佬可以试一下

​不要這樣做。
輸入法進程鎖住了打開的詞典文件，不支持併發訪問。
可以調用 .../`Squirrel --quit; rime_dict_mananger -s` 輸入法退出時短暫讓出詞典文件，在按鍵重新調起輸入法之前立即執行同步。

**Comment by all4fun** [comment]
感谢回复。
完整命令可参考：

`cd /Library/Input\ Methods/Squirrel.app/Contents/MacOS && ./Squirrel --quit; ./rime_dict_manager -s && cd -`

**Comment by nsdont** [comment]
我刚测试了下，我这边需要这么执行

```bash
#!/bin/bash
#
# put this script in ~/Library/Rime

cd ~/Library/Rime
DYLD_LIBRARY_PATH="/Library/Input Methods/Squirrel.app/Contents/Frameworks" "/Library/Input Methods/Squirrel.app/Contents/MacOS/Squirrel" --quit
DYLD_LIBRARY_PATH="/Library/Input Methods/Squirrel.app/Contents/Frameworks" "/Library/Input Methods/Squirrel.app/Contents/MacOS/rime_dict_manager" -s
```

**Comment by Babesun** [comment]
> ```shell
> DYLD_LIBRARY_PATH
> ```

亲测成功！

如果不加DYLD_LIBRARY_PATH，执行rime_dict_manager -s命令会显示
sync dir: sync
user id: unknown

能否解释一下DYLD_LIBRARY_PATH的原理？谢谢

**Comment by Babesun** [comment]
> 我刚测试了下，我这边需要这么执行(需要在 ~/Library/Rime 下，才能执行成功)
> 
> ```shell
> #!/bin/bash
> #
> # put this script in ~/Library/Rime
> 
> cd ~/Library/Rime
> DYLD_LIBRARY_PATH="/Library/Input Methods/Squirrel.app/Contents/Frameworks" "/Library/Input Methods/Squirrel.app/Contents/MacOS/Squirrel" --quit
> DYLD_LIBRARY_PATH="/Library/Input Methods/Squirrel.app/Contents/Frameworks" "/Library/Input Methods/Squirrel.app/Contents/MacOS/rime_dict_manager" -s
> ```

亲测成功！

如果不加DYLD_LIBRARY_PATH，执行rime_dict_manager -s命令会显示
sync dir: sync
user id: unknown

能否解释一下DYLD_LIBRARY_PATH的原理？谢谢

**Comment by pencilheart** [comment]
实现每隔5h同步一次，且正在输入时不打断输入
1. 终端`crontab -e`进入vim编辑
2. 添加`0 */5 * * * if [ -n "$(pgrep 'Squirrel')" ]; then cpu_usage=$(ps -p $(pgrep 'Squirrel') -o %cpu=); if [ "$(echo "$cpu_usage == 0" | bc -l)" -eq 1 ]; then cd ~/Library/Rime && DYLD_LIBRARY_PATH="/Library/Input Methods/Squirrel.app/Contents/Frameworks" "/Library/Input Methods/Squirrel.app/Contents/MacOS/Squirrel" --quit && DYLD_LIBRARY_PATH="/Library/Input Methods/Squirrel.app/Contents/Frameworks" "/Library/Input Methods/Squirrel.app/Contents/MacOS/rime_dict_manager" -s; fi; fi`
3. `!wq`保存

**Comment by leviyanx** [comment]
> 实现每隔5h同步一次，且正在输入时不打断输入
> 
> 1. 终端`crontab -e`进入vim编辑
> 2. 添加`0 */5 * * * if [ -n "$(pgrep 'Squirrel')" ]; then cpu_usage=$(ps -p $(pgrep 'Squirrel') -o %cpu=); if [ "$(echo "$cpu_usage == 0" | bc -l)" -eq 1 ]; then cd ~/Library/Rime && DYLD_LIBRARY_PATH="/Library/Input Methods/Squirrel.app/Contents/Frameworks" "/Library/Input Methods/Squirrel.app/Contents/MacOS/Squirrel" --quit && DYLD_LIBRARY_PATH="/Library/Input Methods/Squirrel.app/Contents/Frameworks" "/Library/Input Methods/Squirrel.app/Contents/MacOS/rime_dict_manager" -s; fi; fi`
> 3. `!wq`保存

将“cpu占用率为0”作为没在输入的判定条件可能有点极端，我观察过，不使用的时候cpu占用率也会有点波动（比如0.2），但一般不会超过0.5，所以判定条件可以设置为`$cpu_usage <= 0.5`。

第二步改成这样：`0 */5 * * * if [ -n "$(pgrep 'Squirrel')" ]; then cpu_usage=$(ps -p $(pgrep 'Squirrel') -o %cpu=); if [ "$(echo "$cpu_usage <= 0.5" | bc -l)" -eq 1 ]; then cd ~/Library/Rime && DYLD_LIBRARY_PATH="/Library/Input Methods/Squirrel.app/Contents/Frameworks" "/Library/Input Methods/Squirrel.app/Contents/MacOS/Squirrel" --quit && DYLD_LIBRARY_PATH="/Library/Input Methods/Squirrel.app/Contents/Frameworks" "/Library/Input Methods/Squirrel.app/Contents/MacOS/rime_dict_manager" -s; fi; fi`
