### ISSUE TITLE
竖排模式键入内容时，候选框遮掩正在输入的文字

### ISSUE THREAD

**Issue by huangziwei** [rime/squirrel#422]
部分文本编辑器支持竖排模式，如 Pages、egword 等。但在竖排模式键入内容时，鼠须管的候选框会遮掩正在输入的文字，无论是候选框 horizontal 的参数是设置成 true 还是 false:

<img width="287" alt="Screenshot 2020-06-05 at 10 55 52" src="https://user-images.githubusercontent.com/3627182/83857627-8e34c500-a71b-11ea-8294-8cc84f88ef75.png">

<img width="448" alt="Screenshot 2020-06-05 at 10 56 59" src="https://user-images.githubusercontent.com/3627182/83857640-9260e280-a71b-11ea-8c10-9d55a5bfad0f.png">

而默认输入法在竖排模式时会自动旋转候选框的方向：

<img width="348" alt="Screenshot 2020-06-05 at 10 55 08" src="https://user-images.githubusercontent.com/3627182/83857737-b290a180-a71b-11ea-9907-ea2bf3fb31b8.png">

**Comment by LEOYoon-Tsaw** [comment]
<img width="151" alt="image" src="https://user-images.githubusercontent.com/4469383/91047218-b24fc600-e5e7-11ea-9ef9-1122f43ef1e6.png">
即將支持豎排模式，但不會隨輸入框的橫豎自動切換，需在鼠鬚管中統一設置。

**Comment by huangziwei** [comment]
Looking forward to the next release!

**Comment by Edenharder** [comment]
> <img alt="image" width="151" src="https://user-images.githubusercontent.com/4469383/91047218-b24fc600-e5e7-11ea-9ef9-1122f43ef1e6.png">
> 即將支持豎排模式，但不會隨輸入框的橫豎自動切換，需在鼠鬚管中統一設置。

请问能否给出一个将选项设置成竖排的简单例子呢？下面我的设置不生效：
```
patch:
 style/horizontal: false                    
 style/color_scheme: native
 style/vertical: true
 text_orientation: vertical 
```

**Comment by LEOYoon-Tsaw** [comment]
參考程序自帶的squirrel.yaml
