### ISSUE TITLE
請教一下按鍵綁定的問題

### ISSUE THREAD

**Issue by yyy33** [rime/squirrel#423]
![1591784949023_sticker](https://user-images.githubusercontent.com/51548147/84296291-6a8bd780-ab7e-11ea-8fa1-638b23808efa.png)

我想將圖中的`ctrl-f`設置爲同時發送`return`和`ctrl-f`,請問應該怎麼寫啊

**Comment by lotem** [comment]
發送 `Return` 會執行回車鍵的動作；發送 `Control+f` 是沒有任何作用的。

**Comment by yyy33** [comment]
> 發送 `Return` 會執行回車鍵的動作；發送 `Control+f` 是沒有任何作用的。

恩，我是想執行回車的動作後再將`Contorl-f`發送給另外一個軟件，比如`vim`。能教下我怎麼做嗎

**Comment by lotem** [comment]
本品不支持發送模擬按鍵。
按鍵綁定的作用是讓輸入法的內部邏輯將`accept:`匹配到的按鍵視爲`send:`所指定的按鍵處理。

**Comment by yyy33** [comment]
> 本品不支持發送模擬按鍵。
> 按鍵綁定的作用是讓輸入法的內部邏輯將`accept:`匹配到的按鍵視爲`send:`所指定的按鍵處理。

好吧，謝謝回復
