### ISSUE TITLE
使用 rime 输入法不能打出 濛 这个字

### ISSUE THREAD

**Issue by chenzhenjia** [rime/squirrel#425]
我刚开始以为是配置问题，我用了 [rime-settings](https://github.com/wongdean/rime-settings) [这个仓库的配置，我在这个仓库里面提了[issue](https://github.com/wongdean/rime-settings/issues/19) ，但是作者说是输入法的问题。请问有办法解决吗

**Comment by lotem** [comment]
同 https://github.com/rime/home/issues/568
