### ISSUE TITLE
保存对话框不能数据中文

### ISSUE THREAD

**Issue by jasen2339** [rime/squirrel#427]
MacOSX 10.15.5，Chrome Version 83
保存文件对话框不能输入中文，切换系统自带输入法没有问题。
保存文件对话框中新建文件夹对话也是一样的问题。
![Screen Shot 2020-06-30 at 20 52 21](https://user-images.githubusercontent.com/16912781/86128680-4899cb00-bb14-11ea-9f50-27602b0b1d3c.png)
![Screen Shot 2020-06-30 at 20 53 27](https://user-images.githubusercontent.com/16912781/86128698-4c2d5200-bb14-11ea-8577-296cbf4bc241.png)

**Comment by lotem** [comment]
同 https://github.com/rime/squirrel/issues/85 、 https://github.com/rime/squirrel/issues/408
