### ISSUE TITLE
0.9.26 mac qq 和其他一些 app 中，不能启用

### ISSUE THREAD

**Issue by zhuangya** [rime/squirrel#43]
尝试了：

官方网站下载的`v4.0.1`, `v3.1.2` ，app store 的 `v3.1.2`

都使用不了，切换输入法到时候变成这样：

![2014-12-22 11 05 35](https://cloud.githubusercontent.com/assets/499038/5520870/7c2ca388-89ca-11e4-9ef1-073d98052d39.png)

系统栏里面成这样：

![image](https://cloud.githubusercontent.com/assets/499038/5520872/9079e35a-89ca-11e4-93ba-60c7bdfd3238.png)

但是其他程序却都这样，是 rimeime 的事情还是 qq 的问题呢？

thanks

**Comment by dongshimou** [comment]
distribution_code_name: Squirrel
distribution_name: "鼠鬚管"
distribution_version: 0.14.0
rime_version: 1.5.3 

依然出现部分app不能使用...

**Comment by hhstore** [comment]
- 这个 bug 似乎还在呀? 
- 当前最新版本, Mac下微信窗口输入, 依然无法使用.
- 切到Chrome, 却是正常的. 

> 鼠须管版本: 

```ruby
鼠须管 0.15.2 是当前的最新版本。
```
