### ISSUE TITLE
修改下squirrel.custom.yaml字体就失去圆角

### ISSUE THREAD

**Issue by Jin6** [rime/squirrel#430]
Mojave下pkg安装的鼠须管，改动下squirrel.custom.yaml，设置字体就丢失圆角以及输入字母会下移到候选框是什么原因呢？
![Screenshot 2020-07-04 at 8 00 31 PM](https://user-images.githubusercontent.com/4217627/86512134-ed2c4d80-be31-11ea-9571-43018107642d.png)
^ 丢失圆角和输入字母位置变化
![Screenshot 2020-07-04 at 7 58 26 PM](https://user-images.githubusercontent.com/4217627/86512137-f1586b00-be31-11ea-9f08-c8f635e6b089.png)
^ 默认状态

**Comment by lotem** [comment]
預設配置文件定義了圓角半徑、邊框等樣式，圖示的配置沒有定義。請參考 https://github.com/rime/home/wiki/CustomizationGuide#%E5%AE%9A%E8%A3%BD%E6%8C%87%E5%8D%97
