### ISSUE TITLE
Chome 網址列與搜尋列，方向、退格等鍵未被完全截獲

### ISSUE THREAD

**Issue by syimyuzya** [rime/squirrel#435]
目前版本的 Chrome 和鼠鬚管（0.14.0），在搜尋列輸入過程中，嘗試按 ↑ ↓ 鍵挑候選詞時，頁面也會跟着滾動；網址列按 ↑ ↓ 甚至會打斷輸入並直接送上當前 preedit。

不排除與 #252 是同一問題的可能。

別的第三方輸入法（如 OpenVanilla）無此問題，因此應當是鼠鬚管的 bug。

**Comment by nb5p** [comment]
请问“搜尋列”指的是Cmd+F弹出的输入框吗？

**Comment by syimyuzya** [comment]
> 请问“搜尋列”指的是Cmd+F弹出的输入框吗？

是的，#252 提到的 Chrome 搜索欄也是這個

**Comment by lotem** [comment]
同 https://github.com/rime/squirrel/issues/252#issuecomment-495257337
Mac輸入法框架決定應用可以優先處理按鍵消息因此無法完全截獲輸入。
這個應該是Chrome的bug。不過本品已經做了對這個BUG的“兼容”：
https://github.com/rime/squirrel/issues/299
