### ISSUE TITLE
某些词语无法被记录

### ISSUE THREAD

**Issue by derekxia1988** [rime/squirrel#437]
当我输入fupan的时候每次我手动挑选了“复盘”，但是之后不管我输入多少次，都不会有“复盘”这个候选词，但是其他的一些词语就没问题，我随便输入的一些没有逻辑的自造词都能被记录，唯独这个词永远不被记录，请问这是为什么呢？
![image](https://user-images.githubusercontent.com/28382254/88470085-d9ed3900-cf2a-11ea-8c5a-d9858ce85a63.png)

**Comment by derekxia1988** [comment]
另外有一个问题，我使用明月简体，但是我无法使用/bq选择emoji表情，我感觉这个和输入法自动分词有关，但是找不到相关的设置，如图：
![image](https://user-images.githubusercontent.com/28382254/88470440-d360c080-cf2e-11ea-953a-3c51a560b22b.png)
我的b和q之间是分隔的，这个该怎么修改配置呢？我查了很多人的配置好像没人提到过有这种问题。。。

**Comment by lotem** [comment]
> 另外有一个问题，我使用明月简体，但是我无法使用/bq选择emoji表情，我感觉这个和输入法自动分词有关，但是找不到相关的设置，如图：
> ![image](https://user-images.githubusercontent.com/28382254/88470440-d360c080-cf2e-11ea-953a-3c51a560b22b.png)
> 我的b和q之间是分隔的，这个该怎么修改配置呢？我查了很多人的配置好像没人提到过有这种问题。。。

朙月拼音·簡化字方案沒有配置這項功能。您可以切換到朙月拼音方案，再切換「漢字→汉字」選項。

**Comment by lotem** [comment]
同 https://github.com/rime/librime/issues/251 、 https://github.com/rime/librime/issues/382

**Comment by derekxia1988** [comment]
感谢，已理解怎么解决了。
