### ISSUE TITLE
xcodeproj: update opencc to 1.1.1

### ISSUE THREAD

**Issue by l2dy** [rime/squirrel#439]
librime updated the opencc submodule in https://github.com/rime/librime/commit/44dd002809a2f90494a73cd7503843ba2a70cae4, which uses the new ocd2 format, but the Xcode project (Squirrel.xcodeproj) still references old filenames like `HKVariantsPhrases.ocd`.

**Comment by lotem** [comment]
working as intended: it should reference the old filenames, because the submodule librime is at an older commit than rime/librime@44dd002.
the project file will be updated in the same commit that updates librime. keep this issue open as a todo item.

**Comment by markwu** [comment]
Any updates of this? I compiled squirrel with the newest `librime`, it could not find `*.ocd` files when `make install`.

Can I copy them manually?

**Comment by l2dy** [comment]
Fixed in https://github.com/rime/squirrel/pull/469.
