### ISSUE TITLE
简拼和英文词典某些词语冲突

### ISSUE THREAD

**Issue by phyzhenli** [rime/squirrel#442]
我在luna_pinyin_simp.custom.yaml中定义了：

"speller/algebra/@before 0": xform/^([b-df-hj-np-tv-z])$/$1_/

但我的luna_pinyin.english.dict.yaml中的一些词语无法显示，比如“are”这个词，我输入are以后无法出现，其余的词语如ok、real、really、around都可以。

这是are的写法：
are        a  r  e

这是为什么呢？是我哪里设置有问题吗？

**Comment by LEOYoon-Tsaw** [comment]
xform/^([b-df-hj-np-tv-z])$/$1_/
後面這個"_"你要如何輸入？

**Comment by phyzhenli** [comment]
> xform/^([b-df-hj-np-tv-z])$/$1_/
> 後面這個"_"你要如何輸入？

您好我没明白您的意思，直接英文模式输入0后面那个字符不就可以了吗？

**Comment by lotem** [comment]
不支持這種用法。因為英文不是由拼音音節組成的。

**Comment by phyzhenli** [comment]
> 不支持這種用法。因為英文不是由拼音音節組成的。

那为什么有些英文单词是可以的呢？有没有什么办法可以解决这个问题呢？

**Comment by LEOYoon-Tsaw** [comment]
> > xform/^([b-df-hj-np-tv-z])$/$1_/
> > 後面這個"_"你要如何輸入？
> 
> 您好我没明白您的意思，直接英文模式输入0后面那个字符不就可以了吗？

那are就是__e

**Comment by phyzhenli** [comment]
> > > xform/^([b-df-hj-np-tv-z])$/$1_/
> > > 後面這個"_"你要如何輸入？
> > 
> > 
> > 您好我没明白您的意思，直接英文模式输入0后面那个字符不就可以了吗？
> 
> 那are就是__e

斯国一，不过我的_是直接commit的，算了不管了。

**Comment by pdog18** [comment]
> > > xform/^([b-df-hj-np-tv-z])$/$1_/
> > > 後面這個"_"你要如何輸入？
> > 
> > 
> > 您好我没明白您的意思，直接英文模式输入0后面那个字符不就可以了吗？
> 
> 那are就是__e

哥, 如果方便的话, 能不能解释一下, 这里你们说的是什么意思啊?
