### ISSUE TITLE
鼠鬚管：Desktop版Chrome在FB新界面下輸入問題

### ISSUE THREAD

**Issue by hammertkh** [rime/squirrel#444]
更新：帖子欄似乎亦有問題

再測試了一次 發現連帖子欄都有輸入問題了
和訊息欄問題相似
1. 中文模式（有選字欄）模式下，無論選字抑或是直接拼音上屏皆會失敗
2. 先在前面輸入一些內容的話，若爲首行，選字後會導致整行文字消失；若非首行，選字後則會跳回首行。

同樣附上錄影作參考
[FB訊息欄輸入.mov.zip](https://github.com/rime/squirrel/files/5139541/FB.mov.zip)

---

Facebook最近強制用戶更新至新界面
新界面下，我用Chrome在帖子欄可以正常輸入
但在訊息欄輸入時，雖然可以彈出選字窗，在選取後卻會輸入失敗，文字消失。
右下訊息欄與全頁訊息界面（https://www.facebook.com/messages/）皆有這個問題

附上熒幕錄影一小段
[螢幕錄製.zip](https://github.com/rime/home/files/5135833/default.zip)

**Comment by hammertkh** [comment]
再測試了一次 發現連帖子欄都有輸入問題了
和訊息欄問題相似
1. 中文模式（有選字欄）模式下，無論選字抑或是直接拼音上屏皆會失敗
2. 先在前面輸入一些內容的話，若爲首行，會導致整行文字消失；若非首行，則會跳回首行。

同樣附上錄影作參考
[FB訊息欄輸入.mov.zip](https://github.com/rime/squirrel/files/5139541/FB.mov.zip)

**Comment by hammertkh** [comment]
感覺起來跟以前在FB上使用Chrome的Google輸入法的問題有點相似？

那時候輸入時backspace一下就會導致刪除一大段文字，還有常常輸入失敗

**Comment by brownsugar** [comment]
我 Chrome 84 測試正常，可能是被 Rime 設定檔或 Chrome 擴充功能影響？

![output](https://user-images.githubusercontent.com/2935980/92091422-51a06480-ee03-11ea-8aff-174c9d0eb387.gif)

**Comment by nb5p** [comment]
@brownsugar 能分享一下你方案的speller/delimiter所使用的符号吗？我曾尝试使用“┊<U+250A>”做分隔符，但他会导致异常行为。

**Comment by brownsugar** [comment]
> @brownsugar 能分享一下你方案的speller/delimiter所使用的符号吗？我曾尝试使用“┊<U+250A>”做分隔符，但他会导致异常行为。

使用方案：https://github.com/oniondelta/Onion_Rime_Files
