### ISSUE TITLE
使用方案选单时switcher/caption被输入到chrome地址栏

### ISSUE THREAD

**Issue by yousong** [rime/squirrel#450]
- squirrel 0.14.0
- chrome "Version 83.0.4103.97 (Official Build) (64-bit)"

在chrome地址栏，使用Ctrl-`调出方案选单

1. 只要使用上下方向键移动高亮的项目，switcher/caption 〔方案選單〕就会被输入到地址栏，之后需要手工删除
2. 如果将`switcher/caption`在default.custom.yaml文件中置为空串，caption会变成`:-)`，因此也没有办法将caption置为空串

另外一个现象在chrome地址栏和正文的`<input type="text">`里有，在`<textarea>`、MacVim、Notes里没有出现出现。如果使用Enter键选定一个项目，Enter还会触发应用原本在这个位置的动作，比如访问地址，搜索关键字等。使用Space选定一个项目就没有这个问题，不知是否符合预期

**Comment by yousong** [comment]
> * 只要使用上下方向键移动高亮的项目，switcher/caption 〔方案選單〕就会被输入到地址栏，之后需要手工删除

更具体的，只要上下方向键按下之后，光标有左右移动（选单位置此时也会随之移动），caption就会上屏

**Comment by yousong** [comment]
> > * 只要使用上下方向键移动高亮的项目，switcher/caption 〔方案選單〕就会被输入到地址栏，之后需要手工删除
> 
> 更具体的，只要上下方向键按下之后，光标有左右移动（选单位置此时也会随之移动），caption就会上屏

地址栏会有下拉提示，上下键除了会改变输入选单的高亮项，也会改变地址栏下拉提示中的高亮项，这大概是光标在地址栏左右移动的原因

**Comment by lotem** [comment]
同 https://github.com/rime/squirrel/issues/252

**Comment by xiaolongGitHub1498** [comment]
希望增加在切换输入法时可以不显示switcher/caption的设置 目前切换输入法时设置的值就会上屏 很影响体验
