### ISSUE TITLE
 Shift_R: 设置为noop 还是能切换中英文

### ISSUE THREAD

**Issue by rockkoca** [rime/squirrel#451]
ascii_composer: # 设置caps、shift、control等键的作用
    good_old_caps_lock: true # 若为true，caps只切换大小写
    switch_key:
      Shift_L: commit_code
      Shift_R: noop

**Comment by rockkoca** [comment]
原来是os的问题 但是搜狗输入法是能区分左右的

**Comment by lotem** [comment]
同 https://github.com/rime/squirrel/issues/35
