### ISSUE TITLE
【鼠须管】 中英切换【指示器皮肤】问题

### ISSUE THREAD

**Issue by sef7uba** [rime/squirrel#452]
back_color: 0x000000    候选条黑色背景
hilited_candidate_text_color: 0x120A00   第一候选项文字黑色

当背景条颜色和第一候选项文字颜色为黑色的话，
中英切换指示器的背景色和文字颜色都是黑色的，会导致看不清楚是【中】还是【A】
问：有没有设置中英切换指示器颜色的参数？
或者在不改变候选条颜色和第一候选项文字颜色的情况下，有没有其它什么解决方法？

**Comment by lotem** [comment]
此處的文字顏色是 `comment_text_color`

**Comment by sef7uba** [comment]
> 此處的文字顏色是 `comment_text_color`

comment_text_color: 0x120A00  

我试了一下，这个可以控制中英切换指示器文字的颜色
这个问题解决了,谢谢您

**Comment by sef7uba** [comment]
有没有控制中英切换指示器背景颜色的参数呢？
