### ISSUE TITLE
求助，Squirrel 設置alternative_select_labels無效

### ISSUE THREAD

**Issue by castting** [rime/squirrel#453]
我希望候選標籤按照我設定的序列顯示，但設定menu/alternative_select_labels後沒有生效，特來請教應該如何設定，感激不盡！
[img.pdf](https://github.com/rime/squirrel/files/5397283/img.pdf)

**Comment by LEOYoon-Tsaw** [comment]
期待新版吧。下一版就有了

**Comment by StayTherapy** [comment]
+1, 还以为是自己配置的问题
期待中......

**Comment by lotem** [comment]
已經做了。
嚐鮮可以裝測試版： https://bintray.com/rime/squirrel/testing

**Comment by StayTherapy** [comment]
> 已經做了。
> 嚐鮮可以裝測試版： https://bintray.com/rime/squirrel/testing

实测`alternative_select_labels `已经生效了😄️

如果之前使用 `brew` 安装的 `Squirrel`，测试版也想用 brew 统一管理的话，可以 tap 下面的资源。
>引用了 Squirrel-0.14.0+git118aee6 测试版。

```bash
# 建议删除原版，避免冲突
brew cask uninstall squirrel
brew tap StayTherapy/cask
brew cask install StayTherapy/cask/squirrel-beta
```
**注意**，uninstall release 版实测会保留`/Users/{User}/Library/Rime`的用户配置文件 , 不放心的话可以备份一份。
