### ISSUE TITLE
新建 Schema 是否都需要新建一套字典?

### ISSUE THREAD

**Issue by StayTherapy** [rime/squirrel#455]
标准开场: 各位大佬好

很久没有折腾 鼠须管 了，用了很久系统自带，加上最近有空，想了一下还是决定用可以高度定制化的 鼠须管，别的不说，自定义符号输入是真的好用。

这次我想从头配置一套全新的 Schema, 跟着 [RimeWithSchemata](https://github.com/rime/home/wiki/RimeWithSchemata) 配了一遍，发现除了 dict 里自定义的词，拼音输入就不能输入其他的任何中文了。把 WiKi 翻了一遍没找到答案，直接复制其他 Schema 的话能解决问题，但是原理还是不太理解。

**所以我不确定的是，新建一套 Schema 是不是要新建一套码表，里面要包含所有中文字符和拼音码？**

这样的话，字典中的配置值 `use_preset_vocabulary: true` **并不是**表示当前字典中没有的对应的 [ 字 (tab) 拼音 ]，会从现有词典中导入？而是其他意思。

`script_translator` 是否跟 `table_translator` 类似，都是从码表 [ 字 (tab) 拼音|输入码 ] 中找到对应，然后获取对应的字形？

**Comment by lotem** [comment]
答标题：不是。

本品不是拼音输入法，不懂字的拼音。
拼音是一种汉字编码。汉字的输入码由`*.dict.yaml`文件定义，即词典或称码表。

输入方案通过配置定义一种输入方法。通常会用到词典，但不是必须的，二者也不是一对一的关系。
在输入方案中，通过`translator/dictionary`配置项为`script_translator`或`table_translator`指定其所需的词典文件。（[示例](https://github.com/rime/rime-double-pinyin/blob/master/double_pinyin.schema.yaml#L87)）

`use_preset_vocabulary: true`指示词典使用预设词汇表。对于其中所设词组，根据码表中的单字编码生成词组编码，并记入词典。

**Comment by StayTherapy** [comment]
> 本品不是拼音输入法，不懂字的拼音。

一句话点破，所以还是应该把 `Squirrel` 理解为一个输入引擎。用惯其他输入法误以为其内置标准拼音字典。所以之前纠结的新建 `方案`，再关联自定义的 `字典` 就是重复造轮子了，应该引用现有的 `字典` 。

`use_preset_vocabulary` 原来是一个**词汇表**， 跟 **字典** 是两个概念。

谢过大佬。
