### ISSUE TITLE
密码输入框无自动切换ABC

### ISSUE THREAD

**Issue by sef7uba** [rime/squirrel#457]
![image](https://user-images.githubusercontent.com/31071649/97536283-da004780-19f7-11eb-8b82-12831b55331d.png)

![image](https://user-images.githubusercontent.com/31071649/97536136-ac1b0300-19f7-11eb-9e71-2d7f0fe59a41.png)
![image](https://user-images.githubusercontent.com/31071649/97536468-264b8780-19f8-11eb-8b21-8382f956169a.png)

系统只开启鼠须管输入法
在密码框输入的时候在中文状态下不会自动切换到英文模式
有没有自动切换的方法呢？

**Comment by sef7uba** [comment]
key_binder/bindings: 
    - {accept: "Control+Shift+2", toggle: ascii_mode, when: always}

**Comment by abestwyc** [comment]
您好, 请教一个题外话

很喜欢您的鼠须管界面, 能否分享一下配置? 感谢!
