### ISSUE TITLE
Big Sur 安装遇到问题，版本11.0.1 。boost 按照安装文档自行下载源码安装的。

### ISSUE THREAD

**Issue by LuciusChen** [rime/squirrel#462]
bash package/add_data_files
found bopomofo.schema.yaml
found bopomofo_express.schema.yaml
found bopomofo_tw.schema.yaml
found cangjie5.dict.yaml
found cangjie5.schema.yaml
found cangjie5_express.schema.yaml
found default.yaml
found essay.txt
found key_bindings.yaml
found luna_pinyin.dict.yaml
found luna_pinyin.schema.yaml
found luna_pinyin_fluency.schema.yaml
found luna_pinyin_simp.schema.yaml
found luna_pinyin_tw.schema.yaml
found luna_quanpin.schema.yaml
found punctuation.yaml
found stroke.dict.yaml
found stroke.schema.yaml
found symbols.yaml
found terra_pinyin.dict.yaml
found terra_pinyin.schema.yaml
xcodebuild -project Squirrel.xcodeproj -configuration Release build | grep -v setenv | tee build.log
** BUILD FAILED **

Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project Squirrel.xcodeproj -configuration Release build

note: Using new build system
note: Planning build
note: Using build description from disk
warning: ONLY_ACTIVE_ARCH=YES requested with multiple ARCHS and no run destination to provide an active architecture; building for all applicable architectures (in target 'Squirrel' from project 'Squirrel')
warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.7, but the range of supported deployment target versions is 10.9 to 11.0.99. (in target 'Squirrel' from project 'Squirrel')
warning: Traditional headermap style is no longer supported; please migrate to using separate headermaps and set 'ALWAYS_SEARCH_USER_PATHS' to NO. (in target 'Squirrel' from project 'Squirrel')
error: The linked and embedded framework 'Sparkle.framework' is missing one or more architectures required by this target: arm64. (in target 'Squirrel' from project 'Squirrel')

**Comment by LEOYoon-Tsaw** [comment]
'MACOSX_DEPLOYMENT_TARGET' is set to 10.7, but the range of supported deployment target versions is 10.9 to 11.0.99. (in target 'Squirrel' from project 'Squirrel')
這不是寫得很明確了

**Comment by LuciusChen** [comment]
我不懂这个需要做哪些操作，麻烦您了。

**Comment by lotem** [comment]
> 'MACOSX_DEPLOYMENT_TARGET' is set to 10.7, but the range of supported deployment target versions is 10.9 to 11.0.99. (in target 'Squirrel' from project 'Squirrel')
> 這不是寫得很明確了

那个不是错误。

从最后一句看，是 arm64 的处理器？
目前的构建目标是[Intel Mac](https://zh.wikipedia.org/wiki/Mac%E5%90%91%E8%8B%B1%E7%89%B9%E5%B0%94%E5%B9%B3%E5%8F%B0%E8%BF%81%E7%A7%BB)，不支持Inter Mac之前的PowerPC处理器的机型。
这个工程里的代码应该也能编译到ARM，麻烦的是使用的第三方库是只支持x64架构的。

**Comment by LuciusChen** [comment]
电脑是 2017 的15寸 Pro 版本（3.1 GHz Quad-Core Intel Core i7），以前就有使用 Squirrel，只是升级到 Big Sur 重装了系统后再次安装时遇到了这个问题。

**Comment by lotem** [comment]
那可能是构建工具默认的目标平台变了。
https://rime.im/download/ 有编译好的。先用着呗。

**Comment by egolearner** [comment]
@LuciusChen 可以patch上这个diff文件
https://gist.github.com/egolearner/2501b68520362d4ddc3c9b0db597736b

**Comment by LuciusChen** [comment]
> @LuciusChen 可以patch上这个diff文件
> https://gist.github.com/egolearner/2501b68520362d4ddc3c9b0db597736b

👍

**Comment by lotem** [comment]
Fixed by https://github.com/rime/squirrel/pull/468
