### ISSUE TITLE
Will Squirrel support M1 Mac in the future?

### ISSUE THREAD

**Issue by bingsmocha** [rime/squirrel#464]
Dear lotem,

As the M1 chips Mac released in the Nov.11, the series of Mac products is going to change from X86 to ARM, so I wonder that will the Squirrel support M1 Mac natively in the future.

**Comment by LEOYoon-Tsaw** [comment]
Depends on dependencies I guess

**Comment by lotem** [comment]
The Sparkle updater framework has already supported Apple Silicon
https://github.com/sparkle-project/Sparkle/releases/tag/1.24.0

**Comment by bingsmocha** [comment]
> The Sparkle updater framework has already supported Apple Silicon
> https://github.com/sparkle-project/Sparkle/releases/tag/1.24.0

Sorry, I don't know much about technology. 

So I have two  more questions:
1. Does Squirrel just rely on the Sparkle updater framework?
2. After Sparkle updater framework support Apple Silicon, will Squirrel support Apple Silicon in foreseeable future?

Thanks for your time!

**Comment by lotem** [comment]
There's also librime and its dependencies.

Travis CI has support for building universal apps:
https://changelog.travis-ci.com/xcode-12-beta-2-and-xcode-12-for-macos-universal-apps-159012

**Comment by lzto** [comment]
It would be great if squirrel got an update to support M1.

**Comment by LEOYoon-Tsaw** [comment]
> It would be great if squirrel got an update to support M1.

Of course it would be great, counting on you buddy

**Comment by lotem** [comment]
Yes, I guess, it'll be supported in the future.

**Comment by hronro** [comment]
I guess this is the issue for tracking native Apple Silicon support?

Why not keep the issue open since the Apple Silicon support is not implemented yet?

**Comment by lotem** [comment]
Yes. It's already implemented.

**Comment by hronro** [comment]
@lotem Cool, but there is no pre-built binaries in GitHub Releases yet.

**Comment by LEOYoon-Tsaw** [comment]
> @lotem Cool, but there is no pre-built binaries in GitHub Releases yet.

What? 0.15+ are universal

**Comment by liul85** [comment]
I got this after installation, it shows the kind of Squirrel app is Apple 

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/1312723/168580263-6772b7b2-b475-4e80-9cc7-5a04a5ee78ee.png">

**Comment by openSourcerer9000** [comment]
Still no apple silicon support??
