### ISSUE TITLE
Trying to install ZhengMa IME for RIME Squirrel MacOS not working

### ISSUE THREAD

**Issue by zgw3kszo** [rime/squirrel#471]
I've been trying to install several different ZhengMa RIME IME's for my Mac because the one I currently have is somewhat clunky but I cannot figure out how to install it correctly so it works.

I've tried these so far but the files found in the Squirrel directory do not seem to match their tutorials:

https://github.com/vfreex/rime-zhengma

https://github.com/acevery/rime-zhengma

If someone could please assist me with how to get this working on MacOS RIME Squirrel I would really appreciate it.

**Comment by lotem** [comment]
Here's one more repo, basically a clone of acevery's work:
https://github.com/lotem/rime-zhengma

To customize, refer to these sections in the doc:

https://github.com/rime/home/wiki/CustomizationGuide#%E5%BF%85%E7%9F%A5%E5%BF%85%E6%9C%83

https://github.com/rime/home/wiki/CustomizationGuide#%E4%B8%80%E4%BE%8B%E5%AE%9A%E8%A3%BD%E6%96%B9%E6%A1%88%E9%81%B8%E5%96%AE

**Comment by zgw3kszo** [comment]
I've looked at the tutorials but my Squirrel RIME installation doesn't seem to have the correct files in it. For example, I have no default.yaml file in the installation for some reason. I've tried reinstalling it several different times and it just installs like this:

[https://i.imgur.com/01oQzlW.png](url)

I also have a bit of a hard time reading through some of the documentation because I'm not very fluent in Mandarin as of now.

**Comment by lotem** [comment]
Summarised steps from the doc:

1. Navigate to `~/Library/Rime/` via [Input method menu > Squirrel > Settings...], put all downloaded `*.yaml` files in this folder.
2. Create (or edit) a file named exactly `default.custom.yaml` in `~/Library/Rime/` with the following contents:
    ```yaml
    patch:
      schema_list:
        - schema: zhengma
    ```
    Replace `zhengma` with whatever appears after `schema_id:` in `*.schema.yaml`.

3. Select [Input method menu > Squirrel > Deploy].

**Comment by zgw3kszo** [comment]
That worked, thank you so much! I'm having some other troubles now with trying to do a custom theme. I made a theme using this editor https://gjrobert.github.io/Rime-See-Me-squirrel/ and pasted it into the default themes, how do you switch themes on Squirrel RIME?

**Comment by lotem** [comment]
That's how you patch the UI config:
https://github.com/rime/home/wiki/CustomizationGuide#%E9%BC%A0%E9%AC%9A%E7%AE%A1%E5%A4%96%E8%A7%80%E8%88%87%E9%8D%B5%E7%9B%A4%E8%A8%AD%E5%AE%9A

**Comment by zgw3kszo** [comment]
I don't have a squirrel.custom.yaml file inside of ~/Library/Rime/build/ or ~/Library/Rime/. Should I add it, if so where? And what should I type to get the custom theme working? I have the output from https://gjrobert.github.io/Rime-See-Me-squirrel/ pasted in squirrel.yaml under preset_color_schemes:, its name is MacOSDM. How should I fix it?

**Comment by lotem** [comment]
You do not have a lot to do without reading through the doc and knowing how YAML patches work.

Basically you are creating code like the existing themes
https://github.com/rime/squirrel/blob/master/data/squirrel.yaml#L42
and then need to change `color_scheme`
https://github.com/rime/squirrel/blob/master/data/squirrel.yaml#L18
to your `aqua` equivalent key.

**Comment by zgw3kszo** [comment]
That worked! Thanks for your help, all of my issues have been solved.
