### ISSUE TITLE
Base keyboard layout on macOS Big Sur

### ISSUE THREAD

**Issue by teddue** [rime/squirrel#472]
Is it possible to change the rime/squirrel base keyboard layout on macOS?
I'm using macOS in German and so the base layout is the German keyboard layout which breaks a lot of functions. 
For example when a rime schema or dict uses the ` key I cannot use it because that key is a dead key on the German layout.

**Comment by teddue** [comment]
So I found out by myself: 

Create a file named `squirrel.custom.yaml` in `~/Library/Rime` and add the lines
`patch:
  us_keyboard_layout: true`

This sets the base keyboard layout to US English and the ` key is available right next to left shift (</> key on German hardware layout)

**Comment by lotem** [comment]
Cool.
It's interesting to know whether a physical Gearman keyboard has all keys working after changing software layout to US English.

By the way, if missing <kbd>`</kbd> key is all the problem you have, you may reconfigure Rime to use a different [key binding](https://github.com/rime/rime-prelude/blob/master/default.yaml#L18) to show the menu. That might help save you from having to switch keyboard layout before selecting Rime. Of course in that case keys that are mapped to non-ASCII characters, like the amlaut vowels and dead keys, are still unsupported in Rime as the code assumes the input is an ASCII char sequence.
