### ISSUE TITLE
Telegram 中的搜索框内打字，每次只会显示一个字母

### ISSUE THREAD

**Issue by LuciusChen** [rime/squirrel#475]
![image](https://user-images.githubusercontent.com/4947981/104260811-291a2c80-54bf-11eb-921a-bc6893298a77.png)
这样没问题，全拼的话就会如下：
![image](https://user-images.githubusercontent.com/4947981/104260854-3a633900-54bf-11eb-9b31-d0c203691195.png)
另外在 Telegram 中的搜索框内打字，每次只会显示一个字母，比如如下截图我是输入的 da （打）字全拼，只剩下字母 a，而不是出现 da。
![image](https://user-images.githubusercontent.com/4947981/104261076-b65d8100-54bf-11eb-9437-993a61ae4682.png)

**Comment by LuciusChen** [comment]
![image](https://user-images.githubusercontent.com/4947981/104263761-2d494880-54c5-11eb-927c-0ba92fe55e41.png)

**Comment by LuciusChen** [comment]
没人解决这个问题么？

**Comment by lotem** [comment]
什麼問題？

**Comment by LuciusChen** [comment]
就是打字的时候，“jiayou"全拼的话，上屏只有一个空格。这种情况还存在于其他词汇。
另外就是在 Telegram 搜索框里面，完全无法输入中文。

**Comment by lotem** [comment]
重現不了只上屏空格的問題。可能是跟個別應用軟件不兼容。

**Comment by LuciusChen** [comment]
那 Telegram 里面搜索框无法输入的问题呢，也没办法复现么

**Comment by lotem** [comment]
> 那 Telegram 里面搜索框无法输入的问题呢，也没办法复现么

怎麼復現？​我沒有遇到這個問題。

**Comment by scomper** [comment]
Telegram 7.4 (212543) Beta 里妥妥的复现，在搜索框只能识别输入的第一个字母。
![](https://i.loli.net/2021/01/31/EHKSRZz7lgrIvbT.jpg)

**Comment by scomper** [comment]
Squirrel-0.14.0+git088cc84.zip 版本 Telegram 搜索框中输入正常。

**Comment by lotem** [comment]
> Squirrel-0.14.0+git088cc84.zip 版本 Telegram 搜索框中输入正常。
> Squirrel-0.14.0+gitd2c3410 挨着的几个版本好像都有问题。

是的。上述版本可以重現問題。

另外我發現宮保拼音仍可以在這裏正常輸入。有可能和處理keyup事件有關。
