### ISSUE TITLE
最新改動有已編譯好的版本嗎，目前可下載的是0.14.0

### ISSUE THREAD

**Issue by wanqulou** [rime/squirrel#478]

**Comment by lotem** [comment]
https://rime.im/download/
下載頁的「測試頻道」有自動構建的版本可供試用。

**Comment by wanqulou** [comment]
謝謝

**Comment by vinurs** [comment]
我觉得既然编译出了新版本也应该更新一下homebrew的

**Comment by okerivy** [comment]
打开页面发现无法下载，没有下载的选项？ 请问怎么下载

![image](https://user-images.githubusercontent.com/4578474/105790695-b7160d00-5fbf-11eb-8f5a-5a889c7b7927.png)

**Comment by wd** [comment]
点 General 那排最右面的 Files。
