### ISSUE TITLE
鼠须管 如何调整词频或删除？

### ISSUE THREAD

**Issue by liuour** [rime/squirrel#481]
只要选过一次英文，例如「D」，那么这个「D」就会永远占居在一地位置。

![GfPcQ7AH4C9eWET](https://i.loli.net/2021/01/18/GfPcQ7AH4C9eWET.png)

还有类似于下图这样

![ej3JnRGkKCXrwbF](https://i.loli.net/2021/01/18/ej3JnRGkKCXrwbF.png)

看了下说明书苹果键盘用 Shift+Fn+Delete ，我按了无效，还是说不适合我的问题？

**Comment by lotem** [comment]
你提的問題不屬於預設的功能。不知道怎樣實現的，我也沒法幫你解決。
如果是固態詞典裏的詞，那是無法通過快捷鍵刪除的。
至於排序很好理解。匹配完整編碼的候選詞應當先於匹配部分編碼的。從截圖無法看出候選詞的來源以及是否經過調頻。

看樣子不是自己寫的配置，那應該是借用別人的配置，用法和注意事項最好問問配置的作者。

**Comment by honeyshine75** [comment]
这个太烦人了，我也是这样，请问怎么解决的？
