### ISSUE TITLE
Problems with Swift PM version Sparkle

### ISSUE THREAD

**Issue by LEOYoon-Tsaw** [rime/squirrel#484]
<img width="345" alt="image" src="https://user-images.githubusercontent.com/4469383/105537397-dd863080-5cbf-11eb-9ef1-f08e823ec28d.png">

With the update to use Sparkle via SPM, xcode gives me this error, how to proceed?

**Comment by kuoruan** [comment]
What's your Xcode version?

**Comment by LEOYoon-Tsaw** [comment]
12.3

**Comment by kuoruan** [comment]
File -> Swift Packages -> Rest Package Caches

Then retry.

**Comment by LEOYoon-Tsaw** [comment]
Thank you @kuoruan problem solved! But another problem, it works when I archive in Xcode, but building with command line it throws error saying Sparkle not found.

**Comment by kuoruan** [comment]
run `xcodebuild clean` before build.

I think there is something wrong with the squirrel project config file.

With the new Xcode build system, there should be a `build/XCBuildData` folder.

But Xcode do not create the folder when build Squirrel.

**Comment by kuoruan** [comment]
@lotem Any opinion?

**Comment by lotem** [comment]
No idea.
I haven't run into the mentioned issues when using command line.
Travis CI is also passing:
https://travis-ci.org/github/rime/squirrel/builds

**Comment by LEOYoon-Tsaw** [comment]
@lotem @kuoruan 
In the xcode profile `ONLY_ACTIVE_ARCH = YES` is set, so I guess it's not building actual universal app

**Comment by lotem** [comment]
> @lotem @kuoruan
> In the xcode profile `ONLY_ACTIVE_ARCH = YES` is set, so I guess it's not building actual universal app

No issue here. The project isn't configured to create separate builds for mulitple architectures. The active and only architecture is to build for "Any Mac" which is universal app.

**Comment by LEOYoon-Tsaw** [comment]
> > @lotem @kuoruan
> > In the xcode profile `ONLY_ACTIVE_ARCH = YES` is set, so I guess it's not building actual universal app
> 
> No issue here. The project isn't configured to create separate builds for mulitple architectures. The active and only architecture is to build for "Any Mac" which is universal app.

In "System Information" app, under Software/Applications one can check if an App is universal or Intel

In my another app, setting ONLY_ACTIVE_ARCH = YES makes it Intel only, only if ONLY_ACTIVE_ARCH = NO, it shows as universal app.

Worth a check at least

**Comment by LEOYoon-Tsaw** [comment]
Another problem is that in the built app, the exact same folder `Sparkle.framework` is duplicated 4 times, under
`Contents/Frameworks/`, `Contents/MacOS/`, `Contents/SharedSupport/`, `Contents/SharedSupport/opencc/`,
which nearly doubles the app size.

**Comment by kuoruan** [comment]
Add `scheme` option to xcodebuild can fix `Sparkle not found`

**Comment by LEOYoon-Tsaw** [comment]
> Add `scheme` option to xcodebuild can fix `Sparkle not found`

But then the built product won't be saved in the build folder, instead, it's saved in Xcode's temp folder

**Comment by kuoruan** [comment]
Use the latest patch. There is a `build` path in the last of command.

**Comment by LEOYoon-Tsaw** [comment]
> Use the latest patch. There is a `build` path in the last of command.

I think that `build` is the command to build, it can be build/archive/debug, not the directory

**Comment by kuoruan** [comment]
@LEOYoon-Tsaw Yes, you are right.

Legacy Xcode build system use `CONFIGURATION_BUILD_DIR` to set the build dir.

With the new build system, we need to use `derivedDataPath`

```
xcodebuild -project Squirrel.xcodeproj -scheme Squirrel -configuration Release build -derivedDataPath build
```

**Comment by kuoruan** [comment]
We can also use
```
xcodebuild -project Squirrel.xcodeproj -scheme Squirrel -configuration Release build SYMROOT=build
```
The `SYMROOT` seems a replace of `CONFIGURATION_BUILD_DIR`

**Comment by kuoruan** [comment]
But my advice is add a new build stage `Copy Build Target`

```sh
if [ -d "${SYMROOT}/${CONFIGURATION}" ] ; then
  test -d "${SRCROOT}/build" || mkdir "${SRCROOT}/build"
  cp -f -R "${SYMROOT}/${CONFIGURATION}" "${SRCROOT}/build"
fi
```

![image](https://user-images.githubusercontent.com/8685618/106099665-030ab280-6176-11eb-9ae7-aa0e462f88ce.png)

**Comment by LEOYoon-Tsaw** [comment]
Copy may not work, my Xcode temp folder is under /var/root/, need sudo to operate

Any idea about duplicated Sparkle.framework?

**Comment by kuoruan** [comment]
sparkle-project/Sparkle#1689

**Comment by LEOYoon-Tsaw** [comment]
I would say it’s too early to use SPM, at most it worth an experimental branch
