### ISSUE TITLE
编译安装最新主分支后，候选词后方出现数字序号

### ISSUE THREAD

**Issue by zhugexiaobo** [rime/squirrel#489]
![image](https://user-images.githubusercontent.com/2577087/106120697-a3220500-6191-11eb-99d2-b51ae2200e04.png)
如图，请问如何去除？2个序号有点多余

**Comment by LuciusChen** [comment]
这个我也遇到过，修改 squirrel.customer.yaml 中的 candidate_format 就可以了。

**Comment by zhugexiaobo** [comment]
> 这个我也遇到过，修改 squirrel.customer.yaml 中的 candidate_format 就可以了。

感谢，果然是皮肤的问题

**Comment by zhugexiaobo** [comment]
但是现在有个新的问题，输入法的名字变成这样了，尝试重启也没有效果
![image](https://user-images.githubusercontent.com/2577087/106259205-ddef7000-6259-11eb-8561-7d4b11020c52.png)

**Comment by scomper** [comment]
修订一下 squirrel.custom.yaml 文件中的 candidate_format: "%c\u2005%@"

**Comment by scomper** [comment]
> 但是现在有个新的问题，输入法的名字变成这样了，尝试重启也没有效果
> ![image](https://user-images.githubusercontent.com/2577087/106259205-ddef7000-6259-11eb-8561-7d4b11020c52.png)

build 中缺对应的配置文件，部署时没有自动添加当前的配置文件到 build 文件夹导致的。

**Comment by lotem** [comment]
> 这个我也遇到过，修改 squirrel.customer.yaml 中的 candidate_format 就可以了。

​爲啥不報BUG

**Comment by LuciusChen** [comment]
> > 这个我也遇到过，修改 squirrel.customer.yaml 中的 candidate_format 就可以了。
> 
> ​爲啥不報BUG

我以为不是 Bug，是主题的问题啊。。。
