### ISSUE TITLE
能否通过 shell 来切换到 ascii_mode ？

### ISSUE THREAD

**Issue by dsdshcym** [rime/squirrel#49]
我在用 emacs 下的 evil-mode ，但是发现无法像在 MacVim 里那样自动切回 ascii_mode 。

查了代码发现是有为 MacVim 做了 Hack 。

想在 emacs 下实现类似的 hack ，但是没找到相关的设置，只有 ascii_mode 的 toggle。希望 @lotem 指点

**Comment by lotem** [comment]
我沒有研究過編輯器，不知有沒有更好的辦法。
Vim 呢，因爲有幾個固定的按鍵切換到 NORMAL 模式，而這些按鍵先一經過輸入法，輸入法就能知道發生了切換。並不需要知曉 Vim 內部狀態。

**Comment by dsdshcym** [comment]
希望能提供 通过 shell script 将 ascii_mode 设为 true 的功能，或者可以将某键（比如 esc）设为此功能。

我现在的两个做法是：

1. 在 emacs 回到 normal mode 时，模拟一个 shift 键，来切换 ascii_mode ，但如果我在 insert mode 下就是 ascii_mode 了，回到 normal mode 时会变成中文输入，所以在找其他的办法。
2. 将 shift+space 设为 ascii_mode 的 toggle ，这个按键组合只能从中文切换到英文，可以满足在 1 里的需求。但是在我打字比较快时，容易误按到这个组合键，比较烦人。

**Comment by lotem** [comment]
我在嘗試把按鍵和功能全部做成可綁定的，目前已改造了 editor 等幾個組件，工作量還不小。

他日都改造完了，就會比較容易吧。

**Comment by dsdshcym** [comment]
了解了，多谢回复！

希望 rime 越来越好！

**Comment by Edenharder** [comment]
我可能遇到了一个类似的问题：如何设置回到Alfred的时候，自动切换为英文？现在是每次重新启动Alfred才会自动切换为英文。

**Comment by jixiuf** [comment]
https://github.com/rime/squirrel/wiki/vim用户与emacs-evil-mode用户-输入法自动切换成英文状态的实现

**Comment by jixiuf** [comment]
https://github.com/jixiuf/squirrel/releases
提供临时解决方案

主要想实现两个功能：

1. 在emacs中 当shift键切换成中文输入状态时，自动进入evil-mode 的insert state (跟vim的输入模式类似）
2. 在emacs中或终端下(iterm2)的emacs里按下escape 键，自动切换成输入英文状态
实际实现的功能：

上面第1条可以完全实现
2.1. 第2 条在emacs 中 当输入法为中文状态时，若此时未输入任何字母，按下escape 无法切换成英文状态（不知道为什么未输入任何字母前 输入法中检测不到按下escape的事件）
2.2. 第2条在iterm2下却能检测到escape 事件，即iterm2下可以实现按下escape 键，自动切换成输入英文状态，但是在输入法中无法检测到iterm2里当前是否打开了emacs
如果习惯在iterm2下使用emacs ，这个版本目前应该可以用。

**Comment by dsdshcym** [comment]
@jixiuf 
squirrel_client 几乎就是我想要的效果了，但是 -s ascii_mode 在 Emacs 里使用延迟比较严重，退到 normal state 输了几个键依然是中文。这似乎是因为 socket 通信造成的

然后没有 get_option 的选项

尝试着在原有代码上自己添加，不过我 C 语言不太了解，最终作罢

**Comment by jixiuf** [comment]
有时间的话， 我尝试下加get_option

**Comment by jixiuf** [comment]
我c语言也不怎么样，现用现查。
延迟的问题，怀疑是write之后只是write 到buffer,没有立即刷到对方，目前还没找到办法解决这个问题。 

get option 功能已经加上。

关联一下 #123

**Comment by Voleking** [comment]
@dsdshcym 时间挺久的了，不确定是否已经解决。Emacs 可以参考这个 [fcitx.el](https://github.com/cute-jumper/fcitx.el) 和 [fcitx-remote-for-osx](https://github.com/CodeFalling/fcitx-remote-for-osx)

**Comment by dsdshcym** [comment]
@Voleking 谢谢！我现在用的也是这个方案，比较稳定。
