### ISSUE TITLE
有没有计划原生支持 Apple Silicon(M1) arm64 [Mac OS]

### ISSUE THREAD

**Issue by ililu2000** [rime/squirrel#490]
Mac 已经开始转向全新的自研芯片 M1，这也是 Mac 未来的趋势.
这么优秀的输入法希望能够原生支持 Apple Silicon(M1) arm64

PS: 搜狗输入法 Mac 已原生支持 Apple Silicon.

**Comment by lotem** [comment]
同 https://github.com/rime/squirrel/issues/464

**Comment by andyandhope** [comment]
目前RIME已经支持M1了吗

**Comment by LEOYoon-Tsaw** [comment]
是
