### ISSUE TITLE
希望mac下能增加选择键盘布局的功能

### ISSUE THREAD

**Issue by vangoah20** [rime/squirrel#491]
我的间盘布局是自己为全拼输入设计的，无法使用squirrel。 希望能像搜狗拼音mac版那样指定键盘布局。如果自己动手改的话，应该怎么修改？

**Comment by lotem** [comment]
​在系統設置輸入源列表裏添加所需的鍵盤佈局和鼠鬚管輸入法，然後先切換到某鍵盤，再切換一次到鼠鬚管，就可以使用該鍵盤佈局輸入了。

**Comment by vangoah20** [comment]
感谢佛振大老，已经可以使用了。

**Comment by vangoah20** [comment]
感谢，已经可以使用了。
