### ISSUE TITLE
希望mac下能够有方法实现定时同步\部署

### ISSUE THREAD

**Issue by jiz4oh** [rime/squirrel#492]
不知道mac的实现方式是否支持通过命令行同步和部署，比如

- 同步：rime sync
- 部署：rime deploy

这样的话就可以通过定时任务来定时同步和部署，不再需要手动点击来实现。

**Comment by ooopscc** [comment]
Deploy 目前通过发送快捷键这样实现：
```shell
osascript -e 'tell application "System Events" to key code 50 using {control down, option down}'
```

**Comment by jiz4oh** [comment]
> Deploy 目前通过发送快捷键这样实现：
> 
> ```shell
> osascript -e 'tell application "System Events" to key code 50 using {control down, option down}'
> ```

感谢~不知道同步是否也能通过这个方式实现

**Comment by lotem** [comment]
有執行部署操作的命令行參數。同步的沒有。

**Comment by baggio630** [comment]
> 有執行部署操作的命令行參數。同步的沒有。

同步的后续会添加吗，自动化同步会方便些~

**Comment by all4fun** [comment]
> 有執行部署操作的命令行參數。同步的沒有。

同步的后续会添加吗，自动化同步会方便些~

**Comment by puttin** [comment]
@baggio630 @all4fun #694 应该能帮到你们
