### ISSUE TITLE
0.14.0+gitd2c3410 版本更新后，候选条的样式变了

### ISSUE THREAD

**Issue by scomper** [rime/squirrel#494]
0.14.0+gitd2c3410 版本更新后，候选条的样式变了。
输入的英文部分应该是透明的
![](https://i.loli.net/2021/01/31/UHPfj9ABvi6DpOX.png)

**Comment by scomper** [comment]
![](https://i.loli.net/2021/01/31/UHPfj9ABvi6DpOX.png)

**Comment by LEOYoon-Tsaw** [comment]
哪變了？「英文部份是透明的」是啥意思？

**Comment by scomper** [comment]
原来样式应该是下面这样，配置没变更新到最新 beta版后就变成上面的样子了。
![](https://raw.githubusercontent.com/scomper/img/master/twitter_ErvemaHVoAMy9y0.jpg)

**Comment by LEOYoon-Tsaw** [comment]
加上 `inline_preedit: true`

**Comment by scomper** [comment]
有这行定义

---
`patch:
  show_notifications_when: appropriate # 状态通知，适当，也可设为全开（always）全关（never）

  #style/color_scheme: mojave_dark
  style/color_scheme: system_blue             # 方案命名，不能有空格
  preset_color_schemes:
    system_blue:
      author: "scomper <scomper@gmail.com>"   # 作者信息
      back_color: 0xFFFFFF                    # 候选条背景色，24位色值，16进制，BGR顺序
      border_color: 0xFFFFFF                  # 边框色
      candidate_text_color: 0x000000          # 预选项文字颜色
      comment_text_color: 0x999999            # 拼音等提示文字颜色
      hilited_back_color: 0xe16300            # 第一候选项背景背景色
      hilited_candidate_text_color: 0xFFFFFF  # 第一候选项文字颜色
      hilited_candidate_label_color: 0xFFFFFF # 第一候选项编号颜色
      hilited_comment_text_color: 0x999999    # 注解文字高亮
      hilited_text_color: 0x999999            # 高亮拼音 (需要开启内嵌编码)
      name: "系统蓝／System Blue"
      text_color: 0x424242                    # 拼音行文字颜色
      label_color: 0x999999                   # 预选栏编号颜色  
      horizontal: true                        # 水平排列
      inline_preedit: true                    # 单行显示，false双行显示
      candidate_format: "%c\u2005%@ \u2005"   # 用 1/6 em 空格 U+2005 来控制编号 %c 和候选词 %@ 前后的空间。
      font_face: "PingFangSC"# 候选词编号字体
      font_point: 16                          # 候选文字大小
      label_font_point: 14                    # 候选编号大小
#      label_font_face: "SFCompactText-Regular"# 候选词编号字体
      corner_radius: 6                        # 候选条圆角
      hilited_corner_radius: 4                # 高亮圆角
      border_height: 4                        # 窗口边界高度，大于圆角半径才生效
      border_width: 4                         # 窗口边界宽度，大于圆角半径才生效
      border_color_width: 0

  "app_options/com.runningwithcrayons.Alfred/ascii_mode": true
  "app_options/com.coteditor.CotEditor/ascii_mode": true`

**Comment by LEOYoon-Tsaw** [comment]
<img width="393" alt="image" src="https://user-images.githubusercontent.com/4469383/106375640-c13b6100-635b-11eb-82ef-7f4a3ebc2981.png">
不知道呀，在我這好著呢，公子能復現bug嗎？ @lotem

**Comment by scomper** [comment]
回滚到了Squirrel-0.14.0+git088cc84.zip，候选条样式正常，不过编号会重复。
将 candidate_format: "%c\u2005%@  \u2005"  修改成 candidate_format: "%c\u2005%@" 就好了。
![](https://i.loli.net/2021/01/31/HFQUo3bG5rBqN6f.png)

**Comment by lotem** [comment]
​可能是我重構搞出來的。
