### ISSUE TITLE
双频加辅助码的问题

### ISSUE THREAD

**Issue by vangoah20** [rime/squirrel#496]
我将地球拼音改成了双拼，又按照[佛振大佬这个帖子 ](https://tieba.baidu.com/p/2094178562?red_tag=0575566261)添加了辅助码。现在的问题是使用辅助码时，辅助码的字母组合有双拼音节对应的话，辅助码无法生效。
比如，声韵映射如下
b：ei
e：ch
r：ong
“他”的辅助码为：tbe
“动”的辅助码为：eace
输入“他”时，可以按键“ta-tbe”直接定位，
输入“动”时，无法通过“dr\eace定位到动，eace执行了拼写转换：cha ce

请问可以通过scheme配置文件，使得“-/〈\”四声之后的字母组合不执行拼写转换吗？可以的话，应该怎么写呢？

**Comment by lotem** [comment]
都改碼表的編碼了，爲啥不把雙拼一起改了呢。

請注意拼寫運算不執行對輸入的轉換，而是把詞典的編碼轉換成輸入碼形式。請檢查一下字的編碼轉換成什麼了。

**Comment by lotem** [comment]
​不屬於本項目的話題。這裏主要關注macOS前端的問題。

**Comment by vangoah20** [comment]
感谢。
没明白您的意思。
1：码表添加辅助码后，需要修改双拼吗？改的话，应该怎么改？能否以上述b、e、r为例说明一下。
2：我将字库和词库分开了。仅改了字库。格式为：quanpin;fuahuma。例如，动 dong;eace。这样有问题吗？
