### ISSUE TITLE
更新到 0.15 配置方案中的标点半角失效

### ISSUE THREAD

**Issue by scomper** [rime/squirrel#497]
更新到 Squirrel-0.15.0+git8ef9442 配置方案中标点的半角和全角切换失效。
面板中已经切换成半角，但是输入依旧是全角标点。

![](https://i.loli.net/2021/02/01/qJK1XTavg7sFCcm.png)

**Comment by scomper** [comment]
'''
patch:
  switches:
    - name: ascii_mode
      reset: 0
      states: ["中文", "西文"]
    - name: full_shape
      states: ["半角", "全角"]
    - name: zh_simp                      # (※1) 繁简转换
      reset: 1
      states: ["漢字", "汉字"]
    - options: ["utf8", "gbk", "gb2312"] # (※2)字符集选单
      reset: 0                           #     默认 UTF
      states:
        - UTF-8
        - GBK
        - GB2312
    - name: show_emoji
      reset: 1
      states: [ "🈚️️\uFE0E", "🈶️️\uFE0F" ]
  simplifier:
    option_name: zh_simp
'''

**Comment by thinkingbringsfreedom** [comment]
我遇到了跟你一样的问题，现在也不知道怎么完美解决，但是我发现了一个比较绕的解决方法：打开squirrel.custom.yaml文件，拉到最下面，有一个“＃ 特定App默认中/英文输入或默认用半角符号”版块，在这里对常用软件自定义一下即可。

不清楚你的那一版有没有可不可以这样。
