### ISSUE TITLE
重新部署后双拼方案没有加入到 Build 文件夹。

### ISSUE THREAD

**Issue by scomper** [rime/squirrel#498]
使用安装包默认安装，重新部署后双拼方案没有加入到 Build 文件夹。
/Users/scomper/Library/Rime 目录下有双拼的配置文件
double_pinyin.schema.yaml

部署时并没有复制这个文件到 build 文件夹，导致方案加载不成功（特征是 ⌃~ 中选择时该方案为英文名称 ）
需手动复制 double_pinyin.schema.yaml 文件到 build 解决。

![](https://i.loli.net/2021/02/01/hOt865SVvW3T4aK.png)

**Comment by lotem** [comment]
部署時不是把YAML文件複製過去。是要編譯YAML文件，把編譯後的結果寫進build目錄。
請檢查一下部署產生的日誌是否報告錯誤。

**Comment by scomper** [comment]
$TMPDIR/rime.Squirrel.INFO 里的替身均定位不到原身，无法查看日志定位问题。

![](https://i.loli.net/2021/02/02/gfqS1AEsJN7nRmX.png)

**Comment by scomper** [comment]
'''
Log file created at: 2021/02/02 09:22:04
Running on machine: scomper-Mac
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0202 09:22:04.410339 1865101312 config_compiler.cc:96] trying to append string to non scalar
E0202 09:22:04.410552 1865101312 config_compiler.cc:214] error applying patch to engine/translators/+
E0202 09:22:04.410571 1865101312 config_compiler.cc:96] trying to append string to non scalar
E0202 09:22:04.410579 1865101312 config_compiler.cc:214] error applying patch to schema/dependencies/+
E0202 09:22:04.410615 1865101312 config_compiler.cc:536] unresolved dependency: Patch(luna_pinyin.custom:patch <optional>)
E0202 09:22:04.410624 1865101312 config_compiler.cc:536] unresolved dependency: Include(luna_pinyin.schema:/)
E0202 09:22:04.410631 1865101312 config_component.cc:255] error building config: luna_pinyin_fluency.schema
E0202 09:22:04.489778 1865101312 config_compiler.cc:96] trying to append string to non scalar
E0202 09:22:04.489794 1865101312 config_compiler.cc:214] error applying patch to schema/dependencies/+
E0202 09:22:04.489811 1865101312 config_compiler.cc:536] unresolved dependency: Patch(double_pinyin_flypy.custom:patch <optional>)
E0202 09:22:04.489818 1865101312 config_component.cc:255] error building config: double_pinyin_flypy.schema

'''

**Comment by scomper** [comment]
```
Log file created at: 2021/02/02 09:22:01
Running on machine: scomper-Mac
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W0202 09:22:01.487886 19348800 tsv.cc:37] invalid metadata at line 3.
E0202 09:22:04.410339 1865101312 config_compiler.cc:96] trying to append string to non scalar
E0202 09:22:04.410552 1865101312 config_compiler.cc:214] error applying patch to engine/translators/+
E0202 09:22:04.410571 1865101312 config_compiler.cc:96] trying to append string to non scalar
E0202 09:22:04.410579 1865101312 config_compiler.cc:214] error applying patch to schema/dependencies/+
E0202 09:22:04.410615 1865101312 config_compiler.cc:536] unresolved dependency: Patch(luna_pinyin.custom:patch <optional>)
E0202 09:22:04.410624 1865101312 config_compiler.cc:536] unresolved dependency: Include(luna_pinyin.schema:/)
E0202 09:22:04.410631 1865101312 config_component.cc:255] error building config: luna_pinyin_fluency.schema
E0202 09:22:04.489778 1865101312 config_compiler.cc:96] trying to append string to non scalar
E0202 09:22:04.489794 1865101312 config_compiler.cc:214] error applying patch to schema/dependencies/+
E0202 09:22:04.489811 1865101312 config_compiler.cc:536] unresolved dependency: Patch(double_pinyin_flypy.custom:patch <optional>)
E0202 09:22:04.489818 1865101312 config_component.cc:255] error building config: double_pinyin_flypy.schema
W0202 09:22:15.027988 19348800 tsv.cc:37] invalid metadata at line 3.
E0202 09:23:27.752014 19348800 charset_filter.cc:106] charset parameter is unsupported by basic charset_filter
```

**Comment by LEOYoon-Tsaw** [comment]
Some patch to `luna_pinyin_fluency.schema` doesn't work

**Comment by lotem** [comment]
可能因爲本地一些`*.schema.yaml`文件被安裝包提供的較高版本文件重載了，而patch是針對本地版本寫的？
