### ISSUE TITLE
更新0.15.0后，CPU和内存吃满

### ISSUE THREAD

**Issue by liuour** [rime/squirrel#499]
一：0.15.0直接升级
二：卸载0.14.0，安装0.15.0
以上两种均出现彩虹无法使用，现在回到0.14.0正常
iMac 2017 27“ 
![](https://i.loli.net/2021/02/01/a3yrFNHY8WTIJoR.png)

**Comment by wd** [comment]
我试过下面的方法
1. 把 rime 配置目录里面自己的配置删除，可以使用了。
2. 把自己的配置再放进去就又死了。
3. 我看似乎是一些皮肤的配置的更新，所以我试过把 squirrel.custom.yaml 删除，也不行。

因为每次死了都需要重启电脑才能继续测试，所以我就没继续看是哪里导致的问题了。

**Comment by liuour** [comment]
> 我试过下面的方法
> 
> 1. 把rime配置目录里面自己的配置删除，可以使用了。
> 2. 把自己的配置再放进去就又死了。
> 3. 我看似是一些皮肤的配置的更新，所以我试过把squirrel.custom.yaml删除，也不行。
> 
> 因为每次死了都需要重启电脑才能继续测试，所以我就没继续看是哪里导致的问题了。

请问同机型，还是 MBP？

**Comment by wd** [comment]
MacBook Pro (16-inch, 2019) 
Bigsur 11.1 (20C69)

**Comment by liuour** [comment]
看来和机型无关，还是配置文件的问题

**Comment by lotem** [comment]
​使用什麼輸入方案？

**Comment by liuour** [comment]
朙月拼音简化字，配置文件：https://github.com/liuour/rime/tree/master/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

**Comment by liuour** [comment]
> ​使用什麼輸入方案？

朙月拼音简化字，配置文件：https://github.com/liuour/rime/tree/master/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

**Comment by lotem** [comment]
​暈吶
這也改得太多了

**Comment by LEOYoon-Tsaw** [comment]
我已經用了半年了，5年前的 macbook，還沒遇到過卡死，難道有地方內存洩漏？

**Comment by lotem** [comment]
> 我已經用了半年了，5年前的 macbook，還沒遇到過卡死，難道有地方內存洩漏？

​你們配置不一樣。上面分析了可能跟配置有關，而且排除了界面配置。

**Comment by liuour** [comment]
我单个测试是 `luna_pinyin_simp.custom` 的问题，部署提示有错误，我正在重新定制。

**Comment by lotem** [comment]
有沒有錯誤日誌？

請參考最近上游的修改，研究一下爲什麼會出現錯誤
https://github.com/rime/rime-luna-pinyin/commits/master

**Comment by LEOYoon-Tsaw** [comment]
是不是字典太大了，關掉幾個大型字典試試

**Comment by liuour** [comment]
重新配置就好了，反正不能直接升级。但现在又遇到个问题，连续按某个键会出现语音报错，此时输入法无法输入中文，电脑需重新登录才正常。

**Comment by liuour** [comment]
> 什麼叫某個鍵？

https://youtu.be/Jlmns_spxZ8

**Comment by LEOYoon-Tsaw** [comment]
https://user-images.githubusercontent.com/4469383/106668610-79455580-6578-11eb-9cbc-d34e4d706fc2.mov

好像我沒遇到這種問題

**Comment by lotem** [comment]
> > 什麼叫某個鍵？
> 
> https://youtu.be/Jlmns_spxZ8

连续崩溃。到Console.app查一下崩溃报告吧。

**Comment by wd** [comment]
> 重新配置就好了，反正不能直接升级。但现在又遇到个问题，连续按某个键会出现语音报错，此时输入法无法输入中文，电脑需重新登录才正常。

重新配置是什么意思？我试过删除 build 等自动产生的目录，只保留我的配置文件也是不行的。

**Comment by lotem** [comment]
请查看日志尝试找到发生问题的原因。

**Comment by LufsX** [comment]
我在添加颜文字时也遇到了这个问题，似乎是这几行引起的，你可以删除试试

https://github.com/liuour/rime/blob/master/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6/luna_pinyin_simp.custom.yaml#L51-L58

**Comment by liuour** [comment]
> > > 什麼叫某個鍵？
> > 
> > 
> > https://youtu.be/Jlmns_spxZ8
> 
> 连续崩溃。到Console.app查一下崩溃报告吧。

已解决，是因为颜文字词库导致。

**Comment by wd** [comment]
> 已解决，是因为颜文字词库导致。

我想问下，是颜文字哪里导致的？你的解决办法是把整个颜文字词库去掉，还是说只是修复了里面有问题的？

**Comment by liuour** [comment]
1. 0.14.0升级0.15.0出现占用所有电脑资源。解决办法：卸载0.14.0，重新安装0.15.0，再一步一步配制新文件。
2. 配制好我加入词库，出现有一些按键连续按出现语音报错。解决办法：删除整个颜文字词库。

以上遇到的问题总结就是词库惹的祸。

**Comment by lotem** [comment]
@liuour 還不能就此放過這個問題。

​根據以上線索，發生崩潰的地方，有一處最值得懷疑：實現顏文字用的simplifier組件及背後的opencc程序庫，後者更新到了一個新版本。

有沒有到Console.app查看Squirrel的崩潰報告？報告裏應該能記錄發生崩潰的代碼位置。

**Comment by wd** [comment]
我这里 CPU 100% 的原因找到了，已经汇报给上游词库。应该和 squirrel 没关系。

顺便发一个 debug 的方式。因为每次 deploy 之后只要敲一个字符立刻会 CPU 100% 导致什么都干不了，所以需要下面这样解决。
1. deploy 前先打开 Activity Monitor
2. 执行 deploy，敲任何字符，如果出现 cpu 100%，可以切换到 activity monitor 然后杀掉 squirrel。
3. logout 然后重新 login。这个时候只要不激活使用 squirrel 系统是可用的。此时可以调整配置文件，如果需要继续测试，那重复 1。

**Comment by YubinXie** [comment]
遇到了同样的问题。我完全没有使用这个输入法但是资源全被吃了：
![3CCA6096-9BEB-41D0-8FC8-EBBFE53D483D](https://user-images.githubusercontent.com/16257776/108551830-76f43280-72be-11eb-9c76-9b1ffb3b2d91.png)

**Comment by YubinXie** [comment]
这个bug在，整个电脑跟本无法用。只有移出特定设置文件才行，我的设置文件如下：
[luna_pinyin_simp.custom.yaml.zip](https://github.com/rime/squirrel/files/6012596/luna_pinyin_simp.custom.yaml.zip)

**Comment by wd** [comment]
> 这个bug在，整个电脑跟本无法用。只有移出特定设置文件才行，我的设置文件如下：
> [luna_pinyin_simp.custom.yaml.zip](https://github.com/rime/squirrel/files/6012596/luna_pinyin_simp.custom.yaml.zip)

建议你用我这里贴的方法： https://github.com/rime/squirrel/issues/499#issuecomment-774048364 
自己排查下是哪个文件导致的问题。

**Comment by YubinXie** [comment]
> > 这个bug在，整个电脑跟本无法用。只有移出特定设置文件才行，我的设置文件如下：
> > [luna_pinyin_simp.custom.yaml.zip](https://github.com/rime/squirrel/files/6012596/luna_pinyin_simp.custom.yaml.zip)
> 
> 建议你用我这里贴的方法： [#499 (comment)](https://github.com/rime/squirrel/issues/499#issuecomment-774048364)
> 自己排查下是哪个文件导致的问题。

找到了，就是我附带的设置文件。

**Comment by wd** [comment]
> 找到了，就是我附带的设置文件。一行一行找具体的代码太累了，但应该还是和这个输入法本身新bug有关。

这个不能这么说，如果比如像我遇到问题那样，是因为配置文件本身有错误导致的，那不能说是代码有 bug。因为代码没有义务兼容这样的情况。
