### ISSUE TITLE
如何关闭新版本在代码编辑器及终端中关闭输入中文的功能

### ISSUE THREAD

**Issue by sleetdrop** [rime/squirrel#5]
有的时候还是需要在代码编辑器中输入中文的，目前发现通过按shift可以开启中文输入法，但想恢复成以前版本的行为，应该怎么配置呢?

**Comment by kanwofeiwo** [comment]
> http://code.google.com/p/rimeime/wiki/CustomizationGuide#%E9%87%9D%E5%B0%8D%E7%89%B9%E5%AE%9A%E7%A8%8B%E5%BA%8F%E7%A6%81%E7%94%A8%E6%BC%A2%E5%AD%97%E8%BC%B8%E5%85%A5
> 
> 修改方法：以Xcode为例，在 ~/Library/Rime/squirrel.custom.yaml 里写 patch: { app_options/com.apple.Xcode: {} }
> 
> 另外调查一下，是那款编辑器？

你好,linux可以设置吗,文档里面没有提到,修改defaultcustom之后也没有生效
