### ISSUE TITLE
最新的编译版本候选栏高度会随着是否有Emoji而变化

### ISSUE THREAD

**Issue by moonagic** [rime/squirrel#501]
效果如录屏所示:
https://user-images.githubusercontent.com/5424240/106542099-1fc03500-653e-11eb-827c-b879c5bf43d8.mov

我是通过 https://dl.bintray.com/rime/squirrel/ 下载的编译版本,  
该问题从0.14.0比较新的某个版本引入,直到Squirrel-0.15.0+git8ed6ce5.zip仍能复现.  
而0.14.0正式版并没有该问题.

所使用设备:2018 MacBook ProPro, 2020 Mac Mini
所使用系统版本:11.1, 11.2
在以上设备及版本上皆能复现此效果.

**Comment by LEOYoon-Tsaw** [comment]
因爲繪文字的繪制大小就是比漢字略大，這是正常現像。

**Comment by LEOYoon-Tsaw** [comment]
主要是爲了跨行高亮、編碼區高亮圖角必須用CoreText，它渲染出來繪文字就是高一些。如果有功夫可以寫一段縮小繪文字字號的代碼，以繪文字更看不清爲代價。或者增加最小行距，以無繪文字時行距變大爲代價。我覺得沒必要。

**Comment by moonagic** [comment]
谢谢解答,不过现在的效果对横排候选词的用户体验影响确实比较明显,我只能先切换到纵向候选词了

**Comment by LEOYoon-Tsaw** [comment]
體驗這種東西，太主觀，我就覺得沒啥

**Comment by scomper** [comment]
日志中会不断提示 charset parameter is unsupported by basic charset_filter 问题
查了一下好像是表情符号不支持charset_filter 这个参数
@LEOYoon-Tsaw 
```
I0202 10:45:40.876783 49855808 simplifier.cc:36] initializing opencc: /Library/Input Methods/Squirrel.app/Contents/SharedSupport/opencc/t2s.json
I0202 10:45:40.880995 49855808 simplifier.cc:36] initializing opencc: /Users/scomper/Library/Rime/opencc/emoji.json
E0202 10:45:40.903920 49855808 charset_filter.cc:106] charset parameter is unsupported by basic charset_filter
I0202 10:45:41.132876 49855808 engine.cc:203] Oops, got a futile translation.
```

**Comment by LEOYoon-Tsaw** [comment]
> 日志中会不断提示 charset parameter is unsupported by basic charset_filter 问题

這個和我的UI沒關係
我正在寫一個pull，讓你可以爲Emoji單獨設字號

**Comment by lotem** [comment]
> 日志中会不断提示 charset parameter is unsupported by basic charset_filter 问题
> 查了一下好像是表情符号不支持charset_filter 这个参数
> @LEOYoon-Tsaw
> 
> ```
> I0202 10:45:40.876783 49855808 simplifier.cc:36] initializing opencc: /Library/Input Methods/Squirrel.app/Contents/SharedSupport/opencc/t2s.json
> I0202 10:45:40.880995 49855808 simplifier.cc:36] initializing opencc: /Users/scomper/Library/Rime/opencc/emoji.json
> E0202 10:45:40.903920 49855808 charset_filter.cc:106] charset parameter is unsupported by basic charset_filter
> I0202 10:45:41.132876 49855808 engine.cc:203] Oops, got a futile translation.
> ```

自动构建版本没有集成librime插件

**Comment by lotem** [comment]
> 主要是爲了跨行高亮、編碼區高亮圖角必須用CoreText，它渲染出來繪文字就是高一些。如果有功夫可以寫一段縮小繪文字字號的代碼，以繪文字更看不清爲代價。或者增加最小行距，以無繪文字時行距變大爲代價。我覺得沒必要。

不如先比较一下改动前的，看看究竟是绘文字字号变了还是行距变了。我觉得尽量保持跟原来的一致比较妥。这样可以最大限度保持用家原来设定的样式。

**Comment by LEOYoon-Tsaw** [comment]
Xcode裏面也一樣的，輸入一個Emoji會讓那一行變高

**Comment by liuour** [comment]
同于到，背景号变，字号不变
![hYd64XKNRZ5lgwS](https://i.loli.net/2021/02/03/hYd64XKNRZ5lgwS.png)

**Comment by LEOYoon-Tsaw** [comment]
#559 更好地修復了這個問題
