### ISSUE TITLE
在 `custom_phrase.txt` 中写入一些配置后，Rime 失去了部分造词能力。

### ISSUE THREAD

**Issue by iDvel** [rime/squirrel#503]
比如我打一个新词，Rime 会记住，下次直接就出现在候选栏里了。

但当我在 `custom_phrase.txt` 写了好多内容之后，  
如「而那」「这便是」「等会」这些词，无论我打多少遍都无法直接出现在候选栏。  

我目前用的 `custom_phrase.txt`：https://github.com/iDvel/rime-settings/blob/70a81d76dfee18fa551a0e52fa5c84b99ca3e322/custom_phrase.txt

简单的复现：删除 `*.userdb/` 文件或删除所有配置文件，在 `custom_phrase.txt` 中写入一些配置，并重新部署。
```
会	hui	1
```
「等会」「干会」这些词不会被记住。  

似乎是如果固定了某个字是第一候选项的话，这个字结尾的自造词就不会被记住。

**Comment by lotem** [comment]
​自定義短語不能和拼音混合造詞。

我記得你曾在 https://github.com/rime/squirrel/issues/97#issuecomment-770838518 發言。如果想瞭解關於這個問題的具體細節，可以回看該主題過往的討論。
