### ISSUE TITLE
0.15.0 测试版 emoji 会把「候选条」的高度顶高一点，如图：

### ISSUE THREAD

**Issue by baggio630** [rime/squirrel#504]
![rime@2x](https://user-images.githubusercontent.com/46696/106701221-499e5800-6621-11eb-8d00-15bcd98c361c.png)

**Comment by lotem** [comment]
相同問題： https://github.com/rime/squirrel/issues/501

**Comment by LEOYoon-Tsaw** [comment]
在 #502 中提供了一種方案，縮小Emoji。未必有多理想，只能說不差。
但我覺得，就像watchOS7移除了ForceTouch，macOS10.15移除了x86_32支持，有人不爽，那就別升級嘛。
0.15的大部分UI升級都是靠換用NSTextStorage達成的，如果退回之前的方案，那就沒有0.15升級了。這個問題目前不好解決，你要是非常介意，可以跳過這個版本，等下個版本

**Comment by baggio630** [comment]
> > 补充下同一份配置情况下 0.14.0 与 0.15.0 「候选条」的高度对比：
> > ![rime@2x](https://user-images.githubusercontent.com/46696/106735073-be3bbb80-664e-11eb-9dd8-0f6a124a40d8.png)
> > 以及打8个字，「候选条」跳动10次的视频：
> > https://user-images.githubusercontent.com/46696/106735194-e3c8c500-664e-11eb-9ce8-559ce0bc0670.mov
> 
> 謝謝，你反應的情況我已瞭解了。
> 我的上一個問題目的是要求證究竟新版是有emoji的情況行高增加了還是沒有emoji的時候行高少算了。
> 
> ​這三副圖最左邊是0.14.0麼？跟右邊兩幅圖邊上的空白距離差別有點兒大呀。出自完全一樣的參數嗎？

是的，最左边的是0.14.0，跟右边两幅图是完全一样的参数。

**Comment by baggio630** [comment]
> 在 #502 中提供了一種方案，縮小Emoji。未必有多理想，只能說不差。
> 但我覺得，就像watchOS7移除了ForceTouch，macOS10.15移除了x86_32支持，有人不爽，那就別升級嘛。
> 0.15的大部分UI升級都是靠換用NSTextStorage達成的，如果退回之前的方案，那就沒有0.15升級了。這個問題目前不好解決，你要是非常介意，可以跳過這個版本，等下個版本

我已经退回了0.14.0正式版，选择跟习惯妥协，我觉得拿蝶式键盘和剪刀式键盘的差异来比喻这次的问题会更恰当些，输入法和键盘很类似是非常高频使用的工具，一个体现在软件层面、一个体现在硬件层面，开发者/工程师技术方面的改进还是应以尽可能贴近用户之前使用习惯为前提，当然这是我个人的立场。

不过还是感谢你们在这个问题上的讨论和工作，期待下个版本。

**Comment by LEOYoon-Tsaw** [comment]
主要是這個不影響功能，只是有輕微跳動，要是好解決的話就搞好了，但是比較麻煩，暫時在「輕微跳動」和「稍小一些的Emoji」之間取捨吧

**Comment by LEOYoon-Tsaw** [comment]
#559 應該已徹底修復
