### ISSUE TITLE
新版鼠须管折行不完美

### ISSUE THREAD

**Issue by yanhuacuo** [rime/squirrel#507]
借助 Lua 插件，实现了自定义短语输出，同文、ibus-rime、以及鼠须管都能正确认别 `\r` 这个折行符。

````
"清明时节雨纷纷，路上行人欲断魂。\r借问酒家何处有？牧童遥指杏花村。","清明•杜牧"
````

上屏后的效果，都挺好的，如下：

![https://upimage.alexhchu.com/2021/02/06/80c6e56f4a50b.png](https://raw.githubusercontent.com/yanhuacuo/blog-css/main/80c6e56f4a50b.png)

在 ibus-rime 里，折行时依 `\r` 折断，并自动与前文对齐，并与数字序号错开，显得有序而整洁。

![3.png](https://raw.githubusercontent.com/yanhuacuo/blog-css/main/22.png)

![4.png](https://raw.githubusercontent.com/yanhuacuo/blog-css/main/33.png)

反观新版鼠须管，效果很差：

![1.png](https://raw.githubusercontent.com/yanhuacuo/blog-css/main/5d5c4b6414be6.png)

![2.png](https://raw.githubusercontent.com/yanhuacuo/blog-css/main/e88c013540e83.png)

希望公子改进。

**Comment by LEOYoon-Tsaw** [comment]
自己動手，豐衣足食。

**Comment by lotem** [comment]
不妨把序号后面加个换行，或者改到候选文字之后。

**Comment by yanhuacuo** [comment]
> 不妨把序号后面加个换行，或者改到候选文字之后。

那样不方便控制上屏样式，如果因鼠须端的这个问题特别修改 lua 短语结构，也影响通用性。

问题不大，凑合能看，就是稍微有点别扭。

**Comment by Jreen** [comment]
@yanhuacuo 请问你那个新版鼠须管用的是哪个样式？我很喜欢你那个样式的风格。

**Comment by lotem** [comment]
> @yanhuacuo 请问你那个新版鼠须管用的是哪个样式？我很喜欢你那个样式的风格。

​就是默認的「系統配色」吧。

**Comment by yanhuacuo** [comment]
> @yanhuacuo 请问你那个新版鼠须管用的是哪个样式？我很喜欢你那个样式的风格。

就是默认的，没有修改。

**Comment by lotem** [comment]
由於在候選中使用換行符不屬於設計中支持的特性，暫不跟進這個問題。
