### ISSUE TITLE
与Telegram.app兼容问题

### ISSUE THREAD

**Issue by iyee** [rime/squirrel#51]
Telegram官方有两个Mac客户端，其中一个跨平台Telegram Desktop好像是QT写的，在OS X下太难看；另外就是原生的Telegram.app了，但是使用鼠须管中英文混合输入会有问题，英文回车没有上屏句子就直接发送出去了，原生输入法正常。

**Comment by lotem** [comment]
爲什麼關閉了？

**Comment by iyee** [comment]
应该是Telegram的问题，换成QIM也这样。
https://github.com/overtake/telegram 有人提交了PR。
