### ISSUE TITLE
0.15.0使用>键只能翻一页，并且输入选项数字后上屏的仍是首页的选项。

### ISSUE THREAD

**Issue by monarchBacilluscoli** [rime/squirrel#513]
系统是macOS Mojave 10.14.6。刚更新了鼠须管并退出登录重新进入了就发现了如题的问题。

比如输入 shenme ，第一页选项是
1.什么 2.甚么 3. 审 4....
`>`键翻到第二页，选项是
1.甚 2. 沈 3....
按下2，“甚么”上屏。

**Comment by grasonchan** [comment]
系统版本同为 10.14.6，完全相同的问题

问题复现：鼠须管更新到 0.15.0 后，移除 `~/Library/Rime` 中的所有文件并重新部署，出现了该问题

问题补充：
1. `右箭头 →` 按键只能切换到第二个候选项，无法再继续往右边移动
2. 当切换到第二个候选项时，按下修饰键 `Ctrl ⌃`、`Shift ⇧` 或 `Option ⌥`，会自动切换回第一个候选项

![候选项切换异常](https://user-images.githubusercontent.com/19476925/107245794-85df1780-6a6a-11eb-8da8-25aca677cd25.png)

问题消失：尝试后发现，加入 0.14.0 版本的个人配置文件 `squirrel.custom.yaml` 后，上述的所有问题消失

包括：
1. @monarchBacilluscoli 描述的问题
2. 个人补充的 2 个问题

个人配置：[squirrel-config](https://github.com/grasonchan/squirrel-config)

![候选项切换正常](https://user-images.githubusercontent.com/19476925/107249516-68ac4800-6a6e-11eb-8daf-5cb95133a0ad.png)

**Comment by monarchBacilluscoli** [comment]
采用了 @grasonchan 的方法及其配置文件`squirrel.custom.yaml`有效。
问题补充：
经逐条测试，只要在@grasonchan 的配置文件中有`horizontal: true`这一句（false/true），即不会产生上述所有问题。

**Comment by lotem** [comment]
令人迷惑。
沒有相同的測試環境，暫時沒法研究。

疑點：
https://github.com/rime/squirrel/issues/513#issuecomment-775296790
@grasonchan 第一張截圖是橫向的候選列表，而出廠配置以及無配置的情況下候選字是縱向排列的。令人迷惑。
如果界面是由設置`horizontal: true`改爲橫向，則按照 @monarchBacilluscoli 的發現不會產生該問題。 

兩位安裝完畢後重新登錄/重啓過嘛？

**Comment by monarchBacilluscoli** [comment]
@lotem 抱歉，我的意思是那一句无论是true还是false都可以，只要这一句配置出现，就不会有问题，无关横向纵向。已修改。

**Comment by lotem** [comment]
> @lotem 抱歉，我的意思是`horizontal`项无论是`true`还是`false`都可以——只要这一句配置出现，就不会有问题，无关横向纵向。已修改。

好的，​不過這也不能消除疑點。即使配置文件包含`horizontal: false`，也不該顯示橫向的候選欄。

**Comment by lotem** [comment]
https://github.com/rime/home/discussions/700 報告裏提到相似情形，macOS版本是10.10。

我自己用macOS 10.13.6以及10.15.6分別做了以下測試：
全新安裝鼠鬚管0.15、先安裝0.14再升級安裝0.15，都沒有重現問題。

推測：未必與特定macOS版本有關。

**Comment by c3110** [comment]
> 系统版本同为 10.14.6，完全相同的问题
> 
> 问题复现：鼠须管更新到 0.15.0 后，移除 `~/Library/Rime` 中的所有文件并重新部署，出现了该问题
> 
> 问题补充：
> 
> 1. `右箭头 →` 按键只能切换到第二个候选项，无法再继续往右边移动
> 2. 当切换到第二个候选项时，按下修饰键 `Ctrl ⌃`、`Shift ⇧` 或 `Option ⌥`，会自动切换回第一个候选项
> 
> ![候选项切换异常](https://user-images.githubusercontent.com/19476925/107245794-85df1780-6a6a-11eb-8da8-25aca677cd25.png)
> 
> 问题消失：尝试后发现，加入 0.14.0 版本的个人配置文件 `squirrel.custom.yaml` 后，上述的所有问题消失
> 
> 包括：
> 
> 1. @monarchBacilluscoli 描述的问题
> 2. 个人补充的 2 个问题
> 
> 个人配置：[squirrel-config](https://github.com/grasonchan/squirrel-config)
> 
> ![候选项切换正常](https://user-images.githubusercontent.com/19476925/107249516-68ac4800-6a6e-11eb-8daf-5cb95133a0ad.png)

装了后squirrel到cpu占用上90%，卡死

**Comment by grasonchan** [comment]
> 好的，​不過這也不能消除疑點。即使配置文件包含`horizontal: false`，也不該顯示橫向的候選欄。

@lotem 出厂配置的情况下，显示为横向的候选栏，出现上述的各种问题

当个人配置文件包含 `horizontal: true` 时，显示为 **横向** 的候选栏，问题消失

当个人配置文件包含 `horizontal: false` 时，显示为 **纵向** 的候选栏，问题消失

![纵向候选栏](https://user-images.githubusercontent.com/19476925/107804961-a0353000-6d9f-11eb-9b77-049f7c13eb41.png)

**Comment by grasonchan** [comment]
@c3110 暂且移除配置文件 `luna_pinyin_simp.custom.yaml`，可解决 CPU 占用极高、甚至导致系统短时间卡住的问题

因为 Repo 中的配置文件适配的是鼠须管 0.10.0-0.14.0 版本，可能有部分配置项与新版本不兼容；暂未排错，目前仍在重新制作一些词典文件；打算制作完词典后，再找时间重新制作和整理所有的配置文件

如若需要，可暂时先使用 `default.custom.yaml` 和 `squirrel.custom.yaml` 这 2 个配置文件；或者，你可以再添加一些已经制作完成的词典文件，位于 Repo 的 `./Rime/dict/` 目录内，词典已进行分类，可按需选择

**Comment by lotem** [comment]
修復了代碼中一處未初始化變量的問題。
爲了兼容舊的配置，`style/candidate_list_layout`這一項沒有設默認值。​估計是候選欄隨機變成橫向的原因。
至此仍然沒有弄明白爲什麼翻頁和選詞受到影響。
可以重現問題的同學請幫忙用測試版驗證一下問題是否完全解決了：
https://bintray.com/rime/squirrel/testing/0.15.1%2Bgite8b87a4

**Comment by lotem** [comment]
> 修復了代碼中一處未初始化變量的問題。
> 爲了兼容舊的配置，`style/candidate_list_layout`這一項沒有設默認值。​估計是候選欄隨機變成橫向的原因。
> 至此仍然沒有弄明白爲什麼翻頁和選詞受到影響。
> 可以重現問題的同學請幫忙用測試版驗證一下問題是否完全解決了：
> https://bintray.com/rime/squirrel/testing/0.15.1%2Bgite8b87a4

@monarchBacilluscoli, @grasonchan, @easior​, @c3110, @cyishere

**Comment by cyishere** [comment]
> 可以重現問題的同學請升级到0.15.2版本，幫忙驗證一下問題是否得到解決。
> 
> @monarchBacilluscoli, @grasonchan, @easior​, @c3110, @cyishere, @xiaolinpg

升级到0.15.2后没有再出现此情况，谢谢。

**Comment by xiaolinpg** [comment]
手动升级到 0.15.2 （为何没收到自动更新推送奇怪），关闭之前的自定义配置文件，初步测试没有再发现这个问题。谢谢！

	（另：仍然存在excel中用“-”、“=”换页时，单元格会输入“-”、“=”这两个符号的问题，Mac OS Mojave 10.14.2，excel 16.16.4，我另提一个issue吧）

Thanks！

**Comment by lotem** [comment]
​謝謝反饋！

**Comment by grasonchan** [comment]
> 可以重現問題的同學請升级到0.15.2版本，幫忙驗證一下問題是否得到解決。
> 
> @monarchBacilluscoli, @grasonchan, @easior​, @c3110, @cyishere, @xiaolinpg

更新：鼠须管未有提示更新，通过手动 `检查新版本...` 从 0.15.0 升级到 0.15.2，更新完成后未见有 `退出登录` 的窗口提示

测试：更新完成后，系统用户未重新登录的情况下，移除 `~/Library/Rime` 中的所有文件并重新部署，未见上述的旧有问题，且候选栏恢复为默认竖排

![默认竖排候选栏](https://user-images.githubusercontent.com/19476925/108594713-8787d400-73b6-11eb-9b59-4485b2284432.png)

系统用户重新登录、系统重启，鼠须管均表现正常；加入 `squirrel.custom.yaml` 表现亦正常

@lotem 辛苦了

**Comment by lotem** [comment]
不提示退出登錄，應該是macOS 11的改動。較早版本的macOS升級這一版輸入法仍會提示退出登錄。
我還觀察到，在macOS 11，重新登錄之前不能切換到更新後的輸入法（不動系統設置的情況下），重新登錄後可以正常切換。

**Comment by grasonchan** [comment]
> 不提示退出登錄，應該是macOS 11的改動。較早版本的macOS升級這一版輸入法仍會提示退出登錄。
> 我還觀察到，在macOS 11，重新登錄之前不能切換到更新後的輸入法（不動系統設置的情況下），重新登錄後可以正常切換。

系统版本仍为 10.14.6，非 macOS 11

这边进行了测试，在卸载鼠须管并重启系统后，安装鼠须管 0.15.1 版本，以及将版本更新到 0.15.2
- 安装 0.15.1 版本后，窗口提示 `退出登录`
- 重新登录系统用户后，测试发现 0.15.0 版本发现的问题仍旧存在
- 手动 `检查新版本...`，从 0.15.1 更新到 0.15.2；更新完成后仍是未见有 `退出登录` 的窗口提示，且未有更新完成的提示，0.15.0 版本发现的问题消失

更新过程截图如下

![准备更新的提示](https://user-images.githubusercontent.com/19476925/108700934-49b7b680-7542-11eb-8d56-ac3302cb9bd9.png)

安装更新

![安装更新](https://user-images.githubusercontent.com/19476925/108701110-7d92dc00-7542-11eb-89d0-4efcb5154976.png)

系统 Dock 栏显示 Logo

![更新 Logo](https://user-images.githubusercontent.com/19476925/108701059-6e139300-7542-11eb-867e-63107c709299.png)

更新完成未退出登录（未见窗口提示），且未见提示更新完成，查看到鼠须管已更新到 0.15.2

![鼠须管 0.15.2](https://user-images.githubusercontent.com/19476925/108701192-98fde700-7542-11eb-93df-a232101cacc8.png)

另，重新登录之前，可使用更新后的输入法（未动系统设置），且未发现问题

更新完无需 `退出登录`，个人觉得这样的体验是好很多的（在不 `退出登录` 不会产生问题的情况下），且有提示更新完成的话会更好些
