### ISSUE TITLE
inline_preedit配置为false时，Chrome地址栏打字删除拼音时会删除光标前的字

### ISSUE THREAD

**Issue by hsingll** [rime/squirrel#514]
macOS 10.15.7+鼠须管 0.15.0+地球拼音+Chrome 88.0.4324.150

以前类似的issues：
#435 
https://github.com/rime/home/issues/267

开始测试：　
<img width="249" alt="Snipaste_2021-02-08_19-31-48" src="https://user-images.githubusercontent.com/26346635/107214148-72b95100-6a44-11eb-8ae8-a0afd84435ea.png">

删除出现异常：
<img width="253" alt="Snipaste_2021-02-08_19-32-25" src="https://user-images.githubusercontent.com/26346635/107214196-849af400-6a44-11eb-833f-81641a822eb4.png">

**Comment by lotem** [comment]
不管
