### ISSUE TITLE
候选词字数过多过长，就会分为两行显示

### ISSUE THREAD

**Issue by ililu2000** [rime/squirrel#515]
<img width="600" alt="1" src="https://user-images.githubusercontent.com/78154435/107323779-d6458c00-6ae1-11eb-9487-ba9af7da5c70.png">

这应该是个新特性
不过，如图，候选词 『6 热情』，『6 热』在第一行，『情』在第二行，一个完整的候选词，分为了两行显示，有点别扭。
有没有一个设置，能让一个完整的候选词显示在同一行？

**Comment by LEOYoon-Tsaw** [comment]
沒有

**Comment by Jreen** [comment]
还有一个办法就是限制候选词，或者取消不需要的日期显示（比如dd/m/yyyy 等）

**Comment by ililu2000** [comment]
> 还有一个办法就是限制候选词数量，或者取消不需要的日期显示（比如 dd/m/yyyy 等）

并没有用，只要候选词字数够多，这个问题就会复现

如图只有5个候选词
![Uploading 屏幕快照 2021-02-09 上午10.18.27.png…]()

**Comment by LEOYoon-Tsaw** [comment]
<img width="676" alt="image" src="https://user-images.githubusercontent.com/4469383/114187361-e0371000-9915-11eb-9a43-5a2430dbafbe.png">
基本上短詞不會再被拆到兩行

**Comment by liang-0131** [comment]
确实多行还对不齐是真的难受

**Comment by LEOYoon-Tsaw** [comment]
已增加短詞不換行的邏輯，目前是10個字符以內的候選（連同序號、注釋）不換行，4個字以內的候選（不含序號、注釋）內部不換行
