### ISSUE TITLE
在terminal中表现与其他应用不一致

### ISSUE THREAD

**Issue by cabins** [rime/squirrel#517]
在terminal这的样子是：

<img width="620" alt="image" src="https://user-images.githubusercontent.com/2500123/107235487-b2416680-6a5f-11eb-85e6-c32251716491.png">

而在其他的应用中是这样：

![image](https://user-images.githubusercontent.com/2500123/107236007-3c89ca80-6a60-11eb-851a-eb68258e1608.png)

即在terminal中是两行显示，而其他应用中单行显示。

**Comment by LEOYoon-Tsaw** [comment]
Terminal 不支持 inline

**Comment by cabins** [comment]
> Terminal 不支持 inline

难怪，那就不是我配置的问题了～

**Comment by lotem** [comment]
> Terminal 不支持 inline

Terminal可以支持。而且似乎挺好用的。有可能一些終端上的編輯器不支持。或者是因爲嵌入編碼容易發生折行。

**Comment by cabins** [comment]
> > Terminal 不支持 inline
> 
> Terminal可以支持。而且似乎挺好用的。有可能一些終端上的編輯器不支持。或者是因爲嵌入編碼容易發生折行。

使用的是默认的终端，没有在终端中打开其他的编辑器。系统是big sur(11.1)，有没有可能与系统版本有关？

**Comment by lotem** [comment]
​沒有關係。就是特意給終端程序配置成這樣的界面樣式。

**Comment by cabins** [comment]
> ​沒有關係。就是特意給終端程序配置成這樣的界面樣式。

原来是这样。明白了~感谢解惑！
