### ISSUE TITLE
求指教如何正确的自定义字符集，和切换字符集呢？

### ISSUE THREAD

**Issue by iDvel** [rime/squirrel#521]
我现在是，比如我有两个 `xxx.dict.yaml` 文件，一个是只保留了 3500 常用字，另一个是 pinyin_simp 一万多字的正常词库。
我只在很少的情况会切换到那个一万多字的版本，但我都是重新部署来切换的，挺费劲的。

Squirrel 0.15.0，我应该用什么适当的办法去解决这个问题呢？可以做到类似切换简繁、切换全半角那样的。

**Comment by lotem** [comment]
​做兩個輸入方案，加載不同詞庫。切換輸入方案。

**Comment by iDvel** [comment]
嘿嘿搞定啦谢谢，这样也不错
