### ISSUE TITLE
候选框随候选自动伸长到屏幕边缘后，回删时不再根据候选自动缩短

### ISSUE THREAD

**Issue by amorphobia** [rime/squirrel#523]
鼠须管版本：0.15.0
macOS 版本：Big Sur (11.2) 与 Catalina (10.15.7)

请看录屏，拼音输入 `shiyong`，候选词长度较长，于是候选框自动伸长，到达屏幕边缘后有一个向左伸长的动作；随后删除输入，正常情况下，候选框应随之缩短以适配候选的长度，但这种情况下并没有。

![屏幕录制](https://user-images.githubusercontent.com/523025/107459455-30515a80-6b91-11eb-957f-37f61603561d.gif)

**Comment by amorphobia** [comment]
抱歉录屏不是太清晰，但亦可看出问题。

**Comment by lotem** [comment]
​沒有問題。是這樣設計的。

**Comment by amorphobia** [comment]
不好意思，可能是我没表达清楚，我想说的是像图里的这种情况：

<img width="960" alt="截屏2021-02-10 17 03 59" src="https://user-images.githubusercontent.com/523025/107488444-52170580-6bc2-11eb-89c5-47153ae26ced.png">

可以看到候选框比候选词长了很多，留下很大的空白。但正常情况下，候选框的长度应该是跟候选词相匹配的，如下图：

<img width="960" alt="截屏2021-02-10 17 17 38" src="https://user-images.githubusercontent.com/523025/107489918-29900b00-6bc4-11eb-9e2e-e6c9c2bcc63e.png">

当输入相同的时候，候选框的长度相同，从用户的角度来看，这应该是期望的行为；假如目前不再自动缩短的行为是为了提示用户，已经碰到屏幕边缘了，也是可以接受的，但多多少少会引起用户的一些疑惑。

**Comment by LEOYoon-Tsaw** [comment]
主要是為了第一候選的位置不跳來跳去。

**Comment by amorphobia** [comment]
感谢两位解答，我明白为什么这样设计了。

> 長時間停頓後更新一次界面作爲優化手段

我认为同样会引起用户的疑惑：为何候选框的长度匹配会有延迟。与其用新的疑惑替代旧的疑惑，不如保持现状。

再次感谢。

**Comment by LEOYoon-Tsaw** [comment]
加一個配置項供用戶自己選擇需不需要這個行為就行了
