### ISSUE TITLE
0.15.0版候選文字置中

### ISSUE THREAD

**Issue by Ponpon55837** [rime/squirrel#525]
在鼠鬚管0.15.0版本
候選框中的文字上下沒有置中
<img width="490" alt="截圖 2021-02-10 下午5 01 21" src="https://user-images.githubusercontent.com/32410486/107488113-e2a11600-6bc1-11eb-8724-bf26b96574ae.png">
最後一項候選文字尤其明顯
<img width="314" alt="截圖 2021-02-10 下午5 01 24" src="https://user-images.githubusercontent.com/32410486/107488122-e5037000-6bc1-11eb-995c-cbcea4769a87.png">

我嘗試調整style/line_spacing與style/spacing但是都無法達成

在0.14.0版本中好像沒有發生這個問題
請問應該設定哪一項參數呢

**Comment by LEOYoon-Tsaw** [comment]
用style/offset調。最後一項下面有margin，不可能置中

**Comment by lotem** [comment]
> 用style/offset調。最後一項下面有margin，不可能置中

`style/base_offset`

**Comment by Ponpon55837** [comment]
感謝兩位 調整成功了
