### ISSUE TITLE
“著”字打不出

### ISSUE THREAD

**Issue by c3110** [rime/squirrel#527]
全拼打字zhu的著字，输入字的排序3，打进来最后是在“注”“住”和“主”中来回，mac系统10.14.4，squirrel版本0.15.1。
![WechatIMG44](https://user-images.githubusercontent.com/37265986/107780710-01e6a180-6d82-11eb-86e0-f66fe300d963.jpeg)

**Comment by LEOYoon-Tsaw** [comment]
同 #513 否？

**Comment by lotem** [comment]
​看上去像是這個問題 https://github.com/rime/squirrel/issues/513

**Comment by c3110** [comment]
> ​看上去像是這個問題 #513
是的很像，他的问题我操作了也可以复现。

也是用了squirrel.custom.yaml 这个搞定了。
