### ISSUE TITLE
Visual Studio Code无法输入文字，没有输入框，只能打字母。

### ISSUE THREAD

**Issue by rufei365** [rime/squirrel#530]
问题如题
版本如下：
系统mac os 11.1
鼠须管0.15.1
Visual Studio Code 1.53.2

**Comment by Jreen** [comment]
我可以输入文字，我刚还在Visual Studio Code里打字来着，和你一样的版本号

**Comment by rufei365** [comment]
> 我可以输入文字，我刚打字了Visual Studio Code，版本号一样

恩，是我的操作问题，问题已关闭。
