### ISSUE TITLE
如何避免「爲」字？（0.15.1）

### ISSUE THREAD

**Issue by ballII** [rime/squirrel#532]
我是台灣繁體字使用者，一律用「為」字，而不用「爲」字。但從0.14更新到0.15後，許多字詞都將「爲」擺為第一選項，一一選字調教實在太費勁了，造成我不小的困擾。

請問我可以修改哪個檔案來避免含「爲」的詞彙出現在選單第一頁？謝謝。

**Comment by lotem** [comment]
在方案選單裏選擇「臺灣字形」或切換方案爲「注音·臺灣正體」。

**Comment by ballII** [comment]
我是用洋蔥版注音：
https://deltazone.pixnet.net/blog/post/360218175
因為已經習慣洋蔥版，所以參照其說明後，我選擇退回0.14，並將 /Library/Input Methods/Squirrel.app/Contents/Info.plist 中唯一的 <string>zh</string> 改成 <string>zh-Hant</string>。

以後有空再研究一下0.15。
