### ISSUE TITLE
- charset_filter@gb2312  好像失效了

### ISSUE THREAD

**Issue by Dreamer57** [rime/squirrel#537]
- charset_filter@gb2312  
好像失效了，从windows里拷过来的配置，折腾了好久一直没效果

**Comment by lotem** [comment]
​不支持的。

**Comment by Dreamer57** [comment]
> ​不支持的。

那应该怎么办，我是刚从windows转过来的，词库已经用习惯了，现在多了很多生僻字，很不习惯。

**Comment by Dreamer57** [comment]
> ​不支持的。

大佬有办法吗，能支个招吗

**Comment by LEOYoon-Tsaw** [comment]
直接改字典是最好的

**Comment by Dreamer57** [comment]
> 直接改字典是最好的

你是说改词库吗，我用的是五笔词库，里面的生僻字还挺多的。
而且我最想要的效果是，设置一个生僻字模式，只打生僻字，而并不想完全删除。

**Comment by LEOYoon-Tsaw** [comment]
那就做兩個字典？分兩個方案用

**Comment by lotem** [comment]
​不支持`gb2312`等具名的字符集。
