### ISSUE TITLE
闲着没事，对比了下几个输入法输入歌词，最惊喜的居然是...

### ISSUE THREAD

**Issue by ililu2000** [rime/squirrel#538]
首先是搜狗（断网测试）
<img width="993" alt="屏幕快照 2021-02-17 下午8 59 56" src="https://user-images.githubusercontent.com/78154435/108207860-42b82f00-7163-11eb-82d6-958df18b0150.png">
<img width="631" alt="截屏2021-02-17 下午8 47 02" src="https://user-images.githubusercontent.com/78154435/108207936-5b284980-7163-11eb-8578-c669438a3b8f.png">
第一句还行，这第二句就。。。

第二个是 rime
<img width="696" alt="截屏2021-02-17 下午8 43 46" src="https://user-images.githubusercontent.com/78154435/108208056-8317ad00-7163-11eb-8928-cda785900489.png">
<img width="696" alt="截屏2021-02-17 下午8 44 41" src="https://user-images.githubusercontent.com/78154435/108208088-89a62480-7163-11eb-9b11-771a3ca975a5.png">

然后试了下 Mac 自带的输入法
<img width="452" alt="截屏2021-02-17 下午8 36 27" src="https://user-images.githubusercontent.com/78154435/108208196-ae020100-7163-11eb-8d4f-16b64e87e4ff.png">
<img width="452" alt="截屏2021-02-17 下午8 37 14" src="https://user-images.githubusercontent.com/78154435/108208215-b2c6b500-7163-11eb-85eb-4e45fa0463fb.png">
出乎意料，居然是表现最好的

最后试了下 Google 在线输入法
差强人意。。。
<img width="565" alt="截屏2021-02-17 下午8 49 00" src="https://user-images.githubusercontent.com/78154435/108208579-2c5ea300-7164-11eb-96d9-5c83765e0d53.png">
<img width="595" alt="截屏2021-02-17 下午8 51 31" src="https://user-images.githubusercontent.com/78154435/108208590-2ff22a00-7164-11eb-9ce2-d4bc90a33c76.png">

**Comment by Prcuvu** [comment]
建议重新发布到 [Discussions 板块](https://github.com/rime/home/discussions)。

**Comment by lotem** [comment]
​噫，帖子咋沒影了。
