### ISSUE TITLE
states 切换如何保持？

### ISSUE THREAD

**Issue by moriwang** [rime/squirrel#539]
最近开始用鼠须管，非常棒的一款输入法，但 states 切换的问题一直困扰着我。

比如我想要切换成英文，使用方案选单或是快捷键切换之后可以生效。但换一个 App 输入就回到中文，需要再切换一次。
尤其是用 Powerpoint 的表格功能，每次光标移动就需要切换，基本是不可用的状态。

请问如何保持住 states ？不止中英，简繁保持也是刚需。

**Comment by lotem** [comment]
​現在是爲每個到輸入法的連接單獨維護一份狀態。
每個連接的初始狀態是中文。
簡繁等選項如果從方案選單切換，會記錄爲後續輸入法連接的初始狀態。但不影響已建立連接的應用程序。

問題同 https://github.com/rime/squirrel/issues/145
