### ISSUE TITLE
Squirrel Mac OSX Big Sur Err

### ISSUE THREAD

**Issue by gshmu** [rime/squirrel#542]
install 0.15.2 from pkg, then run `curl -fsSL https://git.io/rime-install | bash -s -- :preset`

boost::filesystem::status: Permission denied: "/Library/Input Methods/Squirrel.app/Contents/SharedSupport/build/squirrel.yaml"
[two full err log file](https://github.com/rime/squirrel/files/6021958/Archive.zip)

I found the build `/Library/Input Methods/Squirrel.app/Contents/SharedSupport/build/` dir permission err, no read permission for group user and still not `squirrel.yaml`, but fixed this still err.

And I try install old version, still not work...

**Comment by lotem** [comment]
I've no idea what specifically has happened to you.
As a reference, files under `/Library/Input Methods/Squirrel.app` should have permission `-rw-r--r--` and directories `drwxr-xr-x`; that means readable to everyone.

**Comment by gshmu** [comment]
这个dir`/Library/Input Methods/Squirrel.app/Contents/SharedSupport/build/`确实只有root的rx权限，我修复权限后依旧报错。

我之前一直用Squirrel都是ok的，随着系统升级后依旧OK，但最近这次升级后就出问题了，体现在无法输入或这只能输入英文字母。然后我尝试卸载重装都无法正常使用，期间电脑多次出现在登入登出时语音警告。

我想确认下在Big Sur下全新安装是OK的吗？（没有plum，也没有～/Library/Rime的情况下）

**Comment by gshmu** [comment]
补充一下，我现在降级到之前的版本也是报错，无法使用。  完全卸载使用的是AppClearner，且手动删除～/Library/Rime及plum。

**Comment by lotem** [comment]
沒有其他用戶反饋類似問題。
正常安裝後目錄和文件的權限如 https://github.com/rime/squirrel/issues/542#issuecomment-784265827 所示。

**Comment by gshmu** [comment]
原因找到了，umask导致的锅！！！

某一天突然发现Guest居然可以读我的目录，然后怒改了umask 037，然后导致引发血案！！！  感谢
