### ISSUE TITLE
0.15.2版本UI问题：绘制Emoji及符号时文本框的高度不一致

### ISSUE THREAD

**Issue by ssnhd** [rime/squirrel#543]
身为一位不懂代码的美术从业人员，内在美要，外在美更要😃

0.15.2的UI远远不止年前那位朋友提到的Emoji问题，其他符号候选词条高低差距更离谱。

同配置在0.14.0和0.15.2之间比较，候选词纯汉字的情况下，0.15.2在高度和长度都要大于0.14.0
![](https://i.loli.net/2021/02/23/omUHuMILftq5dC6.png)
ps. 可以在新标签页查看大图

**Comment by LEOYoon-Tsaw** [comment]
就是這樣

**Comment by lotem** [comment]
​留待以後優化吧。
Emoji 也是臨時救急的解法。

發散一下，估計得改成按照漢字算出固定的行高，再根據固定行高調整文字的基線位置。
說不定能連帶免去直書文字需要手動調整基線的麻煩。

**Comment by LEOYoon-Tsaw** [comment]
我發了個工單問Apple，也許他們有什麼辦法
