### ISSUE TITLE
按照 "INSTALL.md" 尝试编译 squirrel，执行到 make deps 这一步时提示以下内容 不会编程，所以看不懂，希望有大佬帮我看看怎么回事

### ISSUE THREAD

**Issue by Dreamer57** [rime/squirrel#544]
按照 "INSTALL.md" 尝试编译 squirrel，执行到 make deps 这一步时提示以下内容
不会编程，所以看不懂，希望有大佬帮我看看怎么回事

`MacBook-Air squirrel % make deps
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C librime xcode/dist
make -f xcode.mk dist
cmake . -Bbuild -GXcode \
	-DBUILD_STATIC=ON \
	-DCMAKE_BUILD_WITH_INSTALL_RPATH=ON \
	-DCMAKE_INSTALL_PREFIX="/Users/yinrui/Documents/github/squirrel/librime/dist" \
	
-- Found glog: /Users/yinrui/Documents/github/squirrel/librime/thirdparty/lib/libglog.a
-- Found yaml-cpp: /Users/yinrui/Documents/github/squirrel/librime/thirdparty/lib/libyaml-cpp.a
-- Found leveldb: /Users/yinrui/Documents/github/squirrel/librime/thirdparty/lib/libleveldb.a
-- Found marisa: /Users/yinrui/Documents/github/squirrel/librime/thirdparty/lib/libmarisa.a
-- Found opencc: /Users/yinrui/Documents/github/squirrel/librime/thirdparty/lib/libopencc.a
-- Found X11/keysym.h at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Tk.framework/Headers
-- compiled capnproto schemata (sources): /Users/yinrui/Documents/github/squirrel/librime/build/proto//rime_proto.capnp.c++
-- compiled capnproto schemata (headers): /Users/yinrui/Documents/github/squirrel/librime/build/proto//rime_proto.capnp.h
-- Found plugin: /Users/yinrui/Documents/github/squirrel/librime/plugins/charcode
-- Found the following ICU libraries:
--   uc (required)
CMake Error at /opt/homebrew/Cellar/cmake/3.19.6/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find Boost (missing: locale) (found suitable version "1.75.0",
  minimum required is "1.46.0")
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.19.6/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.19.6/share/cmake/Modules/FindBoost.cmake:2208 (find_package_handle_standard_args)
  plugins/charcode/CMakeLists.txt:15 (find_package)

-- Configuring incomplete, errors occurred!
See also "/Users/yinrui/Documents/github/squirrel/librime/build/CMakeFiles/CMakeOutput.log".
make[2]: *** [release] Error 1
make[1]: *** [xcode/dist] Error 2
make: *** [librime] Error 2`

**Comment by LEOYoon-Tsaw** [comment]
沒有boost

**Comment by Dreamer57** [comment]
> 沒有boost

我通过 brew install boost 这样安装过一次，不知道是不是没装好，现在该怎么办呢

**Comment by lotem** [comment]
如果要用`librime-charcode`，必須先讀
https://github.com/rime/librime/blob/master/README-mac.md#install-boost-c-libraries

**Comment by Dreamer57** [comment]
> 如果要用`librime-charcode`，必須先讀
> https://github.com/rime/librime/blob/master/README-mac.md#install-boost-c-libraries

这个我看不太懂，但是照着步骤做过，麻烦你看下我哪一步出了问题。
到了 “Install Boost C++ libraries” 这一步的时候，我选的是 ”Option 2: Install Boost libraries from Homebrew.“。
”Build third-party libraries“ 这一步是成功执行没有报错的。
然后到 ”Build librime" 这一步的时候，我把上面那段 xcode/release-with-icu 拷下来了，执行的是 make xcode/release-with-icu，然后就出现和上面一样的问题。
是不是只能照着这一步 ”Option 3: Install an older version of Boost libraries from Homebrew.“，然后
brew install boost@1.60
brew link --force boost@1.60
安装这个boost@1.60？

我表达的有点凌乱，因为我不懂编程，只能按步骤操作，然后说出什么操作遇到什么问题。

**Comment by LEOYoon-Tsaw** [comment]
自己編譯boost是最保險的

**Comment by Dreamer57** [comment]
> 自己編譯boost是最保險的

自己编译是指这一步吗：“Option 1 (recommended): Download and build Boost from source.“
在执行了
cd librime
make xcode/thirdparty/boost
和 export BOOST_ROOT="$(pwd)/thirdparty/src/boost_1_75_0"
后 ”Build librime“
make xcode
或
xcode/release-with-icu 
的结果都和上面是一样的

**Comment by Dreamer57** [comment]
有没有哪位大锅能看出是什么问题的 @LEOYoon-Tsaw  @lotem

**Comment by Dreamer57** [comment]
@robinwong @Domon

**Comment by lotem** [comment]
問題在於源碼目錄裏加入了一份squirrel不支持的插件代碼——`librime-charcode`這個插件。
不使用該插件，Boost用哪個選項安裝都可以。
如果一定要編譯這個插件，須手動做出 `librime.1.dylib`，而不能用squirrel的`make deps`命令，具體做法又取決於怎樣安裝ICU庫和Boost庫。

**Comment by Dreamer57** [comment]
> 問題在於源碼目錄裏加入了一份squirrel不支持的插件代碼——`librime-charcode`這個插件。
> 不使用該插件，Boost用哪個選項安裝都可以。
> 如果一定要編譯這個插件，須手動做出 `librime.1.dylib`，而不能用squirrel的`make deps`命令，具體做法又取決於怎樣安裝ICU庫和Boost庫。


我是用 'brew install boost' 安装的 Boost ，在安装 Boost 的时候，好像也顺带把 ICU4C 安装好了，这个 ICU4C 是不是你指的 ICU 库。

我在输入 'brew info boost' 时显示

yinrui@yinruideMacBook-Air librime % brew info boost
boost: stable 1.75.0 (bottled), HEAD
Collection of portable C++ source libraries
https://www.boost.org/
/opt/homebrew/Cellar/boost/1.75.0_1 (15,058 files, 517.4MB) *
  Poured from bottle on 2021-02-26 at 03:21:42
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/boost.rb
License: BSL-1.0
==> Dependencies
Required: icu4c ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 46,811 (30 days), 177,452 (90 days), 655,316 (365 days)
install-on-request: 15,359 (30 days), 59,093 (90 days), 221,033 (365 days)
build-error: 0 (30 days)

输入 'brew info icu4c' 时显示

yinrui@yinruideMacBook-Air librime % brew info icu4c
icu4c: stable 67.1 (bottled) [keg-only]
C/C++ and Java libraries for Unicode and globalization
http://site.icu-project.org/home
/opt/homebrew/Cellar/icu4c/67.1 (258 files, 72.4MB)
  Poured from bottle on 2021-02-26 at 03:21:31
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/icu4c.rb
License: ICU
==> Caveats
icu4c is keg-only, which means it was not symlinked into /opt/homebrew,
because macOS provides libicucore.dylib (but nothing else).

If you need to have icu4c first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/icu4c/bin:$PATH"' >> ~/.zshrc
  echo 'export PATH="/opt/homebrew/opt/icu4c/sbin:$PATH"' >> ~/.zshrc

For compilers to find icu4c you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/icu4c/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/icu4c/include"

==> Analytics
install: 278,656 (30 days), 894,685 (90 days), 4,579,346 (365 days)
install-on-request: 5,439 (30 days), 17,785 (90 days), 130,060 (365 days)
build-error: 0 (30 days)


但是并不能直接输入命令 'icu4c' 或 'boost'

yinrui@yinruideMacBook-Air librime % icu4c
zsh: command not found: icu4c
yinrui@yinruideMacBook-Air librime % boost
zsh: command not found: boost

这样算不算安装好了 Boost 库和 ICU 库，下一步又该怎么操作 
@lotem

**Comment by lotem** [comment]
`make xcode/release-with-icu` 做出 `librime.1.dylib`

**Comment by Dreamer57** [comment]
> `make xcode/release-with-icu`

我在librime目录下执行这个就又会这样

-- Found the following ICU libraries:
--   uc (required)
CMake Error at /opt/homebrew/Cellar/cmake/3.19.6/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find Boost (missing: locale) (found suitable version "1.75.0",
  minimum required is "1.46.0")
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.19.6/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.19.6/share/cmake/Modules/FindBoost.cmake:2208 (find_package_handle_standard_args)
  plugins/charcode/CMakeLists.txt:15 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/yinrui/documents/github/squirrel/librime/build/CMakeFiles/CMakeOutput.log".
make[1]: *** [release-with-icu] Error 1
make: *** [xcode/release-with-icu] Error 2
yinrui@yinruideMacBook-Air librime % pwd
/Users/yinrui/documents/github/squirrel/librime

**Comment by Dreamer57** [comment]
@lotem

**Comment by Dreamer57** [comment]
明明装了，但好像找不到，是不是我还漏了什么，但是我又查不到资料

**Comment by Dreamer57** [comment]
还有我的 xcode 也是新装的 没打开过

**Comment by Dreamer57** [comment]
yinrui@yinruideMacBook-Air librime % make xcode/release-with-icu
make -f xcode.mk release-with-icu
cmake . -Bbuild -GXcode \
	-DBUILD_STATIC=ON \
	-DBUILD_WITH_ICU=ON \
	-DCMAKE_BUILD_WITH_INSTALL_RPATH=ON \
	-DCMAKE_INSTALL_PREFIX="/Users/yinrui/Documents/github/squirrel/librime/dist" \
	-DCMAKE_PREFIX_PATH="/opt/homebrew/opt/icu4c" \
	
-- Found glog: /Users/yinrui/Documents/github/squirrel/librime/thirdparty/lib/libglog.a
-- Found yaml-cpp: /Users/yinrui/Documents/github/squirrel/librime/thirdparty/lib/libyaml-cpp.a
-- Found leveldb: /Users/yinrui/Documents/github/squirrel/librime/thirdparty/lib/libleveldb.a
-- Found marisa: /Users/yinrui/Documents/github/squirrel/librime/thirdparty/lib/libmarisa.a
-- Found opencc: /Users/yinrui/Documents/github/squirrel/librime/thirdparty/lib/libopencc.a
-- Found X11/keysym.h at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/Tk.framework/Headers
-- compiled capnproto schemata (sources): /Users/yinrui/documents/github/squirrel/librime/build/proto//rime_proto.capnp.c++
-- compiled capnproto schemata (headers): /Users/yinrui/documents/github/squirrel/librime/build/proto//rime_proto.capnp.h
-- Found plugin: /Users/yinrui/documents/github/squirrel/librime/plugins/charcode
-- Found the following ICU libraries:
--   uc (required)
CMake Error at /opt/homebrew/Cellar/cmake/3.19.6/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find Boost (missing: locale) (found suitable version "1.75.0",
  minimum required is "1.46.0")
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.19.6/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.19.6/share/cmake/Modules/FindBoost.cmake:2208 (find_package_handle_standard_args)
  plugins/charcode/CMakeLists.txt:15 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/yinrui/documents/github/squirrel/librime/build/CMakeFiles/CMakeOutput.log".
make[1]: *** [release-with-icu] Error 1
make: *** [xcode/release-with-icu] Error 2

**Comment by Dreamer57** [comment]
@lotem 大锅你再来看看吧，我感觉我就要成功了。


事情是这样的，我把 brewhome 卸载了，重新安装了一遍，然后又把从 git 上下载的代码都删除了，重新又弄了一遍。

然后这次可以找到 icu 库了，也不会再报错说找不到 locale 了。

编译信息也一行一行的打印出来了。

但是你应该也已经想到了，事情如果真的这么顺利，我也不会再来找你。

是的，就在我暗自窃喜之时，新的问题，出现了。

……

当时我正在 librime 目录，下载了 charcode ，执行完 'make xcode/thirdparty' ，执行了很久，但没有报错，一切都很正常。

然后我又执行了 'make xcode/release-with-icu' 。

也非常正常，以前出现过的问题并没有再次出现。

但是等了一会后，问题出现了。

Ld /Users/yinrui/documents/github/squirrel/librime/build/lib/Release/librime.1.7.3.dylib normal (in target 'rime' from project 'rime')
    cd /Users/yinrui/Documents/github/squirrel/librime
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target arm64-apple-macos10.9 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -L/Users/yinrui/documents/github/squirrel/librime/build/lib/Release -L/opt/homebrew/lib/Release -L/opt/homebrew/lib -L/Users/yinrui/documents/github/squirrel/librime/thirdparty/lib/Release -L/Users/yinrui/documents/github/squirrel/librime/thirdparty/lib -F/Users/yinrui/documents/github/squirrel/librime/build/lib/Release -filelist /Users/yinrui/documents/github/squirrel/librime/build/src/rime.build/Release/rime.build/Objects-normal/arm64/rime.1.7.3.LinkFileList -install_name /librime.1.7.3.dylib -dynamiclib -Wl,-headerpad_max_install_names -install_name @rpath/librime.1.dylib /Users/yinrui/documents/github/squirrel/librime/build/proto/rime.build/Release/rime-proto-objs.build/Objects-normal/arm64/rime_proto.capnp.o /opt/homebrew/lib/libboost_filesystem-mt.a /opt/homebrew/lib/libboost_regex-mt.a /opt/homebrew/lib/libboost_system-mt.a /Users/yinrui/documents/github/squirrel/librime/thirdparty/lib/libcapnp.a /Users/yinrui/documents/github/squirrel/librime/thirdparty/lib/libglog.a /Users/yinrui/documents/github/squirrel/librime/thirdparty/lib/libyaml-cpp.a /Users/yinrui/documents/github/squirrel/librime/thirdparty/lib/libleveldb.a /Users/yinrui/documents/github/squirrel/librime/thirdparty/lib/libmarisa.a /Users/yinrui/documents/github/squirrel/librime/thirdparty/lib/libopencc.a -licudata -licui18n -licuuc /Users/yinrui/documents/github/squirrel/librime/thirdparty/lib/libkj.a -lpthread -Xlinker -no_adhoc_codesign -compatibility_version 1.0.0 -current_version 1.7.3 -Xlinker -dependency_info -Xlinker /Users/yinrui/documents/github/squirrel/librime/build/src/rime.build/Release/rime.build/Objects-normal/arm64/rime.1.7.3_dependency_info.dat -o /Users/yinrui/documents/github/squirrel/librime/build/lib/Release/librime.1.7.3.dylib
ld: warning: directory not found for option '-L/opt/homebrew/lib/Release'
ld: warning: directory not found for option '-L/Users/yinrui/documents/github/squirrel/librime/thirdparty/lib/Release'
ld: library not found for -licudata
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld /Users/yinrui/documents/github/squirrel/librime/build/lib/Release/librime.1.7.3.dylib normal
(1 failure)
make[1]: *** [release-with-icu] Error 65
make: *** [xcode/release-with-icu] Error 2





这是最后一行输出，我想可能就是这里报错的。

然后我又重新找了一个目录，只单独下载了 librime  并且没有加入 charcode ，按照文档执行。

到最后一步 ‘make xcode’

等了一会后，问题还是出现了。





WriteAuxiliaryFile /Users/yinrui/documents/github/librime/build/src/rime.build/Release/rime.build/Objects-normal/arm64/rime.1.7.3.LinkFileList (in target 'rime' from project 'rime')
    cd /Users/yinrui/Documents/github/librime
    write-file /Users/yinrui/documents/github/librime/build/src/rime.build/Release/rime.build/Objects-normal/arm64/rime.1.7.3.LinkFileList

Ld /Users/yinrui/documents/github/librime/build/lib/Release/librime.1.7.3.dylib normal (in target 'rime' from project 'rime')
    cd /Users/yinrui/Documents/github/librime
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target arm64-apple-macos10.9 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -L/Users/yinrui/documents/github/librime/build/lib/Release -L/opt/homebrew/lib/Release -L/opt/homebrew/lib -L/Users/yinrui/documents/github/librime/thirdparty/lib/Release -L/Users/yinrui/documents/github/librime/thirdparty/lib -F/Users/yinrui/documents/github/librime/build/lib/Release -filelist /Users/yinrui/documents/github/librime/build/src/rime.build/Release/rime.build/Objects-normal/arm64/rime.1.7.3.LinkFileList -install_name /librime.1.7.3.dylib -dynamiclib -Wl,-headerpad_max_install_names -install_name @rpath/librime.1.dylib /Users/yinrui/documents/github/librime/build/proto/rime.build/Release/rime-proto-objs.build/Objects-normal/arm64/rime_proto.capnp.o /Users/yinrui/documents/github/librime/build/plugins/rime.build/Release/rime-plugins-objs.build/Objects-normal/arm64/plugins_module.o /opt/homebrew/lib/libboost_filesystem-mt.a /opt/homebrew/lib/libboost_regex-mt.a /opt/homebrew/lib/libboost_system-mt.a /Users/yinrui/documents/github/librime/thirdparty/lib/libcapnp.a /Users/yinrui/documents/github/librime/thirdparty/lib/libglog.a /Users/yinrui/documents/github/librime/thirdparty/lib/libyaml-cpp.a -ldl /Users/yinrui/documents/github/librime/thirdparty/lib/libleveldb.a /Users/yinrui/documents/github/librime/thirdparty/lib/libmarisa.a /Users/yinrui/documents/github/librime/thirdparty/lib/libopencc.a -licudata -licui18n -licuuc /Users/yinrui/documents/github/librime/thirdparty/lib/libkj.a -lpthread -Xlinker -no_adhoc_codesign -compatibility_version 1.0.0 -current_version 1.7.3 -Xlinker -dependency_info -Xlinker /Users/yinrui/documents/github/librime/build/src/rime.build/Release/rime.build/Objects-normal/arm64/rime.1.7.3_dependency_info.dat -o /Users/yinrui/documents/github/librime/build/lib/Release/librime.1.7.3.dylib
ld: warning: directory not found for option '-L/opt/homebrew/lib/Release'
ld: warning: directory not found for option '-L/Users/yinrui/documents/github/librime/thirdparty/lib/Release'
ld: library not found for -licudata
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **


The following build commands failed:
	Ld /Users/yinrui/documents/github/librime/build/lib/Release/librime.1.7.3.dylib normal
(1 failure)
make[1]: *** [release] Error 65
make: *** [xcode] Error 2





这也是最后两行，全部的输出太长了。



大哥再来看看吧，感觉马上就能成功了。

**Comment by Dreamer57** [comment]
唉，该怎么说呢，这个故事。

该从何说起呢。

那就从最开始说起吧。

本来他已经失败过很多次了，照理说再进行任何尝试都是不理智的。

但是他又想起了儿时学骑自行车时的场景，那是一段有很多遗憾的时光。

说起遗憾，这又何尝不是一个遗憾呢。

可是他的人生已经充满了遗憾，他不想再多留一份遗憾了。

他想再试试，不留遗憾。

想到这里，他又再次删掉之前的代码，从 git 上重新下载新的代码。

执行了已经执行过很多次的命令，熟练，且精准。

他的心情很沉重。通过以往的经验，他已经能够预料到这次尝试的结果，不会出现任何意外：失败。

他时常问起自己，明明知道注定会失败的事，为什么还要去尝试呢。

你有病吗？

“咚咚咚咚”

手指敲击键盘的声音是如此的微弱，但此刻在这个空旷的房间里响起时，却是有了无法想象的重量。

“咚咚咚咚”

他眼神茫然的看着屏幕。上面一行行黑白的编译信息快速的滚动着。

他自己也不知道他到底在坚持着什么，但他就是不肯死心。

为什么会不死心呢。

又有什么好期待的呢。

“咚……咚……咚……咚……”

他一下一下的按击键盘，艰难的输入一段指令，从未感受过如此的难以用力。

'make xcode/release-with-icu‘

他看着屏幕上的这段指令，眼神逐渐放空。

为什么会不死心呢。

可能是眼红别人的成功吧，为什么偏偏别人可以，他却不行呢，为什么。

他按下了回车。

眼睛里映照出一行行快速滚动的黑白单词。

不知为什么，在他的感知里时间流逝得异常缓慢，他渐渐的分了神，想起了那个午后。

那个是一个有阳光的午后，不够强烈，但足够温暖的阳光。

她站在那里，任由稀稀疏疏的阳光穿过树叶，倾洒在她的脸庞。

他看得呆住了。

这是一个美好的故事。

也是一个悲伤的故事。

** BUILD FAILED **

黑白窗口上的滚动停止了，也把他拉回了现实。

他茫然的看着电脑屏幕，一句话也不想说，动也不动一下。

漆黑的房间里，所有的声音都消失了。

他就这样坐在电脑前，不知过了多久，屏幕也熄灭了。

房间里的一切似乎都凝固了。

……

但这种寂静终会被打破，生活还得继续。

他唤醒了电脑屏幕。

按下了键盘。

⬆️

'make xcode/release-with-icu'

回车

黑白单词滚动，又停止。

** BUILD FAILED **

他把手指再次移向了键盘。

⬆️

'make xcode/release-with-icu'

回车

他麻木的一次又一次的重复着这个操作。

电脑屏幕一次又一次的飞快滚动。

他不甘心。

他迷失在过去的回忆里。

迷失在一次次不知所措里。

可怕的不是失败，可怕的是他不知道自己的路。

他的手指一次次在方向键和回车键上来回移动，麻木，颤抖。

或许他真的病得不轻吧。

……

** BUILD SUCCEEDED **

突然出现在屏幕上的一段文字，让他懵了一会儿，好一会儿。

他回过神来，揉了揉眼睛，反复确认了不是因为精神恍惚而眼花。

他从不可思议，难以置信。

渐渐到迷茫不解。

再到坦然接受。

他意识到了自己的渺小无助，和世界的伟大神奇。

同时他的眼神也更加坚定了，他明白了坚持的份量，明白了努力的意义。

“不放弃就不会失败！”

他激动的吼了出来，声若雷鸣，气如山洪。

“失败乃成功之母！”

过往的一切都在此刻被赋予了无比沉重的意义。

”所有的失败，都是为了更好的成功！“

他无比感动，金句不断，仿佛发现了隐藏的人生密码。

他想到了两个矿工的故事。其中一个矿工，在还有一锄头就能挖到金矿的时候放弃了；而另一个矿工坚持到了最后，成功挖到宝藏。

他想他找到自己的路了，找到自己人生的意义了，不放弃就不会失败。

他要做那个成功的矿工。

很多时候，在自己迷茫的时候，不知道人生意义的时候，你只需要再坚持一下，再多试一次，那一次将是改变你命运的那一次。

这，就是通向成功的关键。

听到这里，我已经感动得流下了泪水。

这，就是他和她，还有它的故事。

**Comment by alswl** [comment]
Build steps:

- https://github.com/alswl/librime/blob/cfd8ef961ca750fb57cc7f477486ff9b7e842f16/README-alswl.md
- https://github.com/alswl/squirrel/blob/release-0.15.2-patched/README-alswl.md

**Comment by lotem** [comment]
不敢想象
如果沒有插件機制
各平臺千奇百怪的限制下
誰還敢用百家程序庫跨平臺編程
纔知技術力是多麼地渺小
多麼地無能
