### ISSUE TITLE
如何使用百度百科或者搜狗百科的词条作为词库

### ISSUE THREAD

**Issue by ililu2000** [rime/squirrel#546]
用了中文维基百科的词库，解决了大部分词的覆盖
但是有些网络流行词，还得是百度百科或者搜狗百科收录的全。
有没有大神可以做一个类似的词库

**Comment by ililu2000** [comment]
顺便说下 最近发现一个卡饭输入法，好像就是拿rime改的。
但是他的词库比rime自带的好很多啊，有谁能把词库扒一下😜

**Comment by lotem** [comment]
請參考 https://github.com/rime/home/wiki/RimeWithSchemata#%E7%A2%BC%E8%A1%A8%E8%88%87%E8%A9%9E%E5%85%B8
