### ISSUE TITLE
一直無法在用戶文件夾下配置Rime

### ISSUE THREAD

**Issue by Ngox-Tsjengh** [rime/squirrel#548]
之前在windows上一直用Rime，在 C:/Program File(x86)/Rime/Date 下加入自己的輸入法即可， 
最近使用M1 Mac(Big Sur 11.1 ~11.2.2) ，馬上也下了Squirrel， 查閱wiki後，按我的理解應該放在個人文件夾 ~/Library/Rime 下，之後deploy，但一直無法使用，Squirrel 不會讀取這個文件夾下的文件（但sync user data時會往這個文件夾裏同步文件）， 最後我改名替換根目錄下的 /Library/Input Method/....../Share Support下的預置輸入法，才用上了自己選的輸入法，但每次更新後就要再替換一次，請問這個問題如何解決？

<img width="913" alt="image" src="https://user-images.githubusercontent.com/61036442/110080680-c3169b00-7dc5-11eb-9905-2141d4f173f7.png">
~/Library/Rime，這裏加了沒用

<img width="929" alt="image" src="https://user-images.githubusercontent.com/61036442/110080830-01ac5580-7dc6-11eb-8466-17c0507b18f4.png">
/Library/Input Method/....../Share Support 替換了倉頡輸入法

**Comment by Ngox-Tsjengh** [comment]
放在/Library/Input Method/....../Share Support 下也無用，必須作替換才行，

**Comment by lotem** [comment]
倉頡五代、注音等方案是隨輸入法軟件發行和升級的。您不能替換這些文件。

​`SharedSupport`文件夾用來存放隨輸入法軟件發行的輸入方案文件，與軟件最新版本打包的數據內容一致。
用戶自己的方案應保存在用戶文件夾，且避免與預設的方案重名。

請參考：
https://github.com/rime/home/wiki/RimeWithSchemata#%E5%AE%9A%E8%A3%BD%E6%8C%87%E5%8D%97

請參考：
https://github.com/rime/home/wiki/RimeWithSchemata#rime-%E4%B8%AD%E7%9A%84%E6%95%B8%E6%93%9A%E6%96%87%E4%BB%B6%E5%88%86%E4%BD%88%E5%8F%8A%E4%BD%9C%E7%94%A8

**Comment by Ngox-Tsjengh** [comment]
> 倉頡五代、注音等方案是隨輸入法軟件發行和升級的。您不能替換這些文件。
> 
> ​`SharedSupport`文件夾用來存放隨輸入法軟件發行的輸入方案文件，與軟件最新版本打包的數據內容一致。
> 用戶自己的方案應保存在用戶文件夾，且避免與預設的方案重名。
> 
> 請參考：
> https://github.com/rime/home/wiki/RimeWithSchemata#%E5%AE%9A%E8%A3%BD%E6%8C%87%E5%8D%97
> 
> 請參考：
> https://github.com/rime/home/wiki/RimeWithSchemata#rime-%E4%B8%AD%E7%9A%84%E6%95%B8%E6%93%9A%E6%96%87%E4%BB%B6%E5%88%86%E4%BD%88%E5%8F%8A%E4%BD%9C%E7%94%A8

我當然知道`SharedSupport`不應當動，是迫不得已才去覆寫該文件夾下的文件的，問題的核心是Squirrel 不會讀用戶文件夾下的文件（但sync user data時會往這個文件夾裏同步文件），用了plum也不行（Plum也是往用戶文件夾加方案？）

**Comment by Ngox-Tsjengh** [comment]
Mac 上手後就用 homebrew 安裝了 squirrel, squirrel 0.14.0一路升級到 0.15.2, big sur從 11.1 一路升級到 11.2.1 這個問題也沒有消失， 所以就來提交了issue

**Comment by Ngox-Tsjengh** [comment]
我試了好久不行才來提交的

**Comment by Ngox-Tsjengh** [comment]
應該是我之前沒說清楚，我再整理下
Squirrel 不能讀取用戶文件夾下配置，
向'shared support' 下加入配置文件沒用，必須同名覆寫才有用
總之就是我的squirrel 處在一個只有覆寫 共享文件夾才能改配置的狀態，
我之前試了很多次，也重裝不少遍了，應改只剩從源碼編譯了

**Comment by LEOYoon-Tsaw** [comment]
无法復現

**Comment by Ngox-Tsjengh** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/61036442/110207541-1a4c6680-7ebf-11eb-92fd-2581259a4881.png">
用instrument 查了下deploy 時的文件系統活動，明明有讀取 用戶文件夾下的文件，但是就是不能新加方案，真是奇怪

**Comment by lotem** [comment]
無法復現問題。

讀取用戶文件夾的文件是可以工作的，這個功能經過了不間斷的測試，不需要考慮迂迴的解決方案。
從 #549 給出的文件系統訪問記錄看，也確實讀取了用戶自定義添加的方案。

請參考 https://github.com/rime/squirrel/issues/548#issuecomment-791223642 給出的信息瞭解Rime各種文件的用法和定製中的注意事項，
檢查[日誌](https://github.com/rime/home/wiki/RimeWithSchemata#%E9%97%9C%E6%96%BC%E8%AA%BF%E8%A9%A6)輸出，嘗試排查自定義配置的問題。

**Comment by Ngox-Tsjengh** [comment]
> 無法復現問題。
> 
> 讀取用戶文件夾的文件是可以工作的，這個功能經過了不間斷的測試，不需要考慮迂迴的解決方案。
> 從 #549 給出的文件系統訪問記錄看，也確實讀取了用戶自定義添加的方案。
> 
> 請參考 [#548 (comment)](https://github.com/rime/squirrel/issues/548#issuecomment-791223642) 給出的信息瞭解Rime各種文件的用法和定製中的注意事項，
> 檢查[日誌](https://github.com/rime/home/wiki/RimeWithSchemata#%E9%97%9C%E6%96%BC%E8%AA%BF%E8%A9%A6)輸出，嘗試排查自定義配置的問題。

這個我也懷疑過的，但剛開始的時候，我只往裏加方案文件，沒有改配置文件，是不行的；之後覆寫了方案文件，沒有覆寫配置文件，輸入法的配置沒有改變；現在才是既覆寫了方案文件，又覆寫了配置文件（只改了標點）。應該不是自定義配置的問題，
請問還有別的排查思路嗎

**Comment by lotem** [comment]
你只說這樣行，那樣不行，我能有什麼思路。猜不到。
