### ISSUE TITLE
Rime 讀取用戶配置文件無效

### ISSUE THREAD

**Issue by Ngox-Tsjengh** [rime/squirrel#549]
之前issue的地址：https://github.com/rime/squirrel/issues/548
應該是我之前沒說清楚，我再整理下
Squirrel 不能讀取用戶文件夾下方案和配置，也不能讀取共享文件夾下新增的方案和配置
向shared support 下加入方案文件沒用，必須同名覆寫才有用
總之就是一直以來，我這臺Mac（M1）上的squirrel 處在一個只有覆寫 共享文件夾才能增方案，改配置的狀態，
我之前試了很多次，也重裝不少遍了，沒起作用

<img width="1440" alt="Bildschirmfoto 2021-03-06 um 21 08 09" src="https://user-images.githubusercontent.com/61036442/110207703-3c92b400-7ec0-11eb-928f-ac377ce60032.png">
這是用instrument 查的Rime 在deploy 時的文件系統活動，明明有讀取 用戶文件夾下的文件，但是就是不能新加方案。。。。

**Comment by Ngox-Tsjengh** [comment]
trace 文件太大，不能直接上傳，已發到 google drive
https://drive.google.com/file/d/1Hx5sK1QNDxbUGGLq0fKhI31dZGbD9Vgf/view?usp=sharing

**Comment by lotem** [comment]
同 https://github.com/rime/squirrel/issues/548

**Comment by lotem** [comment]
`zyenpheng`不就是新加的方案嗎？
從上圖看已經編譯出`zyenpheng.table.bin`等文件了，這說明已經添加了中古拼音方案。

**Comment by Ngox-Tsjengh** [comment]
> `zyenpheng`不就是新加的方案嗎？
> 從上圖看已經編譯出`zyenpheng.table.bin`等文件了，這說明已經添加了中古拼音方案。

....這是對倉頡(cangjie5)，進行覆寫的效果，只有這樣才會出現新的輸入法（原來的自帶輸入法就被頂替了），在選單裏的名稱會變成原名稱，會編譯出新的`table.bin`等文件，這是我一直以來的唯一有用的添加(替換)新方案的辦法

**Comment by Ngox-Tsjengh** [comment]
以下圖爲例
<img width="779" alt="image" src="https://user-images.githubusercontent.com/61036442/110258826-7dcdb580-7fdf-11eb-90e9-bbd338cb4089.png">
共享文件夾中有 倉頡輸入法的編譯生成文件（覆寫前殘留，已被中古全拼頂替），雲龍ipa 輸入法文件
<img width="778" alt="Bildschirmfoto 2021-03-08 um 07 33 42" src="https://user-images.githubusercontent.com/61036442/110259061-b326d300-7fe0-11eb-8148-638d7eecc11a.png">
<img width="778" alt="Bildschirmfoto 2021-03-08 um 07 32 25" src="https://user-images.githubusercontent.com/61036442/110259038-925e7d80-7fe0-11eb-97f5-69b84eaa1f1d.png">
用戶文件夾裏有 多種輸入法，包括雲龍ipa，全拼（本來沒有，加了也沒用，是安plum時才有的）

但是deploy後的選單
<img width="212" alt="image" src="https://user-images.githubusercontent.com/61036442/110258719-fed87d00-7fde-11eb-92a2-d2f799929d03.png"> 
選單第一葉
<img width="190" alt="image" src="https://user-images.githubusercontent.com/61036442/110258730-0dbf2f80-7fdf-11eb-8a09-85e16c550afd.png">
選單第二葉

**Comment by lotem** [comment]
不需要向我介紹你的迂迴解決方案，除非您覺得這樣做已經很滿意了。
