### ISSUE TITLE
更新 0.15.2 后，中英切换方块行高异常。

### ISSUE THREAD

**Issue by jasonlam-swatow** [rime/squirrel#550]
![image](https://user-images.githubusercontent.com/8470477/111283461-1fa57000-867a-11eb-996b-060cfcaa9a68.png)
![image](https://user-images.githubusercontent.com/8470477/111283505-2c29c880-867a-11eb-9c1a-149e0d2c40e5.png)
未知是使用哪个 style 配置项呢？屡试不灵。

**Comment by lotem** [comment]
​可以試試設置 `base_offset` 參數。

參考信息： https://github.com/rime/squirrel/issues/528

**Comment by jasonlam-swatow** [comment]
@lotem `base_offset` 调整正负值均无变化；类似的 `spacing`、`line_spacing` 亦都试过。

**Comment by LEOYoon-Tsaw** [comment]
試下 #559 有沒有好些
