### ISSUE TITLE
豎排時，如何移動光標選擇拼音

### ISSUE THREAD

**Issue by nasyxx** [rime/squirrel#552]
如圖，此時無論用 C-b 或者 Left ，都是選擇候選項，而非回退一格選擇拼音。

<img width="429" alt="Screen Shot 2021-03-23 at 07 38 11 AM" src="https://user-images.githubusercontent.com/5007613/112141130-4d734300-8bab-11eb-8b99-ed2db9baa706.png">

橫排的時候，可以 Down 選擇候選項，Left/Right 移動光標，選擇拼音。

<img width="421" alt="Screen Shot 2021-03-23 at 07 44 37 AM" src="https://user-images.githubusercontent.com/5007613/112141404-9fb46400-8bab-11eb-88b4-d7bebdd870e5.png">

**Comment by LEOYoon-Tsaw** [comment]
用這個pull的代碼編譯
rime/librime/pull/397

**Comment by nasyxx** [comment]
> [rime/librime/pull/397](https://github.com/rime/librime/pull/397)

非常感謝！
