### ISSUE TITLE
word下无法使用ctrl+n切换到下一个候选项

### ISSUE THREAD

**Issue by zchtoy** [rime/squirrel#554]
OS版本：macOS Big Sur
Squirrel版本：0.15.2
使用word时，输入法有多个候选项时，使用ctrl+n不能切换到下一个候选项，而是新建另一个word文档。

**Comment by vlaw** [comment]
同样问题，似乎按键没有在输入法中被捕获，触发了Word的快捷键响应

**Comment by lotem** [comment]
​估計無法解決。
終端裏也有類似情況。
從觀察到的現象推測，macOS會先處理系統和APP註冊的快捷鍵，再過輸入法。如果是這樣的話就無解了。

**Comment by zhaoqiang1024** [comment]
这种应该属于输入法冲突，谁优先都不是一个好的办法，最好的办法就是换快捷键

**Comment by zhaoqiang1024** [comment]
这种应该属于快捷键冲突，谁优先都不是一个好的选择，最好的办法就是换快捷键
