### ISSUE TITLE
時不時候選欄會出現過長的問題，即沒有依據候選詞的數量作自適應的候選欄長度

### ISSUE THREAD

**Issue by camxcube** [rime/squirrel#556]
在今年的一次大版本更新後，我的 rime 一直都會發生一個問題。
時不時 Rime 就會出現選欄會過長的問題，也即沒有依據候選詞的數量作自適應的候選欄長度。
這個問題時不時也會發生，心裏很不舒服，請問大家也有遇到類似的情況嗎，有的話，你們是如何解決的？

<img width="1026" alt="Screen Shot 2021-04-02 at 17 20 33" src="https://user-images.githubusercontent.com/17536059/113403427-387f8680-93d9-11eb-9211-6c49ca561d98.png">

**Comment by LEOYoon-Tsaw** [comment]
同 #523

**Comment by camxcube** [comment]
> 同 #523

我這個所說的跟你提到的是不一樣的，我的情況是不碰屏幕邊緣也會變成這樣。

**Comment by LEOYoon-Tsaw** [comment]
如何復現？

**Comment by camxcube** [comment]
我想這個問題應該真的是跟 #523 一樣，我現在無法復現了，就此結案吧。
