### ISSUE TITLE
希望增加在切换输入法时可以不显示switcher/caption的设置

### ISSUE THREAD

**Issue by xiaolongGitHub1498** [rime/squirrel#562]
希望增加在切换输入法时可以不显示switcher/caption的设置
目前如果设置为空的话会显示 :-)
切换输入法时设置的值就会上屏 很影响体验
![image](https://user-images.githubusercontent.com/26108004/116379934-1517f200-a846-11eb-818c-0d7d20f06b84.png)
![image](https://user-images.githubusercontent.com/26108004/116379957-1ba66980-a846-11eb-8b3e-89b9b703c553.png)
![image](https://user-images.githubusercontent.com/26108004/116379977-2103b400-a846-11eb-89fe-f857b5d63560.png)

**Comment by lotem** [comment]
什麼版本？
怎麼上屏的？
#450 已經修復，最新版本在切換輸入法應該不會再上屏提示文字。

**Comment by xiaolongGitHub1498** [comment]
@lotem 
最新的版本v0.15.2
希望能加入可以不显示switcher/caption的设置 这个提示文字不是必须的 而且在vscode里光标在写入状态下切换输入法时 源本已经保存过的文件会因为switcher/caption而变为已修改未保存的状态 即使你按`Esc`键 它依旧会变为已修改未保存的状态

**Comment by lotem** [comment]
要避免改寫文檔的話就得改用其他方式切換。
因爲是小製作，成本有限，方案選單借用了輸入法的候選框做界面，打開他相當於正在輸入，也就意味着編輯了文檔。
目前只有按快捷鍵直接切換方案能行。
