### ISSUE TITLE
候选条宽度问题

### ISSUE THREAD

**Issue by xiaolongGitHub1498** [rime/squirrel#565]
正常的时候 候选条的宽度是正常的

![image](https://user-images.githubusercontent.com/26108004/116980926-7124bf80-acf9-11eb-901f-cabfacc002a2.png)

这时候 候选词文字长 候选条随之变长是正常的

![image](https://user-images.githubusercontent.com/26108004/116981275-dbd5fb00-acf9-11eb-804a-078102ba693e.png)

当删除`s`后 回到刚开始的时候 候选条没有适应的变短 不正常了

![image](https://user-images.githubusercontent.com/26108004/116981515-2ce5ef00-acfa-11eb-8630-52949a7ec7b0.png)

**Comment by xiaolongGitHub1498** [comment]
我发现这个问题好像在候选条右侧贴近屏幕边缘后会出现

**Comment by lotem** [comment]
同 https://github.com/rime/squirrel/issues/523
