### ISSUE TITLE
Update error on macOS Big Sur 11.2.3

### ISSUE THREAD

**Issue by xiebruce** [rime/squirrel#568]
<img width="269" alt="image" src="https://user-images.githubusercontent.com/13575500/119432322-b9f2f580-bd46-11eb-8527-6cfe80b29cb8.png">

无论是否使用代理工具，它都报这个错，以前是不会报的，我重装Squirrel或者重启系统都没用。
而且有一个问题，当Update error时，我无法用其它方式查看我当前的Squirrel版本，希望能增加类似`About`这样的按钮，能单独查看当前版本。

Squirrel version: `0.15.2`

**Comment by JiandanDream** [comment]
macOS Big Sur 11.4 也有这个问题。

**Comment by JiandanDream** [comment]
> macOS Big Sur 11.4 也有这个问题。

若是用 Homebrew 安装的，可直接使用 `brew upgrade --cask squirrel` 更新。

**Comment by LEOYoon-Tsaw** [comment]
從bintray換到GitHub造成的吧，和系統版本無關

**Comment by xiebruce** [comment]
> 從bintray換到GitHub造成的吧，和系統版本無關

原来如此，那要怎么解决？

**Comment by xiebruce** [comment]
> > macOS Big Sur 11.4 也有这个问题。
> 
> 若是用 Homebrew 安装的，可直接使用 `brew upgrade --cask squirrel` 更新。

也是个方法，我倒是忘了可以用homebrew来安装

**Comment by lotem** [comment]
還沒有到下載 在檢查更新信息時就報錯了 也就是獲取appast出錯
​好像是網站TLS證書的問題
Console日誌：

    Error: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection. (null) (URL http://rime.im/release/squirrel/appcast.xml)

**Comment by LEOYoon-Tsaw** [comment]
換成https應該就行了

**Comment by lotem** [comment]
去GitHub Pages后台看了一下，TLS证书一直续不上。通过

    TLS certificate is being provisioned. This may take up to 15 minutes to complete

找到解法
https://stackoverflow.com/questions/62096356/tls-certificate-is-being-provisioned-this-may-take-up-to-15-minutes-to-complete
https://github.community/t/certificate-request-error-is-persistent-tls-certificate-cant-be-provisioned/11008

更新DNS设置后就续签上了。

备注：现在没有启用 Enforce HTTPS 选项，可能小狼毫还需要用HTTP检查更新：
https://rime.im/release/weasel/appcast.xml

**Comment by xiebruce** [comment]
@lotem 既然是证书问题，那就跟客户端无关，所以按道理，我现在更新就是正常的了吧？但问题是，还是一样error
<img width="263" alt="image" src="https://user-images.githubusercontent.com/13575500/120424295-a5de7200-c39e-11eb-8433-d108fb53832e.png">

**Comment by lotem** [comment]
https://rime.im 域名修好了，但是出現了新的情況：
客戶端請求的地址 https://rime.github.io/release/squirrel/appcast.xml
被重定向到HTTP地址：
http://rime.im/release/squirrel/appcast.xml
不太明白GitHub Pages的操作。

**Comment by lotem** [comment]
啓用了 Enforce HTTPS。
應該能解決。
但願小狼毫的WinSparkle也能支持HTTPS吧。 @Prcuvu
