### ISSUE TITLE
关于繁简切换提示的疑惑

### ISSUE THREAD

**Issue by bosconb** [rime/squirrel#569]
之前没有关注繁简切换的提示，今天特别留意了下，和我想象中的有出入，不知是自己的设置问题，还是软件本身逻辑如此。

**环境**：

- 鼠须管 0.15.2
- macos big sur 11.2.3
- 自制的五笔86码表方案，默认简体

### 繁简开关设置

```
  - name: simplification
    reset: 0
    states: [ 汉字, 漢字 ]
```

### 部分快捷键设置
```
optimized_mode_switch:
  __append:
    - { when: always, accept: Control+Shift+space, select: .next }
    - { when: always, accept: Shift+space, toggle: ascii_mode }
    - { when: always, accept: Control+comma, toggle: full_shape }
    - { when: always, accept: Control+period, toggle: ascii_punct }
    - { when: always, accept: Control+slash, toggle: simplification }
    - { when: always, accept: Control+backslash, toggle: extended_charset } 
```

### 快捷键切换

- 初始状态是简体，Control+slash后切换到繁体状态，**提示「汉字」**；
- 初始状态是繁体，Control+slash后切换到简体状态，**提示「漢字」**；

### 菜单栏切换

- 初始状态是简体，选择「汉字—>漢字」后，切换到了「繁体」，**提示「汉字」**；
- 初始状态是繁体，选择「漢字—>汉字」后，切换到了「简体」，**提示「漢字 」**；

调整了`states: [ 汉字, 漢字 ]`中的顺序，仍然如此，我查了下，提示文字似乎是被写死在xcode里的。

我的想法是，切换到「繁体」状态，提示「漢字 」，切换到「简体」状态，提示「汉字」，请教如何实现？

---
临时解决方案：

**1、鼠须管（简中环境)**

```
 $ sudo vi /Library/Input\ Methods/Squirrel.app/Contents/Resources/zh-Hans.lproj/Localizable.strings
```
修改以下内容
```
"simplification" = "輸出繁體";  # 默认设置："汉字"
"!simplification" = "输出简体";  # 默认设置："漢字"
```

**保存后重启或者退出账户再登录后才会生效**。

**2、小狼毫**

参照此文

[Rime (小狼毫) 输入法自编译版本，调整简繁切换以及添加字符切换浮动提示 ](https://sailboatweb.com/2020/09/21/rime-%e5%b0%8f%e7%8b%bc%e6%af%ab-%e8%be%93%e5%85%a5%e6%b3%95%e8%87%aa%e7%bc%96%e8%af%91%e7%89%88%e6%9c%ac%ef%bc%8c%e8%b0%83%e6%95%b4%e7%ae%80%e7%b9%81%e5%88%87%e6%8d%a2%e4%bb%a5%e5%8f%8a%e6%b7%bb/)

**Comment by Ace-Who** [comment]
没看懂疑惑是什么。`simplification` 指「简化」，状态值 0 表示关闭，即繁体候选不会被替换为简化字；1 表示开启，即繁体候选会被替换为简化字。初始状态值是 0 或最近记忆的值（保存在 `user.yaml` 中），方案如有 `reset` 项则在切换至该方案时自动设定为该值。`states` 项定义的是方案选单中各状态值所对应的文字表示。
