### ISSUE TITLE
请问有没有办法禁掉空格上词

### ISSUE THREAD

**Issue by 2unc** [rime/squirrel#57]
习惯了用cmd+空格切换到英文，这个时候已经敲的会中文上屏，还要删掉，比较麻烦。请问有办法禁止么，谢谢。

**Comment by lotem** [comment]
這種情況上詞不是因爲敲了空格——Cmd+空格不會被當作空格處理，而是輸入法在被關閉之前把未完成的輸入提交上去。用戶沒有表示不要卻給清除了，這個風險俺承擔不起，所以有現在這個處理方式。

要捨棄輸入內容，可以改這裏的代碼：
https://github.com/rime/squirrel/blob/develop/SquirrelInputController.m#L264
```
  [self commitComposition:sender];
```
改爲
```
  if (_session) RimeClearComposition(_session);
```

如果用默認的 `Shift` 切換到英文會更加便利，而且即使誤操作也可以再按一次 `Shift` 切回中文字繼續編輯。

**Comment by 2unc** [comment]
多谢回复指导

个人觉得如果参考一些文本编辑器的方式是否更好？就是在关闭输入法的时候将未保存的放入自己的缓冲区，等下次打开的时候作为选项之一丢弃或者继续编辑？

**Comment by lotem** [comment]
相关问题： https://github.com/rime/squirrel/issues/146

**Comment by ShikiSuen** [comment]
@2unc 这个产品需求在实装的时候无法可控。

虽然我是拿威注音输入法举例，但都是 IMK (InputMethodKit) 应用。

IMK 呢，你可以故意用 client().insertText 专门递交字词（上屏）：
<img width="721" alt="image" src="https://user-images.githubusercontent.com/3164826/176098559-a8a707c6-047d-4294-bfa0-00d0b56b546a.png">
但在有些时候，这样的一个步骤会被无视，因为 commitComposition() 会被执行、导致组字区看上去消失。
<img width="663" alt="image" src="https://user-images.githubusercontent.com/3164826/176098684-9733ae94-e59d-43f0-90c4-e6603fcc45ec.png">

你认为内文组字区内有的内容可能只是一串文字就算了，但实际上不见得。
可能会是一堆轨格，每个轨格里面有节点、有候选字词阵列、有当前权重（可能是被使用者词语动态记忆模组改写过的权重，也可能是原厂字词权重），很多复杂的资料。你想让输入法在 deactivateServer() 时全部记下来，就得想办法把这些内容一次性全部 hashable / serializable 成可以被记录的形式。

你要「在关闭输入法的时候将未保存的放入自己的缓冲区，等下次打开的时候…」这个功能。等这个功能做出来了，你在用微信时，一定会靠北。因为微信每当手动换行的时候，都会触发 IMK 的 commitComposition()，然后你会发现你在敲新一行的时候：欸？我上一行敲完的东西，怎么又冒出来一遍？

**Comment by lotem** [comment]
看吶，假臺灣人在打簡體字

**Comment by ShikiSuen** [comment]
@lotem 我现在看对方用简体的话就会打简体，正好测试威注音的简体。
