### ISSUE TITLE
系统自带的邮件、备忘录程序无法使用squirrel

### ISSUE THREAD

**Issue by Yiklek** [rime/squirrel#570]
在自带的邮件、备忘录程序无法正常输入，`Shift`也无法切换中英。系统输入法选项显示如下：
![image](https://user-images.githubusercontent.com/21033316/120139678-8d8a1e00-c20b-11eb-8e79-0abff80d8d3a.png)
不显示squirrel的选项。

MacOs：11.3.1 (20E241)
Squirrel:44c7c4608d078e90762a0463583b9560c9a775b9

**Comment by lotem** [comment]
​未曾遇到過。
無法正常輸入的表現是什麼？
是否已排除 https://github.com/rime/squirrel/issues/281 ？

**Comment by Yiklek** [comment]
重启后可以了，但是我没记错的话squirrel很早就安装过了，而且后面升级了系统，是重启过的  
![image](https://user-images.githubusercontent.com/21033316/120880297-47163400-c5fc-11eb-90a8-0a191d97eb0b.png)

先关掉吧，如果后面再遇到再来讨论
