### ISSUE TITLE
在新的 macOS Monterey 中 fallback 竖向字体方向不对

### ISSUE THREAD

**Issue by nasyxx** [rime/squirrel#571]
是不是新系统的 api 改了？我更新后发现 fallback 的字体似乎方向不对了。虽然不着急 (換到 horizontal），也不知道是不是 bug OS 的问题，总之先报上来

比如我找了一个前面字体无，后面有的： 

当 

`font_face: "Kaiti SC,HanaMinB"`

xhbt 𧖭

<img width="259" alt="Screen Shot 2021-06-10 at 02 05 48 AM" src="https://user-images.githubusercontent.com/5007613/121473257-61e80000-c990-11eb-9356-c82c7c80b67a.png">

当 `font_face: "HanaMinB,Kaiti SC"`

hbu 自

<img width="296" alt="Screen Shot 2021-06-10 at 02 08 12 AM" src="https://user-images.githubusercontent.com/5007613/121473461-b8553e80-c990-11eb-8cf6-8616724c302c.png">

**Comment by LEOYoon-Tsaw** [comment]
豎排字符是否旋轉是用第一字體判斷的，fallback字體就比較隨緣了，確定是macOS12新出現的問題嗎？

**Comment by nasyxx** [comment]
> 豎排字符是否旋轉是用第一字體判斷的

我一开始还以为是字体本身的问题。虽然macOS 11没出问题，但用那个Squirrel.Designer的时候，发现它没有转

<img width="663" alt="Screen Shot 2021-06-10 at 10 03 16 AM" src="https://user-images.githubusercontent.com/5007613/121539202-76012100-c9d3-11eb-8c97-6f6522f61f2f.png">

<img width="708" alt="Screen Shot 2021-06-10 at 10 03 33 AM" src="https://user-images.githubusercontent.com/5007613/121539254-81ece300-c9d3-11eb-9a82-056531a719d6.png">

看来还是有机会顺便判断一下后面的字体啊.

> 確定是macOS12新出現的問題嗎？

是的，macOS 11没有出现这个问题


----

p.s. 字体 https://github.com/cjkvi/HanaMinAFDKO/releases

**Comment by LEOYoon-Tsaw** [comment]
等macOS12正式發佈了再搞吧，真麻煩

**Comment by LEOYoon-Tsaw** [comment]
關了吧，正式版未見此問題

**Comment by nasyxx** [comment]
> 關了吧，正式版未見此問題

是的w
