### ISSUE TITLE
vim不同模式切换输入法的问题

### ISSUE THREAD

**Issue by xiaolongGitHub1498** [rime/squirrel#573]
您好 想问一下 #123 这个方法没有集成到鼠须管里吗？

目前想要这种在vim（终端里的或其他ide集成的vim 比如vscodeVim）的插入模式下自动切换鼠须管到英文状态

因为目前只安装鼠须管一个输入法 像im-select这种方式必须得增加一个英文输入法从而破换一体性 而且mac的不同输入法之间通过shift切换还有瑕疵 找遍了issues没有一个解决方案 app_options的vim_mode也没有效果

希望可以增加一个像 #123 的方法 通过手动调用命令切换输入法状态

**Comment by xiaolongGitHub1498** [comment]
已解决 在squirrel.custom.yaml里添加app_options
之前加在default.custom.yaml里不好使

**Comment by Gowa2017** [comment]
你这个问题还不恼火 要想在i 模式中文才是恼火的事情

**Comment by jackywu** [comment]
应该怎么对neovim设置这个app_options呢？

**Comment by BTBMan** [comment]
这个选项是针对应用程序的 看你用的什么软件了

**Comment by baober90** [comment]
> 你这个问题还不恼火 要想在i 模式中文才是恼火的事情

这个问题大会解决了吗? 怎么处理的
