### ISSUE TITLE
功能：同义词替换

### ISSUE THREAD

**Issue by dwSun** [rime/squirrel#574]
例如这样的功能：
![image](https://user-images.githubusercontent.com/5899962/123051120-03ad2980-d434-11eb-818d-2f1bdfedb620.png)

在现有的框架下，是否能够通过一些配置实现，我暂时想到的是通过 lua 实现，输入某个词，如果能够匹配到词库就展示候选项目。
但是不知道具体要怎么做。例如如何获取候选词而不是输入，同时根据候选词进行候选词的生成，这个是现在能够实现的吗？

可能比较好的实现方式是如图上，另开一个选词窗口，例如有第二个候选词行。

**Comment by dwSun** [comment]
例如  #515 里，利用第二行显示一些输入词的二级以上的候选（同义词，关联词等）。
不过，这种方式，对词库的处理，可能会涉及一个二级的查询，性能影响有多大不太好说。

**Comment by LEOYoon-Tsaw** [comment]
用OPENCC濾鏡實現
