### ISSUE TITLE
有没有人民币大写转换的功能？

### ISSUE THREAD

**Issue by ghost** [rime/squirrel#579]
rime输入法有没有类似搜狗输入法V模式的实现，输入小写人民币直接转成大写人民币

**Comment by LEOYoon-Tsaw** [comment]
沒有

**Comment by maomiui** [comment]
> rime输入法有没有类似搜狗输入法V模式的实现，输入小写人民币直接转成大写人民币

试试添加[大写输入](https://github.com/maomiui/rime#%E5%A4%A7%E5%86%99%E6%95%B0%E5%AD%97)方案

**Comment by LEOYoon-Tsaw** [comment]
想要貨幣轉換功能

**Comment by lotem** [comment]
> > rime输入法有没有类似搜狗输入法V模式的实现，输入小写人民币直接转成大写人民币
> 
> 试试添加[大写输入](https://github.com/maomiui/rime#%E5%A4%A7%E5%86%99%E6%95%B0%E5%AD%97)方案

有才啊

**Comment by LEOYoon-Tsaw** [comment]
已可通過lua實現
