### ISSUE TITLE
請問怎樣使用「鼠鬚管」外掛鄭碼碼表？

### ISSUE THREAD

**Issue by Lulixue** [rime/squirrel#583]
想使用鼠鬚管打鄭碼，應該怎麼做？先謝謝了

**Comment by Ace-Who** [comment]
一个现成的郑码方案可以参考 https://github.com/lotem/rime-zhengma

**Comment by Lulixue** [comment]
> 一个现成的郑码方案可以参考 https://github.com/lotem/rime-zhengma

感谢老铁的回复

**Comment by Lulixue** [comment]
> 一个现成的郑码方案可以参考 https://github.com/lotem/rime-zhengma

感谢老铁的回复，现在已经用上了，谢谢！
