### ISSUE TITLE
[Question]光標在iterm和在其他地方不一樣

### ISSUE THREAD

**Issue by youngH1001** [rime/squirrel#587]
光標在iterm是^，在其他地方是|。
這是爲什麼？可以怎麼統一配置一下？

**Comment by nb5p** [comment]
因为[这里](https://github.com/rime/squirrel/blob/44c7c4608d078e90762a0463583b9560c9a775b9/data/squirrel.yaml#L341)的设置导致的吧

**Comment by youngH1001** [comment]
Hi @nb5p,
你的方向是对的。更准确的是no_inline这个属性在控制。我还以为可以定义任意的字符。
Thanks.
