### ISSUE TITLE
鼠鬚管的拼音候選表現異常，是有參數要調整嗎

### ISSUE THREAD

**Issue by bgc2017** [rime/squirrel#588]
如圖，輸入：kuangqie時。

搜狗：

![image](https://user-images.githubusercontent.com/45348499/134803337-33cac93c-9d4d-4b99-8c90-e2f50882719e.png)

鼠鬚管：
![image](https://user-images.githubusercontent.com/45348499/134803360-3570be0d-fd28-413d-876b-6017e5f632bf.png)

kuangqie 不應該匹配kuangqi，因爲用戶並沒有使用'分割成kuangqi'e。這樣某些情況會顯示大量無效詞條，應該象搜狗那樣隨後顯示單字，即便要輸出kuangqi的詞，順序也要非常靠後。

有什麼參數改變這種行爲嗎？

**Comment by lotem** [comment]
​部分匹配（包括第一個單字）放在完全匹配的候選之後。
不要求用戶一定能正確地使用隔音符號，因此部分匹配的字詞是必要的補充。如果沒有，部分用家很難完成「意圖按」這樣的短語。
反之，不需要這些詞語時，則可以通過左方向鍵、<kbd>Tab</kbd>鍵選中單字。
