### ISSUE TITLE
macOS 12 系统下部分软件无法切换切换到鼠须管输入法

### ISSUE THREAD

**Issue by sogud** [rime/squirrel#591]
鼠须管 0.15.2
目前已知软件 微信 系统备忘录

**Comment by xiyangcai** [comment]
情况相似，具体信息如下：

- 系统：macOS Monterey 12.0.1 + Apple Silicon M1 Pro 
- 输入法版本：鼠须管 0.15.2 from brew

无法切换鼠须管的软件版本：
- 备忘录：4.9 (1965)
- 邮件：15.0 (3693.20.0.1.32)
- 日历：11.0 (2855.1.2)
- Safari：15.1 (17612.2.9.1.20)
- 微信：App Store - Version. 3.2.1 (19797)
- QQ：App Store - V6.7.5

Finder、Apple Music、VS Code、Chrome、Typora、Notion均可正常切换

**Comment by tabris233** [comment]
> 情况相似，具体信息如下：
> 
> * 系统：macOS Monterey 12.0.1 + Apple Silicon M1 Pro
> * 输入法版本：鼠须管 0.15.2 from brew
> 
> 无法切换鼠须管的软件版本：
> 
> * 备忘录：4.9 (1965)
> * 邮件：15.0 (3693.20.0.1.32)
> * 日历：11.0 (2855.1.2)
> * Safari：15.1 (17612.2.9.1.20)
> * 微信：App Store - Version. 3.2.1 (19797)
> * QQ：App Store - V6.7.5
> 
> Finder、Apple Music、VS Code、Chrome、Typora、Notion均可正常切换

我这里也有一样的问题， 除了系统版本其他和你一样， 系统版本是macOS Monterey 12.1

**Comment by Ininit** [comment]
> 

俺也一样，等了一段时间，后面我自己在M1上编译安装后就没有这个问题了。建议你也试一下自己编译。

**Comment by Ininit** [comment]
> > 情况相似，具体信息如下：
> > 
> > * 系统：macOS Monterey 12.0.1 + Apple Silicon M1 Pro
> > * 输入法版本：鼠须管 0.15.2 from brew
> > 
> > 无法切换鼠须管的软件版本：
> > 
> > * 备忘录：4.9 (1965)
> > * 邮件：15.0 (3693.20.0.1.32)
> > * 日历：11.0 (2855.1.2)
> > * Safari：15.1 (17612.2.9.1.20)
> > * 微信：App Store - Version. 3.2.1 (19797)
> > * QQ：App Store - V6.7.5
> > 
> > Finder、Apple Music、VS Code、Chrome、Typora、Notion均可正常切换
> 
> 我这里也有一样的问题， 除了系统版本其他和你一样， 系统版本是macOS Monterey 12.1

俺也一样，等了一段时间，后面我自己在M1上编译安装后就没有这个问题了。建议你也试一下自己编译。

**Comment by tsingyi** [comment]
我也有这个问题，只要切换到某些软件输入法就自动切换到系统的，而且无法切换到鼠须管，困扰了好久，还以为是某些软件的问题，直到我今天仔细看了下[README.md](https://github.com/rime/squirrel/blob/master/README.md#%E5%AE%89%E8%A3%9D%E8%BC%B8%E5%85%A5%E6%B3%95) 。

![image](https://user-images.githubusercontent.com/6947982/148682599-29d6cf58-3165-47b2-83fd-b36f05263801.png)

按照说明，退出重新登录就行了，所有的软件都正常了。

因为我是用homebrew安装的，所以一直没有看过这个文档，不知道你的情况是不是和我的一样。

**Comment by lotem** [comment]
macOS 12 M1 不知道系统改了什么。我有时安装完有些app不能打字，在系统设置里从输入法列表删除鼠须管再加上，这样做不必退出登录就可以用了。

**Comment by xiyangcai** [comment]
> macOS 12 M1 不知道系统改了什么。我有时安装完有些app不能打字，在系统设置里从输入法列表删除鼠须管再加上，这样做不必退出登录就可以用了。

感谢，解决方案可行。

**Comment by lotem** [comment]
關聯 https://github.com/rime/squirrel/issues/590

**Comment by PotatoWen** [comment]
在12.2上通過homebrew裝的，起初無法啓用，重啓電腦後都就可以了

**Comment by seagle0128** [comment]
注销再登录就可以了。
