### ISSUE TITLE
在 Telegram 3.2 上完全无法输入

### ISSUE THREAD

**Issue by sunwgit** [rime/squirrel#593]
rt,更新到[telegram3.2](https://github.com/telegramdesktop/tdesktop/commit/63919422e0cfa3f6413f03dfe2cb2320d061b40d)后，鼠须管(0.15.2)完全无法上屏.
macOS: 10.15.7 Catalina

**Comment by LEOYoon-Tsaw** [comment]
<img width="928" alt="image" src="https://user-images.githubusercontent.com/4469383/140257408-77ffa92f-8438-4f02-9bc2-f83108e96d2f.png">
最新的Telegram是8.1.3

**Comment by xosdy** [comment]
是 tdesktop 版, 不是 macOS 專用的版本
https://github.com/telegramdesktop/tdesktop/issues/17176

**Comment by shanoaice** [comment]
看上去是鼠须管和 Qt6 打架，毕竟 TDesktop 前几天给 Linux 和 macOS 上了 Qt6

**Comment by cubercsl** [comment]
https://apps.apple.com/cn/app/telegram-lite/id946399090

**Comment by Andrewlearntocode** [comment]
我也碰到这种情况，Squirrel在Telegram中打不出字，任何键盘按键都没有反应，切换成其他输入法一切正常。macOS Monterey version 12.0.1，Telegram Desktop version 3.2.2。

**Comment by JonahWong** [comment]
> 我也碰到这种情况，Squirrel在Telegram中打不出字，任何键盘按键都没有反应，切换成其他输入法一切正常。macOS Monterey version 12.0.1，Telegram Desktop version 3.2.2，Squirrel 0.15.2。

一样的问题 here

**Comment by EpLiar** [comment]
Try this version: https://td.telegram.org/tmac/tsetup.3.2.5.dmg

It works on macOS 12.0.1, Rime 0.15.2.

**Comment by Andrewlearntocode** [comment]
> 我也碰到这种情况，Squirrel在Telegram中打不出字，任何键盘按键都没有反应，切换成其他输入法一切正常。macOS Monterey version 12.0.1，Telegram Desktop version 3.2.2，Squirrel 0.15.2。

Telegram Desktop更新到3.2.5后，Squirrel可以正常打出字了。

**Comment by EpLiar** [comment]
> Telegram Desktop更新到3.2.5后，Squirrel可以正常打出字了。

You will find that the commadn+w shortcut does not work on td 3.2.5, I'll still wait for the new version to see if it will be fixed.

**Comment by EpLiar** [comment]
> > Telegram Desktop更新到3.2.5后，Squirrel可以正常打出字了。
> 
> You will find that the command+w shortcut does not work on td 3.2.5, I'll still wait for the new version to see if it will be fixed.
