### ISSUE TITLE
macOS Terminal App 下切换输入法后自动从中文切换成英文的问题

### ISSUE THREAD

**Issue by jtr109** [rime/squirrel#596]
## 问题描述

我遇到一个问题是在 Terminal 中如果切换输入法，切回鼠须管后会自动将输入法设置为英文模式，在其他 App 中未发现该问题。

复现方法：

1. 选择鼠须管输入法，切换为中文。可以正常入手中文。
2. 切换输入法（如 Apple 自带英文）。可以正常输入。
3. 将输入法切换为鼠须管，敲击按键开始输入的瞬间，会出现中英文切换的图标，并且输入内容为英文。

我认为切换后自动指定英文输入法是 `ascii_mode` 导致的，但是我[修改该配置](https://github.com/jtr109/config/blob/e8058971f2a5b82a734b0f02c58277bc0bc9ecb8/rime/default.custom.yaml#L48)没有产生期待中的变化。

想请教以下是我有什么地方配置错了吗？

### 操作系统

macOS 12.0.1

<img width="224" alt="image" src="https://user-images.githubusercontent.com/13946679/140899193-70a06423-5dd3-4a49-8e90-d12221ba86f7.png">

### 鼠须管

0.15.2

<img width="246" alt="image" src="https://user-images.githubusercontent.com/13946679/140899326-f6d16411-5915-456a-8ba9-3ecfedf31e58.png">

自定义配置见[链接](https://github.com/jtr109/config/blob/e8058971f2a5b82a734b0f02c58277bc0bc9ecb8/rime/default.custom.yaml)。

## 操作记录

正常情况：

https://user-images.githubusercontent.com/13946679/140900534-6aae9a2d-fc24-4402-8cae-401a9abc2521.mov

Terminal 中的情况

https://user-images.githubusercontent.com/13946679/140901498-afa6790b-acca-4c5e-acfe-70c3440e9f51.mov

**Comment by lotem** [comment]
試試以下補丁：
```yaml
# ~/Library/Rime/squirrel.custom.yaml
patch:
  app_options/com.apple.Terminal: {}
```

我考慮把一些應用的初始設置恢復默認，只保留因爲兼容性問題必須設的。

**Comment by jtr109** [comment]
谢谢 @Dreamer57 @lotem 二位！

我使用了 @lotem 的配置方法，成功解决了。应该是我错误地将配置放在了 `default.custom.yaml` 中。

另外想请教以下是否有办法全局设置 `ascii_mode: false` 呢？我好像不太需要这个功能，暂时使用的方式是将每个 App 都设置成了默认（空白）值。

话外题：

确实您说的初始设置该帮用户配置到什么程度感觉是一个很两难的问题，作为一个入门使用者有的方面会觉得配置的太多，有的方面会期待提供更开箱即用的初始配置。感觉众口难调。
