### ISSUE TITLE
切换输入方案后，上个方案里的开关设置被带到了下一个方案里。

### ISSUE THREAD

**Issue by Dreamer57** [rime/squirrel#597]
我自己摸索着给鼠须管加了一个用快捷键切换显示与隐藏候选栏的一个效果。

实现方式是在输入方案里加了一个开关，并且设置快捷键切换这个开关。然后自己在鼠须管里读取开关的值，决定要不要显示候选栏。

开始一切都进行得很顺利，我使用快捷键可以正常切换显示隐藏候选栏。这让我感到很欣慰，付出的一切都是有意义的。也让我自己很得意，原来我也可以写代码。

但是第二天，我无意间切换了一个输入方案，结果发现这个方案也没有显示候选栏。但是我这个方案是没有做任何改动的，也就是没有加入隐藏候选栏这个开关。我的理解是，我上一个输入方案的开关设置在我切换了方案后应该不会被带到这个输入方案里来，但却被带过来了。

后来我在另一个输入方案里也加入了隐藏候选栏的开关，并且默认为关闭状态，问题就这么被解决了。切换输入方案时也都是按照方案里的开关设置来决定是显示还是隐藏候选栏，这很符合我预期的。

但是如果输入方案里没有加入这个开关，就会读取到上一个方案里的开关。

这虽然不符合我的预期，但是我只使用一个输入方案，所以也丝毫不影响我的使用。

本来，故事讲到这里也已经讲完了。

我也选择了休息一会儿。

但是在休息的时候，我陷入了回忆之中，我回忆起了我是怎么学会改鼠须管代码的。

那是无数个不眠的夜晚，漆黑、静谥，无尽的黑夜仿佛一只无形的大手，牢牢的握住了我，我的世界里只剩下一台电脑。我看向它，它的屏幕上显示着晦涩难懂的字母。起初我什么都看不到，艰难的使用谷歌翻译和搜索，渐渐地，我能看见了，再后来，我看见的越来越多了。

“是时候了。”

”该下手了。”

我提起手指，敲下了代码。

……

我回过了神来，起身坐在电脑前，找到了起初写下的代码，取开关的值使用的是 `rime_get_api()->get_option()` 。

“是我用错了吗？”我思考着。继续看着代码。

在黑夜的笼罩下，我沉浸在代码的世界里，傲游在编程的海洋中，这一切都让我沉迷。

幸运女神总会光顾努力之人，我终于找到了另一种方式：`rime_get_api()->get_status()` 。

我很兴奋，看向了旁边的镜子，看到了镜中人光滑的头顶，我知道，这是实力的证明，是强者的记号。看着镜中的自己我很满意，渐渐地扬起了嘴角，忍不住地笑了出来。

……

改完之后，我调出鼠须管，按下快捷键，显示、隐藏、显示、隐藏，一切正常，我很开心。

我心里明白。

我变强了。

……

但当我切换输入方案后，发现候选栏的显示状态依然是和上个方案保持一致。

这是个沉重的打击，让我很失落。

我又瞥向了镜中了自己，看见了两鬓还残留有些许头发。

又看到镜中人突然面色一沉。

”还不够～～～还不够～～～还不够～～～”

一个声音不停的在我脑海里回荡。

我知道。

是我还不够强。

我要变得更强。

同时我也知道，这个世界很大，有很多已经很强了的人。也有很多和我一样，强得还不够彻底，正行走在变彻底的路上的人。

所以，命运指引我来到了这里，祈求得到强者的帮助。

**Comment by Dreamer57** [comment]
@lotem @LEOYoon-Tsaw

**Comment by lotem** [comment]
​又講故事？

有這麼優秀的玩家，本品可以參選開源創新榜了。

**Comment by lotem** [comment]
默認不變是正常思維啊，比如簡繁、全半角狀態。
反而是你的程序應該先檢查方案支不支持這個開關再讀值吧。不嚴謹。圖樣。

試試改爲臨時狀態，以下劃線開始的選項名，切換方案時清除。
https://github.com/rime/librime/blob/62a97cf64a75fe86140dfb3f4be5f5c1adfe0e07/src/rime/context.cc#L279

**Comment by Dreamer57** [comment]
@lotem 

感谢大哥的回复，大哥过誉了，我哪里是什么优秀玩家啊，我只是个菜得扣脚的菜鸟玩家。

但是这个开源作品真的太棒了，代码设计得特别精妙，如同古代的榫卯一般，看似零散，但又拼凑得严丝合缝。如同在读一部构思缜密、严谨的悬疑小说，让人停不下来。

大哥给出的关于开关状态的解释，让我觉得很有道理，原来我之前理解错了啊。那我就改为临时状态吧。

至于我为什么没有先检查方案支不支持这个开关再读值嘛。

呃……原因其实也很简单：

我不会🤣

顺便再问一下rime有没有介绍代码的文档啊，比如上面你说的临时状态，必须要把代码读到那里才会知道吗，不读到那里就不知道。

而我读代码是很困难的，英文不好很难理解，得借助谷歌翻译一个个单词的翻。

如果有这么一份介绍，那我觉得，再菜的菜鸟也可以动代码。

**Comment by lotem** [comment]
寫文檔費事費力。將來用中文寫程序就妥了。

**Comment by Dreamer57** [comment]
> 寫文檔費事費力。將來用中文寫程序就妥了。

行吧！
