### ISSUE TITLE
新版本给方案设定专用字体失效

### ISSUE THREAD

**Issue by yanhuacuo** [rime/squirrel#600]
不同方案可能字符集大小不同，大字符集可能需要指定特别的字体，于是：

AAA.custom.yaml  下，可以补丁指定字体如下 ( 异于  squirrel.yaml 默认的字体 )，比如：

``````
patch:
  "style/font_face:": "98WB-U,98WB-V"
  "style/comment_font_face": "98WB-3"
``````

观察 build 文件夹下合并正常，这也在预料之内，因为旧版中一直是这么做的。

新版本中，仅执行默认的  squirrel.yaml  参数，补丁写下的专用字体没有生效。

**Comment by LEOYoon-Tsaw** [comment]
<img width="378" alt="image" src="https://user-images.githubusercontent.com/4469383/142306768-aebbfbcd-c26a-4136-a1b6-0b0ebd936ba5.png">
方案中的字體可以生效，反正我這可以。
