### ISSUE TITLE
用一鍵Shift執行「中文輸出+中英切換」？

### ISSUE THREAD

**Issue by ballII** [rime/squirrel#603]
鼠鬚管預設可用Shift在中文與小寫英文之間切換。但我希望能在輸入注音後，不必按Return，直接按Shift就可直出中文且緊接著打小寫英文。

目前Shift會讓注音編輯碼轉成英文碼，無法直出中文。

不過，我嘗試設定Caps Lock鍵：
```
ascii_composer/switch_key:
    Caps_Lock: commit_text
```

而且關閉Caps Lock的大寫功能：
```
ascii_composer:
    good_old_caps_lock: false
```

發現此設定可成功讓Caps Lock一鍵直出中文並切到小寫英文，不須先按Return來輸出中文。

但  ```Shift: commit_text```  這語碼卻無法成功讓Shift鍵直出中文。

請問有沒有辦法設定讓Shift直出中文且切到小寫英文呢？謝謝。

**Comment by lotem** [comment]
設定方法，請參考代碼模板：
https://gist.github.com/lotem/2981316

**Comment by ballII** [comment]
> 設定方法，請參考代碼模板： https://gist.github.com/lotem/2981316

但我發現，```Caps_Lock```和```Control```鍵都能順利指定commit_text，唯有 ```Shift_L: commit_text``` 和 ```Shift_R: commit_text``` 是沒有效用的。請問這可能是哪裡出錯呢？

**Comment by lotem** [comment]
猜不到是哪裏。

**Comment by ballII** [comment]
已解決。在我陸續又更改部分設定後，```Shift_L: commit_text``` 和 ```Shift_R: commit_text``` 變得有效了。抱歉沒能抓出失效或有效的規律為何。
