### ISSUE TITLE
双拼模式下shift上屏时，如何上屏双拼转义后的拼音，而不是实际键入的内容

### ISSUE THREAD

**Issue by magicwenli** [rime/squirrel#604]
标题可能没有说清楚，举个例子：

![image](https://user-images.githubusercontent.com/48174882/145205579-9f83e597-c312-4f49-a2f3-99a5c2cf7e52.png)

用小鹤双拼输入 `uhpk`，会出现`shang ping`的拼音，如果通过`shift`键上屏，仍然得到`uhpk`。

可否通过特定配置，使得此时上屏内容仍为`shang ping`？

#261 这里提到了一个相反的需求，找了许多相关配置项，还是不得解，希望得到一些帮助。

**Comment by iDvel** [comment]
好像默认配置就是你的需求吧，你自己改了啥。

**Comment by lotem** [comment]
請參考說明書的以下章節：
https://github.com/rime/home/wiki/UserGuide#%E4%BB%A4%E8%BC%B8%E5%85%A5%E7%A2%BC%E7%9B%B4%E6%8E%A5%E4%B8%8A%E5%B1%8F

**Comment by zeahoo** [comment]
jy

**Comment by zeahoo** [comment]
jt

**Comment by 662** [comment]
@magicwenli 可是中间有个空格……

**Comment by LEOYoon-Tsaw** [comment]
> @magicwenli 可是中间有个空格……

用preedit_format去掉不就得了

**Comment by yimingtang** [comment]
ce shi
