### ISSUE TITLE
与自动成词和用户词典相关的迷惑

### ISSUE THREAD

**Issue by dalton-chiou** [rime/squirrel#607]
不好意思，问这么低级的问题：
1，由encode_commit_history控制的“自动成词”，指的是什么行为？
2，enable_encoder 控制的是什么行为？ 对用户词典的影响是什么？
3，有没有办法关闭用户词典，却保留使用中的词频调整？

**Comment by Ace-Who** [comment]
1. `encode_commit_history`：将连续上屏的文本序列——如「自动」、「成」、「词」——拼接（「自动成」、「自动成词」、「成词」）并编码。由 `max_phrase_length` 控制最大词长。
1. `enable_encoder`：启用编码器。即允许造词——允许新词进入用户词典。
1. 没有办法，因为用户词典记录了全部用户习惯。如果想要的不是禁用用户词典，而是禁用造词，只需 `encode_encoder: false`。

**Comment by dalton-chiou** [comment]
> 1. `encode_commit_history`：将连续上屏的文本序列——如「自动」、「成」、「词」——拼接（「自动成」、「自动成词」、「成词」）并编码。由 `max_phrase_length` 控制最大词长。
> 2. `enable_encoder`：启用编码器。即允许造词——允许新词进入用户词典。
> 3. 没有办法，因为用户词典记录了全部用户习惯。如果想要的不是禁用用户词典，而是禁用造词，只需 `encode_encoder: false`。

十分感谢。现在我明白一些了。

**Comment by dalton-chiou** [comment]
继续糊涂。我将enable_encoder，encode_commit_history 都关闭后，只开enable_user_dict，照样从连续输入中自动生成各种组合的新词。

**Comment by lovelock** [comment]
```yaml
translator:
  enable_user_dict: false
```

目前来看这个选项是有用的。我用的小鹤双拼+鹤形辅助码，遇到跟你一样的情况。参考这个讨论：https://github.com/rime/squirrel/issues/97

**Comment by plainee** [comment]
使用了melt_eng方案输入英文，怎么才能自动创造英文词语，比如gaga，输入了很多次，都出不来，必须要回车。

**Comment by plainee** [comment]
> 1. `encode_commit_history`：将连续上屏的文本序列——如「自动」、「成」、「词」——拼接（「自动成」、「自动成词」、「成词」）并编码。由 `max_phrase_length` 控制最大词长。
> 2. `enable_encoder`：启用编码器。即允许造词——允许新词进入用户词典。
> 3. 没有办法，因为用户词典记录了全部用户习惯。如果想要的不是禁用用户词典，而是禁用造词，只需 `encode_encoder: false`。

请问如何对melt_eng/easy_en的进行英文造词，比如我想要gagaga输入几次后，就出现在候选，现在英文单词永远是固定的，不像中文打几次就能出现在候选。

**Comment by gaoqiangks** [comment]
同感, 感觉造词功能基本上无用, 95%以上的造词都是干扰项, 没什么用处. 但是单纯地记录一下词频还是有些用.

**Comment by babesun** [comment]
我觉得Rime的用户词典和自造词功能挺好的。使用时只需要关心你要输入什么就可以，不用去管用户词典文件里那些多余的东西。因为某一些输出错了进去一个奇怪短语，直接无视就好了，长期的使用和输入会把这些错误的优先级压到很低的，根本没必要为了它去花费精力处理。
