### ISSUE TITLE
和手动造词设置有关的警告信息

### ISSUE THREAD

**Issue by dalton-chiou** [rime/squirrel#611]
我的手动造词translator一旦使用了 __include: translator来继承，会在log中出现如下两行警告：
circular dependencies detected in zhengma.schema
accessing blocking node with unresolved dependencies: zhengma.schema 
但不使用继承，将主translator中的设置复制过来就没事了。
相关设置为：
translator:
  dictionary: zhengma
  enable_charset_filter: true
  enable_sentence: false
  enable_encoder: true
  encode_commit_history: false
  max_phrase_length: 4
  enable_user_dict: true

mkph:
  __include: translator
  enable_sentence: true
  prefix: '&'
  tips: "【造词】"
  tag: mkph
如上会有前面说的警告信息，除非改为：
mkph:
 dictionary: zhengma
  enable_charset_filter: true
  enable_encoder: true
  encode_commit_history: false
  max_phrase_length: 4
  enable_user_dict: true
  enable_sentence: true
  prefix: '&'
  tips: "【造词】"
  tag: mkph

这是为什么呢？

engine里的相关设置为：
  segmentors:
    - ascii_segmentor
    - matcher
    - affix_segmentor@mkph
    - affix_segmentor@pinyin
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - table_translator
    - table_translator@mkph
    - script_translator@pinyin

**Comment by lotem** [comment]
警告你了，`zhengma.schema`整個文件還沒有編譯完，此處引用的內容可能和最終的`zhengma.schema:/translator`內容不一致。

比如以下情況，通過補丁文件裏修改了 `translator` 配置：

```yaml
# zhengma.custom.yaml
patch:
  translator: 不一樣的內容，不相同的內容
```

最終編譯結果爲：

```yaml
translator: 不一樣的內容，不相同的內容
mkph: 還是translator原來的內容
```

**Comment by dalton-chiou** [comment]
> 警告你了，`zhengma.schema`整個文件還沒有編譯完，此處引用的內容可能和最終的`zhengma.schema:/translator`內容不一致。

明白是怎么回事了。谢谢。
