### ISSUE TITLE
squirrel+速成 字碼庫沒有“靈”

### ISSUE THREAD

**Issue by sheaahhoi1** [rime/squirrel#612]
squirrel+速成 字碼庫沒有“靈”
神靈/血靈/精靈/靈魂都配不出來

**Comment by LEOYoon-Tsaw** [comment]
沒有就加唄

**Comment by lotem** [comment]
有這個字。

**Comment by sheaahhoi1** [comment]
@lotem 為何與現代通用拆碼不一樣[
](https://humanum.arts.cuhk.edu.hk/Lexis/lexi-can/)
WIN/MAC/IOS自帶的都能以下列拆解
靈：一月口口一

**Comment by sheaahhoi1** [comment]
@lotem 
我找到理由了
靈：一月口口一 這是3代
靈：一月口口人 這是5代
能否提供3代5代混合版速成？

**Comment by lotem** [comment]
預裝的方案是倉頡五代。
如果您有合適的碼表，可以自己製作輸入方案。
