### ISSUE TITLE
Rime 選字框美術或許可以針對 macOS 11 / 12 的 UI 風格做一些調整。

### ISSUE THREAD

**Issue by ShikiSuen** [rime/squirrel#614]
![image](https://user-images.githubusercontent.com/3164826/149864725-a9b83f79-98fb-4fc4-9e4d-2e48678ce215.png)
![image](https://user-images.githubusercontent.com/3164826/149864745-9fb5462b-3ae1-41c8-96d2-1b188f722383.png)
相關源碼當中的美術思路可供參考，比如都用到了哪些 NSColor、怎樣做半透明內描邊……等（與 Yosemite 相容）：https://gitee.com/vchewing/vChewing-macOS/blob/main/Source/UI/CandidateUI/HorizontalCandidateController.swift

**Comment by ShikiSuen** [comment]
P.S.: 不是我不想推 PR，實在是 Boost 這種東西配置起來超麻煩。
Squirrel 除了 RIME 共用件以外的部分完全可以考慮用 Swift 重寫的（除非有相容性問題）。

**Comment by LEOYoon-Tsaw** [comment]
跟boost有啥干係？前端不涉及boost，有想法直接提pr或者具體建議

**Comment by ShikiSuen** [comment]
@LEOYoon-Tsaw 但編譯起來就特麻煩。make clean 之後還得重新弄一堆。
我不知道有哪些東西非得用 boost 來寫。

**Comment by LEOYoon-Tsaw** [comment]
> @LEOYoon-Tsaw 但編譯起來就特麻煩。make clean 之後還得重新弄一堆。
> 
> 我不知道有哪些東西非得用 boost 來寫。

只有librime的東西要用boost，前端不用boost寫。照著編譯方法編譯一次就行了，改前端以後只需編譯squirrel，不需重新編譯librime

**Comment by ShikiSuen** [comment]
@LEOYoon-Tsaw 感謝解釋。
威注音這邊的功能設計讓我有點忙不開，等得閒了我再看看。

**Comment by ShikiSuen** [comment]
我等了十分鐘編譯，就給我等出來了這個。真的很絕望。
威注音詞庫編譯用 python / awk / sort 等工具很慢，但主程式編譯也就一分鐘內的事情。
![image](https://user-images.githubusercontent.com/3164826/150170655-673af4ec-e67d-4eda-9ae4-6e30fe1b3e34.png)

**Comment by LEOYoon-Tsaw** [comment]
不是BUILD SUCCEED了麼？

**Comment by ShikiSuen** [comment]
螢幕截圖上顯示的是error。

**Comment by LEOYoon-Tsaw** [comment]
無所謂啦，反正我也沒看出你截圖的新注音有什麼UI是鼠鬚管做不到的，有的話等你做吧

**Comment by ShikiSuen** [comment]
@LEOYoon-Tsaw 目前的 RIME 的選字 UI 在客製化的時候可以實現描邊嗎？還是說必須動源碼？
我對 RIME 的 yaml 配置不熟，必須動 SquirrelPane.m 的話我再動手。
不過，被我改過的地方往往是無法用 yaml 自己客製化的，可能與 Rime 的哲學相違背。

**Comment by LEOYoon-Tsaw** [comment]
顏色設成半透明唄

**Comment by ShikiSuen** [comment]
那看來沒我的事情了。這討論串先關了。

**Comment by LEOYoon-Tsaw** [comment]
我用純swift寫過一個鼠鬚管UI配置器：https://github.com/LEOYoon-Tsaw/Squirrel-Designer
如果你熟悉swift可以fork了去試試，如果能做出有意思的改進，再考慮寫成Obj-C
