### ISSUE TITLE
Alacritty + Neovim 中 使用backspace删除拼音时，会删除已经输入的文字

### ISSUE THREAD

**Issue by vlaw** [rime/squirrel#617]
初始态如下；
![image](https://user-images.githubusercontent.com/56830/153339251-3ee476f2-211e-458e-8cfa-e5582ca42603.png)

使用backspace后，错误地删除了最后一位：**0**

![image](https://user-images.githubusercontent.com/56830/153339275-b94955e3-f5f5-4cbe-bb48-a493f9555ca0.png)

但(还原到了初始态)，使用 Control+h 无此问题

![image](https://user-images.githubusercontent.com/56830/153339387-446a8d76-1ff1-4a68-90dd-8b70c29f722e.png)

看起来于配置inline与否无关，

```yml
"style/inline_preedit": false
```

又或者

```yml
app_options:
  io.alacritty:
    no_inline: true
```

都有同样的情况。

**Comment by Eliot00** [comment]
這是Alacritty上游庫的問題https://github.com/alacritty/alacritty/issues/44
