### ISSUE TITLE
简体模式下部分字仍是繁体

### ISSUE THREAD

**Issue by SYQsb** [rime/squirrel#619]
设备：MacOS 12.2.1
鼠须管：0.15.2
输入法：明月拼音

在明月拼音调整为简体字后：
![image](https://user-images.githubusercontent.com/70281223/154835274-3b12d474-a54b-4d70-92be-b307fcff7f05.png)

<img width="645" alt="image" src="https://user-images.githubusercontent.com/70281223/154835261-c488e3ba-ffae-40ac-be67-9d79e5b06f35.png">

仍然有一些汉字处于繁体状态，比如tai'qi的选单中只有“擡起”，没有简体字选项
<img width="365" alt="image" src="https://user-images.githubusercontent.com/70281223/154835303-d632b7f0-d19c-4143-8d20-4def010f1f26.png">
在默认词库luna_pinyin.extended.dict.yaml文件中添加对应的简体字词语也无法更改

**Comment by iugo** [comment]
是的, 我用地球拼音也有这个问题.

不过多训练几次就可以了. 抬起抬起抬起~

**Comment by winduser** [comment]
我也遇到了此问题。请问现在有什么做法可以消除这个bug？

**Comment by LEOYoon-Tsaw** [comment]
> 我也遇到了此问题。请问现在有什么做法可以消除这个bug？

自己寫一個opencc字典，或者用同時包含簡繁字的方案

**Comment by LEOYoon-Tsaw** [comment]
有啊，倉頡

**Comment by lotem** [comment]
已經在 0.16 版本改正。
