### ISSUE TITLE
请问是否有可能支持一种特殊的ascii_mode，在使用option键时不会打出特殊字符

### ISSUE THREAD

**Issue by haosdent** [rime/squirrel#623]
您好，背景是这样的，目前在Mac上当使用ascii_mode或者系统默认的英文输入法时，使用`option+字母`会变成特殊字符。比方说`option+v`会变成`√`。
为解决这个问题，需要按照https://stackoverflow.com/questions/11876485/how-to-disable-generating-special-characters-when-pressing-the-alta-optiona 给系统价个单独的Layout。
但我在想squirrel本身有个layout，所以想请教下是不是有一种特殊的ascii_mode可以禁止掉`option+字母`变成特殊字符的情况，或者当前是否已经可以通过配置一些filters来做到类似的效果？
还请大佬们不吝赐教，提供下这个问题的解决建议。

**Comment by haosdent** [comment]
使用punctuator也无法避免输入√, @lotem @kidonng 大佬是否有啥建议吗

**Comment by lotem** [comment]
不是有解决方案嘛。自定义key map。输入法不同于键盘布局，两者可以搭配使用，而不是互换的关系。

**Comment by haosdent** [comment]
请问自定义key map 这个是rime的功能吗，还是是指用 https://karabiner-elements.pqrs.org？@lotem

**Comment by haosdent** [comment]
我其实在尝试改代码，在想是不是这里https://github.com/rime/squirrel/blob/54d872bd5c1d846e33ffca02a1d14f96cb5831e1/SquirrelPanel.m#L221 可以加个layout来避免需要系统中多一个layout的问题。

**Comment by lotem** [comment]
不是。
輸入法和自定義的系統鍵盤佈局不是同類的軟件。

**Comment by haosdent** [comment]
了解，多谢 @lotem
