### ISSUE TITLE
候选框能否设置向前偏移

### ISSUE THREAD

**Issue by Dreamer57** [rime/squirrel#631]
鼠须管：
<img width="127" alt="WX20220419-225932@2x" src="https://user-images.githubusercontent.com/9876662/164035029-a1624fe2-2659-46b8-927a-6e777b109f8e.png">
自带输入法：
<img width="116" alt="WX20220419-225955@2x" src="https://user-images.githubusercontent.com/9876662/164035045-d62f64c3-4af1-4f66-8d8c-edef0ef67bc2.png">

**Comment by Dreamer57** [comment]
还有一个问题，序号能否设定上下居中

**Comment by LEOYoon-Tsaw** [comment]
「候选框能否设置向前偏移」：不能，要改自己改
「序号能否设定上下居中」：我可以試一下

**Comment by Dreamer57** [comment]
@LEOYoon-Tsaw  大佬，我想改，能否指点一下。改哪个文件里的哪一行？

> 「候选框能否设置向前偏移」：不能，要改自己改 「序号能否设定上下居中」：我可以試一下

**Comment by LEOYoon-Tsaw** [comment]
SquirrelPanel.m，1135行附近

**Comment by Dreamer57** [comment]
> SquirrelPanel.m，1135行附近

@LEOYoon-Tsaw 

大佬，这里看起来好像是解决「序号能否设定上下居中」的位置，太复杂了，我看不懂。

我主要还是想解决「候选框能否设置向前偏移」，我找到921行，强行减了15，现在满足需求了。

大佬，那个序号居中的，我搞不定，而且我也不是很急，你能不能帮忙搞下，如果你不帮忙，那我就把这个问题关了。

**Comment by LEOYoon-Tsaw** [comment]
我做了，在我的倉庫裡，不過你也可以單獨做一下，也很簡單，在1558-1561行，baseoffset加上字號差

**Comment by Dreamer57** [comment]
@LEOYoon-Tsaw 

感谢大佬！我已经拷过来了！

再问下，怎么获取序号前面的长度（包括间隙，就是第一个候选字前面整个部分的长度数值）？

**Comment by LEOYoon-Tsaw** [comment]
在這文件裡搜一下labelWidth，不過這次你要想想怎麼把這個變量傳出來了

**Comment by Dreamer57** [comment]
> 在這文件裡搜一下labelWidth，不過這次你要想想怎麼把這個變量傳出來了

@LEOYoon-Tsaw 

大佬，labelWidth和第一个字之间，还有点间隔，还得再减4，这个间隔能获取到吗？

**Comment by Dreamer57** [comment]
<img width="110" alt="WX20220430-224545@2x" src="https://user-images.githubusercontent.com/9876662/166110294-ffbae63a-56b8-41b7-b328-10ac8acd73ea.png">
<img width="109" alt="WX20220430-224813@2x" src="https://user-images.githubusercontent.com/9876662/166110383-dbadff98-7c83-4b3c-83e7-2b952d4baade.png">

**Comment by LEOYoon-Tsaw** [comment]
這是你自己加的空格吧，算一個空格的長度，加上就行了

**Comment by Dreamer57** [comment]
@LEOYoon-Tsaw 

大佬找到了，是 border_width 设置的值，最终再减去 edgeInset.width，刚好合适。

问题都解决了，感谢大佬的帮助。

**Comment by lotem** [comment]
这不能叫解决吧。只是糊弄过去了。
要做到对齐光标，得反过来做，把光标位置传下去，所有布局的计算围绕这个基准座标开展。

**Comment by Dreamer57** [comment]
> 这不能叫解决吧。只是糊弄过去了。 要做到对齐光标，得反过来做，把光标位置传下去，所有布局的计算围绕这个基准座标开展。

不不不不，大佬，不对齐光标。起始位置对齐候选框第一个字，这样就很完美。

很棒，推荐加入鼠须管默认配置。

<img width="109" alt="image" src="https://user-images.githubusercontent.com/9876662/166499401-adbbf0fc-0fe5-4c47-a93f-6103e4e7d299.png">

苹果输入法就是这么设计的，他们的设计很精妙。

**Comment by Dreamer57** [comment]
<img width="62" alt="image" src="https://user-images.githubusercontent.com/9876662/166500699-9b7662f0-6822-4bc5-b14d-d84a2d7b588f.png">

推荐！

**Comment by Dreamer57** [comment]
<img width="67" alt="image" src="https://user-images.githubusercontent.com/9876662/166500938-fcacfa99-a5a0-4353-9244-a452b5aa2412.png">
