### ISSUE TITLE
请教大家，如何去除"全角"提示

### ISSUE THREAD

**Issue by pys1992** [rime/squirrel#634]
如图所示，符号是通过按键编码打出来的，怎么去除红色框标注的提示。
<img width="466" alt="image" src="https://user-images.githubusercontent.com/44765369/165656723-6ac79777-8b5e-46dd-b716-9e23d92f55e2.png">

**Comment by twio142** [comment]
一个 workaround：把提示字号设小一点（`comment_font_point`），颜色设为和背景同色（`comment_text_color`, `hilited_comment_text_color`）

**Comment by lotem** [comment]
绝对是通过符号翻译器定义的符号打出来的。而不是码表里的编码。
