### ISSUE TITLE
自己习惯默认使用粤拼的简体中文，但是默认是繁体中文，通过【Ctrl+ ~】切换之后，关机或者切换到其他APP 输入法还是要繁体中文，每次都要重新使用Ctrl+~切换一次，很麻烦

### ISSUE THREAD

**Issue by ColinWorld** [rime/squirrel#638]
自己习惯默认使用粤拼的简体中文，但是默认是繁体中文，通过Ctrl+`切换之后，关机或者切换到其他APP 输入法还是要繁体中文，每次都要重新使用Ctrl+`切换一次，很麻烦

**Comment by iDvel** [comment]
`switches:` 下面那块，简繁的 `reset` 改成 0 或 1 是不是就行了。

**Comment by ColinWorld** [comment]
> 

我的設置沒有這一項

**Comment by lotem** [comment]
原装方案会记忆在方案选单里选择的简繁状态。记忆的状态会在当前应用和以后打开的应用生效，而其他应用会保留原先的状态——因为也会有不同应用输入不同文字的需求，难以两全。不过这时候只要从输入法菜单选中「部署」就可以在所有应用里重置为保存的状态了。

如果发现切换后保存不住，有可能是配置里没有指定要保存这项状态。

**Comment by ColinWorld** [comment]
> 原装方案会记忆在方案选单里选择的简繁状态。记忆的状态会在当前应用和以后打开的应用生效，而其他应用会保留原先的状态——因为也会有不同应用输入不同文字的需求，难以两全。不过这时候只要从输入法菜单选中「部署」就可以在所有应用里重置为保存的状态了。
> 
> 如果发现切换后保存不住，有可能是配置里没有指定要保存这项状态。

每次切换到简体中文之后，选择输入法的【重新部署】，然后就会变回繁体中文，保存不住，不知道在哪里可以配置这项

**Comment by ColinWorld** [comment]
> `switches:` 下面那块，简繁的 `reset` 改成 0 或 1 是不是就行了。

我的設置沒有這一項。。。

**Comment by lotem** [comment]
原裝的配置會保存。你的設置沒有，那也是自選的，就別抱怨了吧。

https://github.com/rime/rime-jyutping/blob/50100769f645bf92afef5170e3bf42be5147b41b/jyutping.schema.yaml#L28
https://github.com/rime/rime-prelude/blob/dd84abecc33f0b05469f1d744e32d2b60b3529e3/default.yaml#L25
`default.yaml:/switcher/save_options: [simplification]` 表示`simplification`選項的狀態改變後要保存

**Comment by LEOYoon-Tsaw** [comment]
> 我的設置沒有這一項。。。
沒有就加上唄
