### ISSUE TITLE
与微软4000人体工学键盘的兼容性问题。

### ISSUE THREAD

**Issue by VMatrix1900** [rime/squirrel#64]
系统：Mac OS 10.10.4 
squirrel 设置成shift键切换中英文输入。
安装了[微软4000键盘](https://www.microsoft.com/hardware/en-us/p/natural-ergonomic-keyboard-4000)的[驱动](https://www.microsoft.com/hardware/en-us/p/natural-ergonomic-keyboard-4000#support)。
连接微软4000键盘时，执行cmd ＋ tab切换程序时会同时切换中英文输入。
应该是触发了shift键被按下的事件。而且不止一次。
因为在Android Studio中有一个快捷键：连按两次shift键会启动快速查找窗口。而每次切换到该程序，该窗口都会启动，这说明shift键按下的事件至少触发了两次。
以上情况仅出现在连接微软键盘时，且用内置键盘或者鼠标切换不同程序都会触发该bug。
其他键盘不存在这个问题。是不是squirrel和微软键盘的驱动有冲突？

**Comment by lotem** [comment]
和輸入法有關麼？按你的說法怎麼像是驅動的問題，Android Studio 和輸入法都收到了多餘的 Shift 鍵不是嘛。

**Comment by VMatrix1900** [comment]
应该有关，因为关闭squirrel之后就不会出现这个问题了。

**Comment by VMatrix1900** [comment]
现在即使关闭squirrel也会有这个问题，应该是驱动的问题。
