### ISSUE TITLE
候选栏长度异常

### ISSUE THREAD

**Issue by qq420100523** [rime/squirrel#640]
在屏幕右边输入时，候选栏会触发类似边沿吸附效果，
导致候选栏长度异常

鼠须管0.15.2

**Comment by yakirChen** [comment]
> 在屏幕右边输入时，候选栏会触发类似边沿吸附效果， 导致候选栏长度异常
> 
> 鼠须管0.15.2

![截屏2022-05-24 20 17 21](https://user-images.githubusercontent.com/22702893/170032723-3732bc42-6fde-4516-9050-7b28251f48bb.png)
还真有这效果 😄

**Comment by LEOYoon-Tsaw** [comment]
#639

**Comment by lotem** [comment]
合并同类项 https://github.com/rime/squirrel/issues/523
