### ISSUE TITLE
Rime無法正常啟動

### ISSUE THREAD

**Issue by 4e20h** [rime/squirrel#642]
如圖：
<img width="639" alt="image" src="https://user-images.githubusercontent.com/92664048/174085518-0d964617-573a-476b-9371-a349954fe156.png">

系統信息：
M1 Pro
MacOS Ventura Version 13.0 Beta

**Comment by lotem** [comment]
这条提示不是无法启动的意思。是说该输入法没有指定键盘布局。
这是符合设计的，如拼音等不依赖于字母在键盘上位置的输入法可以和用户选择的任意键盘配合使用。

**Comment by noyyyy** [comment]
> 如圖： <img alt="image" width="639" src="https://user-images.githubusercontent.com/92664048/174085518-0d964617-573a-476b-9371-a349954fe156.png">
> 
> 系統信息： M1 Pro MacOS Ventura Version 13.0 Beta

@yadeoxyribose 请问你解决了吗？我遇到了同样的问题
