### ISSUE TITLE
macOS 下左右 shift 键的映射好像有问题

### ISSUE THREAD

**Issue by twio142** [rime/squirrel#643]
`ascii_composer/switch_key`

1. 如下设置，则左、右 shift 键**都能**切换中英文：
```
Shift_L: commit_text
Shift_R: noop
```

2. 如下设置，则左、右 shift 键**都不能**切换中英文：
```
Shift_L: noop
Shift_R: commit_text
```

同时，Karabiner-Elements 能够正常区分左右 shift 键。

会不会是输入法对 Shift_R 键的键值录入有误？

**Comment by lotem** [comment]
同 https://github.com/rime/squirrel/issues/35
