### ISSUE TITLE
关于 fn + shift 的动作

### ISSUE THREAD

**Issue by jiapeng123456** [rime/squirrel#644]
shift 键现在是可以进行中英文切换的，但各个修饰键和 shift 组合的动作不一致。
- ctrl/cmd/opt + shift：ctrl/cmd/opt 其中任意一个键和 shift 一起按下的话，**不触发** shift 的中英文切换功能。
- fn + shift：这两个键同时按的话，**会触发** shift 的中英文切换功能。

请问如何让 fn + shift 同时按下情况下，不触发 shift 的中英文切换功能呢？
（因为使用了 fn 做了一些键盘映射，所以需要 fn + shift 同时按）

**Comment by lotem** [comment]
fn 应该是在硬件驱动或操作系统层面处理的按键。输入法里没有这个。
不清楚你说的用 fn 做键盘映射是怎么回事，这里值得关注的是发给输入法的按键是什么。
输入法按照默认设置，收到单击 shift 键的输入就切换状态。

**Comment by jiapeng123456** [comment]
谢谢
