### ISSUE TITLE
繁體字模式下使用「聽寫」時寫出的字是簡體字

### ISSUE THREAD

**Issue by binotaliu** [rime/squirrel#645]
在 macOS 下使用「聽寫」功能時，即使已將語言設定為「中文（國語 - 台灣）」，在聽寫時還是會寫出簡體中文。

![CleanShot 2022-06-25 at 21 12 22](https://user-images.githubusercontent.com/67255597/175774953-7816c2b6-e43c-4cb5-87e2-3f6c92693219.png)

![CleanShot 2022-06-25 at 21 14 17](https://user-images.githubusercontent.com/67255597/175775040-63ed88c8-f30d-4eac-8ccc-c0e026c0ca23.gif)

在偏好設定裡，鼠鬚管是被放在簡體中文裡的：
![CleanShot 2022-06-25 at 21 15 37](https://user-images.githubusercontent.com/67255597/175775069-ed1fca8a-c862-42d1-bc4b-7fbc41346253.png)

我想這可能是原因？我記得小狼毫能在安裝的時候可以選擇要安裝到繁體中文或簡體中文。鼠鬚管也能有這個選項嗎？

**Comment by LEOYoon-Tsaw** [comment]
我的[鼠鬚管](https://github.com/LEOYoon-Tsaw/squirrel)是在傳統中文下的。
<img width="524" alt="image" src="https://user-images.githubusercontent.com/4469383/175775761-1b5dac58-a010-4d22-a40a-566dd9ccafe4.png">
不可選，你也可以自己改代碼編譯

**Comment by binotaliu** [comment]
謝謝 @LEOYoon-Tsaw 的回覆。我看到你的 Commit：https://github.com/LEOYoon-Tsaw/squirrel/commit/0ce63747f910388722c5832d2cc90d6fdc424636 ，只要改 Info.plist 就可以了。

除了重新編譯沒別的辦法嗎？不能同時顯示在兩個語言下讓用家自己選擇？

**Comment by LEOYoon-Tsaw** [comment]
不能，只得擇一

**Comment by ShikiSuen** [comment]
@LEOYoon-Tsaw 可以的。威注音就是一套 app 對 plist 做手腳之後出兩個副本：
<img width="553" alt="image" src="https://user-images.githubusercontent.com/3164826/176102368-6b94c41c-6809-46cf-929c-7d44e0fc4009.png">
<img width="582" alt="image" src="https://user-images.githubusercontent.com/3164826/176102377-d7d737ab-4429-4546-a393-0a038e35495f.png">

參考結構如下：
https://github.com/ShikiSuen/vChewing-macOS/blob/main/Source/Resources/IME-Info.plist

要不是我這邊搞不定 Squirrel 編譯的話……欸。

**Comment by ShikiSuen** [comment]
我找到辦法了。稍後推 PR。

**Comment by ShikiSuen** [comment]
@binotaliu 您可以嘗試編譯這個 PR：https://github.com/rime/squirrel/pull/648
我測試發現繁體中文輸入模式下可以讓聽寫預設輸入繁體中文，前提是你用的是「鼠鬚管-繁」。

**Comment by ShikiSuen** [comment]
@binotaliu 該問題的修正已被 lotem 整合到 main / master branch，故結案。
