### ISSUE TITLE
原生 ⌥ u、⌥ e 等字符失效

### ISSUE THREAD

**Issue by twio142** [rime/squirrel#646]
在英文键盘和原生拼音键盘下，⌥ u 可以打出变音符 ¨（用于结合其他元音打出 ä, ö, ü 等字母）。但切换到鼠须管时就失效了。同样失效的还有 ´（⌥ e）和 `（⌥ `）等。

请问有什么方法可以恢复吗？我希望在鼠须管的英文模式下也可以打出这些符号。

谢谢 ◡̈

**Comment by LEOYoon-Tsaw** [comment]
切換輸入法唄

**Comment by ShikiSuen** [comment]
可能是下图当中的黄颜色边框的按键的字符敲不了了。

你自己检查一下鼠须管 IMKController 相关型别内的 handleEvent() 或者类似函数，看看是否有对这类字符的输出限制。
如果有的话，手动设为放行（return false）即可。

P.S.: 也可能是对 handleEvent() 所接收的 NSEvent 当中的输入讯号有 unicode 范围限制。如果是这样的话，将这几个字符弄成例外即可。

<img width="541" alt="截图 2022-06-28 13 30 01" src="https://user-images.githubusercontent.com/3164826/176100371-b9c82404-2118-4bbd-9125-66b2b6d9b12a.png">

**Comment by twio142** [comment]
> 你自己检查一下鼠须管 IMKController 相关型别内的 handleEvent() 或者类似函数，看看是否有对这类字符的输出限制。
> 
> P.S.: 也可能是对 handleEvent() 所接收的 NSEvent 当中的输入讯号有 unicode 范围限制。如果是这样的话，将这几个字符弄成例外放行（return false）即可。

@ShikiSuen 可以请教一下具体怎么操作吗？

**Comment by ShikiSuen** [comment]
@twio142 我需要检查一下鼠须管的 IMKController 的具体实作方式。
顺利的话，大概这周能搞定。但你先用别的方法凑合。

**Comment by ShikiSuen** [comment]
我在 handleEvent 裡面加上了 charCode 配對效驗，測試無效。
keyCode 配對效驗也無效。
這種「理論上有效卻實際上無法生效」的情況，恐怕得請 @lotem 看看了。ObjC 對我而言還是比較棘手的。

```objc
    // ignore certain combinations with Option+X / Alt+X hotkeys. [GitHub Issue #646]
    if ([@[@"´", @"¨", @"ˆ", @"˜"] containsObject:event.characters]) return NO;
```
<img width="694" alt="image" src="https://user-images.githubusercontent.com/3164826/176121356-1b25662f-2841-4cfb-a7e5-f9b1a640c27f.png">

**Comment by twio142** [comment]
好的，还是谢谢你啦 :)

**Comment by groverlynn** [comment]
> 我在 handleEvent 裡面加上了 charCode 配對效驗，測試無效。 keyCode 配對效驗也無效。 這種「理論上有效卻實際上無法生效」的情況，恐怕得請 @lotem 看看了。ObjC 對我而言還是比較棘手的。
> 
> ```objc
>     // ignore certain combinations with Option+X / Alt+X hotkeys. [GitHub Issue #646]
>     if ([@[@"´", @"¨", @"ˆ", @"˜"] containsObject:event.characters]) return NO;
> ```
> 
> <img alt="image" width="694" src="https://user-images.githubusercontent.com/3164826/176121356-1b25662f-2841-4cfb-a7e5-f9b1a640c27f.png">

根據[官方文檔](https://developer.apple.com/documentation/appkit/nsevent/1534183-characters?language=objc)，dead key的keyDown.character為空，似乎是因為UTF-8不夠用，需要UTF-16。[這裏](https://developer.apple.com/documentation/coreservices/carbon_core/unicode_utilities?language=objc)有解釋。
如果想要調用UCKeyTranslate來處理dead key，似乎需要換另一套protocol。不能只處理單個的keyDown，而需要用[interpretKeyEvents](https://developer.apple.com/documentation/appkit/nsresponder/1531599-interpretkeyevents)處理一整串。

不過如果鍵盤佈局是USExtended（也就是ABC – Extended），雖然看不到黃底的dead key，但繼續打後面的按鍵，就能打出正確的帶變音符的字母。但是我試了一般的歐洲鍵盤都不行。
