### ISSUE TITLE
授权窗口如何默认英文

### ISSUE THREAD

**Issue by harisonkhlil** [rime/squirrel#647]
已经把本机自带的 ABC 删除了
![SCR-20220628-ej2](https://user-images.githubusercontent.com/70578017/176078547-173121a1-ad87-4a4b-8995-cdd700a20688.jpeg)
如同截图所指，授权窗口默认为中文，每次输入密码或者用户名都要切换中英文

**Comment by harisonkhlil** [comment]
> ![SCR-20220628-ej2](https://user-images.githubusercontent.com/70578017/176078547-173121a1-ad87-4a4b-8995-cdd700a20688.jpeg) 如同截图所指，授权窗口默认为中文，每次输入密码或者用户名都要切换中英文

主要还是没有找到这个窗口的程序id

**Comment by darvintang** [comment]
com.apple.SecurityAgent:
        ascii_mode: true
    com.apple.authorizationhost:
        ascii_mode: true
