### ISSUE TITLE
输入法图标显示模糊

### ISSUE THREAD

**Issue by scomper** [rime/squirrel#658]
升级到 macOS Ventura 13.0 (22A5321d) 以后，菜单栏鼠须管图标显示模糊。
鼠须管版本：0.15.2
![](https://media.cleanshot.cloud/media/149/B2XBk70LyydVqrnHNaWlxoDLWhninRsRsNsTr3MY.jpeg?Expires=1660029205&Signature=l5dEkB~sQevAsCcU2ahTsmqkLVv3uU5slZhFfpvPMjAvukuU7YfUzAlJU2Sry8OXE2DwPCp9vtrYmgb27vH3J87OYmDyVJw~ijGlCHCNrg~16UnIZPOcwtnANFCNWclx1mFVwi3sWzhGiUhCWnwEWHajn7Yr~Sfn7jfcRfKI4LKJ4aet67PaMgF~EtAhQrxjg8ni7G0NkuH44k9MqLXZ2reVdn4KZaLkV~9sAcAswQ9eYMCC9-wsWul9Z2JvUiKw855d9Y8ZmVTe~stpFf3K2hgKMFjLiaCAgei-s3yQLoqCDO~Ri4vSAWm0vncF03sjTPi8Pg7QNsydq3AwiHTwcA__&Key-Pair-Id=K269JMAT9ZF4GZ)

**Comment by scomper** [comment]
重启后恢复正常

**Comment by mingcheng** [comment]
但是因为尺寸修改了，会扇动
