### ISSUE TITLE
针对输入框在屏幕底部的情况上下抖动

### ISSUE THREAD

**Issue by meteorlad** [rime/squirrel#662]
当输入框在屏幕最底部时，输入框上下抖动，这个有办法解决么？

**Comment by LEOYoon-Tsaw** [comment]
不要在最底下

**Comment by lotem** [comment]
說的是候選窗高度變化吧？
內容變化時高度有可能變化。這一點對於在屏幕的哪個位置都一樣會發生。
避免高度變化有兩個因素：
一是候選行數不變——如果是最後一頁候選字數量發生變化，那候選窗大小變化也是難免的；
二是候選行數相同，如果用以渲染候選字的字體不一致，也可能導致候選窗高度輕微變動。

**Comment by llity** [comment]
有图标出现，候选窗不停的变高、变矮

**Comment by LEOYoon-Tsaw** [comment]
我改的版本應該是不會因爲繪文字🈶抖了，不過我不怎麼用橫排，不100%保證
