### ISSUE TITLE
考慮給鼠鬚管新增一個選項、允許使用者藉由圖形介面設定來決定預設的 macOS 鍵盤佈局。

### ISSUE THREAD

**Issue by ShikiSuen** [rime/squirrel#663]
今天有收到这个投诉
```
發現一個問題：我有用鼠須管，有時在威注音打一打，再切鼠須管時，我鼠須管就只能打出「注音文」，但我會再多試試
```
这个问题关键之一在于鼠须管有没有在 IMKInputController 派生型别的 activateServer() 环节对当前键盘布局做强制覆写。
威注音无法直接插手接管其它输入法的这个过程，所以只能在鼠须管这边修。

> 但是，setValue 的话，威注音确实需要做些调整。

刚刚看了仓库当中的 InputController，发现确实不是强制覆写的。
（需要考慮到有人會喜歡用 DVORAK 或 COLEMAK 敲拼音的情況。）
https://github.com/rime/squirrel/blob/fb7e36d61a09f376f2792d6a43e837c838ed7bbb/SquirrelInputController.m#L271-L278
不强制覆写的话，鼠须管的 macOS 基础键盘布局可能就会受到其它输入法的影响。
（威注音预设情况下是会用「Apple 注音键盘布局」的，这样可以实现荧幕虚拟键盘的同步映射显示支持。）

我决定动手推个 PR 来解决这问题：新增一个输入法选单项与弹窗，在其中允许使用者决定：
```
「是否绕过鼠须管配置档案、而强制覆写为指定的 macOS 键盘布局。」
```
**但因为我只有 Xcode 14，所以我这个 PR 可能会将鼠须管的最低系统需求提升至 macOS 10.13**……
……除非我不用 Swift Package。
而且，因为我只熟 Swift （与 C#），我这边写的很多与 IMK 有关的工具也都只有 Swift 的，
所以这个 PR 推了之后，鼠须管每次编译时都会打包 Swift 5 Runtime，体积会肥一些。

注意：这个强制覆写不可以在当前 client() 为输入法本体的时候进行，否则会在每次显示输入法自身的当前视窗的时候出现几秒钟的无限 loop 僵死。

**Comment by ShikiSuen** [comment]
暂时搁置。原因：目前的主分支可能与 Xcode 14 有相容性问题。
我这边建置的时候，Xcode GUI 卡死在 Linking 这个步骤不动了：
<img width="521" alt="image" src="https://user-images.githubusercontent.com/3164826/194261001-854cd20a-60ab-4028-a71a-3d626e3d7418.png">

用命令行建置的时候，卡死在 "Create build description" 不动了。

**Comment by ShikiSuen** [comment]
我稍後會準備推送 PR。目前還在測試功能。

使用者指定鍵盤佈局時的終端指令為：
```
defaults write im.rime.inputmethod.Squirrel BasicKeyboardLayout -string "com.apple.keylayout.Colemak"
```
需要指定為美規鍵盤的話：
```
defaults write im.rime.inputmethod.Squirrel BasicKeyboardLayout -string "com.apple.keylayout.ABC"
```

**Comment by lotem** [comment]
鉴于大部分自定义选项采用YAML文件配置方式，暂不考虑单独为这项功能提供图形配置界面。
