### ISSUE TITLE
no member named 'get_state_label' in 'struct rime_api_t'

### ISSUE THREAD

**Issue by nasyxx** [rime/squirrel#671]
```
...
/Users/Nasy/src/squirrel/SquirrelApplicationDelegate.m:90:47: error: no member named 'get_state_label'
      in 'struct rime_api_t'
    const char *state_label = rime_get_api()->get_state_label(session_id, option_name, state);
...
```

最近更新了macOS系统，重新编译的时候发现这个问题。主要是要更新一下仓库里面的 librime commit（这是6月的 commit https://github.com/rime/squirrel/commit/cfcd4eec55f0917d0d8471878bbb6c02ca186883 引入的问题，librime 那边是 https://github.com/rime/librime/commit/8f9e9c7cbd0ecf8761540d1db9d2c8ab9473f8dc

**Comment by LEOYoon-Tsaw** [comment]
更新一下librime就行，錨定的librime版本沒更新

**Comment by nasyxx** [comment]
对，但是还有其它乱七八糟的问题，我现在去用你的那个 fork 了。不知道有没有什么特别不同的地方？

**Comment by LEOYoon-Tsaw** [comment]
我那邊的librime在豎排（vertical）下方向鍵轉了90°，@lotem 說他有更好的實現，就一直沒merge，這是librime上我的fork和這裡唯一的區別
其他的都是在前端上加的新功能，只涉及squirrel.yaml，而且向後兼容，想用就用，用不上也不需要關心

**Comment by nasyxx** [comment]
啊哈，刚好，我记得之前我本地的就是加了你那个移动的。

说起前端，新系统上

`hilited_candidate_back_color`

不起作用了。如果乃什么时候更新了系统有空的话，看一看

**Comment by LEOYoon-Tsaw** [comment]
沒有失效呀，我剛試了一下，我也是昨天升上Ventura的

**Comment by nasyxx** [comment]
看看我这个

```
      name: "nasy"
      font_face: "Kaiti SC, Kaiti TC, Source Han Serif TC, Source Han Serif SC"
      font_point: 18.0
      label_font_face: "Kaiti SC, Kaiti TC, Source Han Serif TC, Source Han Serif SC"
      label_font_point: 17.0
      comment_font_point: 17.0
      candidate_list_layout: stacked
      text_orientation: vertical
      inline_preedit: true
      inline_candidate: false
      translucency: true
      mutual_exclusive: true
      corner_radius: 3.0
      border_height: 12.0
      border_width: 12.0
      line_spacing: 2.0
      spacing: 2.0
      base_offset: 1.0
      alpha: 1
      shadow_size: 3.0
      color_space: srgb
      back_color: 0xDCECF3
      candidate_back_color: 0xDCECF3
      candidate_text_color: 0x6E624C
      comment_text_color: 0x709C2F
      label_color: 0x8070FF
      hilited_candidate_back_color: 0xBCDBE5
      hilited_candidate_text_color: 0xB50C8C
      hilited_comment_text_color: 0xB50C8C
      hilited_candidate_label_color: 0xB50C8C
      preedit_back_color: 0xDAF1E8
      text_color: 0x6E624C
      hilited_text_color: 0xD86E624C
```
<img width="608" alt="Screenshot 2022-10-25 at 6 06 04 PM" src="https://user-images.githubusercontent.com/5007613/197898439-f5346427-4390-45a4-a2dc-f0726853d350.png">

<img width="768" alt="Screenshot 2022-10-25 at 6 05 52 PM" src="https://user-images.githubusercontent.com/5007613/197898458-51447e0f-51ba-410e-bdc3-1be1da7621f5.png">

**Comment by nasyxx** [comment]
> 沒有失效呀，我剛試了一下，我也是昨天升上Ventura的

我顺着试了一下，问题出在 `text_orientation`

`text_orientation: vertical` 时，就消失了。

<img width="269" alt="Screenshot 2022-10-25 at 10 34 05 PM" src="https://user-images.githubusercontent.com/5007613/197928521-d0f87ecf-5d82-431a-9480-bd562d5d1ee9.png">

<img width="612" alt="Screenshot 2022-10-25 at 10 34 18 PM" src="https://user-images.githubusercontent.com/5007613/197928740-e5c9d7d9-94b6-458e-bd18-d1ebebd1b03c.png">

**Comment by LEOYoon-Tsaw** [comment]
<img width="183" alt="image" src="https://user-images.githubusercontent.com/4469383/200065686-e2e5ee55-7606-40a3-897f-62631de3a211.png">
可是我這真沒有這個問題……不知道怎麼回事儿

**Comment by nasyxx** [comment]
> 可是我這真沒有這個問題……不知道怎麼回事儿

我重新编译了一遍（现在好了，不知道之前是怎么了，也许是 xcode 版本问题？

<img width="375" alt="Screenshot 2022-11-04 at 4 30 55 PM" src="https://user-images.githubusercontent.com/5007613/200078078-c72441a0-692c-4fd0-a8c3-b66eeafdfdbc.png">
