### ISSUE TITLE
在新版的 macOS Ventura 下的图标抖动问题

### ISSUE THREAD

**Issue by mingcheng** [rime/squirrel#672]
如题，可能因为输入法图标的宽度尺寸更改了，所以切换输入法的时候会造成菜单栏抖动，截图如下。

![image](https://user-images.githubusercontent.com/21816/197904562-dd0c2e7b-c292-43b3-8b07-d0649e5ca8cb.png)

目前的使用版本是 squirrel: 0.15.2

**Comment by llity** [comment]
确实有这个情况

**Comment by LEOYoon-Tsaw** [comment]
爲Ventura改了的話，老系統又要抖動了，可怎麼辦呢

**Comment by Dreamer57** [comment]
两张图，安装的时候判断？

**Comment by llity** [comment]
自定义 icon

**Comment by Dreamer57** [comment]
啥时候动手呀。当然我不是催哈，我只是比较期待。

**Comment by LEOYoon-Tsaw** [comment]
> 啥时候动手呀。当然我不是催哈，我只是比较期待。

期待就自己做

**Comment by MaxChang3** [comment]
想临时修改下。

查：`/System/Library/Input Methods/SCIM.app/Contents/PlugIns/SCIM_Extension.appex/Contents/Resources/pinyin.tiff`。 

发现还是原来比例的图标。 

如果能找到新图标的位置或者具体尺寸，可以临时先 diy 一个。

**Comment by LEOYoon-Tsaw** [comment]
我嘗試過一下，似乎沒找到正確方式，改出來仍然略有不同，遂放棄

**Comment by groverlynn** [comment]
> 想提取内置输入法的图标修改来临时过渡。
> 
> 查：`/System/Library/Input Methods/SCIM.app/Contents/PlugIns/SCIM_Extension.appex/Contents/Resources/pinyin.tiff`。
> 
> 发现还是旧比例的 icon，不知道是换位置了还是修改了相关设计（例如动态生成/ 根据当前图标填充宽度？）。
> 
> 如果能找到新图标的位置或者具体尺寸，可以临时先 diy 一个。
> 
> ref:
> 
> #130
> 
> http://ssnhd.com/2022/01/06/sogou-logo/
> 
> https://groups.google.com/g/ukelele-users/c/eaRWJVrsO_A

新的icon應該是用的SF Symbol字體實現的，而且是動態的。比如只有德語瑞士鍵盤或只有法語瑞士鍵盤的時候均顯示為`CH`，同時有德語瑞士鍵盤和法語瑞士鍵盤的時候，分別顯示為`CHDE`和`CHFR`。

**Comment by lotem** [comment]
綜合大家提供的信息，我覺得沒必要追求一致的尺寸了。
我現在的設置是顯示輸入法名稱，切換時也無法對齊文字。這樣的結果應該是蘋果公司設計中考慮到的情況。

**Comment by mingcheng** [comment]
> 綜合大家提供的信息，我覺得沒必要追求一致的尺寸了。 我現在的設置是顯示輸入法名稱，切換時也無法對齊文字。這樣的結果應該是蘋果公司設計中考慮到的情況。

但是菜单栏切换的时候跳动挺难受的，有无好的兼容和解决方案

**Comment by kj-creater** [comment]
Ventura 13.1 切换已经不抖动了

**Comment by lotem** [comment]
蘋果公司修好了。
