### ISSUE TITLE
如何关闭输入光标后面的下划线字符?

### ISSUE THREAD

**Issue by imkerberos** [rime/squirrel#676]
如图所示:
<img width="209" alt="image" src="https://user-images.githubusercontent.com/636187/202328219-e6a035d2-7ace-4e73-8ccd-48a309f17998.png">
光标后有一个下划线, 应该是某个版本增加的, 这个非正常字符导致我的 texmacs 在输入中文的时候卡顿.
<img width="368" alt="image" src="https://user-images.githubusercontent.com/636187/202328603-5a319d7f-27e6-4b52-a63d-96a77be32e1d.png">
如何在配置文件中关闭?

**Comment by groverlynn** [comment]
改用內嵌編碼模式

```
#squirrel.custom.yaml
patch:
  style/inline_preedit: true
```
