### ISSUE TITLE
Move suggestions location closer to typing

### ISSUE THREAD

**Issue by hueykwik** [rime/squirrel#680]
Repro:

Type Chinese in Google Docs using Squirrel

Expect:

Suggestions should appear near where I'm typing (like the default IME)

Actual:

Appear near left corner of browser window 

![image](https://user-images.githubusercontent.com/707311/205227604-3fca1185-3b63-4c8e-84d2-9132a73088cd.png)

**Comment by LEOYoon-Tsaw** [comment]
it seems I'm having no such trouble
<img width="711" alt="image" src="https://user-images.githubusercontent.com/4469383/204390345-63d98267-ae2a-4cbd-a110-13d289cf7ee1.png">

**Comment by hueykwik** [comment]
I attached a screenshot above.

**Comment by LEOYoon-Tsaw** [comment]
There's nothing I can do, cause I can't reproduce the issue.
Maybe someone else can help.

**Comment by lotem** [comment]
鉴于系统自带输入法在用Chrome浏览器运行的Google文档里也无法准确定位，这个BUG应由Google而非吾辈解决。
