### ISSUE TITLE
鼠须管基于github云编译的方法

### ISSUE THREAD

**Issue by red-apricot** [rime/squirrel#684]
国内github访问不是很友好，可不可以搞一个基于github云编译的文档，对代码小白提供一定的帮助

**Comment by lotem** [comment]
原來用的Travis CI。後來不能用了，就準備遷移到GitHub Actions。librime已經遷移完了，squirrel這部分還沒做好。

**Comment by lotem** [comment]
GitHub Actions 已经启用。
