### ISSUE TITLE
版本不支持，怎么解决

### ISSUE THREAD

**Issue by red-apricot** [rime/squirrel#685]
/Users/lionel/squirrel/librime/build/rime.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.9, but the range of supported deployment target versions is 10.13 to 13.1.99. (in target 'rime_patch' from project 'rime')

**Comment by LEOYoon-Tsaw** [comment]
用Xcode打開，改一下target OS唄

**Comment by red-apricot** [comment]
编译好了，现在安装上了，有两个问题：
1. 不确定是不是下载的源码有缺失，编译的app无法自定义配置。
2. 每次进入电脑，都会有语音播报，播报完成后，才可以打字。
3. 稳定性较差，经常崩溃，打不出字，连字母也不会出现。重新安装即可恢复。

**Comment by LEOYoon-Tsaw** [comment]
所謂「語音」是程序崩潰。當然是有問題的，我也不知道你的問題在哪，如果不熟悉編譯或許直接用release的吧

**Comment by red-apricot** [comment]
我也實在是折騰的夠嗆，想要諮詢一下，近期有沒有推出新板本的計劃，如果有的話，我就靜待佳音了
