### ISSUE TITLE
No member named 'get_state_label' in 'struct rime_api_t'

### ISSUE THREAD

**Issue by red-apricot** [rime/squirrel#689]
编译过程报错，没有找到 get_state_label 

// option change
  if (!strcmp(message_type, "option")) {
    show_status_message(message_value, message_type);
    Bool state = message_value[0] != '!';
    const char* option_name = message_value + !state;
    const char *state_label = rime_get_api()->get_state_label(session_id, option_name, state);
    if (state_label) {
      show_status_message(state_label, message_type);
    }
  }

**Comment by LEOYoon-Tsaw** [comment]
更新librime

**Comment by red-apricot** [comment]
执行 make -C librime xcode/thirdparty/boost 会报 curl: (60) SSL certificate problem: certificate has expired 证书过期
我不确定这是我电脑的问题还是什么

**Comment by LEOYoon-Tsaw** [comment]
> make -C librime xcode/thirdparty/boost

沒用過這命令

**Comment by red-apricot** [comment]
<img width="709" alt="截屏2022-12-18 11 51 09" src="https://user-images.githubusercontent.com/34258184/208280466-c833b93d-775f-44da-8153-28480d3961a2.png">
就是管方文档里的啊

**Comment by oniondelta** [comment]
一看到 thirdparty 和 boost_1_75_0 就是對舊版 librime 的編譯
新版 librime 已經是不同路徑

[鼠鬚管主程式編譯](https://github.com/oniondelta/Onion_Rime_Files/wiki/%E9%BC%A0%E9%AC%9A%E7%AE%A1%E4%B8%BB%E7%A8%8B%E5%BC%8F%E7%B7%A8%E8%AD%AF)

**Comment by LEOYoon-Tsaw** [comment]
不要用Squirrel指定的librime，那個一年未更新了，要用最新的librime，master分支
