### ISSUE TITLE
Squirrel quit unexpectedly on El Capitan

### ISSUE THREAD

**Issue by jianlingzhong** [rime/squirrel#69]
在 El Capitan 上 Squirrel 经常出现 quite unexpectedly 的错误，尤其是在切换输入法的时候：

<img width="994" alt="screen shot 2015-10-05 at 10 07 25 pm" src="https://cloud.githubusercontent.com/assets/12853307/10298466/88d26648-6bad-11e5-9153-30d6614b12ac.png">

It still works after clicking OK for most of the time. But sometimes it stops working, like just now...

Is there any fix for this?
Thanks!

**Comment by jakwings** [comment]
可能是升級系統時某些系統生成的輸入法臨時配置文件被改亂了（不是鼠鬚管自行生成的那些）。假如你是直接升級到 El Capitan 的話，不妨試試卸載輸入法後（包括刪除 `/Library/Input Methods/Squirrel.app`）重啓兩次電腦後再安裝一次，或者卸載並將硬盤格式化重裝系統。

我之前升級 10.10.3 時有類似的問題。現在用的是自己編譯的版本，也格盤重裝過，至今未有崩潰報告。

**Comment by jianlingzhong** [comment]
按照你说的删除 /Library/Input Methods/Squirrel.app 之后重启电脑两次之后重新安装 Squirrel.app。问题仍然存在。暂时就先不用Squirrel了。

**Comment by lotem** [comment]
看报告，可能跟字体有关。

**Comment by jianlingzhong** [comment]
最近一次系统升级之后似乎解决了这个问题：Squirrel又可以正常使用。
