### ISSUE TITLE
Mac Ventura 下JetBrains等Java应用修改过info.list英文仍然大写

### ISSUE THREAD

**Issue by Kahen** [rime/squirrel#690]
我已经根据以前的issue修改过info.list
<img width="647" alt="image" src="https://user-images.githubusercontent.com/48155854/208822186-4569a07f-8e82-45a0-8255-72506322550b.png">
<img width="448" alt="image" src="https://user-images.githubusercontent.com/48155854/208822218-f21a5d59-c19a-4d66-b88a-4de35d228e39.png">
<img width="640" alt="image" src="https://user-images.githubusercontent.com/48155854/208822253-9e0d5b51-6019-4bff-878c-be07067d6857.png">
<img width="640" alt="image" src="https://user-images.githubusercontent.com/48155854/208822274-a358de84-2704-4a52-a29b-6f8b201c2882.png">
在一番操作完了之后，在JAVA应用下英文仍然大写

**Comment by ShikiSuen** [comment]
换 OpenJDK 再试试看？
