### ISSUE TITLE
playcover应用内无法输入中文，shift键切换无效

### ISSUE THREAD

**Issue by shpirt** [rime/squirrel#692]
机型: Macbook Pro 14 inch M1 pro
macOS 版本：macOS 13.1
playcover版本：2.0.2
测试应用：墨墨背单词

**Comment by puttin** [comment]
我本地Drafts v35.0.2 macOS13.1 arm64也无法打字

上台电脑是好的（Intel macOS 13.1）
不确定是不是我自己源码用最新librime编译引入的问题
换系统输入法行为正常

**Comment by shpirt** [comment]
> 我本地Drafts v35.0.2 macOS13.1 arm64也无法打字
> 
> 上台电脑是好的（Intel macOS 13.1） 不确定是不是我自己源码用最新librime编译引入的问题 换系统输入法行为正常

我用drafts倒是没问题。
