### ISSUE TITLE
New Aspect Ratio for Manu Bar Icon

### ISSUE THREAD

**Issue by YS-Wong** [rime/squirrel#701]
macOS Ventura adopts new menu bar icon format for input method. Now, the icon should look more rectangular instead of square. `rime.pdf` might be to update.

<img width="358" alt="Input Method Dropdown Menu on macOS Ventura" src="https://user-images.githubusercontent.com/16183548/215363879-2634801b-95af-43bc-bfcd-35828862f628.png">

**Comment by LEOYoon-Tsaw** [comment]
This might be the best compromise to serve both people running older OS and people running Ventura.
That said, I have a version that drops support for all macOS before Ventura, and adopts a wider icon. You can try it out if you want

**Comment by YS-Wong** [comment]
@LEOYoon-Tsaw Thanks for telling me that! I think I’m going to opt in to your version for now.

**Comment by vatnid** [comment]
> This might be the best compromise to serve both people running older OS and people running Ventura. That said, I have a version that drops support for all macOS before Ventura, and adopts a wider icon. You can try it out if you want

How did you make this PDF? I am looking to do the same with some of my other keyboards.

**Comment by LEOYoon-Tsaw** [comment]
With Adobe Illustrator
