### ISSUE TITLE
更新服务器信息未同步？

### ISSUE THREAD

**Issue by lovelock** [rime/squirrel#702]
刚刚升级（自己编译）了最新版本的0.16.1，点击
<img width="310" alt="image" src="https://user-images.githubusercontent.com/2208731/215699899-4f923226-afb5-4e92-b6ed-8a4bb460e113.png">
发现提示是这样的
<img width="372" alt="image" src="https://user-images.githubusercontent.com/2208731/215699955-ba452396-8baa-4841-9fc2-b15fc7c784a2.png">

负责检查更新的服务器没有同步到最新的版本更新？

**Comment by lotem** [comment]
没有。
需要充分验证新版本再推送给全球用家。
