### ISSUE TITLE
鼠须管更新到 0.16.1 之后候选栏中的表情符号无法加载

### ISSUE THREAD

**Issue by scomper** [rime/squirrel#703]
查了 ERROR 日志，提示 opencc 配置文件找不到，但是路径指向的文件是正常的。
E20230201 22:17:29.566795  8274 simplifier.cc:45] opencc config not found: /Users/scomper/Library/Rime/opencc/emoji.json

**Comment by lotem** [comment]
我试过简繁转换可以工作，说明这条码路是通的。会不会是 opencc 升级后旧的 `.ocd` 格式不兼容？

**Comment by yzlnew** [comment]
[这里](https://github.com/wongdean/rime-settings#4emoji-%E7%9A%84%E7%9B%B8%E5%85%B3%E9%97%AE%E9%A2%98)有写。不过我把 `luna_pinyin.custom.yaml` 里面的 emoji_suggestion reset 改为 0，之后还是显示不了 Emoji。

**Comment by LEOYoon-Tsaw** [comment]
參攷 #708

**Comment by yzlnew** [comment]
> 參攷 #708

感谢，可以了，请问有办法让 tips 显示简体吗？

**Comment by LEOYoon-Tsaw** [comment]
tips倒是可以關掉，但不能轉換簡繁

**Comment by LEOYoon-Tsaw** [comment]
> > 參攷 #708
> 
> 感谢，可以了，请问有办法让 tips 显示简体吗？

能說說具體是怎麼操作之後就可以了嗎？也許可以幫到其它人😈

**Comment by yzlnew** [comment]
我执行了一次手动安装 [rime-emoji](https://github.com/rime/rime-emoji)，完全替换掉 `opencc` 文件夹内的内容， 然后把 `emoji_suggestion.yaml` 里面的内容添加到 `luna_pinyin.custom.yaml` 就好了。
之前的配置 emoji 联想太少了，并且会有同一个词联想到一串 emoiji 导致打字翻页的情况，换了之后联想词表丰富和适当许多，建议大家都使用 `rime-emoji`。

**Comment by lirenchong** [comment]
采用以上各位的各种方法无效之后，看到`emoji_suggestion.yaml`第一行代码：

# encoding: utf-8

从GBK字符集切换到`utf-8`，emoji显示出来了😂

换字符集的目的，是减少超大字符集的生僻字数量，结果更新后导致这个字符集不支持emoji的锅🤔

供参考

**Comment by curoky** [comment]
我这边基本实锤了，我用的 rime-symbols ，里面有个重复的符号注释，删除之后就解决了。https://github.com/fkxxyz/rime-symbols/pull/3

https://github.com/rime/squirrel/issues/708 里面有一些讨论。
