### ISSUE TITLE
mac 提取搜狗备份词库 xxx.bin转 鼠须管 词库  自测完全ok

### ISSUE THREAD

**Issue by wangz-code** [rime/squirrel#705]
MacBook Air (M1, 2020)  12.5 macos Monterey
搜狗输入法 v6.6.0.13588  
python版本  Python 3.8.9

使用这个仓库  https://github.com/h4x3rotab/Sogou-User-Dict-Converter

` python3 parse.py <input-bin-dict> <output-tsv>`

原作的代码输出有些许出入, 我不确定 [鼠须管] 能否正确识别, 

修改两行就能输出鼠须管格式相同的字典 
参考 https://github.com/wangz-code/Sogou-User-Dict-Converter/commit/aee2f17f98f183840fb21d45ade85d9638c3937f

**Comment by lotem** [comment]
善哉
