### ISSUE TITLE
0.61.1  在系统 Menu Bar 中展示的文字变小了, 看起来好难受

### ISSUE THREAD

**Issue by xqin** [rime/squirrel#706]
iMac,  10.15.7 下的效果:

Squirrel 升级后:

<img width="376" alt="image" src="https://user-images.githubusercontent.com/1265888/216216274-2819f9da-5119-4f91-a729-ce0e4954db6a.png">

系统英文输入法 ABC

<img width="349" alt="image" src="https://user-images.githubusercontent.com/1265888/216216306-68706eac-d000-4cff-bc9c-2be556b2b473.png">

---

M1, 13.2

Squirrel 升级前:

<img width="353" alt="image" src="https://user-images.githubusercontent.com/1265888/216216543-c09b7004-6997-4c24-a0c3-6712bac4c678.png">

Squirrel 升级后:

<img width="511" alt="image" src="https://user-images.githubusercontent.com/1265888/216217055-aa21cfcd-7028-4337-9013-7f184dedcb64.png">

**Comment by LEOYoon-Tsaw** [comment]
因爲變長了。

**Comment by lotem** [comment]
考虑再改改。

还有一个注册到繁体粤语的PR，到时候就有三个输入法注册项，中文名也不得不想办法区分。

**Comment by LEOYoon-Tsaw** [comment]
或者不必區分了，就是個標簽而已，選哪個沒有任何實質影響

**Comment by lotem** [comment]
> 或者不必區分了，就是個標簽而已，選哪個沒有任何實質影響

就怕添加输入法的界面分不清楚。

**Comment by lotem** [comment]
关联 https://github.com/rime/squirrel/pull/696

**Comment by LEOYoon-Tsaw** [comment]
> > 或者不必區分了，就是個標簽而已，選哪個沒有任何實質影響
> 
> 就怕添加输入法的界面分不清楚。

添加時應該都會在相應的語言下，可以測試一下

**Comment by lotem** [comment]
> 測試一下

一旦启用了多个，在选输入法的界面就分不清了。

**Comment by LEOYoon-Tsaw** [comment]
> > 測試一下
> 
> 一旦启用了多个，在选输入法的界面就分不清了。

任意刪到只剩一個就好吧

**Comment by lotem** [comment]
> > > 測試一下
> > 
> > 
> > 一旦启用了多个，在选输入法的界面就分不清了。
> 
> 任意刪到只剩一個就好吧

那要是想启用繁体中文和繁体粤语两项呢，认不出来，没法切换。

**Comment by LEOYoon-Tsaw** [comment]
沒有必要嘛，背後都是一樣的東西

**Comment by lotem** [comment]
我又查閱PR裏的討論，英文標籤加 ` - Traditional` 或 ` - Simplified` 後綴是爲了在區分兩個輸入模式的同時，和系統中其他繁、簡中文輸入法的命名保持一致。既然系統自帶的中文輸入法名稱都是這樣長的，那麼這也可以不視爲本品的問題了。

**Comment by ShikiSuen** [comment]
選單名稱這樣英文命名吧：

RIME-CHS
RIME-CHT
RIME-YUE

**Comment by groverlynn** [comment]
> 我又查閱PR裏的討論，英文標籤加 ` - Traditional` 或 ` - Simplified` 後綴是爲了在區分兩個輸入模式的同時，和系統中其他繁、簡中文輸入法的命名保持一致。既然系統自帶的中文輸入法名稱都是這樣長的，那麼這也可以不視爲本品的問題了。

應該用`–`（en dash）而不是`-`（hyphen）。其他所有輸入法和鍵盤佈局都已經改成合規範的en dash，只有中文和粵語輸入法沒有更新……

**Comment by groverlynn** [comment]
> 選單名稱這樣英文命名吧：
> 
> RIME-CHS RIME-CHT RIME-YUE

CH是瑞士，ISO的語言編碼中沒有任何一個語言是CH（不存在瑞士語）。而漢語是ZH、ZHO/CHI。
CHS是南加州原住民的丘馬什語，CHT是祕魯原住民的喬隆語。
繁簡是文字書寫系統而非語言，按ISO規則是放在第二部分的：ZH-hant、ZH-hans。同樣地，也有YUE-hant、YUE-hans、WUU-hant、WUU-hans等。
