### ISSUE TITLE
0.16.1 方案里的 emoji 不会显示了

### ISSUE THREAD

**Issue by Attiv** [rime/squirrel#708]
之前的版本是可以正常显示的，新版本 0.16.1 输入框里不会出现 emoji 候选了

**Comment by lotem** [comment]
预设方案和配置没有emoji候选。你谈的可能是自定的功能，我没法诊断。

**Comment by LEOYoon-Tsaw** [comment]
剛裝了一遍`0.16.1`，並使用 https://github.com/rime/rime-emoji ，沒有遇到轉換問題。
如果你們用的第三方 Emoji 轉換方案，諮詢一下方案作者

**Comment by iDvel** [comment]
0.15.2 的时候 `emoji.txt` 里可以有重复内容，Emoji 还会正常显示。
我试过从 0.15.4 开始就不行了。
检查你的 Emoji 映射里，肯定是有重复的。

**Comment by LEOYoon-Tsaw** [comment]
> 0.15.2 的时候 `emoji.txt` 里可以有重复内容，Emoji 还会正常显示。
> 我试过从 0.15.4 开始就不行了。
> 检查你的 Emoji 映射里，肯定是有重复的。

應該是OpenCC升級的緣故

**Comment by leeight** [comment]
@LEOYoon-Tsaw 我把 `opencc/emoji_word.txt` 处理了一下重复的行之后，现在依然还是无法输入 emoji。

```
sort opencc/emoji_word.txt | uniq > a.txt
mv a.txt opencc/emoji_word.txt
```

然后也重新 `Deploy` 了一次。

**Comment by iDvel** [comment]
@leeight 开头重复的也不行。
比如
```
好	好 👌
好	好 👍
```
需要合并成一行：
```
好	好 👌 👍
```

**Comment by iczrac** [comment]
> @leeight 开头重复的也不行。 比如
> 
> ```
> 好	好 👌
> 好	好 👍
> ```
> 
> 需要合并成一行：
> 
> ```
> 好	好 👌 👍
> ```

请问有处理好的文件吗

**Comment by LEOYoon-Tsaw** [comment]
[rime/rime-emoji](http://github.com/rime/rime-emoji)

**Comment by iczrac** [comment]
> [rime/rime-emoji](https://github.com/rime/rime-emoji)

😄  我也刚刚处理了一遍   谢谢  还是用你的  🙏🏻

**Comment by leeight** [comment]
@iczrac @iDvel 现在好了，非常感谢🙏🏻

**Comment by curoky** [comment]
@iczrac @iDvel 特别感谢，删除掉重复的后解决了🙏🏻
