### ISSUE TITLE
macOS 13.1 中的 0.16.1 无法简单切换到半角英文

### ISSUE THREAD

**Issue by ZoomQuiet** [rime/squirrel#709]
## 背景
从１３年全面使用 ＭＡＣ 作日常环境以来，就长期使用 rIME 作为输入法，
参考：[ZqBXM/Rime\-Squirrel at master · ZoomQuiet/ZqBXM](https://github.com/ZoomQuiet/ZqBXM/tree/master/Rime-Squirrel)

## 习惯
之前为了编程方便统一将中文标点也切换为半角的，
只是在进行翻译工作时，就不得不反复在中／英／全角／半角的状态中反复切换，
幸好有对应快捷键：
Shift+Space～切换全半角
Ctrl+. ～切换中英标点
只是有时要组合起来，先切换到中文输入，再切换为半角，才能在 rIME 中输入半角英文；

## 问题
现在升级到最新版本后，这种快捷键失效了，只能通过 Ctrl+` 进入选择菜单来切换，
效率一下降低了很多；
想想，其实我只是需要使用 Shift 切换中英输入状态时，
确保英文时上屏的都是半角 ASCII 标准字符就好，
但是，现在上屏的是全角英文以及标点，就很奇怪；

有什么配置思路？

**Comment by lotem** [comment]
> 现在上屏的是全角英文以及标点
这是因为用 <kbd>Shift+space</kbd> 切换到全角字符了吧。
「全角」「半角」这对选项控制的是涵盖所有ASCII可打印字符的，不止包括标点。

根据「习惯」里的描述，是不是只需要用 <kbd>Ctrl+.</kbd> 切换中西文标点，与单击Shift进行中/西文状态切换，就可以满足编程、中文写作、英文写作三种使用场景了。

「全角」对应的用法是是中文、西文、数字、符号全部按照方块字的大小排版，以求整齐，应该是用不到的。

**Comment by lotem** [comment]
我看了一下你的配置。
https://github.com/ZoomQuiet/ZqBXM/blob/master/Rime-Squirrel/Library_Rime/alternative.yaml#L58

这里 `alternative.yaml:/punctuator/half_shape` 现在完全可以用 `Ctrl+.` 切换中西文标点完成；从而也不再需要把原本（半角）中文标点定义到 `full_shape` 状态下。

看来标点符号配置里的 `half_shape` `full_shape` 比较容易误解。本意是和全角/半角字符配合时，该用哪些（中文）标点。

举例来说：

`．` 和 `.` 互为全角、半角关系，他们是西文句点的全角、半角形式。
`。` 和以上二者是中文标点与西文标点的区别。

输入语言为中文时，无论字符是全角、半角，一般都用中文句号 `。`；
用 `Ctrl+.` 切换到西文标点后，则中文模式下不使用中文句号 `。` 而视全/半角字符设置改为西文句点 `．` 或 `.`。

**Comment by ZoomQuiet** [comment]
@lotem 是的哪，
因为在翻译以及相关场景中，正文需要全部全角标点，
但是，涉及技术代码、术语时，又必须切换为半角ASCII 码，导致很分裂；
之前，通过 `Ctrl+.` 切换　full_shape　和　half_shape，配合　`Shift+Space` 分别组合配置了不同的输入场景：

- 代码编写时，可以输入中文，同时英文以及标点又都是half_shape
- 翻译写作时，根据需要临时从全中文＋full_shape　切换到　half_shape　英文和符号，以便兼容 Markdown 格式要求

现在升级到 0.16.1 后，就只能通过多级菜单选择切换效率无法控制，主要是无法盲打了，
搜索了一下，有网友只能使用临时切换回 ABC 英文输入法来解决感觉太不 rIME 了。。。

**Comment by ZoomQuiet** [comment]
> 我看了一下你的配置。 https://github.com/ZoomQuiet/ZqBXM/blob/master/Rime-Squirrel/Library_Rime/alternative.yaml#L58
> 
> 这里 `alternative.yaml:/punctuator/half_shape` 现在完全可以用 `Ctrl+.` 切换中西文标点完成；从而也不再需要把原本（半角）中文标点定义到 `full_shape` 状态下。
> 
> 看来标点符号配置里的 `half_shape` `full_shape` 比较容易误解。本意是和全角/半角字符配合时，该用哪些（中文）标点。
> 
> 举例来说：
> 
> `．` 和 `.` 互为全角、半角关系，他们是西文句点的全角、半角形式。 `。` 和以上二者是中文标点与西文标点的区别。（其实 `。` 也有个对应的半角字符，但只有日本人用）
> 
> 输入语言为中文时，无论字符是全角、半角，一般都用中文句号 `。`； 用 `Ctrl+.` 切换到西文标点后，则中文模式下不使用中文句号 `。` 而视全/半角字符设置改为西文句点 `．` 或 `.`。

的确首先这么尝试的，但是发现 `Ctrl+.` 失效了，组合按后，只是闪一下屏幕没有任何变化。
而俺的配置并没有什么转变，就是将
alternative.yaml　中的　config_version　变成了 0.16

**Comment by lotem** [comment]
默认的快捷键 `Ctrl+.`  配置为切换 `ascii_punct` 选项。你的方案里没有定义这个选项，所以不支持。
https://github.com/ZoomQuiet/ZqBXM/blob/master/Rime-Squirrel/Library_Rime/bxm4zq2mac.schema.yaml#L57

**Comment by ZoomQuiet** [comment]
补充一点，其实在 rIME 的帮助下，大家并不想遵循中文标点的约定，
特别是程序猿们，习惯配置为即便是中文输入状态，但是所有标点也都是 ASCII 的半角符号，
并只使用 , ; 不使用 . 最多也是用 ... 来替代……

只是到了翻译等有出版要求时，不得不切换回所谓传统的混合配置。

**Comment by lotem** [comment]
我觉得你肯定改过什么东西。
从上面的对话没看出来为什么要用两组开关，

> Shift+Space～切换全半角
> Ctrl+. ～切换中英标点

或者说原先的配置怎么让这两组快捷键同时起作用，代码里没有线索。

**Comment by LEOYoon-Tsaw** [comment]
> 习惯配置为即便是中文输入状态，但是所有标点也都是 ASCII 的半角符号
就是公子說的 `ascii_punct`，即`句讀→標點`，你可以點認設爲關。

**Comment by ZoomQuiet** [comment]
> 我觉得你肯定改过什么东西。 从上面的对话没看出来为什么要用两组开关，
> 
> > Shift+Space～切换全半角
> > Ctrl+. ～切换中英标点
> 
> 或者说原先的配置怎么让这两组快捷键同时起作用，代码里没有线索。

时间太久，有些没有发布，
[ZqBXM/Rime-Squirrel/Library_Rime at master · ZoomQuiet/ZqBXM](https://github.com/ZoomQuiet/ZqBXM/tree/master/Rime-Squirrel/Library_Rime)

将当前　/Users/zoomq/Library/Rime/　中有关表形码日常使用的配置更新上来了，
也在逐一看，应该是有哪儿冲突了，
对了，不知道为什么 没有　default.yaml　专门给改名了

**Comment by ZoomQuiet** [comment]
> 我觉得你肯定改过什么东西。 从上面的对话没看出来为什么要用两组开关，
> 
> > Shift+Space～切换全半角
> > Ctrl+. ～切换中英标点
> 
> 或者说原先的配置怎么让这两组快捷键同时起作用，代码里没有线索。

可能描述有误，并不是同时起作用，是先后：

- 在鼠须管输入法中，发现要使用半角符号和英文时
- 先用 `Shift+space` 切换到中文
- 然后用 `Ctrl+.` 切换到半角
- 再用 `Shift+space` 切换到英文
- 此时，就可以获得完全的 ASCII 字符输入状态
- 要切换回正常的中文翻译、写作状态，就得将上一流程反向来一下

**Comment by LEOYoon-Tsaw** [comment]
> 要使用半角符号和英文时

直接按 `Shift` 就行了，不懂爲何能搞出3個步驟。

**Comment by lotem** [comment]
看来你的配置里 `Shift+space` 切换 `ascii_mode`，`Ctrl+.` 切换 `full_shape`。

建议你可以在方案里把标点改成默认配置。要保留原来使用快捷键的习惯，可以修改快捷键定义，
`Shift+space` 仍用来切换 `ascii_mode`，`Ctrl+period` 改为切换 `ascii_punct`，不再使用 `full_shape` 状态。

**Comment by ZoomQuiet** [comment]
> > 要使用半角符号和英文时
> 
> 直接按 `Shift` 就行了，不懂爲何能搞出3個步驟。

对的，这是也是俺的期望，只是现在使用 `Shift` 时，出来的英文也是全角的，包含标点也是，只是不是中文全角，是英文全角，这就很囧……

**Comment by ZoomQuiet** [comment]
@lotem https://github.com/ZoomQuiet/ZqBXM/blob/e883ec048ff64a420ce86aed0f704bb0843a2c43/Rime-Squirrel/Library_Rime/default.custom.yaml#L28

根据各种文档，尝试在default.custom.yaml中追加：
```
  key_binder:
    bindings:
      - { when: always, accept: Shift+space,    toggle: ascii_mode}
      - { when: always, accept: Control+period, toggle: ascii_punct}
```

组合 `Control+.` 时没有反应
而默认的 `Shift` 好象覆盖了 `Shift+space` 还是中英切换
也尝试过

 >       - { when: always, accept: Control+Shift+2,  toggle: ascii_mode }

同样是无反应。

**Comment by lotem** [comment]
> 默认的快捷键 `Ctrl+.` 配置为切换 `ascii_punct` 选项。你的方案里没有定义这个选项，所以不支持。 https://github.com/ZoomQuiet/ZqBXM/blob/master/Rime-Squirrel/Library_Rime/bxm4zq2mac.schema.yaml#L57

**Comment by ZoomQuiet** [comment]
PS:
![zshot 2023-02-02 15 57 46](https://user-images.githubusercontent.com/22494/216265129-1d133650-aedf-42a4-9912-dea2f5490b57.jpg)

万万没想到 `Ctrl+.` 在 GitHub 中是网页快捷键,如果没有专门关闭,
那么, rIME 配置的组合键是被覆盖的...

**Comment by lotem** [comment]
> 说明

这些讨论都是围绕自定义的配置而言，没有普遍意义，就不必在这儿跟进讨论了。

**Comment by LEOYoon-Tsaw** [comment]
> 万万没想到 Ctrl+. 在 GitHub 中是网页快捷键,如果没有专门关闭

大可以換成別的組合鍵
