### ISSUE TITLE
状态名称 “中文/西文” 可以通过配置改回 “中/A” 吗？

### ISSUE THREAD

**Issue by iclementine** [rime/squirrel#711]
如题：
鼠须管：更新到 0.16.1 ，按下 shift  状态名称为 “中文/西文” ，可以通过配置改回 “中/A” 吗？

**Comment by iDvel** [comment]
方案里改 states 就可以了。
```
switches:
  - name: ascii_mode
    states: [ 中, A ]
```

**Comment by lotem** [comment]
相关讨论 https://github.com/rime/librime/issues/608
