### ISSUE TITLE
不再显示中英文切换以及全角半角切换悬浮框

### ISSUE THREAD

**Issue by KGZaker** [rime/squirrel#713]
我的系统为 mac os X 13.2，发现在更新最新版本的鼠须管后，不再显示中英文切换以及全半角切换的悬浮框（注：功能正常，只是不显示悬浮框，短按 shift_L 依然可以切换中英文，短按 shift+space 依然可以切换全半角）。想咨询下有什么设置需要修改以重新显示悬浮框吗？

**Comment by lotem** [comment]
同 https://github.com/rime/squirrel/issues/707
