### ISSUE TITLE
brew安装后出现两个鼠须管

### ISSUE THREAD

**Issue by xiebruce** [rime/squirrel#714]
我最初是这么安装的
```
 brew install --cask squirrel
```

刚刚突然弹出窗口，提示有0.16.1版本，我就直接在弹窗提示里点了更新。

更新后重启电脑，出现两个鼠须管，一个简体一个繁体
<img width="246" alt="image" src="https://user-images.githubusercontent.com/13575500/216320707-da6bcaf9-28f7-42f6-bd3c-0e6c0ca38b24.png">

我发现这两个位置都有Squirrel.app
<img width="480" alt="image" src="https://user-images.githubusercontent.com/13575500/216325345-1493e5d0-3b12-450e-b4c5-f703353fb436.png">

我看它们并不是软链接的关系，但是用diff对比，又一模一样
```
diff /System/Volumes/Data/Library/Input\ Methods/Squirrel.app /Library/Input\ Methods/Squirrel.app
```

删除System的这个，根目录Library下的那个也会消失，感觉这两份是同一份？
```
sudo rm -rf /System/Volumes/Data/Library/Input\ Methods/Squirrel.app
```

不过删除System下的那个之后，再`brew reinstall --cask squirrel`，再重启电脑，它竟然又好了。

macOS: Big Sur 11.5.1 (20G80)

**Comment by ynwvitusr** [comment]
我昨天更新后也出现两个鼠须管，不过我是在键盘偏好设置里，将简体那个删除了，好像并没有影响....

**Comment by lotem** [comment]
將輸入法註冊到簡繁兩種語言是一項新的功能 https://github.com/rime/squirrel/pull/648
看來並不能如預想，讓不關心該功能的用戶不受任何影響，已經造成了些許混亂。
如果不能解決安裝時只啓用一項的問題，考慮下次改回去。https://github.com/rime/squirrel/pull/696 也別做了。

---

`/System/Volumes/Data` 是 macOS 文件系統佈局中疊加在系統分區上的數據分區。

**Comment by sweard** [comment]
0.15.2 在这两个位置都有Squirrel.app。
我其中一台电脑更新到0.16.1后，在顶部状态栏也出现了两个鼠须管，重新配置下键盘又好了。

**Comment by lotem** [comment]
> 在这两个位置都有Squirrel.app

兩個路徑在文件系統中是同一個位置

**Comment by lotem** [comment]
https://github.com/rime/squirrel/commit/3bc6c2c0edbb1adaa22e79da65c6f0116b164de7 嘗試修復

CI構建結果： https://github.com/rime/squirrel/actions/runs/4090629857

**Comment by FranklinYu** [comment]
我这边看到的情况是，在系统输入法设置里能看到简繁两个鼠须管，但打开都是空的：

<img width="609" alt="圖片" src="https://user-images.githubusercontent.com/3153452/216787537-6bd6fa7c-03b7-413e-bcb5-358501c0ae27.png">

实际上只有 macOS 自带的输入法可以输入。上述 CI 安装以后有同样的症状。

**Comment by FranklinYu** [comment]
我覺得 #648 是挺不錯的功能，值得鼓勵；只是由於測試不夠，導致有些 bug 未被發現。是否考慮 beta channel？這樣可以提前測試問題。目前的穩定版兩年未發版，[0.16.0](https://rime.im/release/squirrel/#0-16-0-2023-01-30) 中包含了諸多更動。不如添加一個 beta channel，採取「小步快跑」的發版策略？

**Comment by xiebruce** [comment]
> 將輸入法註冊到簡繁兩種語言是一項新的功能 #648 看來並不能如預想，讓不關心該功能的用戶不受任何影響，已經造成了些許混亂。 如果不能解決安裝時只啓用一項的問題，考慮下次改回去。#696 也別做了。
> 
> `/System/Volumes/Data` 是 macOS 文件系統佈局中疊加在系統分區上的數據分區。

这个，输入法菜单里的显示语言，不能通过一个设置项来修改吗？我不太清楚原理哈，就是问问。

至于那个数据分区，果然是同一个位置，我之前就猜它是同一个位置。

**Comment by lotem** [comment]
https://github.com/rime/squirrel/commit/3bc6c2c0edbb1adaa22e79da65c6f0116b164de7
這項改動能包全新安裝只添加一項輸入法，以及後續升級保留原來的簡、繁輸入法選項。（只包不會自動添加兩項，不包能用）
系統輸入法選擇界面似乎有BUG，不能保證從0.15升級安裝結果是正確的；往往需要重新手動添加輸入法才能用。
