### ISSUE TITLE
菜单栏图标改为长方形以保持和系统输入法一致

### ISSUE THREAD

**Issue by yzlnew** [rime/squirrel#717]
<img width="165" alt="image" src="https://user-images.githubusercontent.com/4904877/216547032-f0e7b6f8-d505-4e6c-bd53-1b50e87109c1.png">

对 MacOS 开发不是很熟悉，我猜测是 [这个链接](https://github.com/rime/squirrel/tree/master/Assets.xcassets/RimeIcon.appiconset) 下的图标。
找到 HIG 并没有详细描述尺寸。

几个可能有用的链接：

- https://developer.apple.com/design/human-interface-guidelines/components/system-experiences/the-menu-bar/
- https://developer.apple.com/design/human-interface-guidelines/foundations/icons
- https://bjango.com/articles/designingmenubarextras/

不过我可以手动绘制一个和系统输入法一致大小的图标。

**Comment by firimar** [comment]
提供一个修改的图标  [rime.pdf](https://github.com/rime/squirrel/files/10773940/rime.pdf)<img width="195" alt="image" src="https://user-images.githubusercontent.com/20078939/219856817-369936d0-6069-4127-8790-cbd791ef7f96.png">

**Comment by jaye2fung** [comment]
> 提供一个修改的图标 [rime.pdf](https://github.com/rime/squirrel/files/10773940/rime.pdf)<img alt="image" width="195" src="https://user-images.githubusercontent.com/20078939/219856817-369936d0-6069-4127-8790-cbd791ef7f96.png">
你好，请问你是怎么替换的？

**Comment by jaye2fung** [comment]
> 提供一个修改的图标 [rime.pdf](https://github.com/rime/squirrel/files/10773940/rime.pdf)<img alt="image" width="195" src="https://user-images.githubusercontent.com/20078939/219856817-369936d0-6069-4127-8790-cbd791ef7f96.png">

请问你是怎么改的？

**Comment by firimar** [comment]
> > 提供一个修改的图标 [rime.pdf](https://github.com/rime/squirrel/files/10773940/rime.pdf)<img alt="image" width="195" src="https://user-images.githubusercontent.com/20078939/219856817-369936d0-6069-4127-8790-cbd791ef7f96.png">
> 
> 请问你是怎么改的？

替换 /Library/Input Methods/Squirrel.app/Contents/Resources路径下rime.pdf即可

**Comment by jaye2fung** [comment]
> > > 提供一个修改的图标 [rime.pdf](https://github.com/rime/squirrel/files/10773940/rime.pdf)<img alt="image" width="195" src="https://user-images.githubusercontent.com/20078939/219856817-369936d0-6069-4127-8790-cbd791ef7f96.png">
> > 
> > 
> > 请问你是怎么改的？
> 
> 替换 /Library/Input Methods/Squirrel.app/Contents/Resources路径下rime.pdf即可

好的，感谢！
