### ISSUE TITLE
当输入窗口靠右，输入法窗口触及桌面右边界后，窗口右侧超出候选词的空白部分不收缩

### ISSUE THREAD

**Issue by widcardw** [rime/squirrel#719]
问题描述如下视频所示，视频的右边界即为桌面的右边界，当候选词窗口触及桌面右边界时，就不再收缩

https://user-images.githubusercontent.com/55699713/216752109-98824700-9a61-4dd8-bea3-bc4f8cadd4c1.mp4

https://user-images.githubusercontent.com/55699713/216752273-cd6253cb-dabf-4aca-94cc-d2f72cce68eb.mp4

该问题在 0.15.2 版本就出现了，0.16.1 依然存在，不影响使用，只是在观感上稍微差了点。

环境

- MacBook Pro
- chip: Apple M1
- macOS Ventura 13.1

Squirrel 0.16.1 安装方式：自动更新

**Comment by lotem** [comment]
相同問題 https://github.com/rime/squirrel/issues/523
