### ISSUE TITLE
OS X 10.11 + Xcode 7.1.1无法编译

### ISSUE THREAD

**Issue by messiahluo** [rime/squirrel#72]
Undefined symbols for architecture x86_64:
      "snappy::RawCompress(char const*, unsigned long, char*, unsigned long*)", referenced from:
      leveldb::TableBuilder::WriteBlock(leveldb::BlockBuilder*, leveldb::BlockHandle*) in libleveldb.a(table_builder.o)
      "snappy::RawUncompress(char const*, unsigned long, char*)", referenced from:
      leveldb::ReadBlock(leveldb::RandomAccessFile*, leveldb::ReadOptions const&, leveldb::BlockHandle const&, leveldb::BlockContents*) in libleveldb.a(format.o)
      "snappy::MaxCompressedLength(unsigned long)", referenced from:
      leveldb::TableBuilder::WriteBlock(leveldb::BlockBuilder*, leveldb::BlockHandle*) in libleveldb.a(table_builder.o)
      "snappy::GetUncompressedLength(char const*, unsigned long, unsigned long*)", referenced from:
      leveldb::ReadBlock(leveldb::RandomAccessFile*, leveldb::ReadOptions const&, leveldb::BlockHandle const&, leveldb::BlockContents*) in libleveldb.a(format.o)
    ld: symbol(s) not found for architecture x86_64

~~另外，有什么办法可以查到当前运行的应用的 BundleIdentifier 吗？有些应用我用在 info.plist 中拿到的BundleIdentifier 设置了 app_options 后没有生效，如 Android Studio， IntelliJ IDEA 等~~
不好意思上面问题是配置出错，不过编译问题还是存在的

**Comment by chenrui333** [comment]
@messiahluo You are building from source?
what is the issue now?

**Comment by messiahluo** [comment]
@chenrui333 yes, I tried to build follow this [Build Instruction](https://github.com/rime/squirrel/blob/develop/INSTALL.md), but encountered above error when running 
    
    make deps

**Comment by jakwings** [comment]
用 MacPorts 毫无问题，Xcode 版本一样。建议贴出详细过程（gist）。

**Comment by messiahluo** [comment]
brew reinstall boost 之后成功了。。sorrry

**Comment by jakwings** [comment]
请问你重装时是不是加了 --c++11 这选项？

**Comment by messiahluo** [comment]
@jakwings 印象中没有
