### ISSUE TITLE
选择模式下候选框最后一个字符总是会换行

### ISSUE THREAD

**Issue by penglei** [rime/squirrel#720]
主题启用了 horizontal模式，按  `ctrl+grave` 后，进入选择当前输入法的模式菜单，最后一个字符总是会换行：

<img width="453" alt="image" src="https://user-images.githubusercontent.com/1140325/216767188-6dc29013-1ce1-439e-b3fb-16fc564e8967.png">
<img width="503" alt="image" src="https://user-images.githubusercontent.com/1140325/216767300-933ffd6e-8233-49ee-84c7-6ba2bd1b4759.png">

主题配置：

```
horizontal: true
candidate_format: "%c %@ "
font_point: 16
label_font_point: 15
corner_radius: 6
line_spacing: 10
text_color: 0x666666
candidate_text_color: 0x000000
back_color: 0xFFFFFF
border_color: 0xE2E2E2
hilited_text_color: 0x000000
hilited_back_color: 0xFFFFFF
hilited_candidate_text_color: 0xffffff
hilited_candidate_back_color: 0xCE7539
comment_text_color: 0x6D6D6D
hilited_comment_text_color: 0xEBC6B0
hilited_candidate_label_color: 0xfafafa
```

版本：
```
distribution_code_name: Squirrel
distribution_name: "鼠鬚管"
distribution_version: 0.16.1
install_time: "Fri Feb  3 00:23:38 2023"
rime_version: 1.8.4
```

**Comment by LEOYoon-Tsaw** [comment]
#515

**Comment by penglei** [comment]
但是没有超过屏幕一半呢。
<img width="1458" alt="image" src="https://user-images.githubusercontent.com/1140325/216771464-70ee15c6-990f-4bb5-9abc-dab0ca341b8e.png">
而且，我打词「一半」的时候，候选框显然超过上面折断的情况：

**Comment by LEOYoon-Tsaw** [comment]
你截圖的範圍造成了長度超過的假象

**Comment by penglei** [comment]
我原来的截图可能更能说明问题，如果是超出一定宽度再折断的话，那可以得出下面第二个截图也应该从 `5` 后面折断，而不是最后的 「字」之前。
<img width="654" alt="image" src="https://user-images.githubusercontent.com/1140325/216771901-e6ab43c5-5c5d-40a6-bf7f-ba80ec33487d.png">

**Comment by penglei** [comment]
我怀疑是计算可见「字符宽度」有问题。这么一想的话最可能是emoji字符导致，我去试试换成英文字符看看。

**Comment by LEOYoon-Tsaw** [comment]
有可能吧，你可以試試 #700

**Comment by penglei** [comment]
测试发现，去掉下面配置中的 `\uFE0F` 这个unicode字符就没问题了 。
```
states: [ "🈚️️\uFE0E", "🈶️️\uFE0F" ]
```
查了一下，这个 unicode这是用来修改emoji的显示样子，

**Comment by LEOYoon-Tsaw** [comment]
> 测试发现，去掉下面配置中的 `\uFE0F` 这个unicode字符就没问题了 。
> 
> ```
> states: [ "🈚️️\uFE0E", "🈶️️\uFE0F" ]
> ```


`"🈚️️\uFE0E", "🈶️️\uFE0F"` 顯然不應該是你看到的 `🔢`，而我這邊一切正常。不過你改了能用就行。

**Comment by penglei** [comment]
它不是🔢，它是 schema/switches 里面的配置。 我不知道 `\uFE0F` 算不算 combining mark ，这种情况下字符宽度的计算确实比较麻烦。

**Comment by LEOYoon-Tsaw** [comment]
<img width="205" alt="image" src="https://user-images.githubusercontent.com/4469383/216773252-1eab7652-ec50-4790-99c5-f91439acd979.png">
FE0F和FE0E是用來把「有」按emoji顯示，而「無」按文本顯示，正常的顯示效果是我圖中的樣子。不知爲何你那邊兩個都按Emoji顯示了，不過這無所謂了……

**Comment by groverlynn** [comment]
> <img alt="image" width="205" src="https://user-images.githubusercontent.com/4469383/216773252-1eab7652-ec50-4790-99c5-f91439acd979.png">
> 
> FE0F和FE0E是用來把「有」按emoji顯示，而「無」按文本顯示，正常的顯示效果是我圖中的樣子。不知爲何你那邊兩個都按Emoji顯示了，不過這無所謂了……

你看unicode源碼，`🈚️️`是`\U1F21A\uFE0F`，所以`🈚️️\uFE0E`=`\U1F21A\uFE0F\uFE0E`，末位的那個變體選擇無效。而`🈶️️`是`\U1F236`，所以`🈶️️\uFE0F`=`\U1F236\uFE0F`，這個變體選擇是有效的。

**Comment by LEOYoon-Tsaw** [comment]
> 你看unicode源碼，🈚️️是\U1F21A\uFE0F，所以🈚️️\uFE0E=\U1F21A\uFE0F\uFE0E，末位的那個變體選擇無效。而🈶️️是\U1F236，所以🈶️️\uFE0F=\U1F236\uFE0F，這個變體選擇是有效的。

那可以直接寫unicode嘛
