### ISSUE TITLE
更新了之后图标不显示，微信无法使用

### ISSUE THREAD

**Issue by robbinhan** [rime/squirrel#724]
更新到0.16.1，顶部输入法没有显示小图标了
![image](https://user-images.githubusercontent.com/241873/216868944-b8837e2f-87a5-4430-9304-bc240a49bbb8.png)
![image](https://user-images.githubusercontent.com/241873/216868970-0a8f21d8-fda3-48b0-8dd6-e077c694e84f.png)

同时在mac版微信无法切换到鼠须管输入法，其他软件暂未发现问题

**Comment by LEOYoon-Tsaw** [comment]
最新版macOS(13.2)、最新版微信(3.6.2)沒問題，無法復現
<img width="298" alt="image" src="https://user-images.githubusercontent.com/4469383/216870188-a6813196-171e-4216-a450-f6f859b25d5b.png">

**Comment by lotem** [comment]
注销用户、重新登录试试？
https://github.com/rime/squirrel/issues/281
或者再手动添加一次输入法
https://github.com/rime/squirrel/issues/704

**Comment by robbinhan** [comment]
可以了，谢谢
