### ISSUE TITLE
更新0.16.2后每次切换输入法至Squirrel都会弹出第三方插件启动许可提示

### ISSUE THREAD

**Issue by DehanLUO** [rime/squirrel#725]
系统版本 macOS Ventura Version 13.1 (22C65)
![screenshot](https://user-images.githubusercontent.com/53093688/216893654-1734933d-acf8-4419-8254-653d744d492a.gif)

**Comment by lotem** [comment]
似乎要注销Mac用户、重新登录。

**Comment by DehanLUO** [comment]
> 似乎要注销Mac用户、重新登录。

是的，注销之后重新登入，可以恢复正常。

**Comment by sjx95** [comment]
+1 我是直接重新启动了，也能恢复正常。

不过我遇到另一个问题就是，现在输入法选择界面里蹦出来两个鼠须管，但是输入时又都是简化字……
![image](https://user-images.githubusercontent.com/18415916/216957068-dc9f186c-4fbb-47e6-b513-ab066674e102.png)

**Comment by ZoomQuiet** [comment]
> +1 我是直接重新启动了，也能恢复正常。
> 
> 不过我遇到另一个问题就是，现在输入法选择界面里蹦出来两个鼠须管，但是输入时又都是简化字…… ![image](https://user-images.githubusercontent.com/18415916/216957068-dc9f186c-4fbb-47e6-b513-ab066674e102.png)

每次升级其实都是全新安装,
需要重启, 以及手工删除原有的输入法, 再重新添加新版 鼠须管 回来,
一切才恢复.

**Comment by DehanLUO** [comment]
> > +1 我是直接重新启动了，也能恢复正常。
> > 不过我遇到另一个问题就是，现在输入法选择界面里蹦出来两个鼠须管，但是输入时又都是简化字…… ![image](https://user-images.githubusercontent.com/18415916/216957068-dc9f186c-4fbb-47e6-b513-ab066674e102.png)
> 
> 每次升级其实都是全新安装, 需要重启, 以及手工删除原有的输入法, 再重新添加新版 鼠须管 回来, 一切才恢复.

这个问题我在上周升0.16.1的时候遇到过。当时在设置界面手动删除了繁体版。
这次从0.16.1->0.16.2倒没有出现这个问题。

**Comment by toplyb** [comment]
我升级后遇到了个问题,就是找不到这个输入法了,有没有大哥遇到过?

**Comment by DehanLUO** [comment]
> 我升级后遇到了个问题,就是找不到这个输入法了,有没有大哥遇到过?

试试这个流程：
1. 注销/重启
2. `System Settings`-`Keyboard`-`Text Input` 重新删除/添加一遍Squirrel

**Comment by xwnwho** [comment]
> +1 我是直接重新启动了，也能恢复正常。
> 
> 不过我遇到另一个问题就是，现在输入法选择界面里蹦出来两个鼠须管，但是输入时又都是简化字…… ![image](https://user-images.githubusercontent.com/18415916/216957068-dc9f186c-4fbb-47e6-b513-ab066674e102.png)

這個是怎麼解決的？我是不管用的是簡體還是繁體，打出來的都是繁體。

**Comment by DehanLUO** [comment]
> > +1 我是直接重新启动了，也能恢复正常。
> 
> > 
> 
> > 不过我遇到另一个问题就是，现在输入法选择界面里蹦出来两个鼠须管，但是输入时又都是简化字…… ![image](https://user-images.githubusercontent.com/18415916/216957068-dc9f186c-4fbb-47e6-b513-ab066674e102.png)
> 
> 
> 
> 這個是怎麼解決的？我是不管用的是簡體還是繁體，打出來的都是繁體。

系统输入法选择界面里手动删除这两个输入法后重新添加。

**Comment by xwnwho** [comment]
> > > +1 我是直接重新启动了，也能恢复正常。
> > 
> > 
> > > 
> > 
> > 
> > > 不过我遇到另一个问题就是，现在输入法选择界面里蹦出来两个鼠须管，但是输入时又都是简化字…… ![image](https://user-images.githubusercontent.com/18415916/216957068-dc9f186c-4fbb-47e6-b513-ab066674e102.png)
> > 
> > 
> > 這個是怎麼解決的？我是不管用的是簡體還是繁體，打出來的都是繁體。
> 
> 系统输入法选择界面里手动删除这两个输入法后重新添加。

我試過，不行，重啓後，也試了。我的系統是Ventura 13.2，Squirrel的版本是0.16.2，通過brew安裝的，我第一次添加了繁體，後面就全是繁體了。

**Comment by likeisall** [comment]
这种问题怎么解决

![Image](https://github.com/user-attachments/assets/2b44f3ef-2cb0-4fbd-b104-0cde51aaa2bf)
