### ISSUE TITLE
更新0.16.2之后无法使用

### ISSUE THREAD

**Issue by yy306525121** [rime/squirrel#728]
更新0.16.2之后状态栏没有出现鼠须管的图标，系统设置-输入法里面有鼠须管，但是无法删除，也无法添加，打字没有任何反应， 也没有报错日志，重启过也没有反应。
系统环境：MacOS 12.2.1
CPU：Intel

**Comment by lotem** [comment]
请参考 https://github.com/rime/squirrel/issues/704

**Comment by egan-ysk** [comment]
我已经切换为 15.X 版本了。   按照其他基友的操作方案，都不行，暂时放弃了。

**Comment by yy306525121** [comment]
> 我已经切换为 15.X 版本了。 按照其他基友的操作方案，都不行，暂时放弃了。

我刚试了用brew安装之后可以用了。
