### ISSUE TITLE
Fail to install squirrel

### ISSUE THREAD

**Issue by chenrui333** [rime/squirrel#73]
Command I have run:

> x>brew cask install squirrel
> Already downloaded: /Library/Caches/Homebrew/squirrel-0.9.26.2.zip
> Error: Permission denied - /opt/homebrew-cask/Caskroom/squirrel

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

```
  brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
```

Brew task is already up-to-date

> x>brew update
> Already up-to-date.

**Comment by toyjack** [comment]
@chenrui333 Why don't you just check the folder and fix it by yourself^_^
```
sudo chown -R $USER:staff /opt/homebrew-cask
