### ISSUE TITLE
鼠须管的图标过大，不与 Big Sur 的风格相符

### ISSUE THREAD

**Issue by cat0x1f** [rime/squirrel#731]
这是鼠须管的默认图标大小，看起来过于大了：
<img width="314" alt="image" src="https://user-images.githubusercontent.com/72690879/217714937-6528cbff-aa83-4eb3-9b7b-578f44f45a09.png">

这是我自己替换过图标后的样子，和其他应用的图标相同大小：

<img width="314" alt="image" src="https://user-images.githubusercontent.com/72690879/217714890-0e3154cf-a19c-4865-8745-5262db97b718.png">

希望能修改图标。

**Comment by ShikiSuen** [comment]
先备忘：
https://developer.apple.com/design/resources/
这里有 macOS 11 - 13 的 App Icon Template 可用。
