### ISSUE TITLE
方案选单选中方案使用emoji后只能显示组合emoji中的第一个

### ISSUE THREAD

**Issue by RoyRao2333** [rime/squirrel#734]
标题表述不清楚，不好意思 😂 请看设置：

<img width="446" alt="image" src="https://user-images.githubusercontent.com/31413093/218354361-953bfd4f-bca2-45f8-aa73-674babde8c35.png">

缩略：

<img width="679" alt="image" src="https://user-images.githubusercontent.com/31413093/218353911-3803816f-524f-4150-aa58-6b92633ccfac.png">

点开后显示正常：

<img width="818" alt="image" src="https://user-images.githubusercontent.com/31413093/218353983-7c74574c-4844-46ed-852b-f8c69262e6ae.png">

对于组合emoji我搜了一下，例如🇭🇰：

<img width="749" alt="image" src="https://user-images.githubusercontent.com/31413093/218354105-d7127e8a-f599-4553-a65b-e5ac91572ed3.png">

**Comment by LEOYoon-Tsaw** [comment]
librime那邊對於多碼位字符的處理能力很糟糕。自動截取第一個字符實際是截取第一個碼位。
很快就會有新的方法設置這裏的短標籤（#733 ），不必受制於自動截取，請期待

**Comment by LEOYoon-Tsaw** [comment]
已經解決
