### ISSUE TITLE
安装完成 所有输入法找不到鼠须管选项

### ISSUE THREAD

**Issue by chinalihua** [rime/squirrel#735]
系统macos13.2 intel 安装了Squirrel-0.16.1和Squirrel-0.16.2都不行
<img width="374" alt="image" src="https://user-images.githubusercontent.com/28050413/219376693-6b558676-ae42-4bf7-ab91-9deb1360b232.png">
<img width="689" alt="image" src="https://user-images.githubusercontent.com/28050413/219376789-a345753f-a36c-44b4-9f23-f86501bb26ac.png">
<img width="615" alt="image" src="https://user-images.githubusercontent.com/28050413/219376828-c7fc9e9a-0f24-44be-9d02-964a6cfa0e28.png">
退出登陆安装完成后
<img width="632" alt="image" src="https://user-images.githubusercontent.com/28050413/219376895-2b4fad95-f2bd-4b25-9fe4-97b3d20c7405.png">

**Comment by LEOYoon-Tsaw** [comment]
點➕添加一下

**Comment by chinalihua** [comment]
> 

谢谢！

**Comment by xwnwho** [comment]
M1 通过brew 安装，提示安装成功了，但是添加的时候，找不到是什么原因？
