### ISSUE TITLE
简体模式下部分字仍是繁体

### ISSUE THREAD

**Issue by KarryCharon** [rime/squirrel#738]
#619 提到过这个问题, 不过看回复已经解决, 但我仍然出现了这个问题

<img width="736" alt="image" src="https://user-images.githubusercontent.com/49889381/223337338-0c4170c8-6d77-49d4-930d-864730b2e960.png">

<img width="494" alt="image" src="https://user-images.githubusercontent.com/49889381/223337469-86166291-e6a3-4087-b776-f56e34bf860a.png">

<img width="485" alt="image" src="https://user-images.githubusercontent.com/49889381/223337782-3a6d83f1-2387-40f3-aa3c-2855c7b35781.png">

Squirrel 版本为 : 0.16.2
系统版本: Ventura 13.2.1
simplification 已经选择了 简体, 且 添加了 engine/filters 列表的 simplifier

**Comment by LEOYoon-Tsaw** [comment]
用的甚麼方案？試試明月拼音，如果明月拼音沒問題，多半是方案的問題，可能它自帶的OpenCC文檔腐爛了，找作者修吧

**Comment by KarryCharon** [comment]
@LEOYoon-Tsaw 我使用的 小鹤双拼 输入方案, 这个bug可以这样复现: 1. 先切换到 小鹤双拼 输入方案, 2. 然后 执行 重新部署 . 这时候输入 就会出现 部分繁体

**Comment by LEOYoon-Tsaw** [comment]
知道了，要麼自己修，要麽找作者吧，已經告訴你是方案自帶的OpenCC的問題了
