### ISSUE TITLE
Error loading spelling algebra definition #1: 'xlit|abcdefghijklmnopqrstuvwxyz~|'.

### ISSUE THREAD

**Issue by jkhnfk** [rime/squirrel#739]
求解。
squirrel 突然重新加载时报错，通过日志文件，里面报错的主要内容为：

I20230310 20:26:26.781280  3884 engine.cc:72] starting engine.
I20230310 20:26:26.781441  3884 engine.cc:124] updated option: extended_charset
I20230310 20:26:26.781647  3884 engine.cc:124] updated option: _auto_commit
I20230310 20:26:26.781757  3884 dictionary.cc:318] loading dictionary 'bzzm'.
E20230310 20:26:26.781797  3884 algebra.cc:88] Error loading spelling algebra definition #1: 'xlit|abcdefghijklmnopqrstuvwxyz~|'.

注释掉相应的代码行，仍然报这个错误，但是不影响使用。
请问此问题何解？

**Comment by mokapsing** [comment]
不如你把方案文件传上来

**Comment by LEOYoon-Tsaw** [comment]
xlit是單字轉單字，每一個字符都要有對應的目的
