### ISSUE TITLE
高亮背景显示错乱

### ISSUE THREAD

**Issue by xiehuc** [rime/squirrel#748]
<img width="301" alt="image" src="https://user-images.githubusercontent.com/571878/231926894-14b6b9c0-111b-4126-bbb4-e9c6cffcddc4.png">
<img width="293" alt="image" src="https://user-images.githubusercontent.com/571878/231926924-543a15ca-55db-49e6-8524-081d13726f27.png">

只输入的一个 n。

有空我再研究下源码看看bug在哪。

**Comment by xiehuc** [comment]
试了下，LEOYoon-Tsaw 的fork能完美显示，简直太棒了。希望早日合入主干。

**Comment by LEOYoon-Tsaw** [comment]
多謝捧場！
