### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by davincimindai** [rime/squirrel#758]
/Applications/Xcode.app/Contents/Developer/usr/bin/make librime
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C librime xcode/deps
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f xcode.mk deps
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f deps.mk
cd /Users/yueliu/Desktop/Projects/github/squirrel/librime/deps/glog; \
	cmake . -Bcmake-build \
	-DBUILD_SHARED_LIBS:BOOL=OFF \
	-DBUILD_TESTING:BOOL=OFF \
	-DWITH_GFLAGS:BOOL=OFF \
	-DCMAKE_BUILD_TYPE:STRING="Release" \
	-DCMAKE_INSTALL_PREFIX:PATH="/Users/yueliu/Desktop/Projects/github/squirrel/librime" \
	&& cmake --build cmake-build --target install
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - broken
CMake Error at /usr/local/Cellar/cmake/3.26.2/share/cmake/Modules/CMakeTestCXXCompiler.cmake:60 (message):
  The C++ compiler

    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/yueliu/Desktop/Projects/github/squirrel/librime/deps/glog/cmake-build/CMakeFiles/CMakeScratch/TryCompile-KvZkqf
    
    Run Build Command(s):/usr/local/Cellar/cmake/3.26.2/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_caf53/fast && /Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_caf53.dir/build.make CMakeFiles/cmTC_caf53.dir/build
    Building CXX object CMakeFiles/cmTC_caf53.dir/testCXXCompiler.cxx.o
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -mmacosx-version-min=13.0 -MD -MT CMakeFiles/cmTC_caf53.dir/testCXXCompiler.cxx.o -MF CMakeFiles/cmTC_caf53.dir/testCXXCompiler.cxx.o.d -o CMakeFiles/cmTC_caf53.dir/testCXXCompiler.cxx.o -c /Users/yueliu/Desktop/Projects/github/squirrel/librime/deps/glog/cmake-build/CMakeFiles/CMakeScratch/TryCompile-KvZkqf/testCXXCompiler.cxx
    Linking CXX executable cmTC_caf53
    /usr/local/Cellar/cmake/3.26.2/bin/cmake -E cmake_link_script CMakeFiles/cmTC_caf53.dir/link.txt --verbose=1
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -mmacosx-version-min=$(RECOMMENDED_MACOSX_DEPLOYMENT_TARGET) -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/cmTC_caf53.dir/testCXXCompiler.cxx.o -o cmTC_caf53 
    clang: error: invalid version number in '-mmacosx-version-min=$(RECOMMENDED_MACOSX_DEPLOYMENT_TARGET)'
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    make[6]: *** [cmTC_caf53] Error 1
    make[5]: *** [cmTC_caf53/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

-- Configuring incomplete, errors occurred!
make[4]: *** [glog] Error 1
make[3]: *** [deps] Error 2
make[2]: *** [xcode/deps] Error 2
make[1]: *** [librime/lib/libmarisa.a] Error 2
make: *** [lib/librime.1.dylib] Error 2

---------------------------------------------------------------------------------------------------------------------------------
tried setting CMAKE_OSX_DEPLOYMENT_TARGET in squirrel/librime/deps/glog/CMakeLists.txt, did not work. Can you please help

**Comment by LEOYoon-Tsaw** [comment]
try `make MACOSX_DEPLOYMENT_TARGET='13.0'`

**Comment by davincimindai** [comment]
> 

yueliu@MacBook-Pro-4 squirrel %make MACOSX_DEPLOYMENT_TARGET='13.0'
/Applications/Xcode.app/Contents/Developer/usr/bin/make librime
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C librime xcode/deps
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f xcode.mk deps
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f deps.mk
cd /Users/yueliu/Desktop/Projects/github/squirrel/librime/deps/glog; \
	cmake . -Bcmake-build \
	-DBUILD_SHARED_LIBS:BOOL=OFF \
	-DBUILD_TESTING:BOOL=OFF \
	-DWITH_GFLAGS:BOOL=OFF \
	-DCMAKE_BUILD_TYPE:STRING="Release" \
	-DCMAKE_INSTALL_PREFIX:PATH="/Users/yueliu/Desktop/Projects/github/squirrel/librime" \
	&& cmake --build cmake-build --target install
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - broken
CMake Error at /usr/local/Cellar/cmake/3.26.2/share/cmake/Modules/CMakeTestCXXCompiler.cmake:60 (message):
  The C++ compiler

    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/yueliu/Desktop/Projects/github/squirrel/librime/deps/glog/cmake-build/CMakeFiles/CMakeScratch/TryCompile-5cxre2
    
    Run Build Command(s):/usr/local/Cellar/cmake/3.26.2/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_5d13c/fast && /Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_5d13c.dir/build.make CMakeFiles/cmTC_5d13c.dir/build
    Building CXX object CMakeFiles/cmTC_5d13c.dir/testCXXCompiler.cxx.o
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -mmacosx-version-min=13.0 -MD -MT CMakeFiles/cmTC_5d13c.dir/testCXXCompiler.cxx.o -MF CMakeFiles/cmTC_5d13c.dir/testCXXCompiler.cxx.o.d -o CMakeFiles/cmTC_5d13c.dir/testCXXCompiler.cxx.o -c /Users/yueliu/Desktop/Projects/github/squirrel/librime/deps/glog/cmake-build/CMakeFiles/CMakeScratch/TryCompile-5cxre2/testCXXCompiler.cxx
    Linking CXX executable cmTC_5d13c
    /usr/local/Cellar/cmake/3.26.2/bin/cmake -E cmake_link_script CMakeFiles/cmTC_5d13c.dir/link.txt --verbose=1
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -mmacosx-version-min=$(RECOMMENDED_MACOSX_DEPLOYMENT_TARGET) -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/cmTC_5d13c.dir/testCXXCompiler.cxx.o -o cmTC_5d13c 
    clang: error: invalid version number in '-mmacosx-version-min=$(RECOMMENDED_MACOSX_DEPLOYMENT_TARGET)'
    clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
    make[6]: *** [cmTC_5d13c] Error 1
    make[5]: *** [cmTC_5d13c/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


-- Configuring incomplete, errors occurred!
make[4]: *** [glog] Error 1
make[3]: *** [deps] Error 2
make[2]: *** [xcode/deps] Error 2
make[1]: *** [librime/lib/libmarisa.a] Error 2
make: *** [lib/librime.1.dylib] Error 2

did not seem working with that

**Comment by LEOYoon-Tsaw** [comment]
clean the build files before retry

**Comment by haoyuc1** [comment]
遇到了相同的问题, MacOS 13.6, Xcode 15.0, cmake 3.27.6, clang 15.0, xcode-select 2397, 错误码如下

**Comment by haoyuc1** [comment]
> 遇到了相同的问题, MacOS 13.6, Xcode 15.0, cmake 3.27.6, clang 15.0, xcode-select 2397, 错误码如下

MacBook-Pro:squirrel$ sudo make ARCHS='x86_64' MACOSX_DEPLOYMENT_TARGET='13.0'
/Applications/Xcode.app/Contents/Developer/usr/bin/make librime
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C librime xcode/deps
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f xcode.mk deps
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f deps.mk
cd /Users/roychen/Downloads/squirrel/librime/deps/googletest; \
	cmake . -Bbuild \
	-DBUILD_GMOCK:BOOL=OFF \
	-DCMAKE_BUILD_TYPE:STRING="Release" \
	-DCMAKE_INSTALL_PREFIX:PATH="/Users/roychen/Downloads/squirrel/librime" \
	&& cmake --build build --target install
CMake Deprecation Warning at CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is AppleClang 15.0.0.15000040
-- The CXX compiler identification is AppleClang 15.0.0.15000040
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - broken
CMake Error at /usr/local/Cellar/cmake/3.27.6/share/cmake/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "/Library/Developer/CommandLineTools/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: '/Users/roychen/Downloads/squirrel/librime/deps/googletest/build/CMakeFiles/CMakeScratch/TryCompile-N8UEhR'
    
    Run Build Command(s): /usr/local/Cellar/cmake/3.27.6/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_90c5b/fast
    /Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_90c5b.dir/build.make CMakeFiles/cmTC_90c5b.dir/build
    Building C object CMakeFiles/cmTC_90c5b.dir/testCCompiler.c.o
    /Library/Developer/CommandLineTools/usr/bin/cc   -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min= -MD -MT CMakeFiles/cmTC_90c5b.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_90c5b.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_90c5b.dir/testCCompiler.c.o -c /Users/roychen/Downloads/squirrel/librime/deps/googletest/build/CMakeFiles/CMakeScratch/TryCompile-N8UEhR/testCCompiler.c
    clang: error: invalid version number in '-mmacosx-version-min='
    make[6]: *** [CMakeFiles/cmTC_90c5b.dir/testCCompiler.c.o] Error 1
    make[5]: *** [cmTC_90c5b/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:10 (project)


-- Configuring incomplete, errors occurred!
make[4]: *** [gtest] Error 1
make[3]: *** [deps] Error 2
make[2]: *** [xcode/deps] Error 2
make[1]: *** [librime/lib/libmarisa.a] Error 2
make: *** [lib/librime.1.dylib] Error 2
(base) HAOYUs-MacBook-Pro:squirrel roychen$ make clean
rm -rf build > /dev/null 2>&1 || true
rm build.log > /dev/null 2>&1 || true
rm bin/* > /dev/null 2>&1 || true
rm lib/* > /dev/null 2>&1 || true
rm data/plum/* > /dev/null 2>&1 || true
rm data/opencc/* > /dev/null 2>&1 || true

**Comment by LEOYoon-Tsaw** [comment]
和googletest有關，librime後續跟新了很多次這方面的依賴，可以再試試，我便宜的時候沒有問題。然後這也不是前端的問題，就關閉了
