### ISSUE TITLE
输出能否实现换行的功能？

### ISSUE THREAD

**Issue by hongxunming** [rime/squirrel#759]
我使用小鹤音形，经常会在自建字库中添加新词、语句，现在需要添加带有换行的内容，但是不知道怎么设置。我使用\n，但是输出时还是\n。
1.比如，我想输出的内容是：
床前明月光，疑是地上霜。
举头望明月，低头思故乡。

2.我在字库"flypy_user.txt"中新增内容如下
<img width="420" alt="image" src="https://user-images.githubusercontent.com/43163254/234071376-f2a17441-cf10-4517-b4be-32a34d6e2c27.png">

3.实际输出内容是
床前明月光，疑是地上霜。\n举头望明月，低头思故乡。

**Comment by LEOYoon-Tsaw** [comment]
可以，用0x0D字符表示換行，該字符可由Vim中摁下`ctrl`+`v`後輸入x0d輸入（如下圖中顯示爲`^M`者）
<img width="315" alt="image" src="https://user-images.githubusercontent.com/4469383/234099988-7c149047-794c-4f74-a326-293b362a61c7.png">
實現換行
<img width="174" alt="image" src="https://user-images.githubusercontent.com/4469383/234100099-f15cddfa-9e02-4121-97d3-3f12fce10aaf.png">

**Comment by groverlynn** [comment]
> 我使用小鹤音形，经常会在自建字库中添加新词、语句，现在需要添加带有换行的内容，但是不知道怎么设置。我使用\n，但是输出时还是\n。 1.比如，我想输出的内容是： 床前明月光，疑是地上霜。 举头望明月，低头思故乡。
> 
> 2.我在字库"flypy_user.txt"中新增内容如下 <img alt="image" width="420" src="https://user-images.githubusercontent.com/43163254/234071376-f2a17441-cf10-4517-b4be-32a34d6e2c27.png">
> 
> 3.实际输出内容是 床前明月光，疑是地上霜。\n举头望明月，低头思故乡。

用`\n`（line feed）的unicode ，也就是`\x0a`或`\u000a`。要兼容win平台的話需要用`\r\n`，也就是`\x0d\x0a`或者`\u000d\u000a`。類似的還有`\x85`或`\u0085`（next line/NEL）、`\u2028`（line separator）、`\u2029`（paragraph separator）

**Comment by hongxunming** [comment]
> > 我使用小鹤音形，经常会在自建字库中添加新词、语句，现在需要添加带有换行的内容，但是不知道怎么设置。我使用\n，但是输出时还是\n。 1.比如，我想输出的内容是： 床前明月光，疑是地上霜。 举头望明月，低头思故乡。
> > 2.我在字库"flypy_user.txt"中新增内容如下 <img alt="image" width="420" src="https://user-images.githubusercontent.com/43163254/234071376-f2a17441-cf10-4517-b4be-32a34d6e2c27.png">
> > 3.实际输出内容是 床前明月光，疑是地上霜。\n举头望明月，低头思故乡。
> 
> 用`\n`（line feed）的unicode ，也就是`\x0a`或`\u000a`。要兼容win平台的話需要用`\r\n`，也就是`\x0d\x0a`或者`\u000d\u000a`。類似的還有`\x85`或`\u0085`（next line/NEL）、`\u2028`（line separator）、`\u2029`（paragraph separator）

你好，我用的是Mac版的，我试过这些符号，都不行的。文件里是怎么样的，输出就是怎么样的，不会自动换行。

**Comment by LEOYoon-Tsaw** [comment]
> 你好，我用的是Mac版的，我试过这些符号，都不行的。文件里是怎么样的，输出就是怎么样的，不会自动换行。

我 Apr 24, 2023 就回你了，看不到麼？

**Comment by hongxunming** [comment]
> > 你好，我用的是Mac版的，我试过这些符号，都不行的。文件里是怎么样的，输出就是怎么样的，不会自动换行。
> 
> 我 Apr 24, 2023 就回你了，看不到麼？

Hi，刚试了一下你的方法，换行成功了，非常感谢！😘

**Comment by hongxunming** [comment]
> > 我使用小鹤音形，经常会在自建字库中添加新词、语句，现在需要添加带有换行的内容，但是不知道怎么设置。我使用\n，但是输出时还是\n。 1.比如，我想输出的内容是： 床前明月光，疑是地上霜。 举头望明月，低头思故乡。
> > 2.我在字库"flypy_user.txt"中新增内容如下 <img alt="image" width="420" src="https://user-images.githubusercontent.com/43163254/234071376-f2a17441-cf10-4517-b4be-32a34d6e2c27.png">
> > 3.实际输出内容是 床前明月光，疑是地上霜。\n举头望明月，低头思故乡。
> 
> 用`\n`（line feed）的unicode ，也就是`\x0a`或`\u000a`。要兼容win平台的話需要用`\r\n`，也就是`\x0d\x0a`或者`\u000d\u000a`。類似的還有`\x85`或`\u0085`（next line/NEL）、`\u2028`（line separator）、`\u2029`（paragraph separator）

我刚尝试另一个做法，已经换行成功了。谢谢你的回复！
