### ISSUE TITLE
大小写切换状态提示

### ISSUE THREAD

**Issue by web-dahuyou** [rime/squirrel#764]
这两天从搜狗输入法切换到rime输入法了，非常喜欢，有一个体验问题想请教：

我想要在切换大小写时，提示当前大小写状态，就像切换中英文时的提示。

目前我切换大小写的时候是静默的，只有在输入字母时才知道当前是大写还是小写。

另外要是系统顶部的状态栏也能显示当前的中英文状态以及大小写状态，那就更好了

**Comment by LEOYoon-Tsaw** [comment]
大小寫不是輸入法狀態吧

**Comment by web-dahuyou** [comment]
可能我表达的不清楚吧，我是想问有没有像搜狗输入法那样的交互，切换大小写的时候会有提示，小写状态是英，大写状态显示的 A；系统状态栏也会展示当前处于大写还是小写状态。我看rime配置项里好像只有中英文切换的配置，所以请教下是我配置的不对还是rime没有这种配置

**Comment by web-dahuyou** [comment]
知道了，感谢

**Comment by groverlynn** [comment]
Caps Lock默認是硬件級的狀態，各個鍵盤（包括軟鍵盤、遠程控制、虛擬機等連接的鍵盤）分別控制。所以軟件層面根本沒有一個單一的大小寫狀態

**Comment by groverlynn** [comment]
MacOS 14 Sonoma系統強制顯示大寫鎖定（⇪）了，但是一個鍵盤開啓另一個關閉的時候，顯示就不準確了
