### ISSUE TITLE
两个小细节希望优化一下

### ISSUE THREAD

**Issue by Johnson0907** [rime/squirrel#766]
macos: 13.3.1
squirrel: 0.16.2

1、系统状态栏，鼠须管的图标和其他输入法的图标尺寸不一致，鼠须管的要短一截

![状态栏图标](https://github.com/rime/squirrel/assets/64899466/f5be34d9-7891-4799-9ca7-d3720b28faea)

2、使用Finder时，状态通知会移动到上面，而不是在屏幕左下角

![状态通知](https://github.com/rime/squirrel/assets/64899466/d95b6079-05b8-4f15-b163-5c8b65046fa3)

**Comment by groverlynn** [comment]
1. see #686 
2. Finder其實是有隱藏輸入框的（將文件名頭文字快速定位擴展到任意字符）。這個輸入框尺寸位置可隨意調節。使用Finder時的狀態通知其實是跟隨那個隱藏輸入框裡的遊標位置。其實如果沒有輸入框的話輸入法是無法響應鍵盤操作的。而區分用戶是否喚醒了這個輸入框並不容易實現。但是用戶自行調整隱藏輸入框的位置其實很容易
<img width="1299" alt="Screenshot 2023-06-02 at 08 02 42" src="https://github.com/rime/squirrel/assets/14979243/0756075b-c426-4c66-811d-58c88dd8f02e">

**Comment by Johnson0907** [comment]
明白了，谢谢
