### ISSUE TITLE
#756完全無法使用

### ISSUE THREAD

**Issue by LEOYoon-Tsaw** [rime/squirrel#768]
回應一下 #756 #767 ，因爲 @groverlynn 不知從哪學來的惡習，不讓我直接在它的貼下留言，新開一貼吧

我這邊的橫排也好，豎排也好，都用得好好的；當然，如果有人故意要做出很醜的配色，我也攔不住，但至少能在 [Squirrel Designer](https://github.com/LEOYoon-Tsaw/Squirrel-Designer) 中自己改進，行距大了您調小一點不就行了，我截圖中這麼窄的行距都能做到，我不知道爲啥有人做不到。

<img width="131" alt="image" src="https://github.com/rime/squirrel/assets/4469383/67d5ff53-bcdb-48ae-855c-20429ca6b6c5">

---

而 @groverlynn 版本的問題就太得多了，遠不是用戶改改配置能解決的：

<img width="209" alt="image" src="https://github.com/rime/squirrel/assets/4469383/70a75b53-91de-4f0c-b700-04c397ebad9b">

![](https://user-images.githubusercontent.com/4469383/233805580-8ff0212d-16fa-4f28-91dd-509d2ce80630.png)

如果要說是我編譯有問題，那請釋出二進制，我可以再試一下。而那位的PR #756 自提出到現在已經 patch 了27個commit，不知現在是穩定了嗎？不知它提PR時是怎麼想的，爲何不等成熟了再提。

關於最低版本問題隨著時間進移，用上 TextKit 2 是遲早的，當然，如果 #756 能做到能用，那提升（而不是降低）一下老系統用戶的體驗也是善事，可以分 branch 嘛

**Comment by LEOYoon-Tsaw** [comment]
用 https://github.com/rime/squirrel/pull/756/commits/72b9f781c6cd849ec76468d1585a524731a6e2a3 的 CI 產物又試了一下

這 Emoji 是我眼花了嗎，爲啥是糊的？
<img width="127" alt="image" src="https://github.com/rime/squirrel/assets/4469383/c17e307a-f4d6-4477-91c5-8b33bd25b521">

豎排模式下，組合字符根本組不起來，包括nɑ̀ nɑ́ nɑ̄、≎̸
<img width="137" alt="image" src="https://github.com/rime/squirrel/assets/4469383/15659afb-547c-4065-aa56-afdcd9a27b08">

**Comment by ShikiSuen** [comment]
看你俩吵架这么久，我都觉得是不是非得用 Web-based 选字窗才能满足你们的需求。
一切只需要对 Safari 支持的 HTML5 标准负责就好。
