### ISSUE TITLE
MacOS Ventura 13.3 高内存占用

### ISSUE THREAD

**Issue by fengpanhe** [rime/squirrel#769]
重新部署内存会降下去，但是随着使用时间变长，内存不断增长；
鼠须管高内存占用如图：
![image](https://github.com/rime/squirrel/assets/12868426/4cd3a9da-1d5f-431f-8bbe-2b0ea8fbfd59)
系统信息：
![image](https://github.com/rime/squirrel/assets/12868426/19832d1d-f3b5-41eb-b06b-4a3922286481)

**Comment by LEOYoon-Tsaw** [comment]
<img width="402" alt="image" src="https://github.com/rime/squirrel/assets/4469383/25e94586-a454-4053-9eb7-1144dfa51446">
和方案有關吧，我的只佔50MB不到

**Comment by tamhaywoo** [comment]
系统：Monterey 12.6.6
内存占用：15.1 Mb
