### ISSUE TITLE
鼠鬚管在 Mac 平台已經至少一年多不能使用台灣繁體輸出了…

### ISSUE THREAD

**Issue by ShikiSuen** [rime/squirrel#77]
方案選單當中根本就沒有相關選項，不知這是不是故意淘汰之。

**Comment by liangqi** [comment]
0.9.26.1有“明月拼音 台湾正体”。我这里第一次选单有5项，翻页就可以看到了。

**Comment by lotem** [comment]
下一次發佈時，輸入方案不再以預裝形式提供。
輸入法安裝包僅保留一個內容縮減的拼音輸入方案，以示輸入法程序能夠正常工作。
[輸入方案](https://github.com/rime/plum#packages) 由用家選擇安裝。
試試 [一句話安裝指令](https://github.com/rime/plum#usage)

**Comment by Enig123** [comment]
輸入方案中，沒有「臺灣繁體」選項啊。請問當如何設定爲臺灣繁體？
