### ISSUE TITLE
发现一个奇怪的现象，在句子中输入[uhxm]（自然码 shangxian） 时，上限总是会拼到句子中

### ISSUE THREAD

**Issue by wudanyang6** [rime/squirrel#770]
比如：
<img width="101" alt="image" src="https://github.com/rime/squirrel/assets/8189540/44882a65-e421-495b-8595-776eb78b42b4">

<img width="253" alt="image" src="https://github.com/rime/squirrel/assets/8189540/e633d255-6fa1-430f-bf0b-12ce6a067bdb">

在拼词的时候上限总是在第一位，只有我单独输入 uhxm 的时候上线才会出现在第一位

<img width="147" alt="image" src="https://github.com/rime/squirrel/assets/8189540/e1637f80-d219-43bb-a9e0-c81059903b0d">

有没有人知道怎么调整一下？我已经把用户字典和luna拼音字典中各种地方的 【上限】全都给删除掉了，还是不能解决上面的问题

**Comment by lotem** [comment]
把「上線」上屏一次，是不是就行了。

我這裏「上線」調整爲首選詞後，「上線個東西」拼對了。而「你好上限」沒變。



> <img alt="image" width="253" src="https://user-images.githubusercontent.com/8189540/239190276-e633d255-6fa1-430f-bf0b-12ce6a067bdb.png">

這幅圖中的詞語順序表明「上線」尚未在同音詞中調整爲首選，因此他也不會優先出現在句中。

**Comment by wudanyang6** [comment]
已经上屏很多次了，无法解决这个问题

**Comment by wudanyang6** [comment]
一直上屏“上线”，上线就会出现在第一位了
