### ISSUE TITLE
一旦输入法的提示框的超出屏幕范围，就会出如图12的bug，如果不超出则屏幕则正常如图34所示。

### ISSUE THREAD

**Issue by TomatoFryEggs** [rime/squirrel#771]
![image](https://github.com/rime/squirrel/assets/9395814/42dc030d-0d4a-483f-bf28-d949df64113a)
![image](https://github.com/rime/squirrel/assets/9395814/74428026-79c6-4389-ba8c-a8adcd88606d)

![image](https://github.com/rime/squirrel/assets/9395814/3755a7d1-ec38-4f83-a455-a57588e9112a)
![image](https://github.com/rime/squirrel/assets/9395814/3451badc-669e-4c28-a81b-d63a823e963a)

**Comment by TomatoFryEggs** [comment]
测试了新出的微信输入法，当有多字时也是图2这样，会强行补空白，但是只有单字时不会像图1这样选中框变长。

**Comment by TomatoFryEggs** [comment]
@lotem

**Comment by lotem** [comment]
记忆屏幕右边界吧？你查查以前的讨论。

**Comment by TomatoFryEggs** [comment]
> 记忆屏幕右边界吧？你查查以前的讨论。
报歉不是
https://github.com/rime/squirrel/issues/523
描述的情况。
如果我没理解错上述说的问题是我图2表述的，经测试大多输入法都会这样。

我更大的问题困扰是图1的情况，选中蓝色的框太长了。

**Comment by TomatoFryEggs** [comment]
> #749 加入了控制選項：
> squirrel.custom.yaml:
> style/memorize_size: true/false

@lotem @LEOYoon-Tsaw 
我理解这个是解决的图2问题，我的主要问题是图1，不知道这个参有没有解决图1的问题，目前用的正式的release版，等这个功能上线后我再测试下，感谢了。

**Comment by lotem** [comment]
图1和图2只是候选字数量不同吧。

**Comment by TomatoFryEggs** [comment]
> 图1和图2只是候选字数量不同吧。

对，只有一个字的时候就会造成选中框填满整个候选框，会给人造成一个突然不一样的干扰，和您设置固定的候选框的长度为了不给用户跳来跳去的干扰的理念冲突了就。
有五笔模式的时候才同码字少，所以我感受比较明显。

**Comment by LEOYoon-Tsaw** [comment]
沒有那麼細緻的配置，如果你需要分別設置這兩種情況（說實話我也不知道你到底想怎麼區分這兩種情況）還是自己做吧。

**Comment by TomatoFryEggs** [comment]
> 沒有那麼細緻的配置，如果你需要分別設置這兩種情況（說實話我也不知道你到底想怎麼區分這兩種情況）還是自己做吧。

我没有一定要区分这两种表像。不过我大概懂你的意思了，我给你看下微信输入法和RIME的对比。

![image](https://github.com/rime/squirrel/assets/9395814/836eab9f-3e78-457a-a5b6-9219610576fa)

![image](https://github.com/rime/squirrel/assets/9395814/761e3bcb-a1cd-4128-9e42-21c3a2d9c8e1)

**Comment by lotem** [comment]
第一个、最后一个候选占满左右两边空白是为了无边框设计更好看~ 候选窗边框是后加的功能~
做得细致一点儿的话，可以在右边留有空白的情况，不扩展高亮区域。有时间可以研究研究怎么改。

**Comment by groverlynn** [comment]
> > 沒有那麼細緻的配置，如果你需要分別設置這兩種情況（說實話我也不知道你到底想怎麼區分這兩種情況）還是自己做吧。
> 
> 报歉我可能没表达清楚，我没有一定要区分这两种表像。我的问题是最后一个选中框占满全部候选了，不是根据字词大小占用的，不过我大概懂你的意思了，我给你看下微信输入法和RIME的对比。
> 
> ![image](https://user-images.githubusercontent.com/9395814/240840240-836eab9f-3e78-457a-a5b6-9219610576fa.png)
> 
> ![image](https://user-images.githubusercontent.com/9395814/240840225-761e3bcb-a1cd-4128-9e42-21c3a2d9c8e1.png)
> 
> 对于好的输入体验来说，维持住候选的框的长度是可以的，就像 @lotem 说的这是有意的设计。 但是最一个默认占用全部的候选我认为有点不合理。

![Screenshot 2023-05-25 at 18 39 22](https://github.com/rime/squirrel/assets/14979243/c948596d-02dd-423a-be24-fbc7ecc49469)
#756 線性模式下高亮區域一律只覆蓋候選項

**Comment by LEOYoon-Tsaw** [comment]
@TomatoFryEggs 
如果你說的是這樣，那最新的鼠鬚管已經是你要的樣子了。只是需要自己編譯一下。
<img width="148" alt="image" src="https://github.com/rime/squirrel/assets/4469383/7115e578-8887-4b3b-95c3-ad13a93d2bc9">

**Comment by TomatoFryEggs** [comment]
https://github.com/rime/squirrel/blob/master/INSTALL.md
已重新编译0.17.2，确实好的，记录下编译中遇到的问题。
https://github.com/rime/librime/issues/633
https://github.com/rime/squirrel/issues/654
https://github.com/rime/squirrel/issues/256

**Comment by TomatoFryEggs** [comment]
> @TomatoFryEggs
> 如果你說的是這樣，那最新的鼠鬚管已經是你要的樣子了。只是需要自己編譯一下。
> <img alt="image" width="148" src="https://user-images.githubusercontent.com/4469383/241073472-7115e578-8887-4b3b-95c3-ad13a93d2bc9.png">

在0.17.2下发现个新问题，在候选只有一个字的时候和多个字的时候的高度是不一致的，会拌动一下。

**Comment by LEOYoon-Tsaw** [comment]
用的什麼字體？

**Comment by TomatoFryEggs** [comment]
> 用的什麼字體？

默认的苹方

**Comment by LEOYoon-Tsaw** [comment]
> 默认的苹方

@TomatoFryEggs 我這的蘋方叫`PingFangTC-Regular`。以下爲測試：
爲求全面，我測了三種情況：全無編碼提示、全無提示但有繪文字、有編碼提示。
<img width="458" alt="all" src="https://github.com/rime/squirrel/assets/4469383/38627596-39d3-4635-9a6b-1adb6ac56d88">

爲便於比對文字基線位置，我將三幅截屏疊在一摞，可以確定地看到：**繪文字、編碼提示均未影響文字位置**。
<img width="460" alt="darken" src="https://github.com/rime/squirrel/assets/4469383/d4d12a75-cdc8-4630-858d-a2fdeb08530b">

**Comment by TomatoFryEggs** [comment]
> > 默认的苹方
> 
> @TomatoFryEggs 我這的蘋方叫`PingFangTC-Regular`。以下爲測試： 爲求全面，我測了三種情況：全無編碼提示、全無提示但有繪文字、有編碼提示。 <img alt="all" width="458" src="https://user-images.githubusercontent.com/4469383/241588045-38627596-39d3-4635-9a6b-1adb6ac56d88.png">
> 
> 爲便於比對文字基線位置，我將三幅截屏疊在一摞，可以確定地看到：**繪文字、編碼提示均未影響文字位置**。 <img alt="darken" width="460" src="https://user-images.githubusercontent.com/4469383/241588072-d4d12a75-cdc8-4630-858d-a2fdeb08530b.png">

我改成`PingFangTC-Regular`并重新编译后依然有此问题。
![image](https://github.com/rime/squirrel/assets/9395814/60d50165-6138-4d19-9c20-ae77f7ac1bf7)

ps：我在安装过程中，INSTALL.md 中的 `bash `./travis-install.sh`是不是改名字了？未找到这个文件，是`action-install.sh`这个文件吗？

**Comment by LEOYoon-Tsaw** [comment]
那我不知道了，復現不了。

**Comment by groverlynn** [comment]
> > > 默认的苹方
> > 
> > 
> > @TomatoFryEggs 我這的蘋方叫`PingFangTC-Regular`。以下爲測試： 爲求全面，我測了三種情況：全無編碼提示、全無提示但有繪文字、有編碼提示。 <img alt="all" width="458" src="https://user-images.githubusercontent.com/4469383/241588045-38627596-39d3-4635-9a6b-1adb6ac56d88.png">
> > 爲便於比對文字基線位置，我將三幅截屏疊在一摞，可以確定地看到：**繪文字、編碼提示均未影響文字位置**。 <img alt="darken" width="460" src="https://user-images.githubusercontent.com/4469383/241588072-d4d12a75-cdc8-4630-858d-a2fdeb08530b.png">
> 
> 我改成`PingFangTC-Regular`，你这应该是繁体的，我试了很多字体，并重新编译后依然有此问题。除了字体是否还有别有可能性？ ![image](https://user-images.githubusercontent.com/9395814/241605505-60d50165-6138-4d19-9c20-ae77f7ac1bf7.png)
> 
> ps：我在安装过程中，INSTALL.md 中的 `bash ./travis-install.sh`是不是改名字了？未找到这个文件，是`action-install.sh`这个文件吗？

看起來是取整的時候恰好有編碼的是去尾，沒編碼的是進一，結果把計算精度差放大幾個數量級變成了一個像素點。換一個字號試試看？

**Comment by xiebruce** [comment]
我也遇到了，只要超出边框，它就直接变成很长，你看
<img width="614" alt="image" src="https://github.com/rime/squirrel/assets/13575500/a3bba841-89ae-4e85-8b18-63eb2356946e">

而没超出边框的时候就正常
<img width="329" alt="image" src="https://github.com/rime/squirrel/assets/13575500/d2efafd7-7bbe-42ac-9948-fd72e90f9ffb">

**Comment by xiebruce** [comment]
按以下方式测试，我这边百分百复现bug。

先卸载
```bash
# brew安装的，这样卸载
brew uninstall Squirrel

# 也可以直接这样卸载，其实就是删掉Squirrel.app
rm -rf /Library/Input\ Methods/Squirrel.app
```

把用户配置文件整个文件夹移动到“下载”文件夹中，注意不能用`cp`，因为我这既相当于备份原配置，也相当于删除原配置，这样就相当把原来squirrel相关的东西全部删掉了
```bash
mv ~/Library/Rime/ ~/Downloads/
```

重新安装squirrel
```bash
brew install --cask squirrel
```

重啓macOS系統。

进入rime用户配置目录
```bash
cd ~/Library/Rime/
```

下载东风破工具
```bash
git clone https://github.com/rime/plum.git
```

进入东风破文件夹，并下载三个包：prelude essay wubi，最后退出plum文件夹返回到`~/Library/Rime/`文件夹
```bash
cd plum
bash rime-install prelude essay wubi
cd ..
```

新建一个`default.custom.yaml`文件
```bash
touch default.custom.yaml 
```

把以下內容粘貼到`default.custom.yaml`中并保存
```yaml
# ~/Library/Rime/default.custom.yaml

patch:
  # 方案列表(即输入法列表)
  schema_list:
    - schema: wubi86 # 86版五笔

  # 显示方案选单(即输入法列表)的快捷键
  switcher/hotkeys:
    - Control+grave
    - Control+Shift+grave
    # Command需要写成Super，Option要写成Alt
    - Super+Alt+grave
    - Alt+Shift+grave
    - Super+Control+grave
    - F4

  # 设置按左shift键上屏并切换到英文输入状态
  ascii_composer/switch_key/Shift_L: commit_code
  # 设置按右shift键上屏并切换到英文输入状态
  ascii_composer/switch_key/Shift_R: commit_code
```

新建一个`squirrel.custom.yaml`文件
```bash
touch squirrel.custom.yaml
```

把以下內容粘貼到`squirrel.custom.yaml`中并保存
```yaml
patch:
    app_options:
        {}
    style:
        color_scheme: native
        # 横向显示
        horizontal: true
        inline_preedit: true
        corner_radius: 5
```

`` control+option+` `` deploy一下，以使前面的设置生效。

Telegram窗口放到屏幕最右边，像我这样
<img width="444" alt="image" src="https://github.com/rime/squirrel/assets/13575500/c24b9d54-d970-4016-aec8-13f936365124">

由于在`default.custom.yaml`中我只放了一种五笔输入法，所以当前切换到Squirrel后就只有五笔，现在在Telegram框里输入`imya`，效果如下
<img width="603" alt="image" src="https://github.com/rime/squirrel/assets/13575500/97a525f2-48ac-4df5-87b7-93ddeecd9ca1">

如果Telegram不放在侧边，则不会有这个问题
<img width="329" alt="image" src="https://github.com/rime/squirrel/assets/13575500/d2efafd7-7bbe-42ac-9948-fd72e90f9ffb">

测试系统：
`macOS BirSur 11.5.1 (20G80)`
<img width="260" alt="image" src="https://github.com/rime/squirrel/assets/13575500/b150a11f-f268-43e6-80ee-bb3705acd1a8">

并且个人认为这个应该是跟系统无关的bug。

**Comment by LEOYoon-Tsaw** [comment]
@xiebruce 自己編譯一下最新版
> #749 加入了控制選項：
squirrel.custom.yaml:
style/memorize_size: true/false

**Comment by xiebruce** [comment]
> @xiebruce 自己編譯一下最新版
> 
> > #749 加入了控制選項：
> > squirrel.custom.yaml:
> > style/memorize_size: true/false

太麻烦了哈哈，我还是等发布吧，不知道预计什么时候发布下一版？

**Comment by TomatoFryEggs** [comment]
> > > > 默认的苹方
> > > 
> > > 
> > > @TomatoFryEggs 我這的蘋方叫`PingFangTC-Regular`。以下爲測試： 爲求全面，我測了三種情況：全無編碼提示、全無提示但有繪文字、有編碼提示。 <img alt="all" width="458" src="https://user-images.githubusercontent.com/4469383/241588045-38627596-39d3-4635-9a6b-1adb6ac56d88.png">
> > > 爲便於比對文字基線位置，我將三幅截屏疊在一摞，可以確定地看到：**繪文字、編碼提示均未影響文字位置**。 <img alt="darken" width="460" src="https://user-images.githubusercontent.com/4469383/241588072-d4d12a75-cdc8-4630-858d-a2fdeb08530b.png">
> > 
> > 
> > 我改成`PingFangTC-Regular`，你这应该是繁体的，我试了很多字体，并重新编译后依然有此问题。除了字体是否还有别有可能性？ ![image](https://user-images.githubusercontent.com/9395814/241605505-60d50165-6138-4d19-9c20-ae77f7ac1bf7.png)
> > ps：我在安装过程中，INSTALL.md 中的 `bash ./travis-install.sh`是不是改名字了？未找到这个文件，是`action-install.sh`这个文件吗？
> 
> 看起來是取整的時候恰好有編碼的是去尾，沒編碼的是進一，結果把計算精度差放大幾個數量級變成了一個像素點。換一個字號試試看？

好像你是对的， 原来的字号是17， 我换成18字号就好了， 顺便也试了下，16、15 ，却还是不行。

**Comment by LEOYoon-Tsaw** [comment]
我上面測試用的字號是15，無法復現這個問題，無從「修復」啊

**Comment by TomatoFryEggs** [comment]
> 我上面測試用的字號是15，無法復現這個問題，無從「修復」啊

已找到原因，我将字号设成浮点数就好了， 改成了16.0，之前用的是整数。
可以终结了，感谢各位。
