### ISSUE TITLE
一个关于编码提示的疑问

### ISSUE THREAD

**Issue by TomatoFryEggs** [rime/squirrel#773]
比如**明天**这个词，拼音是`ming tian`

当我输入到`mingt`的时候将会提示有明天这个词，但是当我输入到`mingti`、`mingtia`的时候明天的提示又没了，直到我输入`mingtian`

**Comment by groverlynn** [comment]
因為你沒有開啓編碼提示。mingt裏的t是首碼簡拼。ti、tia都只能理解成全拼
