### ISSUE TITLE
能否增加一个 TISIntendedLanguage 配置，来允许鼠须管作为系统唯一的输入法？

### ISSUE THREAD

**Issue by glacjay** [rime/squirrel#778]
来源在[这里](https://apple.stackexchange.com/a/87829/106088)，说是这样就能禁用系统默认的 US 键盘布局，只用鼠须管了。

**Comment by LEOYoon-Tsaw** [comment]
插眼，有空研究一下

**Comment by groverlynn** [comment]
> 来源在[这里](https://apple.stackexchange.com/a/87829/106088)，说是这样就能禁用系统默认的 US 键盘布局，只用鼠须管了。

鼠鬚管沒有自己的鍵盤佈局（Keyboard Layout），只是輸入法（input method），本身是依賴系統鍵盤佈局（不一定是US鍵盤）實現輸入的。而系統必須啓用至少一個鍵盤佈局（不一定是系統語言的鍵盤佈局），但必須是獨立的鍵盤佈局，不計輸入法私有的鍵盤佈局
