### ISSUE TITLE
[BUG] 0.16.2在vscode中无法输入中文标点的问题

### ISSUE THREAD

**Issue by Xrtero** [rime/squirrel#779]
版本: 鼠须管0.16.2，明月拼音
问题描述：在vscode中无法输入中文标点符号，原生的输入法能够正常输入。只在vscode中出现该问题，其他软件中没有出现。

**Comment by dog-fish** [comment]
我通过更新vscode版本解决了这个问题，当前vscode版本为1.79.2。

**Comment by groverlynn** [comment]
有嘗試切換ascii_punct選項嗎？

**Comment by groverlynn** [comment]
> 有尝试过该选项，对vscode配置如下：
> 
> ```yaml
>     com.microsoft.VSCode:
>         ascii_mode: false 
>         ascii_esc: true
>         ascii_punct: true  # 不管是true or false
> ```
> 
> 结果还是无法输入中文标点。使用原生的输入法倒是没这个问题，可以排除是vscode插件的问题。



> 有尝试过该选项，对vscode配置如下：
> 
> ```yaml
>     com.microsoft.VSCode:
>         ascii_mode: false 
>         ascii_esc: true
>         ascii_punct: true  # 不管是true or false
> ```
> 
> 结果还是无法输入中文标点。使用原生的输入法倒是没这个问题，可以排除是vscode插件的问题。

我說的是在選單切換，或者快捷鍵切換，不是設置初始狀態。因爲你的初始狀態設置成ascii模式＋ascii標點。你退出ascii模式後仍是ascii標點啊。
如果選單切換仍舊不能輸出半角或全角標點，那建議檢查一下`punctuation.yaml`及`punctuation.custom.yaml`設置

**Comment by blueidea2500** [comment]
ascii_mode: true                #true 英文 false 中文
      ascii_punct: false               #中文状态输出英文标点
      vim_mode: true                  #VIM esc 时切为英文

我是这么定义的，正常使用，不过我用的不是明月拼音

**Comment by dog-fish** [comment]
<img width="771" alt="image" src="https://github.com/rime/squirrel/assets/20829673/56cca862-9dfb-413a-af83-7c0c3efcacd4">
按照@blueidea2500 的方法配置后可以正常输入了。
