### ISSUE TITLE
Mac Air M1 13.4 安裝後無輸入法出現

### ISSUE THREAD

**Issue by dodolove88514** [rime/squirrel#781]
如題，不管用PKG安裝還是用brew安裝，都沒有輸入法出現，安裝完跳出的第三方輸入法也有按接受，也登出再登入過，重新安裝也試過了就是沒有，請協助．

**Comment by lotem** [comment]
同 https://github.com/rime/squirrel/issues/704

在系統語言設定裏手動添加
