### ISSUE TITLE
Enter error when install using 'brew install squirrel'(0.16.2) on macOS 13.4

### ISSUE THREAD

**Issue by caoruijuan13** [rime/squirrel#782]
<img width="331" alt="Screenshot 2023-06-20 at 17 45 28" src="https://github.com/rime/squirrel/assets/7274086/173c3c39-c3ad-4e09-b88a-9a9ad884e357">

**Comment by blueidea2500** [comment]
brew 装不了，就下载安装。

**Comment by CodeDreamfy** [comment]
一样的问题， Mac OS 13.4.1 (22F82)版本，使用下载的方式装了好几次，每次添加完后要我退出登陆，退出登陆重新进来后输入法里面依然没有鼠须管

**Comment by floyddcn** [comment]
我也是，请问解决了么
![image](https://github.com/rime/squirrel/assets/48442748/3210286e-6c15-431e-8b3d-3c2273606e18)

**Comment by groverlynn** [comment]
> 一样的问题， Mac OS 13.4.1 (22F82)版本，使用下载的方式装了好几次，每次添加完后要我退出登陆，退出登陆重新进来后输入法里面依然没有鼠须管

重新登錄後添加輸入法

**Comment by caoruijuan13** [comment]
同为13.4，用download没遇到这个问题
