### ISSUE TITLE
请问输入法中英状态图标能否关闭？

### ISSUE THREAD

**Issue by HF706** [rime/squirrel#783]
<img width="307" alt="image" src="https://github.com/rime/squirrel/assets/34521475/b64f667f-8965-400b-8ad6-463df1138482">

因为我已经分配唯一的快捷键分别给中文、英文输入法，所以不需要知道现在的输入状态是英文还是中文了，有什么办法可以关闭呢？

**Comment by blueidea2500** [comment]
squirrel.custom.yaml

patch: 这行下面增加
  show_notifications_when: never 

`
patch:
  show_notifications_when: never     # 状态通知，可设为全开（always）全关（never）appropriate
`

**Comment by HF706** [comment]
@blueidea2500 可用，感谢感谢。

**Comment by chen-ysh** [comment]
> squirrel.custom.yaml
> 
> patch: 这行下面增加
> 
> show_notifications_when: never
> 
> 注意前面有2个空格

太感谢了，bro
