### ISSUE TITLE
大佬们，中文输入模式下输入数字或英文字母后，紧接着的标点会自动变成英文标点，怎么禁用这个功能？

### ISSUE THREAD

**Issue by dnxxymcj** [rime/squirrel#785]
大佬们，中文输入模式下输入数字或英文字母后，紧接着的标点会自动变成英文标点，怎么禁用这个功能？

**Comment by groverlynn** [comment]
無法禁用。
相關代碼在 https://github.com/rime/librime/blob/master/src/rime/gear/punctuator.cc 的75–83行，可以自行刪除這段代碼

**Comment by dnxxymcj** [comment]
好的，谢谢！以后会弄成可配置的吗

**Comment by groverlynn** [comment]
> 好的，谢谢！以后会弄成可配置的吗

漢語的句子幾乎不可能以數字結尾，更不可能以阿拉伯數字結尾。阿拉伯數字之後的句點、冒號，甚至逗號、撇號，九成九情況下都是應該用西文標點的。真的遇上要用東亞標點的時候，刪掉再打一次就好。個人認爲完全沒有配置的必要

**Comment by dnxxymcj** [comment]
> > 好的，谢谢！以后会弄成可配置的吗
> 
> 漢語的句子幾乎不可能以數字結尾，更不可能以阿拉伯數字結尾。阿拉伯數字之後的句點、冒號，甚至逗號、撇號，九成九情況下都是應該用西文標點的。真的遇上要用東亞標點的時候，刪掉再打一次就好。個人認爲完全沒有配置的必要

嗯，我遇到了一种情况：我是用的虎码输入方案（一种形码），会使用到标顶（使用标点符号把首选字顶上屏）这个功能，由于句号和冒号会变成英文的，所以标顶失较了~

**Comment by groverlynn** [comment]
> > > 好的，谢谢！以后会弄成可配置的吗
> > 
> > 
> > 漢語的句子幾乎不可能以數字結尾，更不可能以阿拉伯數字結尾。阿拉伯數字之後的句點、冒號，甚至逗號、撇號，九成九情況下都是應該用西文標點的。真的遇上要用東亞標點的時候，刪掉再打一次就好。個人認爲完全沒有配置的必要
> 
> 嗯，我遇到了一种情况：我是用的虎码输入方案（一种形码），会使用到标顶（使用标点符号把首选字顶上屏）这个功能，由于句号和冒号会变成英文的，所以标顶失较了~

只有緊跟數字的句點和冒號會變成ASCII的，緊跟字母的標點不變，而且如果數字是輸入碼的一部分的時候標點也不變。應該不可能出現你所描述的情形

**Comment by dnxxymcj** [comment]
> > > > 好的，谢谢！以后会弄成可配置的吗
> 
> > > 
> 
> > > 
> 
> > > 漢語的句子幾乎不可能以數字結尾，更不可能以阿拉伯數字結尾。阿拉伯數字之後的句點、冒號，甚至逗號、撇號，九成九情況下都是應該用西文標點的。真的遇上要用東亞標點的時候，刪掉再打一次就好。個人認爲完全沒有配置的必要
> 
> > 
> 
> > 嗯，我遇到了一种情况：我是用的虎码输入方案（一种形码），会使用到标顶（使用标点符号把首选字顶上屏）这个功能，由于句号和冒号会变成英文的，所以标顶失较了~
> 
> 
> 
> 只有緊跟數字的句點和冒號會變成ASCII的，緊跟字母的標點不變，而且如果數字是輸入碼的一部分的時候標點也不變。應該不可能出現你所描述的情形

- [ ] 嗯，没有数字的时候是正常的，在数字后面打中文，然后输入冒号，冒号会直接上屏了，输入句号的话，第一下没反应，第二下会和中文一起上屏，我录了个视频https://github.com/rime/squirrel/assets/7660888/5728d43f-7797-4a9a-85c4-c2700f9daab6

**Comment by nc11cn** [comment]
其实汉字以数字结尾是很正常的，尤其在网络式的简化用语的背景下。当不同的情况，会出现不同的结果，会导致阻碍形成肌肉记忆。个人观点，给一个配置，可以关闭这样的功能，让不同人各取所需，是很有必要的。

**Comment by LEOYoon-Tsaw** [comment]
這個需要在librime提
