### ISSUE TITLE
请问是否有方法可以完全隐藏 preedit 区域？

### ISSUE THREAD

**Issue by pimgeek** [rime/squirrel#787]
我仔细研究了 color_scheme 中的相关配置项，发现这样的规律：

如果设置 `inline_candidate` 和 `inline_preedit` 均为 `false`，不会有任何编码 / 首选条目上屏，但是候选列表上方会出现 preedit 区域；如果设置 `inline_candidate: false` 和 `inline_preedit: true`，候选列表上方不会出现 preedit 区域，但是会有编码上屏。

有没有一种方法，可以让候选列表保持正常显示，但是 preedit 区域完全隐藏？（我在调试中、英文混输的方案，使用了 `~` 作为前导，`grave` 符号代替空格，Lua 翻译器配合转换，但是 preedit 区域的显示感觉有点乱，直接设置 `inline_candidate: true` 又显重复，而且中文输入时不希望首选直接上屏）

![image](https://github.com/rime/squirrel/assets/1609306/ff732f80-b6ec-4ba1-bbf5-629dab20e997)

```
preset_color_schemes:
  metro:
    inline_candidate: false
    inline_preedit: true
    preedit_type: composition
    spacing: 1
    text_color: 0x00FFFFFF
    preedit_back_color: 0x00FFFFFF
    hilited_text_color: 0x00FFFFFF
    hilited_back_color: 0x00FFFFFF

style:
  color_scheme: metro
```

**Comment by pimgeek** [comment]
我阅读学习了 https://github.com/hchunhui/librime-lua/issues/194 和一些 Rime 的 Lua 插件相关代码，最终解决了这个中英文混输时完全隐藏 preedit 的需求，我使用 `~` 作为引导字符，主要因为 `v` 在小鹤和虎码中都是常用编码，`/` 与 WorkFlowy 等 App 的快捷指令冲突，而 `;` 已经用于引导常用短语词汇等 。lua_translator 实现代码如下：

```
function english_translator(input, seg)
  local cand = ""
  if (input:sub(1, 1) == "~") then
    cand = Candidate("typing", seg.start, seg._end, input:gsub("^~", ""):gsub("`"," "), "🔤")
    cand.preedit = " " -- 如果觉得预编辑区中空格有干扰，可以用 <0x200b> <0x200c> <0x200d> 中的任何一个字符代替，它们都是 Zero-width
  end
  cand.quality = 1
  yield(cand)
end
```

**Comment by pimgeek** [comment]
借这个机会稍微介绍一下目前实现的中英混输效果：

❶ 输入第一个 `~` 时，显示如下（实际编码 `~`），按下空格后 ~ 立刻上屏：

![image](https://github.com/rime/squirrel/assets/1609306/ed8cdf25-ec0e-4c64-95d5-fc20665cab74)

❷ 开始输入英文句子时，显示如下（实际编码 ```~A`Quick`Brown`Fox```），按下空格不会退出编码模式，按回车键以蓝色背景首选项的样子上屏，并且已经去掉了引导字符 `~`。

![image](https://github.com/rime/squirrel/assets/1609306/e4543706-d84e-44d4-bd24-8e2839dcdd84)

这里空格不退出编辑，回车键不直接输出原始 input 是因为引入了 lua_processor 捕捉 `Space` 和 `Return` 按键，改变了 Rime 的默认按键行为；引导字符 `~` 和模拟空格字符 ```grave (`)``` 没有出现在最终结果里，是因为 `lua_processor` 和 `lua_translator` 都做过正则替换，确保输出候选项时没有这些多余字符。

❸ 输入中文的时候，空格键与回车键没有任何差别，因为所使用的 `lua_processor` 和 `lua_translator` 只针对 `~` 开头的编码。

为解决这个需求，花了很多时间看 GitHub 上相关的 Issue。我感觉中英混输问题虽然不算特别高频的需求，但还是会困扰到经常需要写代码的人（包括我）。目前的实现方式还比较粗糙 / hacky，希望能起到抛砖引玉的效果，引起 Rime 社区的关注，或许有助于促成更优雅的中英文混输解决方案 🤓

下面引用的这些 Issue 是我印象比较深刻的，或者对我实现当前这个方案有一定启发的：

* [我只是在一段话中输入几个英文缩写，来回切换太麻烦了](https://github.com/rime/squirrel/issues/581) by @hicaicai - rime/squirrel
* [在中文输入状态下，能实现单词大小写混合输入吗？](https://github.com/rime/squirrel/issues/434) by @llity - rime/squirrel
* [使用 `affix_segmentor` 配置 `prefix: ";"` 来实现临时英文功能，但是按回车键会带上分号](https://github.com/rime/librime/issues/607) by @tomgrean - rime/librime
* [不想要在英文输入 A 状态和中文输入下频繁用 `Shift` 键切换](https://github.com/rime/librime/issues/501) by @HarryRen - rime/librime
* [Shift 切换中英文经常出现不希望的切换](https://github.com/rime/squirrel/issues/376) by @netjune - rime/squirrel
* [希望输入“v”临时切换为英文输入模式（类似Google输入法）](https://github.com/rime/librime/issues/134) by @buaabyl - rime/librime
· [经常需要写中文 LaTeX 文档或者带公式的 Markdown 文档，中英文切换非常烦人](https://github.com/rime/librime/issues/75) by @plus2047 - rime/librime
* [经常敲代码的时候忘记切成英文输入, 不小心按了空格上屏的却是中文](https://github.com/rime/home/issues/249) by @RRRRRm - rime/home
* [没有办法：用分号打头的输入会被识别出来，但输出结果却不包含分号？](https://gist.github.com/lotem/3076166) by @Igotit - lotem/gist - default.custom.yaml
* [怎么在emacs-rime中临时切为英文模式？](https://github.com/DogLooksGood/emacs-rime/issues/194) by @whjiang - DogLooksGood/emacs-rime

**Comment by pimgeek** [comment]
> 用preedit_format把preedit改成空字符串就行

我最开始就尝试过这个方法，刚刚又再次按你说的修改成空字符串，临时英文的输出结果是这样的： ```~Not`work`as`expected```，如果你的 Rime 版本能够用这种方式达成目标，我推测可能还有一些相关设定需要做（我在使用 macOS 上的鼠须管 Squirrel 0.16.2 ）

<img width="304" alt="image" src="https://github.com/rime/squirrel/assets/1609306/5fdf02fa-b9ce-41eb-b554-db9c2153c16a">

上图是实际效果，inline_preedit 区域还是会有内容（我不想用非 inline，因为要占掉一大块区域）🤔

**Comment by LEOYoon-Tsaw** [comment]
別全刪完，畱個空格唄
```yaml
- xform/.*/ /
```
<img width="208" alt="image" src="https://github.com/rime/squirrel/assets/4469383/0e015027-9de8-424e-9945-c44b86b11be0">

**Comment by pimgeek** [comment]
> 別全刪完，畱個空格唄
> 
> ```yaml
> - xform/.*/ /
> ```

我按照你说的这种方式也尝试过多次，刚才又重新尝试了几次。主要是加在 english_translator 的设定中。

```yaml
english_translator@librime_lua_shewer:
  tag: abc
  prefix: "~"
  preedit_format:
    - xform/.*/_/
```

迄今为止从来没有成功过，如果这招能成功，我肯定不会绕路去学 lua `cand.preedit = "..." ` 那种方式。也可能是你的其它配置细节与我的不同。
