### ISSUE TITLE
升级到 macOS 14 beta 4 (23A5301g) 以后，鼠须管的候选栏无法显示了。

### ISSUE THREAD

**Issue by scomper** [rime/squirrel#789]
![CleanShot 2023-07-26 at 06 58 09@2x](https://github.com/rime/squirrel/assets/13041847/0490f17b-c053-42ae-893e-6e128409e725)
鼠须管  0.17.2 版本，无法正确显示候选内容。
重新安装 [0.16.2](https://github.com/rime/squirrel/releases/tag/0.16.2) 恢复正常

**Comment by LEOYoon-Tsaw** [comment]
我這邊沒問題

**Comment by fatpa** [comment]
有 0.17.2 版本吗

**Comment by LEOYoon-Tsaw** [comment]
0.17.2就是我做的

**Comment by fatpa** [comment]
> 0.17.2就是我做的

看着好像还没 release 出来，是要自己打包吗？还是有链接可以分享？

**Comment by scomper** [comment]
重新下载 鼠须管 0.17.2 版本覆盖安装后没有复现问题，😢
