### ISSUE TITLE
Which was the last version to build with Xcode 3.2?

### ISSUE THREAD

**Issue by barracuda156** [rime/squirrel#790]
If anyone remembers :)

**Comment by LEOYoon-Tsaw** [comment]
Xcode 3.2 was released in 2009, to my best knowledge, the answer is none.

**Comment by barracuda156** [comment]
I see, thank you. I will try to build it still, who knows, might work.
It is unfortunate to need to depend on Xcode, since Apple dumps older systems from support. If we could build with GCC, on 2009 10.6 and in fact on 10.5 we have GCC 13 working.
