### ISSUE TITLE
想请教一下，如图片中，序号的占用符是%c，候选字的占位符是%@，编码的占位符是什么？

### ISSUE THREAD

**Issue by laughmaker** [rime/squirrel#802]
<img width="245" alt="image" src="https://github.com/rime/squirrel/assets/1858816/47b92e4c-2a34-4419-b31d-619f27227ed7">
想请教一下，如图片中，序号的占用符是%c，候选字的占位符是%@，编码的占位符是什么？

**Comment by LEOYoon-Tsaw** [comment]
包含在%@中，要改註釋的格式可以用正則修改

**Comment by laughmaker** [comment]
> 包含在%@中，要改註釋的格式可以用正則修改

比如，我candidate_format: "  %c.%@  " ，这样我是想调整“5.破~b”这一起两边的间距，结果调整的是破后面有了空格，而不是b后面有空格，有什么办法吗？

**Comment by Lumen01** [comment]
不知道你的问题解决了没有，可以尝试下这个：
> candidate_format: "%c\u2005.\u2005%@\u2005\u2005"

**Comment by fliu721** [comment]
我也想知道

**Comment by LEOYoon-Tsaw** [comment]
%c變成序號，其它一切都在%@裏，如果想要玩得花，可以討論一個comment的佔位符

**Comment by LEOYoon-Tsaw** [comment]
> > 包含在%@中，要改註釋的格式可以用正則修改
> 
> 比如，我candidate_format: " %c.%@ " ，这样我是想调整“5.破~b”这一起两边的间距，结果调整的是破后面有了空格，而不是b后面有空格，有什么办法吗？

b後面要空格就在comment_format裏用正則加啊，xform/$/       /

**Comment by fliu721** [comment]
![image](https://github.com/rime/squirrel/assets/4555774/70923b68-c270-4d03-8992-056d3625b957)
我现在是这样的，不知道怎么调整候选字和[之间的距离。这个距离在0.16.2上没这么大，0.18以后变大了

**Comment by LEOYoon-Tsaw** [comment]
默認的沒這麼大距離，你看看方案裡comment_format加了什麼

**Comment by fliu721** [comment]
scheme.yaml的配置：
```
chaifen:
  opencc_config: hu_cf.json
  option_name: chaifen
  show_in_comment: true
  comment_format:
    - "xform/&nbsp;//"
    - "xform/\t//"
```

hu_cf.json 的内容：
```
{
  "name": "hu_cf",
  "segmentation": {
    "type": "mmseg",
    "dict": {
      "type": "text",
      "file": "hu_cf.txt"
    }
  },
  "conversion_chain": [{
    "dict": {
      "type": "text",
      "file": "hu_cf.txt"
    }
  }]
}
```
hu_cf.txt 的内容
![image](https://github.com/rime/squirrel/assets/4555774/71592b2c-b28c-4e94-8174-6e349f9003d1)
帮忙看看是不是hu_cf.txt的内容导致的。这里有个TAB，但是不能去掉，去掉就不显示〔〕的内容了。

**Comment by LEOYoon-Tsaw** [comment]
用comment_format把comment全替換成「回」，看看還剩多大間距，然後換幾個字體再看看，就知道了

**Comment by LEOYoon-Tsaw** [comment]
我準備改成`[label]. [candidate] [comment]`，徹底解決此疑惑

**Comment by LEOYoon-Tsaw** [comment]
已在 #898 更新
