### ISSUE TITLE
输入个别字符时，候选框高度会变高

### ISSUE THREAD

**Issue by hikinsley** [rime/squirrel#806]
打出 xin 的时候，候选框高度会变高
出现问题的字符：
![image](https://github.com/rime/squirrel/assets/42203894/d9d04fc9-3cc1-45e2-b6f5-79787c284fb3)
正确的样子：
![image](https://github.com/rime/squirrel/assets/42203894/a762ce46-6823-46f4-a4d4-d1aa863de2e3)

**Comment by TomatoFryEggs** [comment]
试试配置界面的参数为浮点数，加个`.0`就行，我之前遇到这种情况这样处理就解决了，用整数就有问题。

**Comment by hikinsley** [comment]
> 试试配置界面的参数为浮点数，加个`.0`就行，我之前遇到类似这种情况这样处理就解决了，用整数就有问题。

大概是哪个参数，我改掉之后没有变化

**Comment by TomatoFryEggs** [comment]
> > 试试配置界面的参数为浮点数，加个`.0`就行，我之前遇到类似这种情况这样处理就解决了，用整数就有问题。
> 
> 大概是哪个参数，我改掉之后没有变化

color_schemes 里面的任何宽高相关的数值。

**Comment by hikinsley** [comment]
> > > 试试配置界面的参数为浮点数，加个`.0`就行，我之前遇到类似这种情况这样处理就解决了，用整数就有问题。
> > 
> > 
> > 大概是哪个参数，我改掉之后没有变化
> 
> color_schemes 里面的任何宽高相关的数值。

好的，谢谢

**Comment by groverlynn** [comment]
當前字體不包含某個字符時，系統自動選擇fallback字體。此時會儘量確保襯線、字重、字寬、字高（排名有先後）相同。對於罕用符號，支持顯示的字體可能就個位數，可能每一個的字高都完全不同。#756 用了三重辦法鎖定，還是有1%的機會行高會被超高字體帶跑
