### ISSUE TITLE
Mac OS 14 安装 0.16.2 后无法使用

### ISSUE THREAD

**Issue by natamox** [rime/squirrel#809]
<img width="902" alt="image" src="https://github.com/rime/squirrel/assets/120485290/70f989a0-ca88-4fb0-809f-67c21ec021b1">

<img width="171" alt="image" src="https://github.com/rime/squirrel/assets/120485290/81568db6-b71a-4cdb-a7d0-22bb474a43b2">

**Comment by natamox** [comment]
<img width="752" alt="image" src="https://github.com/rime/squirrel/assets/120485290/6a77faa4-1c2e-4a9e-a5ff-9e824d8d25d3">

**Comment by LEOYoon-Tsaw** [comment]
添加一下

**Comment by CRtree** [comment]
需要添加一下，如圖：
<img width="640" alt="image" src="https://github.com/user-attachments/assets/f02e77ae-dc1e-4351-b917-57d6d5c6f9d6">
<img width="523" alt="image" src="https://github.com/user-attachments/assets/537b6e20-0039-4b98-8283-926fa8fcd549">
