### ISSUE TITLE
最新源码编译，按shift键时无法提示中英状态

### ISSUE THREAD

**Issue by haroldcrane** [rime/squirrel#810]
macOS Sonoma (14.0) 上编译最新版本 (0.17.2)，按shift键时没有悬浮框提示中英状态，其他功能都正常。
下载安装编译好的pkg，可以正常显示。
action-install.sh 和 make package 时也没有看到报错，不太清楚是什么原因

**Comment by LEOYoon-Tsaw** [comment]
可能你的方案中沒有設置中英切換的標籤

**Comment by haroldcrane** [comment]
谢谢回复。是指的是 states: ["中文", "西文"] 吗？我看输入方案中都已经添加了这个，并且使用自带的方案时也没有提示。

**Comment by haroldcrane** [comment]
没有用action-build.sh，而是自己编译Boost，可以正常显示提示框了。
