### ISSUE TITLE
使用左右Shift选择二三候选词的问题

### ISSUE THREAD

**Issue by choijck** [rime/squirrel#813]
输入方案为雾凇拼音，添加了如下代码，使用左右Shift来选择第二三候选词。（不知道为什么要写Shift+Shift）
```
    # 二三候选词快捷键
    - { when: has_menu, accept: Shift+Shift_L, send: 2 }
    - { when: has_menu, accept: Shift+Shift_R, send: 3 }
``
但是在输入邮箱的时候，输入@，会导致第二候选+@上屏。

请问有没有方法可以继续保持左右Shift做候选词快捷键，又不影响拼音状态下的邮箱输入？

**Comment by groverlynn** [comment]
`Shift+Shift_L`，`Shift`是修飾鍵，`Shift_L`是主鍵。但凡`Shift_L`或`Shift_R`按下，必然伴隨`Shift`修飾狀態。也就是説不可能存在單獨的`Shift_L`或`Shift_R`。而Rime要求必須提供主鍵，所以不能只有`Shift`（或者説這種情況下`Shift`被當作主鍵，然而不存在名為`Shift`的主鍵）。
既然你已經定死了主鍵是`Shift_L`，修飾鍵是`Shift`，那麼你按下`Shift_L`的時候必然要立刻響應對應動作（第二候選上屏），就如同你按下`2`。規則寫得這麼死，繞不過啊。

**Comment by netvolcano** [comment]
哪位大侠能够解决这种这个问题呢？在使用Shift输入大写字母的时候，与使用shift来选择候选词，这两个功能如何能避免冲突？如果达到以前拼音加加的效果，就非常好了。

**Comment by LEOYoon-Tsaw** [comment]
我感覺我能解決此問題，如果按下Shift後直接放開，則選字，如果按下後又按了其它鍵，則不再選字

**Comment by netvolcano** [comment]
希望能尽早看到你的解决方案，^-^
 
Sender: LEO Yoon-Tsaw
Send Time: 2024-05-17 08:37
Receiver: rime/squirrel
cc: netvolcano; Comment
Subject: Re: [rime/squirrel] 使用左右Shift选择二三候选词的问题 (Issue #813)
我感覺我能解決此問題，如果按下Shift後直接放開，則選字，如果按下後又按了其它鍵，則不再選字

**Comment by LEOYoon-Tsaw** [comment]
> 希望能尽早看到你的解决方案，^-^

https://github.com/LEOYoon-Tsaw/squirrel/commit/e101438d84d929ea72a6f8aa34610f899a792e0b

**Comment by LEOYoon-Tsaw** [comment]
@netvolcano 幫忙測一下看看解決問題沒有
https://github.com/LEOYoon-Tsaw/squirrel/releases/tag/0.99.5

**Comment by netvolcano** [comment]
囧，我是一个windows用户，无法使用这个版本来测试。
 
Sender: LEO Yoon-Tsaw
Send Time: 2024-05-17 22:42
Receiver: rime/squirrel
cc: netvolcano; Mention
Subject: Re: [rime/squirrel] 使用左右Shift选择二三候选词的问题 (Issue #813)
@netvolcano 幫忙測一下看看解決問題沒有
https://github.com/LEOYoon-Tsaw/squirrel/releases/tag/0.99.5

**Comment by lotem** [comment]
r²ime 會支持~

**Comment by LEOYoon-Tsaw** [comment]
> 這個功能目前不支持。
> 
> 
> 
> 而且他跟前端沒有關係，最好不要在前端處理。

行，那還是不改了

**Comment by netvolcano** [comment]
写了一个lua脚本来搞定windows下小狼毫使用左右shift来选词的功能。使用时在engine的processors中加入
```yaml
engine:
  processors:
    - lua_processor@*shift_enhanced
```


shift_enhanced.lua的内容如下：

```lua
-- 左右shift来作为第2、3候选词的选择键
-- V1.0: 20250311 netvolcano

local function init(env)
    env.toggle_expired_ = 0
    env.shift_key_pressed_ = false
    env.other_key_pressed_ = false
    env.XK_Shift_L, env.XK_Shift_R = 0xffe1, 0xffe2
    env.kRejected, env.kAccepted, env.kNoop = 0, 1, 2
    env.TIME_WINDOW = 0.5  -- 时间窗口：0.5 秒
end

local function is_within_time_window(env)
    return os.time() < env.toggle_expired_
end

local function select_candidate(env, context, key_code)
    local composition = context.composition
    if not composition:empty() then
        local segment = composition:back()
        local menu = segment.menu

        if not menu then
            -- log.error("候选菜单为空")
            return
        end

        local candidate_count = menu:candidate_count()
        -- log.error("当前候选词数量：", candidate_count)

        if key_code == env.XK_Shift_L and candidate_count >= 2 then
            context:select(1)  -- 选择第 2 候选词（索引从 0 开始）
            context:commit()
        elseif key_code == env.XK_Shift_R and candidate_count >= 3 then
            context:select(2)  -- 选择第 3 候选词
            context:commit()
        else
            -- log.error("候选词数量不足")
        end
    end
end

local function processor(key, env)
    local context = env.engine.context
    local is_shift = key.keycode == env.XK_Shift_L or key.keycode == env.XK_Shift_R

    -- 如果按下其他修饰键（如 Ctrl/Alt），直接跳过
    if key:ctrl() or key:alt() or key:super() then
        return env.kNoop
    end

    if is_shift then
        if key:release() then
            if env.shift_key_pressed_ and not env.other_key_pressed_ then
                if is_within_time_window(env) then
                    -- log.error("Shift 键单独释放，尝试选择候选词")
                    select_candidate(env, context, key.keycode)
                else
                    -- log.error("Shift 键释放超时")
                end
            end
            env.shift_key_pressed_ = false
            env.other_key_pressed_ = false
        else
            if not env.shift_key_pressed_ then
                env.shift_key_pressed_ = true
                env.toggle_expired_ = os.time() + env.TIME_WINDOW
                -- log.error("Shift 键按下，时间窗口开始")
        end
        end
        return env.kAccepted
    else
        if env.shift_key_pressed_ then
            env.other_key_pressed_ = true
            -- log.error("检测到其他键按下")
        end
        env.shift_key_pressed_ = false
        return env.kNoop
    end
end

return {init = init, func = processor}

```

**Comment by netvolcano** [comment]
更新一下shift_enhanced.lua文件：

···lua
-- 左右shift来作为第2、3候选词的选择键
-- 改进版：根据光标位置决定是否直接上屏
-- V1.1: 20250311 netvolcano
-- V1.2: 20250314 netvolcano

local function init(env)
    env.toggle_expired_ = 0
    env.shift_key_pressed_ = false
    env.other_key_pressed_ = false
    env.XK_Shift_L, env.XK_Shift_R = 0xffe1, 0xffe2
    env.kRejected, env.kAccepted, env.kNoop = 0, 1, 2
    env.TIME_WINDOW = 0.3  -- 时间窗口：0.3 秒
end

local function is_within_time_window(env)
    return os.time() < env.toggle_expired_
end

local function is_caret_at_end(context)
    -- 检查光标是否在输入字符串的末尾
    local input = context.input
    local caret_pos = context.caret_pos
    return caret_pos == #input
end

local function update_segment_preedit(env, context, candidate)
    local composition = env.engine.context.composition
    local segmentation = composition:toSegmentation()

    -- 获取当前分段的起始和结束位置
    local preedit = context.input
    local start_pos = segmentation:get_current_start_position()
    local end_pos = segmentation:get_current_end_position()

    log.error("before preedit = " .. preedit)
    -- 替换 preedit 字符串中当前分段的内容
    local new_preedit = string.sub(preedit, 1, start_pos) .. candidate.text .. string.sub(preedit, end_pos + 1)
    log.error("after preedit =" .. new_preedit)
    -- context.input = new_preedit
end

local function select_candidate(env, context, key_code)
    local composition = context.composition
    if not composition:empty() then
        local is_caret_at_end_flag = is_caret_at_end(context)
        local segment = composition:back()

        local menu = segment.menu
        if not menu then
            -- log.error("候选菜单为空")
            return
        end

        local selected_candidate_index = segment.selected_index
        local candidate_count = menu:candidate_count()

        if key_code == env.XK_Shift_L and candidate_count >= 2 then
            context:select(selected_candidate_index + 1)  -- 第 2 候选词
        elseif key_code == env.XK_Shift_R and candidate_count >= 3 then
            context:select(selected_candidate_index + 2)  -- 第 3 候选词
        end
        -- 光标在末尾，直接上屏
        if is_caret_at_end_flag then
            context:commit()
        end
    end
end

local function processor(key, env)
    local context = env.engine.context
    local is_shift = key.keycode == env.XK_Shift_L or key.keycode == env.XK_Shift_R

    -- 如果按下其他修饰键（如 Ctrl/Alt），直接跳过
    if key:ctrl() or key:alt() or key:super() then
        return env.kNoop
    end

    if is_shift then
        if key:release() then
            if env.shift_key_pressed_ and not env.other_key_pressed_ then
                if is_within_time_window(env) then
                    -- log.error("Shift 键单独释放，尝试选择候选词")
                    select_candidate(env, context, key.keycode)
                else
                    -- log.error("Shift 键释放超时")
                end
            end
            env.shift_key_pressed_ = false
            env.other_key_pressed_ = false
        else
            if not env.shift_key_pressed_ then
                env.shift_key_pressed_ = true
                env.toggle_expired_ = os.time() + env.TIME_WINDOW
                -- log.error("Shift 键按下，时间窗口开始")
            end
        end
        return env.kAccepted
    else
        if env.shift_key_pressed_ then
            env.other_key_pressed_ = true
            -- log.error("检测到其他键按下")
        end
        env.shift_key_pressed_ = false
        return env.kNoop
    end
end

return {init = init, func = processor}

···

**Comment by shewer** [comment]
{Control+F12}{Control+Release+F12}{Control+Release+Control_L}
{Shift_L}A{Shift+Release+Shift_L}
{Shift_L}{Shift+Release+Shift_L}
{Shift_L}C{Shift+Release+Shift_L}
看起來 
得記下 上一個key Shift_L   接着下一個key 必須 {Shift+Release+Shift_L}   才送出候選

**Comment by netvolcano** [comment]
你打算来改进一下吗？另外，你提供的print_key的这个lua脚本，在方案的yaml中是不是要加一句如下的：
```yaml
print_key: 0
```

**Comment by shewer** [comment]
不用吧

```yaml
patch:
    engine/processors/@after 0:   <---    在0之後 加入

**Comment by shewer** [comment]
試試這code    shift_l   current index +1    shift_r  current_index +2 


```lua
 local Rejected = 0 
 local Accepted = 1
 local Noop = 2

 local function select(ctx, index)
   local segment = ctx.composition:back()
   ctx:select( segment.selected_index + index)
 end

 local M = {}
 function M.init(env)
   env.shift_l = KeyEvent("Shift_L") -- W: Undefined global `KeyEvent`.
   env.shift_r = KeyEvent("Shift_R") -- W: Undefined global `KeyEvent`.
   env.shift_l_release = KeyEvent("Shift+Release+Shift_L") 
   env.shift_r_release = KeyEvent("Shift+Release+Shift_R")
   env.last_key = KeyEvent("a") 
 end


 function M.func(key, env)
   local context = env.engine.context

   if not context:has_menu() then
       return Noop
   end


   if key:eq(env.shift_l_release) and env.last_key:eq(env.shift_l) then
     select(context,1)
     return Accepted
      -- W: Line with spaces only.
   elseif key:eq(env.shift_r_release) and env.last_key:eq(env.shift_r) then
     select(context,2)
     return Accepted
   end

   env.last_key = KeyEvent(key:repr()) --  將 目前key 備份
   return Noop
 end

 return M
```

**Comment by netvolcano** [comment]
没有弄懂你说的「不用吧」是指的什么？和下面的那个patch的代码没有关系吧？

**Comment by netvolcano** [comment]
> select_candidate.lua 使用 Shift_L Shift_R commit 目前候選 次一 次二 試試這code shift_l current index +1 shift_r current_index +2
> 
>  local Rejected = 0 
>  local Accepted = 1
>  local Noop = 2
> 
>  local function select(ctx, index)
>    local segment = ctx.composition:back()
>    ctx:select( segment.selected_index + index)
>  end
> 
>  local M = {}
>  function M.init(env)
>    env.shift_l = KeyEvent("Shift_L") -- W: Undefined global `KeyEvent`.
>    env.shift_r = KeyEvent("Shift_R") -- W: Undefined global `KeyEvent`.
>    env.shift_l_release = KeyEvent("Shift+Release+Shift_L") 
>    env.shift_r_release = KeyEvent("Shift+Release+Shift_R")
>    env.last_key = KeyEvent("a") 
>  end
> 
> 
>  function M.func(key, env)
>    local context = env.engine.context
> 
>    if not context:has_menu() then
>        return Noop
>    end
> 
> 
>    if key:eq(env.shift_l_release) and env.last_key:eq(env.shift_l) then
>      select(context,1)
>      return Accepted
>       -- W: Line with spaces only.
>    elseif key:eq(env.shift_r_release) and env.last_key:eq(env.shift_r) then
>      select(context,2)
>      return Accepted
>    end
> 
>    env.last_key = KeyEvent(key:repr()) --  將 目前key 備份
>    return Noop
>  end
> 
>  return M

我试了一下，好像没有起作用，你自己也可以尝试一下，看看是不是哪个地方的还需要改进。

**Comment by shewer** [comment]
Shift_L  Shift_R 是不是已綁定了其他功能了  ，
我已將 Shift_L   Shift_R 改成 Control_L Control_R

**Comment by netvolcano** [comment]
我想过这个问题，shift键一般就是用来控制大小写，而ctrl是用来实现好多的功能；在键盘上，shift大一些，也距离字母键近一些，方便小手指触碰。当然，每一个人的习惯不一样，我是从拼音加加过来的。

**Comment by shewer** [comment]
上面有檢查keyTools你可以自己測試那鍵比較適合你

**Comment by netvolcano** [comment]
这两天有空，折腾了一下，在小狼豪weasel上实现了，把代码贴一下：
```lua
-- 左右shift来作为第2、3候选词的选择键
-- 改进版：根据光标位置决定是否直接上屏
-- V1.5: 20250411 netvolcano

local Rejected = 0 
local Accepted = 1
local Noop = 2

local function select(ctx, index)
    local composition = ctx.composition
    if not composition:empty() then
        local segment = ctx.composition:back()
        local menu = segment.menu
        if not menu then
            -- log.error("候选菜单为空")
            return
        end
        local candidate_count = menu:candidate_count()

        local selected_candidate_index = segment.selected_index
        local new_index = selected_candidate_index + index

        if new_index > candidate_count - 1 then
            new_index = candidate_count - 1
        end

        ctx:select(new_index)
    end
end

local M = {}
function M.init(env)
    env.shift_l = KeyEvent("Shift+Shift_L")
    env.shift_r = KeyEvent("Shift+Shift_R")
    env.shift_l_release = KeyEvent("Release+Shift_L") 
    env.shift_r_release = KeyEvent("Release+Shift_R")
    env.last_key = KeyEvent("Escape")
end

function M.func(key, env)
    if not key:repr() then
        return Noop
    end

    if key:ctrl() or key:alt() or key:super() then
        env.last_key = KeyEvent(key:repr())
        return Noop
    end

    local context = env.engine.context

    if not context:has_menu() then
        env.last_key = KeyEvent(key:repr())
        return Noop
    end

    if key:eq(env.shift_l_release) and env.last_key:eq(env.shift_l) then
        select(context, 1)
        env.last_key = KeyEvent(key:repr())
        return Accepted
    elseif key:eq(env.shift_r_release) and env.last_key:eq(env.shift_r) then
        select(context, 2)
        env.last_key = KeyEvent(key:repr())
        return Accepted
    end

    env.last_key = KeyEvent(key:repr())
    return Noop
end

return M

```
