### ISSUE TITLE
在emacs中候选框字母部分不是显示为inline

### ISSUE THREAD

**Issue by sleetdrop** [rime/squirrel#819]
emacs   29.1   (homebrew emacs-mac)
macOS  13.6.1
squirrel  0.6.12

如截图(emacs为异常，在textedit中正常，哪位了解这个需要在 emacs 中配置，还是需要在 squirrel 中配置。

<img width="433" alt="emacs" src="https://github.com/rime/squirrel/assets/88603/dc57d41c-1ac4-4e53-9064-d381f596d695">

<img width="405" alt="textedit" src="https://github.com/rime/squirrel/assets/88603/8d7fdd32-4e09-4aa1-8e27-6fb258e3787b">

**Comment by groverlynn** [comment]
`squirrel.custom.yaml`設定檔中
`app_option`的子項`org.gnu.Emacs`，去掉`no_inline: true`，或者改成`inline: true`

**Comment by sleetdrop** [comment]
非常感谢，测试已生效。
