### ISSUE TITLE
如何在中文输入过程中输入"-"

### ISSUE THREAD

**Issue by pencilheart** [rime/squirrel#820]
在现在的设置中，"-"作为"minus"起到"Page_Up"的作用。但在实际使用中，无法实现输入中打"-"的效果(但此可在mac自带中文输入法中实现)。有无办法可实现在输入的过程中打出"-"？

**Comment by LEOYoon-Tsaw** [comment]
把「"-"作为"minus"起到"Page_Up"的作用」關掉不就好了

**Comment by groverlynn** [comment]
key_binder/bindings中的這個綁定：
`{ when: has_menu, accept: minus, send: Page_Up }`
改成：
`{ when: paging, accept: minus, send: Page_Up }`
就和系統輸入法相同了

**Comment by Syntax-J** [comment]
> 

系统自带的输入法在没有使用过"+"进行翻页时候, "-"还有一个不上屏效果,在rime我配置了: 
recognizer中的`underscore: "^[A-Za-z]+[_-].*"  # 下划线不上屏`,这样虽然可以实现输入"-"不上屏, 但是`{ when: paging, accept: minus, send: Page_Up }`这个翻页就失效了
