### ISSUE TITLE
在中文输入模式下如何快捷输入h3c这个词?

### ISSUE THREAD

**Issue by jackywu** [rime/squirrel#826]
在中文输入模式下如何快捷输入h3c这个词?

**Comment by Jreen** [comment]
建议你在custom_phrase里面增加以下内容，可以快捷输入，只需输入h就可以出来h3c这个词，记得弄完后保存后要部署
```
h3c	h	1
```

**Comment by LEOYoon-Tsaw** [comment]
你看你的標題，h3c就不是中文，中文輸入法肯定不方便輸入。
輸入西文可以關閉中文輸入法，等需要輸入中文再打開

**Comment by jackywu** [comment]
thanks for response from everyone.

**Comment by tamhaywoo** [comment]
直接在中文输入的模式下按住shift键输入H然后输入3再按住Shift键输入C，就是H3C
