### ISSUE TITLE
如何解决在不同输入框下使用使用一个输入法状态

### ISSUE THREAD

**Issue by 52funny** [rime/squirrel#828]
我经常在不同的输入框下进行输入，可能在之前那个输入框里面是英文，然后切换到下一个输入框就变成了中文。
这种问题该如何设置？始终使用一个中英文状态，即使在不同的输入框中。

**Comment by groverlynn** [comment]
系統強制每個進程分配一個輸入服務，每個輸入服務會開啓一個獨立的輸入法分身。Rime的臨時ASCII模式切換僅對當前分身起效；要全局都起效需要通過switcher且save_options中包含ascii_mode（當然你也可以直接改librime的代碼來實現臨時切換全局有效）。

**Comment by tywtyw2002** [comment]
自己参考CODE和编译吧，不保证100%能用，我用了几天感觉没啥问题。

CHANGES: https://github.com/tywtyw2002/squirrel/commit/17d40cb52a1d51b1ccd30a10921591ed7a9f74df

BRANCH: https://github.com/tywtyw2002/squirrel/tree/z/v2024.01b

**Comment by 52funny** [comment]
好滴感谢各位

**Comment by groverlynn** [comment]
> 自己参考CODE和编译吧，不保证100%能用，我用了几天感觉没啥问题。
> 
> CHANGES: [tywtyw2002@17d40cb](https://github.com/tywtyw2002/squirrel/commit/17d40cb52a1d51b1ccd30a10921591ed7a9f74df)
> 
> BRANCH: https://github.com/tywtyw2002/squirrel/tree/z/v2024.01b

杀鸡用牛刀啊……librime四行代码的事情……
