### ISSUE TITLE
使用actions自动构建的pkg无法使用

### ISSUE THREAD

**Issue by free-150** [rime/squirrel#829]
macOS Big Sur  
版本 11.3  
fork squirrel后用actions自动构建的pkg安装后无法使用，没有更改任何代码，squirrel.app的图标是个叉。图如下：  
![3AEEDD23FD329D281D36453F51C62957](https://github.com/rime/squirrel/assets/92285544/8ff43c75-7bed-4574-a5fb-aba81f8728a4)  
![56A6B1ECF1C13B405C1B016DFC27A306](https://github.com/rime/squirrel/assets/92285544/02e5c43d-dccf-4e3f-9178-356852d00bc8)  
![AA55921E6126602A2385EE9EBD3FBBA1](https://github.com/rime/squirrel/assets/92285544/68650e44-5c43-4d09-b25b-46c9ce018848)

**Comment by groverlynn** [comment]
因為你fork的branch的系統最低要求是MacOS 13

**Comment by free-150** [comment]
可以更改兼容低版本吗

**Comment by groverlynn** [comment]
> 可以更改兼容低版本吗

https://github.com/rime/squirrel/pull/756
