### ISSUE TITLE
*.userdb.txt 在哪里？

### ISSUE THREAD

**Issue by zaifoo** [rime/squirrel#830]
什么地方有系统完整的说明书？不能完全明白rime文件夹里一些文件的作用。

**Comment by vlaw** [comment]
`*.userdb.txt` 是同步文件夹里生成的内容。如下所示
```yaml
D:\Dropbox\RimeSync\id-zzz\luna_pinyin.userdb.txt
```
[UserGuide](https://github.com/rime/home/wiki/UserGuide#%E5%90%8C%E6%AD%A5%E7%94%A8%E6%88%B6%E8%B3%87%E6%96%99)
