### ISSUE TITLE
使用iShot截图软件添加文字备注时，鼠须管的候选框不显示

### ISSUE THREAD

**Issue by dawnray** [rime/squirrel#831]
使用iShot截图软件添加文字备注时，鼠须管的候选框不显示，可以使用空格选字上屏。

使用官方或者搜狗输入法没有问题。

鼠须管版本： 0.16.2
macOS 版本： Sonama 14.2.1 （历史版本也这样）
iShot版本： iShot Pro 2.4.5（历史版本也这样）

**Comment by LEOYoon-Tsaw** [comment]
用cmd+shift+3/4截屏

**Comment by dawnray** [comment]
还可以直接用其他输入法呢。
