### ISSUE TITLE
在overleaf中出现不可删除的红点

### ISSUE THREAD

**Issue by Yiklek** [rime/squirrel#840]
![image](https://github.com/rime/squirrel/assets/21033316/3ef780a4-9be3-4cee-a347-f3ecc70a9324)
![image](https://github.com/rime/squirrel/assets/21033316/0adf32a9-ec4c-40c3-8b07-bba0628b9671)
这个红点会导致一些奇怪的问题

1. 这个红点无法使用`backspace`删除
2. 出现红点这一行无法使用`backspace`删除

squrrel: 0.15.0 (0.16未验证，因为在我的电脑上会崩掉)

设备： Macbook Pro 2018
macOS: 14.3.1

浏览器：
![image](https://github.com/rime/squirrel/assets/21033316/9baab6f2-f0a3-478e-82a0-07a3f507d6c0)

**Comment by groverlynn** [comment]
為什麼會有人在mac上用Edge……
瀏覽器儘量使用inline模式，尤其是這種幾乎全屏文本的網頁。不管OS平台和輸入法，瀏覽器大段文本都會有定位光標的問題，inline模式相對不容易出錯

**Comment by Yiklek** [comment]
> 為什麼會有人在mac上用Edge…… 瀏覽器儘量使用inline模式，尤其是這種幾乎全屏文本的網頁。不管OS平台和輸入法，瀏覽器大段文本都會有定位光標的問題，inline模式相對不容易出錯

哈哈，其实在Safari上也有这个问题，我用Edge只是因为PC是windows，同步方便一些。

关于您提到的浏览器定位光标的问题我不太了解，不过按照您的提示开启了`inline_preedit`，没有再出现这个问题。非常感谢！@groverlynn
