### ISSUE TITLE
是否有网格状（多排多列）的候选窗口？

### ISSUE THREAD

**Issue by ohjunk2001** [rime/squirrel#844]
类似苹果原生输入法的窗口
<img width="493" alt="Screenshot 2024-02-23 at 19 28 42" src="https://github.com/rime/squirrel/assets/69291515/dd2fedd7-d3f5-4697-88d8-662153da4a3f">
如果考虑到细节的话

直接输入拼音是横排的

<img width="530" alt="Screenshot 2024-02-23 at 19 27 40" src="https://github.com/rime/squirrel/assets/69291515/39f7b280-323c-48a8-b9a8-a652d8782d30">

只有当按动翻页键后，才会变成多排多列

<img width="493" alt="Screenshot 2024-02-23 at 19 28 42" src="https://github.com/rime/squirrel/assets/69291515/9bf16d84-4402-4eeb-b61d-592ad6dd549b">

**Comment by LEOYoon-Tsaw** [comment]
有考慮過，但沒人做

**Comment by ohjunk2001** [comment]
> 有考慮過，但沒人做

明白了，老哥，我还是接着用搜狗吧

**Comment by ShikiSuen** [comment]
@ohjunk2001 你还可以用我开发的威注音。但威注音的汉语拼音模式要求全拼＋声调。
https://vchewing.github.io/

**Comment by ShikiSuen** [comment]
@ohjunk2001 你笑啥玩意？威注音的选字窗算是目前所有开源中文输入法里面最先进的（特别是其前后端分离的设计）。
看你也是码农，你随时可以自己移植给 RIME 再来个 PR。

**Comment by ohjunk2001** [comment]
抱歉，老哥
我不知道这个 laugh 的表情会冒犯到你
我以为这个😄 表情对所有人来说都是“赞同”的意思

我知道下面这几个表情会冒犯到别人，但没想过这个也会
😅 :sweat_smile:
😂 :joy:

**Comment by ShikiSuen** [comment]
@ohjunk2001 怪我太过敏。这些年接触的傻逼太多了。
