### ISSUE TITLE
系统对话框无法进行中英文切换

### ISSUE THREAD

**Issue by viogus** [rime/squirrel#85]
重现步骤如下：
用Preview打开任意一个pdf，另存为，在对话框内无法切换中英文进行输入。
类似的word，excel等都是如此。据说spotlight内也无法进行切换

**Comment by beyondkmp** [comment]
自己下载编译安装最新版本

**Comment by hotoo** [comment]
Spotlight 确实无法切换到中文输入状态。试了 Mac 自带的“简体拼音”输入法是 OK 的。

每次都只能其他地方输入中文复制粘贴到 Spotlight 好尴尬，麻烦解决下 ：）

**Comment by beyondkmp** [comment]
编译安装的最新版本,如果切换不了,可以重新部署下就可以使用中文了.不过每次开机都要重新部署比较麻烦啊

**Comment by lotem** [comment]
快捷鍵 <kbd>Control+Shift+2</kbd> 可用

**Comment by beyondkmp** [comment]
> Control+Shift+2

确实可以，是不是shift键冲突与safari冲突？

**Comment by linroex** [comment]
看起來是 shift 這個按鍵的問題，測試 macOS Launchpad、VSCode 還有某些地方都會遇到，測試如果把 shift:commit_code 改成其他按鍵就會正常，所以問題應該是 shift

想問大家有沒有什麼想法，暫時沒有頭緒搞不懂為什麼 macOS launchpad 會衝到 shift，查了系統的快捷鍵似乎也沒有用到 shift，用 karabiner event viewer 查看在 launchpad 時 shift 確實是 shift 沒錯，到這邊卡住不知道能怎麼往下解決這個問題

**Comment by LEOYoon-Tsaw** [comment]
可以試下刪除鼠鬚管的英文功能（刪去ascii_translator），用系統的cap lock切換中英

**Comment by nb5p** [comment]
@linroex 我把Shift改成noop了,还是不成.
我推测这个问题是系统的问题,其他的输入法都通过某种其他方式实现让输入法接受到Shift行为.

**Comment by beyondkmp** [comment]
曲线救国的方法，在系统框用其它快捷键 shift space一下，
```
  key_binder/bindings:
    - when: always 
      accept: Shift+space 
```

**Comment by kaedea** [comment]
这个问题有完美的解决方案了吗？

**Comment by nb5p** [comment]
> 这个问题有完美的解决方案了吗？

由于系统限制，目前没有完美方案。其他输入法的实现方式是，请求『辅助功能』权限，使用API监控Shift按键状态。

**Comment by lotem** [comment]
打開方案選單<kbd>Control+`</kbd>選2切換「中文」「西文」

或使用快捷鍵<kbd>Control+Shift+2</kbd>

**Comment by ShikiSuen** [comment]
@linroex 這個問題有解法，但需要 Swift。
參見這些資料：
https://github.com/vChewing/vChewing-macOS/tree/main/Packages/Qwertyyb_ShiftKeyUpChecker
https://github.com/vChewing/vChewing-macOS/blob/e314b303d284b1aaff9524a22931576c0e332d89/Source/Modules/SessionCtl_HandleEvent.swift#L56-L82
https://github.com/vChewing/vChewing-macOS/blob/e314b303d284b1aaff9524a22931576c0e332d89/Source/Modules/SessionCtl_Core.swift#L75-L77

credit: @qwertyyb

**Comment by jdhao** [comment]
同遇到 shift 失灵的问题，发现失灵的时候 IME 菜单 squirrel 显示很奇怪，

![image](https://user-images.githubusercontent.com/16662357/200186766-11827ab0-da2e-4213-bf2d-84ae13e30205.png)

环境：

+ macOS：12.3，M1 CPU
+ squirrel：最新版

**Comment by supermanc88** [comment]
> 同遇到 shift 失灵的问题，发现失灵的时候 IME 菜单 squirrel 显示很奇怪，
> 
> ![image](https://user-images.githubusercontent.com/16662357/200186766-11827ab0-da2e-4213-bf2d-84ae13e30205.png)
> 
> 环境：
> 
> * macOS：12.3，M1 CPU
> * squirrel：最新版

系统 13.3.1 
squirrel 0.16.2
有同样的问题，并且就在刚才我使用 ctrl + shift + 2切换都不生效

**Comment by ShikiSuen** [comment]
cc @lotem 要不要试试看这个方法？：https://juejin.cn/post/7236196894988369957
或许可以解决这个问题：
<img width="481" alt="圖片" src="https://github.com/rime/squirrel/assets/3164826/597ef600-3191-4bbd-a855-7e2d46efc64a">

**Comment by lotem** [comment]
mark

**Comment by supermanc88** [comment]
![截屏2023-05-31 09 41 38](https://github.com/rime/squirrel/assets/8957358/c2891830-16f5-4d15-8042-7101d6d60be3)
我测试了其它两个输入法，在shift失灵时，都是这种情况

**Comment by ShikiSuen** [comment]
@supermanc88 你要不要测试一下威注音？
（有汉语拼音＋声调的输入模式；可以挂 CIN 格式的码表来打小鹤音形或五笔。）

**Comment by yam-liu** [comment]
同遇到这个问题，有解法了么？ ![Image](https://github.com/user-attachments/assets/896d212c-54be-4d2c-8fdd-c5425d458b43)

**Comment by b19g3r** [comment]
我使用中有个问题: 比如在 antigravity(google 家的 ai 编辑器) 的输入框中,偶尔会出现无法打出中文的情况.
我使用 CapsLock 切换 Squirrel (只输入中文) 和 U.S. (只输入英文) 
Shift 键 被我设置成了 none
无论切换多少次还是中间间隔几秒切换两个输入法 Squirrel 都无法输入中文 当我重新 Deploy 后就可以输入了

有人遇到和我一样的问题吗? 是我的配置问题还是 Squirrel 的问题?

**Comment by spance** [comment]
<img width="262" height="365" alt="Image" src="https://github.com/user-attachments/assets/5734a229-106b-403a-8e6b-abd87b61350d" />

没有开启 所有输入法-自动切换到文稿的输入法。
在多个程序之间频繁切换的时候，很容易出现这个问题，可疑的日志有：

```
I20260516 15:53:52.668037 0x20037f100 engine.cc:72] starting engine.
E20260516 15:53:52.668279 0x20037f100 key_event.cc:69] parse error: unrecognized modifier 'Option'
I20260516 15:53:52.668391 0x20037f100 engine.cc:133] updated option: simplification
I20260516 15:53:52.668694 0x20037f100 engine.cc:133] updated option: _auto_commit
I20260516 15:53:52.668842 0x20037f100 table_db.cc:73] stabledb 'custom_phrase' does not exist.
I20260516 15:53:52.668880 0x20037f100 dictionary.cc:380] loading dictionary 'luna_pinyin'.
I20260516 15:53:52.668944 0x20037f100 engine.cc:377] ConcreteEngine::InitializeOptions
I20260516 15:53:52.668953 0x20037f100 engine.cc:382] found switch option: ascii_mode, reset: 0
I20260516 15:53:52.668956 0x20037f100 engine.cc:133] updated option: ascii_mode
I20260516 15:53:52.668959 0x20037f100 engine.cc:382] found switch option: full_shape, reset: -1
I20260516 15:53:52.668962 0x20037f100 engine.cc:382] found switch option: zh_simp, reset: 1
I20260516 15:53:52.668965 0x20037f100 engine.cc:133] updated option: zh_simp
I20260516 15:53:52.668967 0x20037f100 engine.cc:382] found switch option: ascii_punct, reset: -1
I20260516 15:54:52.760752 0x20037f100 engine.cc:96] engine disposed.
I20260516 15:54:52.769394 0x20037f100 engine.cc:96] engine disposed.
I20260516 15:56:36.055226 0x20037f100 engine.cc:72] starting engine.
```

**Comment by wallleap** [comment]
就是这个问题，好像用其它输入法也会遇到

**Comment by ShikiSuen** [comment]
@spance 您这个问题如果是通过 CapsLock 中英切换触发、且与 Control+Shift+2 无关的话，请另开工单（务必注明触发条件）。

**Comment by spance** [comment]
> [@spance](https://github.com/spance) 您这个问题如果是通过 CapsLock 中英切换触发、且与 Control+Shift+2 无关的话，请另开工单（务必注明触发条件）。

没有开启 CapsLk 切换，用 Shift 切换中英语言，用 Control + Space 切换输入法。
不能稳定复现，大致是停止打字输入稍微久一点，容易出现这个问题。
