### ISSUE TITLE
咨询下各位大佬，鼠须管输入过程中编码下划线能否去除？

### ISSUE THREAD

**Issue by Sauhun** [rime/squirrel#857]
使用的极点五笔方案，单行模式，输入文字过程中输入的编码下方会有一条横线，导致像输入 j 看着像输入 i ，g像a。如果想取消编码下方的下划线，需要怎么配置呢？感谢！
![1711546202059](https://github.com/rime/squirrel/assets/25004176/d30bbc84-5346-4fd8-a5d3-42a395eb0acb)

**Comment by LEOYoon-Tsaw** [comment]
這個不是鼠鬚管加的，是系統自帶的吧

**Comment by Sauhun** [comment]
如果说是系统的问题那就没法搞了。敲字搞快点就当看不见吧。哈哈。谢谢大佬！
