### ISSUE TITLE
safari下淘宝二级界面搜索框输入非常卡顿，用chrome没有问题

### ISSUE THREAD

**Issue by SakuraYuki56** [rime/squirrel#859]
目前仅在Safari下复现， 系统版本：sonoma 14.1.2,safari 版本17.1.2 (19616.2.9.11.12)

**Comment by ksqsf** [comment]
macOS 14.4.1, Safari 17.4.1 未能复现

**Comment by SakuraYuki56** [comment]
> macOS 14.4.1, Safari 17.4.1 未能复现

试了下更新到14.4.1，问题依旧，关掉所有插件开无痕模式还是很卡，好像也不是rime的问题，切到原生输入法也有输入延迟

**Comment by LEOYoon-Tsaw** [comment]
大概你用了嵌入，輸入的時候搜索欄的文字快速變化，每次變化都觸發搜索更新，然後搜索更新又很慢。Google也同樣實時更新搜索，但沒有什麼卡頓，不是輸入法能解決的問題
