### ISSUE TITLE
如何批量添加词组？

### ISSUE THREAD

**Issue by freewind** [rime/squirrel#86]
我想把同事的名字事先批量添加进输入法，不知道有没有办法做到？另外希望添加的时候，直接输入中文即可，而不要手动输入编码，可以实现么？

比如可以直接把下面的内容输入到某个地方就可以了：

```
张三
李四
王五
```

**Comment by iDvel** [comment]
词库里写上 `use_preset_vocabulary: true`
然后把人名直接丢进去就行了，不用写拼音。

**Comment by lotem** [comment]
> 词库里写上 `use_preset_vocabulary: true`
> 然后把人名直接丢进去就行了，不用写拼音。

​是這個辦法。
