### ISSUE TITLE
Squirrel给不同的输入方案设置不同的悬浮图标

### ISSUE THREAD

**Issue by mediocrebaby** [rime/squirrel#865]
如小狼毫上的issue: [给不同小狼毫输入方案添加不同的托盘图标](https://github.com/rime/weasel/issues/527)。

**Comment by LEOYoon-Tsaw** [comment]
鼠鬚管沒有懸浮圖標啊

**Comment by mediocrebaby** [comment]
<img width="51" alt="image" src="https://github.com/rime/squirrel/assets/88031150/72f95334-9625-47f1-89ec-7e9f183fcb80">

不好意思，我开始以为这也是个图标，修改配置的时候发现是放的字符上去的
