### ISSUE TITLE
部分應用（如Chrome）首次輸入候選框可能位於窗口外

### ISSUE THREAD

**Issue by LokChunYu** [rime/squirrel#870]
<img width="1235" alt="iShot_2024-05-05_06 00 35" src="https://github.com/rime/squirrel/assets/18650603/58373427-c0dd-40ae-9734-0d0e1f6c0b23">
1、Chrome浏览器124.0.6367.119（正式版本）和edge浏览器版本 124.0.2478.80 (正式版本) ，macOS14.4.1，首次启动输入法，候选框仍在一角；

<img width="219" alt="iShot_2024-05-05_06 03 05" src="https://github.com/rime/squirrel/assets/18650603/0dbb24a8-1f2a-4110-bf5a-d1b74db4dd26">
2、“检查新版本”按钮点击不起作用。

**Comment by LEOYoon-Tsaw** [comment]
左上角的問題沒完全修復的話，那就再繼續研究吧，多謝反饋
檢查新版本還不能用是故意的，過一兩週才會開始推送

**Comment by LokChunYu** [comment]
非常感谢回复。关于第一点，每次打开浏览器在输入框内首次会出现这样的问题。

**Comment by LEOYoon-Tsaw** [comment]
> 非常感谢回复。关于第一点，每次打开浏览器在输入框内首次会出现这样的问题。

那我確實無法復現，我的Chrome是123，Edge是124。打開瀏覽器第一次輸入沒有問題

**Comment by doviscn** [comment]
> > 非常感谢回复。关于第一点，每次打开浏览器在输入框内首次会出现这样的问题。
> 
> 那我確實無法復現，我的Chrome是123，Edge是124。打開瀏覽器第一次輸入沒有問題

Chrome 124，完全复现，只要新开标签页也默认光标焦点位置是在搜索框内的（比如Google、百度、淘宝），直接打字（不要手动去点光标位置）就会发现这个问题。

**Comment by LEOYoon-Tsaw** [comment]
反正我沒法復現，等別人研究吧

**Comment by cobaltdisco** [comment]
> 反正我沒法復現，等別人研究吧（Chrome已升124）
> 
>  Screen.Recording.2024-05-05.at.10.42.30.mov

需要在Google的主页输入框上进行，标签页的话是没法复现的。

不过我刚自己试了下，其实v16.2也有一样的问题。

**Comment by LEOYoon-Tsaw** [comment]
> 需要在Google的主页输入框上进行

我打開新標籤焦點默認在地址欄

**Comment by yuhuangniu** [comment]
进入google首页：https://www.google.com/，然后在主页的搜索框里输入，会复现这个问题。

**Comment by yuhuangniu** [comment]
> > 需要在Google的主页输入框上进行
> 
> 我打開新標籤焦點默認在地址欄

进入google首页：[https://www.google.com/]，然后在主页的搜索框里输入，会复现这个问题。

**Comment by LEOYoon-Tsaw** [comment]
確實，找到方法復現了。輪入google網址進入google，光標自動聚焦到搜索框，此時輪入，候選欄在窗口外

**Comment by groverlynn** [comment]
> 確實，找到方法復現了。輪入google網址進入google，光標自動聚焦到搜索框，此時輪入，候選欄在窗口外

```
  NSRect IbeamRect = NSZeroRect;
  [self.client attributesForCharacterIndex:0
                       lineHeightRectangle:&IbeamRect];
  if (NSEqualRects(IbeamRect, NSZeroRect) && _inlineString.length == 0) {
    if (self.client.selectedRange.length == 0) {
      // activate inline session, in e.g. table cells, by fake inputs
      [self.client setMarkedText:@" "
                  selectionRange:NSMakeRange(0, 0)
                replacementRange:NSMakeRange(NSNotFound, NSNotFound)];
      [self.client attributesForCharacterIndex:0
                           lineHeightRectangle:&IbeamRect];
      [self.client setMarkedText:@""
                  selectionRange:NSMakeRange(0, 0)
                replacementRange:NSMakeRange(NSNotFound, NSNotFound)];
    } else {
      [self.client attributesForCharacterIndex:self.client.selectedRange.location
                           lineHeightRectangle:&IbeamRect];
    }
  }
```

**Comment by LEOYoon-Tsaw** [comment]
系統輸入法有同樣的表現，認為是Chromium的問題
