### ISSUE TITLE
更新日志中是不是写错日期啦？

### ISSUE THREAD

**Issue by bbingz** [rime/squirrel#872]
好像把5月4日写错成5月14日了…

**Comment by LEOYoon-Tsaw** [comment]
主要是不確定什麼時候檢查更新可以用

**Comment by bbingz** [comment]
嗯嗯，那不确定话，可能写 Release 的日期比较好哟。昨天收到更新提醒时，弹出来是未来的日期有点懵。

**Comment by LEOYoon-Tsaw** [comment]
不再改了吧，改來改去更混亂

**Comment by lotem** [comment]
Fixed via https://github.com/rime/home/commit/64a7766759be37490e82d759eea904d12fa7953a
