### ISSUE TITLE
無法顯示內選區域

### ISSUE THREAD

**Issue by Ponpon55837** [rime/squirrel#874]
系統版本： MacOS Sonoma 14.4.1  intel

在上一個鼠鬚管版本當中
我在squirrel.custom.yaml設定
style/inline_preedit: true  # 內嵌編碼（僅支持TSF）
style/display_tray_icon: true  # 顯示托盤圖標
可以正常顯示內選區域 
  
目前鼠鬚管版本  0.18
相同設定無法顯示內選區域

請問該如何修改或是這次版本調整了哪部分呢

**Comment by lotem** [comment]
> `style/inline_preedit: true`

鼠鬚管的默認值就是 `true`，不設也可以的。

在個別應用中會強制開啓或關閉這個選項。詳見
https://github.com/rime/squirrel/blob/41f85272299b9dc9e320a16199761367475c94a6/data/squirrel.yaml#L332

> `style/display_tray_icon: true`

鼠鬚管不支持這項功能。

**Comment by Ponpon55837** [comment]
是的  我參照指南上寫的 原先版本在某些應用上會顯示內選區域，但是目前這個版本則是任何應用都是不顯示
