### ISSUE TITLE
i 键在某些 app 中会被错误地直接上屏

### ISSUE THREAD

**Issue by Sponge-bink** [rime/squirrel#883]
https://github.com/rime/squirrel/assets/33798984/992dfa82-3b31-4a0a-b5d7-44880fd45e01

**Comment by LEOYoon-Tsaw** [comment]
你的方案壞掉了吧

**Comment by LEOYoon-Tsaw** [comment]
我怎麼個詳細說明，我這又不能復現

**Comment by fxliang** [comment]
这个是表达一种可能性，提示要检查是否方案关联，试试就可

**Comment by LEOYoon-Tsaw** [comment]
你好歹把你用的方案說明一下，是否自帶方案也這樣，等等情況說明一下，光看你個截屏幾乎沒有幫助。
