### ISSUE TITLE
使用 `'` 触发 Lua 脚本, 升级 0.18 后 `'` 开始上屏

### ISSUE THREAD

**Issue by Renkai** [rime/squirrel#884]
配置位置:
https://github.com/Renkai/tiger-code/blob/main/tigress.schema.yaml#L63
脚本:
https://github.com/Renkai/tiger-code/blob/main/lua/wrap_spaces.lua
系统:
macOS 14.1 (23B2073)

![Kapture 2024-05-10 at 08 30 43](https://github.com/rime/squirrel/assets/3381789/67344315-c946-4f29-b9eb-a9f6659d03c2)

**Comment by Attiv** [comment]
一样，我是用 \ 触发脚本，结果也上屏了

**Comment by LEOYoon-Tsaw** [comment]
@Renkai 你的「'」是easy_english的引導，也是historyDM2的input，還在主引擎的alphabet裏。我不知道你預期是怎樣，但rime顯然不知道你想怎樣

**Comment by LEOYoon-Tsaw** [comment]
@Attiv 請提供相關的配置

**Comment by Attiv** [comment]
> @Attiv 這是你的配置：
> 
> ```
> recognizer:
>     zhuan: "^\\\\.*$" 
> ```
> 
> 而我用了這麼多，都能正常使用（包括剛加上測試用的你的這條）：
> 
> ```
> recognizer:
>   import_preset: default
>   patterns:
>     email: ^[a-z][-_.0-9a-z]*@.*$
>     url: ^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$
>     reverse_lookup: "`[a-z]*;?$"
>     pinyin_lookup: "`P[a-z]*;?$"
>     jyutping_lookup: "`J[a-z]*;?$"
>     hangyl_lookup: "`H[a-z]*;?$"
>     nihongo_lookup: "`N[a-z]*;?$"
>     taigi_lookup: "`T[a-z]*;?$"
>     unicode: (?<![`A-Z])U[0-9a-f]*;?$
>     pinyin: (?<![`A-Z])P[a-z']*;?$
>     jyutping: (?<![`A-Z])J[a-z']*;?$
>     tiungqox: (?<![`A-Z])Z[a-z']*;?$
>     hangyl: (?<![`A-Z])H[a-z']*;?$
>     nihongo: (?<![`A-Z])N[a-z']*;?$
>     greeks: (?<![`A-Z])G[a-z]*;?$
>     punct: "^z([a-z]+|[0-9])$"
>     zhuan: "^\\\\.*$"
> ```

\ 也是有候选的，现在也是直接就上屏了。
你既然没遇到这情况的话那就等等看别人有没有这情况吧

**Comment by LEOYoon-Tsaw** [comment]
> \ 也是有候选的，现在也是直接就上屏了。
> 你既然没遇到这情况的话那就等等看别人有没有这情况吧

大概是你別的配置衝突了，你提供的信息不足，無從判斷原因

**Comment by Attiv** [comment]
> > \ 也是有候选的，现在也是直接就上屏了。
> > 你既然没遇到这情况的话那就等等看别人有没有这情况吧
> 
> 大概是你別的配置衝突了，你提供的信息不足，無從判斷原因

我使用的是这个方案：[hugh7007/xmjd6-rere: 基于星空键道，拓展出来百万词库版本 - 星猫键道 6](https://github.com/hugh7007/xmjd6-rere)
如果需要的话可以参考下

**Comment by Renkai** [comment]
@Attiv @LEOYoon-Tsaw 虽然我们的配置不完美, 但是我试了下另一个前端, 没有这个问题, 所以应该是在端就被截取上屏没有经过rime engine?
https://github.com/fcitx-contrib/fcitx5-macos-installer/blob/master/README.zh-CN.md

**Comment by LEOYoon-Tsaw** [comment]
0.18沒改按鍵處理這部分啊，定位不到問題

**Comment by Attiv** [comment]
> 0.18 沒改按鍵處理這部分啊，定位不到問題 @Renkai @Attiv 可以試一下我準備的下一版，不確定有沒有改善。主要是方案本身定義有歧意，那程序解讀出問題是再正常不過的，也可能是 librime 更新造成的，最主要還是把方案定義寫清楚，消除歧意
> 
> https://github.com/LEOYoon-Tsaw/squirrel/releases/tag/0.99.6

@Renkai @LEOYoon-Tsaw 我用小企鹅和0.16版本的 rime 也是正常的，0.18就不行，我不知道是哪里出的问题应该怎么改，不过这个最新的 https://github.com/LEOYoon-Tsaw/squirrel/releases/tag/0.99.6 这个里的action 的那个是可以正常使用的。

**Comment by LEOYoon-Tsaw** [comment]
謝謝反饋
