### ISSUE TITLE
请问候选字在候选框中没有上下居中可能是什么设置导致的？

### ISSUE THREAD

**Issue by joshaken** [rime/squirrel#888]
<img width="764" alt="image" src="https://github.com/rime/squirrel/assets/137023588/4c7eeb45-0cc8-462a-9d3a-6ba78ecc04a7">

**Comment by joshaken** [comment]
和配色方案有没有关系吧？
<img width="1040" alt="image" src="https://github.com/rime/squirrel/assets/137023588/04dfdabb-dd61-4106-9834-6f2a6ad6591a">

**Comment by LEOYoon-Tsaw** [comment]
所有字体都这样吗？可以用base_offset調節的

**Comment by joshaken** [comment]
> 所有字体都这样吗？可以用base_offset調節的

感谢回复，是的，所有字体都这样，
base_offset设置成负数可以解决这个问题，感谢！感谢！
