### ISSUE TITLE
MacOS 12.4 升级到0.18后不可用，要怎么退回到0.16.2版本，直接下载0.16.2pkg文件安装后还是最新版本

### ISSUE THREAD

**Issue by Muscleape** [rime/squirrel#889]

**Comment by lotem** [comment]
退出當前用戶並重新登錄
測試一下是不是退回了舊版本

**Comment by LEOYoon-Tsaw** [comment]
降級可能需要手動刪除 /Library/Input Method/Squirrel.app
可以試一下

**Comment by alswl** [comment]
@Muscleape 

1. 删除 Squirrel
2. logout
3. 重新安装 Squirrel v0.16.2，我临时打了一个 tap https://github.com/alswl/homebrew-cask-me/blob/master/Casks/squirrel%40v0.16.2.rb
4. logout

恢复正常。

**Comment by Muscleape** [comment]
为啥0.18版本不支持MacOS 12的系统了呢？

**Comment by LEOYoon-Tsaw** [comment]
自動升級應該設置了macOS13的下限，沒起作用？你是直接收到推送升級的嗎

**Comment by alswl** [comment]
如果通过 homebrew 安装的，那在 May 5, 2024 ~ May 6, 2024 之间可能会安装成功 squirrel v0.18。
https://github.com/Homebrew/homebrew-cask/commit/c3d4f279dc36b0216635a9cbd7aa978410ab5eef
这个 Commit 修复了 macOS 依赖检查问题。
