### ISSUE TITLE
同步用户数据是否能添加快捷键

### ISSUE THREAD

**Issue by Anber55** [rime/squirrel#890]
重新部署已经有快捷键了，非常方便的进行自动化，但是同步用户数据目前没有快捷键，希望能添加快捷键

**Comment by LEOYoon-Tsaw** [comment]
可以用command line
/Library/Input\ Methods/Squirrel.app/Content/MacOS/Squirrel --sync

**Comment by Anber55** [comment]
你好，我知道这种方法，但是这个方法经常是需要第二步操作（比较多），也就是运行完之后需要再点击一次桌面的任何地方才会生效

另外，直接点击，状态栏图标的部署和同步其实也会有问题，就是点击之后没有任何反应（比较少），这时需要点击几下状态栏，重新点击部署和同步才可以正常运行

希望在这方面得到优化，或者直接给个同步的快捷键，快捷键的问题好像很少，谢谢

**Comment by LEOYoon-Tsaw** [comment]
全局的快捷鍵越少越好，看有多少人需要吧。
你甚至可以寫個腳本定時同步，我覺得比快捷鍵還好用

**Comment by LEOYoon-Tsaw** [comment]
在macOS上還可以用Shortcuts，可以快捷鍵觸發，甚至可以Siri觸發，完全沒必要由鼠鬚管來定義快捷鍵，關了啊
