### ISSUE TITLE
`Check for updates`失效

### ISSUE THREAD

**Issue by RoyRao2333** [rime/squirrel#892]
在更新到0.18后，点击`Check for updates`没有任何反应

- macOS 14.4.1
- M1 Pro chip

<img width="460" alt="image" src="https://github.com/rime/squirrel/assets/31413093/50c2291a-8db2-4ffb-b41b-0cf7190a9fc6">

**Comment by LEOYoon-Tsaw** [comment]
似乎升級上來的和使用.zip安裝的會有這個問題，直接安裝.pkg的能正常升級。下個版本應該不會再有這樣的問題了，如果檢查更新一直未能正常工作，可能得麻煩等更新後手動升級一次了。

**Comment by RoyRao2333** [comment]
@LEOYoon-Tsaw 

感谢回复，我是用.pkg覆盖升级的，并不是.zip。看看下版本会不会还有这个问题，感谢。

**Comment by RoyRao2333** [comment]
v1.0.1 已解决
