### ISSUE TITLE
macos14安装最新0.18后，退出登录后啥也没有

### ISSUE THREAD

**Issue by trainliang** [rime/squirrel#893]
m1 的macos14安装最新0.18后，退出登录后啥也没有（没有图标、没有任何输入法信息）

**Comment by dengjianjun** [comment]
[Mac OS 14 安装 0.16.2 后无法使用 #809](https://github.com/rime/squirrel/issues/809) 添加一下就有了

**Comment by LEOYoon-Tsaw** [comment]
似乎是因為只有`im.rime.inputmethod.Squirrel`是ASCII capable，但是`im.rime.inputmethod.Squirrel.hans`、`im.rime.inputmethod.Squirrel.hant`都不是，然後遇到的情況就是程序裡他們都enabled了，但是UI上看不到。
我也不知道怎麼讓這倆hans、hant ASCII capable，先默認開啟`im.rime.inputmethod.Squirrel`，應該能解決問題

**Comment by Mycroft0121** [comment]
13.5.2 (22G91) 重新添加后选择鼠须管就会跳出对话框 “TextInputMenuAgent” would like to enable third-party input method “Squirrel”. 选择allow后还是无法使用选项变灰
![image](https://github.com/rime/squirrel/assets/7549260/0ca7410c-b488-4ddb-a0e9-e7ec7e8d8067)

**Comment by LEOYoon-Tsaw** [comment]
> 13.5.2 (22G91) 重新添加后选择鼠须管就会跳出对话框 “TextInputMenuAgent” would like to enable third-party input method “Squirrel”. 选择allow后还是无法使用选项变灰
> 
> 
> 

幫忙看看計畫發布的下一個版本是否仍然有這個問題：https://github.com/LEOYoon-Tsaw/squirrel/releases/tag/1.0.0

**Comment by LEOYoon-Tsaw** [comment]
經安裝 Ventura 13.0 後測試，鼠鬚管 1.0 可正常使用，唯安裝後與 Sonoma 一樣需手動添加（打開設置-鍵盤-加號）。
添加後即可正常使用，過程中未跳出對話框。**Ventura 13.0 可用**
首次安裝無法自動添加入輸入法的問題在開源中文輸入法中廣泛存在，如有人能解決此問題則善莫大焉！
