### ISSUE TITLE
Squirrel 0.18 使用雾凇拼音時内存佔用大

### ISSUE THREAD

**Issue by J-StrawHat** [rime/squirrel#895]
这几天内存占用一直在涨，现在已经升到 420 多 MB了。

输入方案为雾凇拼音， 可能是 [Lua 的原因](https://github.com/iDvel/rime-ice/issues/850#issuecomment-2106251919)

**Comment by Attiv** [comment]
把 `ReverseDb` 换成 `ReverseLookup(dict_name)` 试试

**Comment by J-StrawHat** [comment]
搜索了一下，雾凇拼音的 Lua 中使用的是 [`ReverseLookup`](https://github.com/iDvel/rime-ice/blob/main/lua/cold_word_drop/processor.lua#L127) 

ps. 现在内存占用已经接近 500 MB 了

**Comment by LEOYoon-Tsaw** [comment]
過了3天才漲了80MB？這怕不叫內存泄露

**Comment by J-StrawHat** [comment]
之前的版本应该不会涨到这么多

**Comment by mirtlecn** [comment]
@J-StrawHat 

你用的是 rime_ice 里面的全拼吗？

**Comment by J-StrawHat** [comment]
使用的是双拼

**Comment by Muscleape** [comment]
<img width="1305" alt="image" src="https://github.com/rime/squirrel/assets/16682039/8cab2a38-1195-4437-bec6-f6449fcf43a7">

**Comment by ksqsf** [comment]
可嘗試使用 Instruments 中的 Leaks 工具測試（須從 Running Applications 列表中選取 Squirrel）。我使用的是某個 custom build，無法代表 release 版的情況，但是的確發現了 leak。

<img width="1617" alt="image" src="https://github.com/rime/squirrel/assets/23358293/e8e9da6b-26db-44c1-a9d4-8c11f17c61d8">

**Comment by ksqsf** [comment]
I believe this could be fixed by #898 .

**Comment by mirtlecn** [comment]
@J-StrawHat CI 版本好了吗？

**Comment by mirtlecn** [comment]
我自己用 CI 版本试了下，好像没看到什么特别明显的内存问题。

[1716690587.webm](https://github.com/rime/squirrel/assets/76689045/f1b77a34-8fc6-4b9b-bae8-651b9bc6f998)
