### ISSUE TITLE
mac的聚焦搜索spotlight用不了输入法输入

### ISSUE THREAD

**Issue by Zxxja** [rime/squirrel#897]
<img width="1463" alt="截屏2024-05-19 18 57 52" src="https://github.com/rime/squirrel/assets/170238371/a66b28b0-744d-4828-a682-49f7bd8fffb0">
看了一个大佬的修改方法，把代码复制进去，然后重新配置还是不行。
我纯编程小白一个不知道是哪里弄错了？😭

**Comment by LEOYoon-Tsaw** [comment]
不要改squirrel.yaml，用squirrel.custom.yaml。
好好讀讀幫助：https://github.com/rime/home/wiki/CustomizationGuide#%E4%B8%80%E4%BE%8B%E5%AE%9A%E8%A3%BD%E5%B0%8F%E7%8B%BC%E6%AF%AB%E9%85%8D%E8%89%B2%E6%96%B9%E6%A1%88

**Comment by Zxxja** [comment]
> 不要改squirrel.yaml，用squirrel.custom.yaml。 好好讀讀幫助：https://github.com/rime/home/wiki/CustomizationGuide#%E4%B8%80%E4%BE%8B%E5%AE%9A%E8%A3%BD%E5%B0%8F%E7%8B%BC%E6%AF%AB%E9%85%8D%E8%89%B2%E6%96%B9%E6%A1%88
<img width="1132" alt="image" src="https://github.com/rime/squirrel/assets/170238371/0b39ab02-ad94-4350-be6e-6b9ba35817b3">
看了一下，好像应该是这一项，但我的ustom.yaml里完全没有 app_options这项内容呀

**Comment by LEOYoon-Tsaw** [comment]
https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/squirrel.custom.yaml

**Comment by Zxxja** [comment]
> 沒有就加，給你個參考，照葫蘆畫瓢
> 
> https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/squirrel.custom.yaml

<img width="664" alt="image" src="https://github.com/rime/squirrel/assets/170238371/18895315-8a3e-45be-b136-3683e1b4e900">
[捂脸]照着加上了，重新部署后还是没有用

**Comment by LEOYoon-Tsaw** [comment]
patch 前面不要有別的東西
