### ISSUE TITLE
Squirrel 在 Alfred 中不能输入中文

### ISSUE THREAD

**Issue by gfZeng** [rime/squirrel#90]
1. Squirrel 在 Alfred 中不能输入中文？
2. 提供命令行切换中英文状态就好了？方便 vim 和 emacs

**Comment by freewind** [comment]
下载SCU这个图形配置工具，把下面的去掉

![image](https://cloud.githubusercontent.com/assets/333781/12005253/787eb284-abd5-11e5-8f19-d4c553fc6602.png)

**Comment by gfZeng** [comment]
@freewind  谢谢
