### ISSUE TITLE
簡繁異常

### ISSUE THREAD

**Issue by yecheng0324** [rime/squirrel#900]
最近我發現在有些應用 莫名它就出現了繁體，而在微信中打字，它就都是簡體中文。
就像我來返饋這個問題的文字描述，在Chrome中也出現簡繁參雜的情況。
上次一次出現 在上週。我重新安裝重啓了倆次設備 後 它就好了。然後今天我就正常關屏  打開後它就又出現了這個問題。

我切换到自带输入法，输入时并无此问题，简繁错乱的问题（这是系统输入法 输入的）
<img width="818" alt="image" src="https://github.com/rime/squirrel/assets/66433322/06b9ce2b-63e6-4009-956c-9520f3ec4b10">
<img width="1671" alt="image" src="https://github.com/rime/squirrel/assets/66433322/cda5c148-866c-4abf-b562-f1796de1fe49">
xi to shu ru fa szhe yang d m y chu xian shang m na g w ti
<img width="1679" alt="image" src="https://github.com/rime/squirrel/assets/66433322/7e11e071-6fef-4c37-bfc7-4f5d5994427f">

**Comment by yecheng0324** [comment]
<img width="495" alt="image" src="https://github.com/rime/squirrel/assets/66433322/566b429f-6223-4c0f-945a-5c137127149b">

**Comment by LEOYoon-Tsaw** [comment]
看不太懂你在說甚麼，你的預期是甚麼，實際表現又是甚麼？

**Comment by yecheng0324** [comment]
我的预期，
在正常情况下它输出的字应该是 简体字。
在异常情况下 可实际输出的字 却是繁体

**Comment by LEOYoon-Tsaw** [comment]
```yaml 
 - name: simplification
    reset: 1
    states: [ 漢字, 汉字 ]
```
reset 設爲1就行了

**Comment by yecheng0324** [comment]
***@***.***
好的，我重新更改下配置 谢谢

发件人: LEO Yoon-Tsaw ***@***.***>
答复: rime/squirrel ***@***.***>
日期: 2024年5月23日 星期四 上午9:23
收件人: rime/squirrel ***@***.***>
抄送: yecheng0324 ***@***.***>, Author ***@***.***>
主题: Re: [rime/squirrel] 繁常 (Issue #900)


 - name: simplification

    reset: 1

    states: [ h字, 汉字 ]

reset O1就行了

―
