### ISSUE TITLE
升级MacOS和squirrel后打字出现方括号，导致打字快了会出错。

### ISSUE THREAD

**Issue by swahpy** [rime/squirrel#902]
https://github.com/rime/squirrel/assets/57909991/819d1303-7077-4e83-941d-20bcb0cba573

你好，如图所示，升级MacOS和squirrel后，每次打字字母两边都会出现方括号。打字很快的时候经常出错。请问这个是squirrel的bug还是跟MacOS不兼容呢？谢谢！

**Comment by LEOYoon-Tsaw** [comment]
這是你自己方案帶的，看一下preedit_format

**Comment by ksqsf** [comment]
这个输入效果看着像并击方案

**Comment by swahpy** [comment]
> 这个输入效果看着像并击方案

这个是星空键道6，音形方案。

**Comment by ksqsf** [comment]
那就是方案配置有问题

**Comment by swahpy** [comment]
> 那就是方案配置有问题

谢谢回复，应该是配置问题。我换了星猫键道的配置之后可以了。所以我先关闭这个issue了。
