### ISSUE TITLE
[Bug] label_font_size 与 font_size 不同时并未竖直居中

### ISSUE THREAD

**Issue by thep0y** [rime/squirrel#908]
**簡要描述 Bug：**
如标题。

**預期行爲：**

**實際行爲：**
<img width="141" alt="截屏2024-05-27 19 29 24" src="https://github.com/rime/squirrel/assets/51874567/c64d9068-6836-4dde-a46f-83f4224da3de">

**環境**
 - 系統版本： (macOS 14.5)
 - 鼠鬚管版本： (0.18)
 - 方案： (如果你用的是自定義或第三方的方案，且該 Bug 可能與方案有關，請提供方案鏈接)
 - [ ] 使用了 Lua： (用了甚麼 Lua 腳本？)
 - [ ] 與其它 App 有關： (哪個 App？)

**我試過：**
  - [ ] 我換了內置的方案（如`朙月拼音`）後問題仍存在
  - [ ] 我找到了導致問題出現的具體設置： (何設置？)
  - [ ] 這是個新 Bug，以前真的沒有
  - [ ] 我對原因有一些猜想： (你的寳貴想法)
  - [x] 在 Issues（包括已關閉的 Issue） 中未找到相關的報告

**Comment by LEOYoon-Tsaw** [comment]
會在1.0修復
<img width="291" alt="image" src="https://github.com/rime/squirrel/assets/4469383/472704cc-6dfe-402b-8bb8-a04b89736df8">

**Comment by thep0y** [comment]
安装了 1.0，标签并未居中，而是中间偏上，标签上边距是6个像素，下边距是9个像素，算得上肉眼可见的不同。

<img width="903" alt="截屏2024-05-31 17 38 57" src="https://github.com/rime/squirrel/assets/51874567/c031715e-c66c-416b-88d6-7efb7ab73ff6">
