### ISSUE TITLE
[Bug] 1.0 install error

### ISSUE THREAD

**Issue by Songggggr** [rime/squirrel#909]
Sonoma 14.5

安装失败

**Comment by Songggggr** [comment]
here pkg install success
https://github.com/LEOYoon-Tsaw/squirrel/releases/tag/1.0.0

**Comment by LEOYoon-Tsaw** [comment]
The failed one, was it from nightly or my draft release?

**Comment by LEOYoon-Tsaw** [comment]
The CI build (nightly) is arm64 only, if you are using x86_64, it will not install
Official release will be universal

**Comment by Songggggr** [comment]
@LEOYoon-Tsaw 确实，现在好了，感谢
