### ISSUE TITLE
[Bug]无法通过按 Caps Lock 切换 ABC 输入法与鼠须管

### ISSUE THREAD

**Issue by linlin08591** [rime/squirrel#911]
**簡要描述 Bug：**

更新 1.0.0 后，无法通过按 Caps Lock 切换 ABC 输入法与鼠须管输入法。

**預期行爲：**

**實際行爲：**

**環境**
 - 系統版本： (macOS 14.5)
 - 鼠鬚管版本： (1.0.0)
 - 方案： (如果你用的是自定義或第三方的方案，且該 Bug 可能與方案有關，請提供方案鏈接)
 - [ ] 使用了 Lua： (用了甚麼 Lua 腳本？)
 - [ ] 與其它 App 有關： (哪個 App？)

**我試過：**
  - [ ] 我換了內置的方案（如`朙月拼音`）後問題仍存在
  - [ ] 我找到了導致問題出現的具體設置： (何設置？)
  - [ ] 這是個新 Bug，以前真的沒有
  - [ ] 我對原因有一些猜想： (你的寳貴想法)
  - [ ] 在 Issues（包括已關閉的 Issue） 中未找到相關的報告

**Comment by hfziu** [comment]
> 預期行爲：

Squirrel 是中文输入法。在 macOS 上按下 Caps Lock 鍵時，應切換至上次使用的 Latin 輸入法（如 ABC）

> 實際行為：

Squirrel 激活狀態下，按下 Caps Lock 鍵，會切換到上次使用的非 Latin 輸入法（如「簡體拼音」/「繁體雙拼」等）

> 環境

In macOS Settings - Keyboard - Input Sources:

- [X] Use the Caps Lock key to switch to and from last used **Latin** input source

> 我試過：

- [X] 我對原因有一些猜想：Squirrel 1.0.0 在 macOS 中被系統識別為 Latin input source.

**Comment by LEOYoon-Tsaw** [comment]
info.plist 裏 Caps Lock Language Switch Capable 是 YES
不知道爲啥，等高手來看

**Comment by LEOYoon-Tsaw** [comment]
@hfziu 你的反饋很有幫助

**Comment by LEOYoon-Tsaw** [comment]
先開著吧，省得不斷有人提重複的問題，急著用可以用nightly，不急的可以等過兩天發1.0.1

**Comment by closure11** [comment]
> 先開著吧，省得不斷有人提重複的問題，急著用可以用nightly，不急的可以等過兩天發1.0.1

@LEOYoon-Tsaw 
啊，你lock了我的issue那我回复在这边吧: 
抱歉，我是早上第一时间看了没有人提交相关的问题，然后重复安装测试新、旧版本和写issue花了一段时间，提交的时候没再看一遍有没有人发过了

**Comment by gaojjx** [comment]
刚刚更新到了1.0.1还是不行

> 先開著吧，省得不斷有人提重複的問題，急著用可以用nightly，不急的可以等過兩天發1.0.1
