### ISSUE TITLE
[Bug]无法通过大写锁定键切换系统ABC输入法/鼠须管

### ISSUE THREAD

**Issue by closure11** [rime/squirrel#914]
## 簡要描述 Bug
我习惯使用鼠须管来输入中文，系统ABC输入法来输入英文，更新1.0.0之后，大写锁定键无法再在ABC/鼠须管之间切换

## 可能的原因

观察到系统设置-键盘-所有输入法选项中，“使用“中/英”键切换“ABC”输入法]”的选项消失，使用旧版本时有该选项。根据[macOS使用手册](https://support.apple.com/zh-cn/guide/mac-help/mchl84525d76/14.0/mac/14.0):

> 此选项仅在你添加了非拉丁输入法时才会显示

怀疑1.0.0版本的某个配置有所改动，导致系统不再认定鼠须管为“非拉丁输入法”，从而关闭了大写锁定键切换输入法的功能

## 截图
<img width="640" alt="image" src="https://github.com/rime/squirrel/assets/16165094/7c4c1df8-5136-4dac-8ecb-a61b3a4b02d0">

<img width="640" alt="image" src="https://github.com/rime/squirrel/assets/16165094/e41e13a7-13bb-43c0-9203-9090d904108f">

## 環境
 - 系統版本： (macOS 14.5)
 - 鼠鬚管版本： (1.0.0)

**Comment by LEOYoon-Tsaw** [comment]
已經有了#911，而且已經修好了，麻煩看一下已有的issue啊，這在模板裡專門提醒了
