### ISSUE TITLE
launchpad的搜索框里面中英文输入失效

### ISSUE THREAD

**Issue by beyondkmp** [rime/squirrel#92]
想在launchpad设置默认为英文输入法，但是就是不成功，配置如下：
```
 com.apple.launchpad.launcher:
    ascii_mode: true
```
后面才发现是在搜索框中，shift更换不起作用。

**Comment by beyondkmp** [comment]
我已经解决了！那个launchpad里面的输入框的bundle id是  com.apple.dock.ecti，将上面的配置更改，先在搜索框输入，再在日志系统中就可以找到这个bundle id。：
```
com.apple.dock.ecti:
    ascii_mode:  true
```
虽然上面设置后输入时默认是英文，但是又不能切换到中文，shift键还是不起作用。不过看了default.yaml里面还有一个快捷键就是ctl+shift+2可以激活ascii_mode，所以在lauchpad 下的搜索框下就用ctl+shift+2来做中英文切换，如果觉的太长，可以自己修改快捷键。

**Comment by lotem** [comment]
Let's put this in `squirrel.yaml`
