### ISSUE TITLE
[Bug]label_font_size 与 font_size 不同时竖直居中向上偏移，非完全竖直居中

### ISSUE THREAD

**Issue by thep0y** [rime/squirrel#920]
**簡要描述 Bug：**
如题

**預期行爲：**

**實際行爲：**

虽然我把截图放大了，但即便不放大也是肉眼可见的靠上，而非完全居中。

<img width="854" alt="截屏2024-06-01 08 32 17" src="https://github.com/rime/squirrel/assets/51874567/7d3b584e-1d9b-4c69-a269-bf6b6e6d6862">

**環境**
 - 系統版本： macOS 14.5
 - 鼠鬚管版本： 1.0.0
 - 方案： (如果你用的是自定義或第三方的方案，且該 Bug 可能與方案有關，請提供方案鏈接)
 - [ ] 使用了 Lua： (用了甚麼 Lua 腳本？)
 - [ ] 與其它 App 有關： (哪個 App？)

**我試過：**
  - [ ] 我換了內置的方案（如`朙月拼音`）後問題仍存在
  - [ ] 我找到了導致問題出現的具體設置： (何設置？)
  - [ ] 這是個新 Bug，以前真的沒有
  - [ ] 我對原因有一些猜想： (你的寳貴想法)
  - [ ] 在 Issues（包括已關閉的 Issue） 中未找到相關的報告

**Comment by LEOYoon-Tsaw** [comment]
<img width="974" alt="image" src="https://github.com/rime/squirrel/assets/4469383/81fa2575-2b26-438e-ace7-74c416e8e585">
這是系統輸入法，也同樣做不到100%居中，而且我想各個字體也會略有不同。
如果你研究出來完美的解決辦法歡迎提PR！

**Comment by thep0y** [comment]
你是对的，系统输入法也没有实现完全居中，但是系统输入法的标签是稍偏下，而不是偏上。

偏下可能比偏上视觉上更美观，而且系统输入法的偏移量也小一些。

<img width="1063" alt="截屏2024-06-01 20 58 18" src="https://github.com/rime/squirrel/assets/51874567/4de445f8-3450-4262-8d9b-e6a7d1c83527">


我现在只有提个 issue 的时间，读代码、改代码、编译调试短期内没时间，非常遗憾。

**Comment by LEOYoon-Tsaw** [comment]
要想偏下可以在這裏把 1/2 字號大小之差改成 1/3
https://github.com/rime/squirrel/blob/e70691077392b9d3d39119d12dd7ccca95258d42/sources/SquirrelTheme.swift#L118
但是hardcode總是不理想，最好有更好的辦法
如果實在覺得寫死1/3更好，我也不反對

**Comment by thep0y** [comment]
如果hardcode后的表现更接近系统输入法，我个人觉得挺好的。

如果把标签位置的上下几个像素的偏移量写也入配置中，反而有些过分。
