### ISSUE TITLE
[Bug] 鼠须管布署以后，squirrel.yaml被移入新生成的trash文件夹的原因？？

### ISSUE THREAD

**Issue by derek0x** [rime/squirrel#922]
**簡要描述 Bug：**

鼠须管布署以后，squirrel.yaml被移入新生成的trash文件夹的原因？？

![a725cc37a50d15965546318200e2e883](https://github.com/rime/squirrel/assets/18011180/3ab34799-df0d-4594-8c6f-c57a1d3262f9)

**環境**
 - 系統版本： (macOS 13.6.7)
 - 鼠鬚管版本： (1.0.1)

**我試過：**
  - 我換了內置的方案（如`朙月拼音`）後問題仍存在

**Comment by LEOYoon-Tsaw** [comment]
有別的影響嗎？

**Comment by derek0x** [comment]
> 有別的影響嗎？

没有，就发现皮肤无法生效了

**Comment by LEOYoon-Tsaw** [comment]
看看log有沒有報錯？

**Comment by derek0x** [comment]
我查了日志，没有相关的报错信息，但是，除了会把 squirrel.yaml 被移入新生成的 trash 文件夹 ，build 中 会自动生成一个 squirrel.yaml 文件， 但这并不是我的文件，可能是默认的。

内容如下：
`
__build_info:
  rime_version: 1.11.2
  timestamps:
    squirrel: 1717178200
    squirrel.custom: 0
app_options:
  co.zeit.hyper:
    ascii_mode: true
  com.alfredapp.Alfred:
    ascii_mode: true
  com.apple.Spotlight:
    ascii_mode: true
  com.apple.Terminal:
    ascii_mode: true
    no_inline: true
  com.apple.dt.Xcode:
    ascii_mode: true
  com.barebones.textwrangler:
    ascii_mode: true
  com.blacktree.Quicksilver:
    ascii_mode: true
  com.github.atom:
    ascii_mode: true
  com.google.Chrome:
    inline: true
  com.googlecode.iterm2:
    ascii_mode: true
    no_inline: true
  com.macromates.TextMate.preview:
    ascii_mode: true
  com.microsoft.VSCode:
    ascii_mode: true
  "com.runningwithcrayons.Alfred-2":
    ascii_mode: true
  com.sublimetext.2:
    ascii_mode: true
  org.gnu.Aquamacs:
    ascii_mode: true
  org.gnu.Emacs:
    ascii_mode: true
    no_inline: true
  org.vim.MacVim:
    ascii_mode: true
    no_inline: true
    vim_mode: true
  ru.keepcoder.Telegram:
    inline: true
chord_duration: 0.1
config_version: 1.0
keyboard_layout: last
preset_color_schemes:
  apathy:
    author: "LIANG Hai"
    back_color: 0xFFFFFF
    border_height: 0
    border_width: 0
    candidate_format: "%c %@ "
    comment_text_color: 0x999999
    corner_radius: 5
    font_face: "PingFangSC-Regular,HanaMinB"
    font_point: 16
    hilited_candidate_back_color: 0xFFF0E4
    hilited_candidate_text_color: 0xEE6E00
    horizontal: true
    inline_preedit: true
    label_font_face: "STHeitiSC-Light"
    label_font_point: 12
    name: "冷漠／Apathy"
    text_color: 0x424242
  aqua:
    author: "佛振 <chen.sst@gmail.com>"
    back_color: 0xeeeceeee
    candidate_text_color: 0x000000
    comment_text_color: 0x5a5a5a
    hilited_candidate_back_color: 0xeefa3a0a
    hilited_candidate_text_color: 0xffffff
    hilited_comment_text_color: 0xfcac9d
    hilited_text_color: 0x000000
    name: "碧水／Aqua"
    text_color: 0x606060
  azure:
    author: "佛振 <chen.sst@gmail.com>"
    back_color: 0xee8b4e01
    candidate_text_color: 0xffeacc
    comment_text_color: 0xc69664
    hilited_candidate_back_color: 0x00000000
    hilited_candidate_text_color: 0x7ffeff
    hilited_text_color: 0xffeacc
    name: "青天／Azure"
    text_color: 0xcfa677
  clean_white:
    author: "Chongyu Zhu <lembacon@gmail.com>, based on 搜狗「简约白」"
    back_color: 0xeeeeee
    border_height: 6
    border_width: 6
    candidate_format: "%c %@"
    candidate_text_color: 0x000000
    comment_text_color: 0x808080
    corner_radius: 6
    font_point: 16
    hilited_candidate_back_color: 0xeeeeee
    hilited_candidate_label_color: 0xa0c98915
    hilited_candidate_text_color: 0xc98915
    hilited_text_color: 0x000000
    horizontal: true
    label_color: 0x888888
    label_font_point: 12
    name: "简约白／Clean White"
    text_color: 0x808080
  dark_temple:
    author: "佛振 <chen.sst@gmail.com>, based on ir_black"
    back_color: 0x222222
    candidate_text_color: 0xd8e3e6
    comment_text_color: 0x606cff
    hilited_back_color: 0x222222
    hilited_candidate_back_color: 0x10000000
    hilited_candidate_text_color: 0x92f6da
    hilited_text_color: 0xffcf9a
    name: "暗堂／Dark Temple"
    text_color: 0x92f6da
  dust:
    author: "Superoutman <asticosmo@gmail.com>"
    back_color: 0xeeffffff
    border_color: 0xE0B693
    border_height: 3
    border_width: 8
    candidate_format: "%c %@ "
    candidate_text_color: 0x555555
    comment_text_color: 0x999999
    corner_radius: 2
    font_face: "HYQiHei-55S Book,HanaMinA Regular"
    font_point: 14
    hilited_candidate_back_color: 0xfff0e4
    hilited_candidate_label_color: 0x555555
    hilited_candidate_text_color: 0x000000
    hilited_comment_text_color: 0x9e9e9e
    hilited_text_color: 0x9e9e9e
    horizontal: true
    inline_preedit: true
    label_color: 0xcbcbcb
    label_font_face: SimHei
    label_font_point: 10
    name: "浮尘／Dust"
    text_color: 0x424242
  google:
    author: "skoj <skoj@qq.com>"
    back_color: 0xFFFFFF
    border_color: 0xE2E2E2
    candidate_text_color: 0x000000
    comment_text_color: 0x6D6D6D
    hilited_back_color: 0xFFFFFF
    hilited_candidate_back_color: 0xCE7539
    hilited_candidate_text_color: 0xFFFFFF
    hilited_comment_text_color: 0xEBC6B0
    hilited_text_color: 0x000000
    name: "谷歌／Google"
    text_color: 0x666666
  ink:
    author: "佛振 <chen.sst@gmail.com>"
    back_color: 0xeeffffff
    candidate_text_color: 0x000000
    comment_text_color: 0x5a5a5a
    hilited_candidate_back_color: 0xcc000000
    hilited_candidate_text_color: 0xffffff
    hilited_comment_text_color: 0x808080
    hilited_text_color: 0x000000
    name: "墨池／Ink"
    text_color: 0x5a5a5a
  lost_temple:
    author: "佛振 <chen.sst@gmail.com>, based on ir_black"
    back_color: 0xee303030
    comment_text_color: 0xbb82e6ca
    hilited_candidate_back_color: 0x82e6ca
    hilited_candidate_text_color: 0x000000
    hilited_comment_text_color: 0xbb203d34
    hilited_text_color: 0x82e6ca
    name: "孤寺／Lost Temple"
    text_color: 0xe8f3f6
  luna:
    author: "佛振 <chen.sst@gmail.com>"
    back_color: 0xdd000000
    candidate_text_color: 0xeceeee
    comment_text_color: 0xa5a5a5
    hilited_candidate_back_color: 0x40000000
    hilited_candidate_text_color: 0x7fffff
    hilited_comment_text_color: 0x449c9d
    hilited_text_color: 0x7fffff
    name: "明月／Luna"
    text_color: 0xa5a5a5
  mojave_dark:
    author: "xiehuc <xiehuc@gmail.com>"
    back_color: 0x252320
    border_color: 0x020202
    border_height: 6
    border_width: 6
    candidate_format: "%c %@"
    candidate_text_color: 0xdedddd
    comment_text_color: 0xdedddd
    corner_radius: 5
    font_face: PingFangSC
    font_point: 16
    hilited_back_color: 0x252320
    hilited_candidate_back_color: 0xcb5d00
    hilited_candidate_label_color: 0xffffff
    hilited_candidate_text_color: 0xffffff
    hilited_corner_radius: 3
    hilited_text_color: 0xdedddd
    horizontal: true
    inline_preedit: true
    label_color: 0x888785
    label_font_point: 14
    name: "沙漠夜／Mojave Dark"
    text_color: 0xdedddd
  native:
    name: "系統配色"
  psionics:
    author: "雨過之後、佛振"
    back_color: 0x444444
    candidate_text_color: 0xeeeeee
    comment_text_color: 0x808080
    hilited_back_color: 0x444444
    hilited_candidate_back_color: 0xd4bc00
    hilited_candidate_label_color: 0xfafafa
    hilited_candidate_text_color: 0xfafafa
    hilited_comment_text_color: 0x444444
    hilited_text_color: 0xeeeeee
    name: "幽能／Psionics"
    text_color: 0xc2c2c2
  purity_of_essence:
    author: "佛振"
    back_color: 0xfafafa
    candidate_text_color: 0x000000
    comment_text_color: 0x808080
    hilited_back_color: 0xfafafa
    hilited_candidate_back_color: 0x444444
    hilited_candidate_text_color: 0xeeeeee
    hilited_text_color: 0x000000
    name: "純粹的本質／Purity of Essence"
    text_color: 0x2c2ccc
  purity_of_form:
    author: "雨過之後、佛振"
    back_color: 0x444444
    candidate_text_color: 0xeeeeee
    comment_text_color: 0x808080
    hilited_back_color: 0x444444
    hilited_candidate_back_color: 0xfafafa
    hilited_candidate_text_color: 0x000000
    hilited_text_color: 0xeeeeee
    name: "純粹的形式／Purity of Form"
    text_color: 0xc2c2c2
  solarized_dark:
    author: "雪齋 <lyc20041@gmail.com>"
    back_color: 0xF0352A0A
    border_color: 0x2A1F00
    candidate_text_color: 0x7389FF
    comment_text_color: 0xC38AFF
    hilited_back_color: 0xC9DADF
    hilited_candidate_back_color: 0x403516
    hilited_candidate_label_color: 0xCC8947
    hilited_candidate_text_color: 0x989F52
    hilited_comment_text_color: 0x289989
    hilited_text_color: 0xBE706D
    label_color: 0x478DF4
    name: "曬經・月／Solarized Dark"
    preedit_back_color: 0xD7E8ED
    text_color: 0x756E5D
  solarized_light:
    author: "雪齋 <lyc20041@gmail.com>"
    back_color: 0xF0E5F6FB
    border_color: 0xEDFFFF
    candidate_text_color: 0x595E00
    color_space: display_p3
    comment_text_color: 0x005947
    hilited_back_color: 0x4C4022
    hilited_candidate_back_color: 0xD7E8ED
    hilited_candidate_label_color: 0x2566C6
    hilited_candidate_text_color: 0x3942CB
    hilited_comment_text_color: 0x8144C2
    hilited_text_color: 0x2C8BAE
    label_color: 0xA36407
    name: "曬經・日／Solarized Light"
    preedit_back_color: 0x403516
    text_color: 0xA1A095
  solarized_rock:
    author: "Aben <tntaben@gmail.com>, based on Ethan Schoonover's Solarized color scheme"
    back_color: 0x362b00
    border_color: 0x362b00
    candidate_text_color: 0x969483
    comment_text_color: 0xc098a12a
    hilited_candidate_back_color: 0x8236d3
    hilited_candidate_text_color: 0xffffff
    hilited_comment_text_color: 0x362b00
    hilited_text_color: 0x98a12a
    name: "曬經石／Solarized Rock"
    text_color: 0x8236d3
  starcraft:
    author: "Contralisk <contralisk@gmail.com>, original artwork by Blizzard Entertainment"
    back_color: 0xee000000
    border_color: 0x1010a0
    candidate_text_color: 0x30bb55
    comment_text_color: 0x1010d0
    hilited_back_color: 0x000000
    hilited_candidate_back_color: 0x00000000
    hilited_candidate_text_color: 0x70ffaf
    hilited_comment_text_color: 0x1010f0
    hilited_text_color: 0xfecb96
    name: "星際我爭霸／StarCraft"
    text_color: 0xccaa88
show_notifications_when: appropriate
style:
  border_height: "-2"
  border_width: "-2"
  candidate_format: "[label]. [candidate] [comment]"
  candidate_list_layout: stacked
  color_scheme: native
  corner_radius: 7
  font_face: Avenir
  hilited_corner_radius: 0
  inline_candidate: false
  inline_preedit: true
  line_spacing: 5
  memorize_size: true
  mutual_exclusive: false
  shadow_size: 0
  spacing: 8
  text_orientation: horizontal
  translucency: false
`

**Comment by LEOYoon-Tsaw** [comment]
那建議你用squirrel.custom.yaml，而不要直接寫squirrel.yaml

**Comment by derek0x** [comment]
> 那建議你用squirrel.custom.yaml，而不要直接寫squirrel.yaml

谢谢，我移动后试试。

**Comment by derek0x** [comment]
确实，我把空山明月 Rime_wubi 方案中的squirrel.yaml 的东西都转移到squirrel.custom.yaml中后，问题就解决了。谢谢大佬

<img width="408" alt="image" src="https://github.com/rime/squirrel/assets/18011180/d6bb03d9-ee4a-44d3-8ddd-8519b431aa08">

**Comment by derek0x** [comment]
我今天花时间又重新测试了下，0.18的 版本，布署完成以后没有任何问题，也没有报错日志。
后重新升级后，发现系统有报错。
<img width="1229" alt="image" src="https://github.com/rime/squirrel/assets/18011180/6258ce51-1ca4-4318-81a4-b393662254c4">
似乎检测 wb_spelling.reverse.bin 时，并还没build完成，就已经ERROR了。

另外在未发现其他ERROR日志的情况下，还是发现squirrel.yaml会被清理到trash文件夹中。

我将在附件中附上我的squirrel文件内容，因为我检查过后并没有发现什么异常，他在0.18中也是正常工作的。

[squirrel.yaml.txt](https://github.com/user-attachments/files/15528351/squirrel.yaml.txt)

**Comment by lotem** [comment]
跟鼠鬚管自帶的同名文件衝突了。

**Comment by derek0x** [comment]
> 跟鼠鬚管自帶的同名文件衝突了。

所以我还像之前一样，把东西放到squirrel.custom.yaml 中去就可以了吗？
那个reverse.bin的报错该如何解决，佛振大佬。
