### ISSUE TITLE
不再支持 `style/horizontal` 和 `style/vertical` 如何设置支持横排显示呢

### ISSUE THREAD

**Issue by CoutureOne** [rime/squirrel#925]
**Environment**
 - OS version: (macOS 13.6.5)
 - Squirrel version: (1.0.1)
 - Schema: (If you are using a custom schema, and think it might be related to the schema, please provide a link)
想知道各位大佬，style/horizontal移植以后，如何支持设置横排显示的，求解，谢谢

**Comment by CoutureOne** [comment]
对了，我想说的候选词横排显示

**Comment by Rachel030219** [comment]
参见 [changelog](https://github.com/rime/squirrel/tree/master/CHANGELOG.md) ，只需要将 `style/horizontal: true` 改为 `style/candidate_list_layout: linear` 即可

**Comment by CoutureOne** [comment]
> 参见[changelog](https://github.com/rime/squirrel/tree/master/CHANGELOG.md)，只需要`style/horizontal: true`修改`style/candidate_list_layout: linear`即可

好的，谢谢已经成功了

**Comment by yezhu64** [comment]
能問問是改哪個文件嗎？

**Comment by Rachel030219** [comment]
> 能問問是改哪個文件嗎？

`squirrel.xml` 里的 `style` ，或针对 `preset_color_schemes` 下某个具体的主题修改都可以，当然也可以在 `squirrel.custom.xml` 里修改

<img width="334" alt="image" src="https://github.com/rime/squirrel/assets/13704467/cd4da171-f146-40df-a151-b18c02454b20">

or
<img width="385" alt="image" src="https://github.com/rime/squirrel/assets/13704467/74983b38-28d8-4da5-9dfd-761d933c57b5">

**Comment by yezhu64** [comment]
修改了前一個文件，重新部署後，好像還是無效

**Comment by yezhu64** [comment]
而且好像無法修改，再次打開文件，沒有添加到內容

**Comment by yezhu64** [comment]
終於成功！謝謝。要如何把候選字設置大些呢？請教一下

**Comment by yezhu64** [comment]
麻煩再問一下，不知後選詞大小該如何修改呢？

**Comment by anaer** [comment]
[squirrel.yaml 配置指南](https://github.com/rime/squirrel/wiki/squirrel.yaml-%E9%85%8D%E7%BD%AE%E6%8C%87%E5%8D%97)

**Comment by yezhu64** [comment]
謝謝！已設置好字號
