### ISSUE TITLE
[Bug] 每次开机会重新部署 Squirrel

### ISSUE THREAD

**Issue by pengcu** [rime/squirrel#927]
**Describe the bug:**
我发现更新到1.0.1后，每次开机会重新部署 Squirrel，（会提示Deploying Rime input method engine. => Squirrel is ready.）
不知道这是一个 bug，或者是新版本有意这样设置？
`squirrel.custom.yaml`中设置了`show_notifications_when: appropriate`

**Environment**
 - OS version: (macOS 13.6.7) (intel 平台)
 - Squirrel version: (1.0.1)
 - Schema: (If you are using a custom schema, and think it might be related to the schema, please provide a link)
 - [ ] Using Lua: (what Lua script do you use?)
 - [ ] Related to other apps: (which app?)

**Things you've tried**
  - [ ] I tried a built-in schema (like `luna pinyin`), but the bug persists
  - [ ] I found the exact setting that produced this bug: (which one?)
  - [ ] This bug is new in this version
  - [ ] I think the cause might be: (your thoughts)
  - [ ] I don't find a similar report in Issues (including closed Issues)

**Comment by LEOYoon-Tsaw** [comment]
mac用戶不是不關機的嗎🤖
