### ISSUE TITLE
[Bug]更新后提示框和文字太小

### ISSUE THREAD

**Issue by greenflute** [rime/squirrel#929]
**簡要描述 Bug：**
更新后提示框和文字太小
<img width="395" alt="screenshot 2024-06-04 13 00 35" src="https://github.com/rime/squirrel/assets/526909/d7e69536-6e8e-4602-9813-5f2fb9bc36a3">

**預期行爲：**

**實際行爲：**

**環境**
 - 系統版本： (macOS 13.6.7)
 - 鼠鬚管版本： (1.0.1)
 - 方案： (如果你用的是自定義或第三方的方案，且該 Bug 可能與方案有關，請提供方案鏈接)
 - [ ] 使用了 Lua： (用了甚麼 Lua 腳本？)
 - [ ] 與其它 App 有關： (哪個 App？)

**我試過：**
  - [ ] 我換了內置的方案（如`朙月拼音`）後問題仍存在
  - [ ] 我找到了導致問題出現的具體設置： (何設置？)
  - [ ] 這是個新 Bug，以前真的沒有
  - [ ] 我對原因有一些猜想： (你的寳貴想法)
  - [ ] 在 Issues（包括已關閉的 Issue） 中未找到相關的報告

**Comment by LEOYoon-Tsaw** [comment]
默認字號改成系統字號了，像大一點就自訂字號

**Comment by greenflute** [comment]
谢谢，试一下
