### ISSUE TITLE
关于新建造词的逻辑

### ISSUE THREAD

**Issue by sequencer** [rime/squirrel#93]
有时候输入的时候会造词来运行
比如谐振腔这个词
会这样输
和谐 右移 del 左移 振动 del 腔
这样来输入
也就是说能否用addLocalMonitorForEventsMatchingMask:handler这个api来获取方向键的输入从而来自动生成谐振腔这个词了？
或者说在输入的时候进行如此造词可能会更好实现一些。让光标右移的时候把已经生成的汉字转换为拼音可供删除然后造词。

**Comment by lotem** [comment]
有难度。左右移动光标输入法都知道。就算不移光标、不删除，也很难判断哪些字应该组成一个词。这要专门做一个课题。
还有这种靠记录编辑动作维护状态的方法一定是不可靠的，鼠标或应用程序自己都有可能移走光标。更可靠的方法有，从文本框拿到编辑后的结果文本再进行分词，或者由输入法支持在未上屏内容上编辑。主张最后这种方法，既可靠，又较容易实现。
