### ISSUE TITLE
[咨询]皮肤里的label font没有垂直居中配置？

### ISSUE THREAD

**Issue by scutvange** [rime/squirrel#931]
**Describe the bug:**
在squirrel.custom.yaml里配置了皮肤仿Mac原生，但是始终找不到数字序号垂直居中的字段设置，只有字基高（base_offset）的设置

**Expected behavior:**
希望有一个字段可以设置数字序号垂直居中

**Environment**
 - OS version: (macOS 14.5)
 - Squirrel version: (1.11.2)

<img width="338" alt="image" src="https://github.com/rime/squirrel/assets/8445583/b87c2327-2b59-4140-8930-9dd160af0486">

**Comment by LEOYoon-Tsaw** [comment]
Squirrel 沒有 1.11.2 你用的啥版本？點檢查更新可以看到

**Comment by scutvange** [comment]
> Squirrel 沒有 1.11.2 你用的啥版本？點檢查更新可以看到

搞错了，是1.0.1
<img width="229" alt="image" src="https://github.com/rime/squirrel/assets/8445583/0127dd9a-ad50-4ace-b294-313dbe51cceb">

**Comment by scutvange** [comment]
更新了最新版后，序号的垂直对齐变成偏上了，是否可以提供一个字段让用户自己设置序号垂直对齐呢？跟base_offset一样。

**Comment by scutvange** [comment]
<img width="360" alt="image" src="https://github.com/rime/squirrel/assets/8445583/e8088ceb-d38b-4b98-a147-3fd3a2fc8024">

**Comment by DreamingloveR** [comment]
请问大佬如何设置成横向候选词？ 我更新后重新部署，全变成纵向了，改配置文件也没用

**Comment by LEOYoon-Tsaw** [comment]
同 #920

**Comment by LEOYoon-Tsaw** [comment]
> 请问大佬如何设置成横向候选词？ 我更新后重新部署，全变成纵向了，改配置文件也没用

#925

**Comment by DreamingloveR** [comment]
> > 请问大佬如何设置横向候选词？ 我更新后重新撰写，全变成纵向的了，配置文件也没用。
> 
> #925

感谢!已解决
