### ISSUE TITLE
[Bug]更新1.0.2后 横排候选字失效

### ISSUE THREAD

**Issue by glenxoseph** [rime/squirrel#935]
**簡要描述 Bug：**
1.0.2前，鼠须管的候选字为横排显示，和我的设置相同。但更新后，在设置没有变化的情况下，候选字改为竖排显示。
squirrel.custom.yaml 中，patch: preset_color_schemes: solarized_rock: 下有 horizontal: true，且部署后在 squirrel.yaml 中也成功同步，但无法横排显示。
我尝试过将 horizontal: true 直接移动至 patch: style: 下，亦能成功同步至 squirrel.yaml，但仍不可横排显示。

**預期行爲：**
候选字为横排显示
**實際行爲：**
候选字为竖排显示
**環境**
 - 系統版本： (macOS 14.1)
 - 鼠鬚管版本： (1.0.3)
 - 方案： (如果你用的是自定義或第三方的方案，且該 Bug 可能與方案有關，請提供方案鏈接)
 - [ ] 使用了 Lua： (用了甚麼 Lua 腳本？)
 - [ ] 與其它 App 有關： (哪個 App？)

**我試過：**
  - [ ] 我換了內置的方案（如`朙月拼音`）後問題仍存在
  - [ ] 我找到了導致問題出現的具體設置： (何設置？)
  - [ ] 這是個新 Bug，以前真的沒有
  - [ ] 我對原因有一些猜想： (你的寳貴想法)
  - [ ] 在 Issues（包括已關閉的 Issue） 中未找到相關的報告

**Comment by cobaltdisco** [comment]
请使用“candidate_list_layout: linear”来代替。

**Comment by glenxoseph** [comment]
@cobaltdisco 感谢，已解决。
我直到更新1.0.2才注意到这个问题，所以在发issue前只看了1.0.2的release note，没有往下翻，刚刚才发现这个问题早已在release note的1.0.0部分提及了。
