### ISSUE TITLE
[Bug] #937 升級鼠鬚管1.02 Mac後，在「中文」模式下只能打出英文拼音

### ISSUE THREAD

**Issue by ekliao** [rime/squirrel#937]
**簡要描述 Bug：**
最新鼠鬚管Mac版1.02，安裝重新log in後，無法打出中文。即使切換shift鍵，確定是「中文」狀態（而非英文），打出來的仍是英文字加underline，也沒有中文選字框的出現。確定選擇了「朙月」。

**預期行爲：**
應該能跟以往一樣打出中文

**實際行爲：**
打出的是英文拼音，加上有underline

**環境**
 - 系統版本： (macOS 14.5)
 - 鼠鬚管版本： (1.0.0) -> 1.02
 - 方案： (如果你用的是自定義或第三方的方案，且該 Bug 可能與方案有關，請提供方案鏈接)
 - [ ] 使用了 Lua： (用了甚麼 Lua 腳本？)
 - [ ] 與其它 App 有關： (哪個 App？) 

**我試過：**
  - [x] 我換了內置的方案（如`朙月拼音`）後問題仍存在
  - [ ] 我找到了導致問題出現的具體設置： (何設置？)
  - [x] 這是個新 Bug，以前真的沒有
  - [ ] 我對原因有一些猜想： (你的寳貴想法)
  - [x] 在 Issues（包括已關閉的 Issue） 中未找到相關的報告

**Comment by LEOYoon-Tsaw** [comment]
你提供的信息不足以復現問題，我也用的macOS14.5，沒有這種問題

**Comment by ekliao** [comment]
我可以提供一個短的螢幕錄影，放到Youtube，並給你link來查看嗎？

**Comment by ekliao** [comment]
我所能想到的原因，就只是從 1.01 升級到
1.02，僅此而已。我沒有改變過設置。1.01以及之前，都沒有這個在「中文」模式下，只能打出英文拼音及底線的狀況。

我會改標題。

Regards,
Eric

---------------
Eric K. Liao

https://ericliaointerpreting.com (view or download CV/résumé
可瀏覽或下載履歷/可浏览或下载履历)
*Mandarin Chinese<>English In-person/Remote Conference and Court
Interpreter*
*San José, California | **(408)916-7129 | Email
***@***.***> | LinkedIn
<https://www.linkedin.com/in/ericliaointerpreter/>*
MA in Conference Interpretation, MIIS
Certified Court Interpreter, California/NJ/AZ/WY
Certified Medical Interpreter

**Comment by LEOYoon-Tsaw** [comment]
你是否使用大寫字幕？Caps Lock、Shift？

**Comment by ekliao** [comment]
沒有。我確認，在烱月「中文」狀態下，是打出小寫的英文字母。如果同時按下shift再打，就打出大寫英文。

這時如果按一下shift，會切換中文英文，如果按caplock一下，會切換輸入法，離開鼠鬚管，到英文輸入法。

有沒有辦法讓我取得前一版本 （1.00 或 1.01）讓我試試？

**Comment by LEOYoon-Tsaw** [comment]
在這裡可以找到所有版本

https://github.com/rime/squirrel/releases

抱歉無法提供幫助

**Comment by ekliao** [comment]
謝謝。我刪除了所有 ~/<user>/library/RIME 的內容，再重新安裝，就恢復正常了。

**Comment by QuantumRoseinAmethystVase** [comment]
一样的问题，注销后再登录可解决
