### ISSUE TITLE
why the app don't support macos 12

### ISSUE THREAD

**Issue by ofzo** [rime/squirrel#938]
<img width="663" alt="image" src="https://github.com/rime/squirrel/assets/18000037/5ce20f94-08a7-4a0d-aa01-4f0808c29bf1">

**Comment by LEOYoon-Tsaw** [comment]
Because I cannot guarantee best experience on it anymore

**Comment by ofzo** [comment]
> Because I cannot guarantee best experience on it anymore
> 
> Squirrel 0.16.2 works best for macOS 12, feel free to use that version

@LEOYoon-Tsaw 
Is it possible to provide a way to download 0.16.2 for brew?

**Comment by LEOYoon-Tsaw** [comment]
I don't maintain brew channel, but generally specifying a version in brew is common
