### ISSUE TITLE
[Bug]  在指定 `"style/color_scheme_dark": native` 的情况下， Squirrel不会跟随系统设置将颜色设置成深色。

### ISSUE THREAD

**Issue by thelastlin** [rime/squirrel#939]
**簡要描述 Bug：**
Squirrel的界面颜色总是保持浅色，和系统设置不同步，即使指定`"style/color_scheme_dark": native`后仍如此。

**預期行爲：**
指定`"style/color_scheme_dark": native`时，系统设置选用深色主题时，Squirrel也应使用对应的深色主题。

**實際行爲：**
此时Squirrel总是使用浅色主题。
将`style/color_scheme_dark`修改成其他深色主题（如`solarized_dark`）时可规避此问题。

**相关配置**
`squirrel.custom.yaml`: 
```
patch:
  "style/font_point": 20
  "style/label_font_point": 18
  #  "style/inline_preedit": false
  "app_options/com.googlecode.iterm2/no_inline": false
  "app_options/com.microsoft.VSCode/no_inline": true
  "app_options/com.googlecode.iterm2/ascii_mode": false
  "style/color_scheme_dark": native
```

**環境**
 - 系統版本： macOS 14.5 (23F79)
 - 鼠鬚管版本： 1.0.2
 - 方案： （不适用）
 - [ ] 使用了 Lua
 - [ ] 與其它 App 有關

**我試過：**
  - [ ] 我找到了導致問題出現的具體設置： (何設置？)
  - [x] 這是個新 Bug，以前真的沒有
  - [ ] 在 Issues（包括已關閉的 Issue） 中未找到相關的報告
       相关Issue： #934

**Comment by LEOYoon-Tsaw** [comment]
無法復現。
<img width="253" alt="image" src="https://github.com/rime/squirrel/assets/4469383/a931aa08-7aca-440c-a70a-aa099011a0ce">

**Comment by LEOYoon-Tsaw** [comment]
另外提醒一下，no_inline": false是沒用的，想要強制inline設inline: true

**Comment by thelastlin** [comment]
不保存窗口状态退出登录并重启，问题解决。
