### ISSUE TITLE
在 Alfred 的搜索框中无法输入中文

### ISSUE THREAD

**Issue by inferjay** [rime/squirrel#94]
OS：Mac OSX 10.11.2 (15C50)
Alfred：v2.8.2 (432)

**Comment by weijianwen** [comment]
参考 #90 ，将`squirrel.yaml`中关于ascii设置的如下两行做如下修改：

```
  com.runningwithcrayons.Alfred-2:
    ascii_mode: false
```

重新Deploy后就能在Alfred2中输入中文了。

**Comment by inferjay** [comment]
@weijianwen 问题已解决，谢谢 :)
