### ISSUE TITLE
鼠须管的日志问题

### ISSUE THREAD

**Issue by Anber55** [rime/squirrel#948]
**簡要描述 Bug：**
鼠须管的日志总是莫名消失，而且消失后有新的错误或者日志也不再产生显示，一直是软链接的形式
这个时候除非将Mac重启，才可以正常显示错误，否则是不行的

这给我带来了很大的困扰，日志本来就是查询自己的错误，但是看不见没办法筛查错误，一直重启Mac也不是好主意

我觉得Fcitx5的日志功能做的还可以，可以借鉴一下：
1、不需要3个文件，可以融为一个文件（这个不是重点，3个文件也没关系）
2、Fcitx5的日志文件只有在重启等一些时候才会重置，但是在开机期间，会一直存在，不会消失（关键所在）

**預期行爲：**
希望大佬将日志这一块加强一下，不要在正常运行时莫名其妙消失，而且不再恢复就行

**實際行爲：**
莫名消失，只显示不能打开的软链接文件，不重启就不再重新显示
<img width="223" alt="截屏2024-06-19 08 51 14" src="https://github.com/rime/squirrel/assets/117334130/2d8401f6-2d40-468d-a51d-ed0ca5dc8d3a">

**環境**
 - 系統版本： (macOS 14.5)
 - 鼠鬚管版本： (1.0.2)
 - 方案： (雾凇)

**我試過：**
  - [ ] 我換了內置的方案（如`朙月拼音`）後問題仍存在

**Comment by LEOYoon-Tsaw** [comment]
日誌是librime控制的，前端不管

**Comment by ksqsf** [comment]
在这个问题彻底解决之前的 workaround：在终端启动 Squirrel，日志会印到 stderr 上

```bash
/Library/Input\ Methods/Squirrel.app/Contents/MacOS/Squirrel --quit && /Library/Input\ Methods/Squirrel.app/Contents/MacOS/Squirrel
```
