### ISSUE TITLE
0.9.26.1无法激活地球拼音

### ISSUE THREAD

**Issue by liangqi** [rime/squirrel#95]
OS X 10.11.3，安装了0.9.26.1之后，方案菜单中只有“明月拼音 台湾正体”、“中半汉。”、“明月拼音”、“明月拼音 简化字”、“明月拼音 语句流”和“仓颉”。没有“地球拼音”选项。

在/Library/Input Methods/Squirrel.app/Contents/SharedSupport中发现了terra_pinyin.dict.yaml和terra_pinyin.schema.yaml。

并且/Users/liangqi/Library/Rime中没有这两个文件，自行复制后，没有效果。重启Squirrel以及登出后再登入，都没有效果。

**Comment by lotem** [comment]
这样子不行。
不是所有的方案都加载，不经济，耗资源。
按需要来，挑选方案，写入配置。

**Comment by liangqi** [comment]
麻烦问一下怎样才行呀？

**Comment by lotem** [comment]
手机上操作不便。还没写完的：
地球拼音默认未启用。
选方案需要修改这项配置
https://github.com/rime/home/wiki/CustomizationGuide#%E5%9C%A8%E6%96%B9%E6%A1%88%E9%81%B8%E5%96%AE%E4%B8%AD%E6%B7%BB%E5%8A%A0%E4%BA%94%E7%AD%86%E9%9B%99%E6%8B%BC

**Comment by liangqi** [comment]
好像编辑/Users/liangqi/Library/Rime/default.yaml，在schema_list一节中加入“  - schema: terra_pinyin”一行，就有些效果了。
