### ISSUE TITLE
[Bug] 在firefox的perplexity.ai网站上候选词无法上屏

### ISSUE THREAD

**Issue by 1997cui** [rime/squirrel#950]
**簡要描述 Bug：**
视频见下面，具体而言，使用Firefox在perplexity.ai上使用时，候选框能正确弹出，但按“1”后候选框消失，但候选项并没有上屏，反而是拼音+空格上屏了。

https://github.com/rime/squirrel/assets/5462776/d90de1d4-e61a-411f-9007-2102d9c8ac57

**預期行爲：**

候选词上屏。

**實際行爲：**

候选词没上屏。

**環境**
 - 系統版本： (macOS 14.5)
 - 鼠鬚管版本： (1.0.2)
 - 方案： (如果你用的是自定義或第三方的方案，且該 Bug 可能與方案有關，請提供方案鏈接)
[雾凇拼音](https://github.com/iDvel/rime-ice)

**我試過：**
  - [ ] 我換了內置的方案（如`朙月拼音`）後問題仍存在
    雾凇拼音会禁用内置方案，所以没法测试，但我附上了我现在在用的配置文件
    [squirrel.yaml.txt](https://github.com/user-attachments/files/15919130/squirrel.yaml.txt)
  - [ ] 我找到了導致問題出現的具體設置： (何設置？)
  - [x] 這是個新 Bug，以前真的沒有
  - [ ] 我對原因有一些猜想： (你的寳貴想法)
  - [x] 在 Issues（包括已關閉的 Issue） 中未找到相關的報告

**Comment by ksqsf** [comment]
Reproduced in Firefox. Not reproduced in Chrome and Safari.

**Comment by LEOYoon-Tsaw** [comment]
既然是Firefox在特定網站上的bug⋯

**Comment by 1997cui** [comment]
> 既然是Firefox在特定網站上的bug⋯還是多問一句，系統輸入法是什麼表現？

巧了，我刚刚用MacOS的默认输入法试了一下，也是坏的，所以我现在怀疑是这个网站坏了。

**Comment by hairuo** [comment]
遇到同样的问题，Firefox 中无法上屏，Chrome可以。
系统： Windows 11
Firefox: 127.0.1 (64-bit)
Chrome: 126.0.6478.127 (Official Build) (64-bit)
