### ISSUE TITLE
squirrel.custom.yaml下配置patch/stype/horizontal: true 不能水平展示候选词

### ISSUE THREAD

**Issue by Lucius-Wang** [rime/squirrel#952]
**簡要描述 Bug：**
~~我其實沒有遇到Bug~~

**預期行爲：**
候选词水平展示
**實際行爲：**
候选词依然垂直展示
**環境**
 - 系統版本： (macOS 14.5)
 - 鼠鬚管版本： (1.0.2)
 - 方案： (如果你用的是自定義或第三方的方案，且該 Bug 可能與方案有關，請提供方案鏈接)
 - [ ] 使用了 Lua： (用了甚麼 Lua 腳本？)
 - [ ] 與其它 App 有關： (哪個 App？)

**我試過：**
  - [ ] 我換了內置的方案（如`朙月拼音`）後問題仍存在
  - [ ] 我找到了導致問題出現的具體設置： (何設置？)
  - [ ] 這是個新 Bug，以前真的沒有
  - [ ] 我對原因有一些猜想： (你的寳貴想法)
  - [ ] 在 Issues（包括已關閉的 Issue） 中未找到相關的報告

**Comment by ksqsf** [comment]
horizontal 支持已移除。请参考 https://github.com/rime/squirrel/releases/tag/1.0.0

**Comment by Lucius-Wang** [comment]
> horizontal 支持已移除。请参考 https://github.com/rime/squirrel/releases/tag/1.0.0

感谢！完美解决了
