### ISSUE TITLE
[Bug] 每次开机都会重新部署

### ISSUE THREAD

**Issue by thep0y** [rime/squirrel#954]
**簡要描述 Bug：**
1.0.2版本每次开机都会重新部署。

**預期行爲：**
应与之前的版本一样，当用户配置未改变时不重新部署。

**實際行爲：**

**環境**
 - 系統版本： (macOS 14.5)
 - 鼠鬚管版本： (1.0.2)
 - 方案：
   - 词库：https://github.com/thep0y/rime-98/tree/master/dist
   - 皮肤：https://github.com/thep0y/rime-98/blob/master/themes/squirrel.custom.yaml

**我試過：**
  - [x] 這是個新 Bug，以前真的沒有

**Comment by LEOYoon-Tsaw** [comment]
不部署怎麼知道有沒有改東西呢，現在是啟動輸入法時部署，如果沒改東西部署是很快的

**Comment by thep0y** [comment]
可以计算用户所有配置文件的 md5，部署后保存这个 md5，在下次开机部署前对比 md5 是否有变化，有变化才部署。

**Comment by lotem** [comment]
> 可以计算用户所有配置文件的 md5，部署后保存这个 md5，在下次开机部署前对比 md5 是否有变化，有变化才部署。

部署時候會計算的。內容沒變化就不會重做文件。

是否啓動部署流程會看用戶文件夾的修改時間。

**Comment by thep0y** [comment]
> > 可以计算用户所有配置文件的 md5，部署后保存这个 md5，在下次开机部署前对比 md5 是否有变化，有变化才部署。
> 
> 部署時候會計算的。內容沒變化就不會重做文件。
> 
> 是否啓動部署流程會看用戶文件夾的修改時間。

通过目录时间判断也是合理的，但目前 squirrel 在开机后的部署会占用可明显感知的时间，**接近秒级**，在部署完成前无法输入文字。

如果仅是比较目录的修改时间我想应该不会需要耗费太长时间，几微秒就可以跳过部署，之前的 squirrel 版本中没有发现这个问题，开机、切换到 squirrel、到输入文字没有可感知的时间消耗。

而且如果目录未变化，不需要重新部署，不应该弹出系统通知提示部署完成，而是应该跳过部署。

**Comment by fxliang** [comment]
也有可能是不是加了什么方案脚本改方案或者词典内容了？

**Comment by lotem** [comment]
我沒觀察到這樣的問題。
請用默認的配置試試吧。

**Comment by thep0y** [comment]
> 我沒觀察到這樣的問題。 請用默認的配置試試吧。
> 
> 好的，通知中心有一條 Ready 的消息。可能是太快完成了，沒看到過彈出消息氣泡。

最近几天我试了几次，这个问题不是必然出现的，未发现能复现的步骤。

**Comment by eiqli-zhao** [comment]
我也遇到了  只要macOS 重启或者开机 ，输入法会自动重新部署，希望能改到我没修改的时候不要重新自动部署

**Comment by vstar37** [comment]
同样，我是刚开机没部署 开始打字就部署。造成无法立即输入，给人一种阻塞感。
