### ISSUE TITLE
「求助」升级到1.0.2后，无法调整至横向显示，老版本是好的

### ISSUE THREAD

**Issue by Joey0217** [rime/squirrel#956]
<img width="632" alt="image" src="https://github.com/rime/squirrel/assets/36755962/342da33f-cc4a-45c6-98ea-194bfe86fa24">
在squirrel.yaml文件中，已经把style和皮肤字段都设置了横向

style：
text_orientation: horizontal  # horizontal | vertical

皮肤：
horizontal: true             # true横排，false竖排
尝试过删除此条语句，也无效

感谢

**Comment by LEOYoon-Tsaw** [comment]
text_orientation: horizontal 確實是橫排（和英文一樣），vertical是傳統中文的豎排

完整的選項在這裡有：https://github.com/rime/squirrel/wiki/squirrel.yaml-%E9%85%8D%E7%BD%AE%E6%8C%87%E5%8D%97

你想要的可能是candidate_layout: linear

**Comment by Joey0217** [comment]
> text_orientation: horizontal 確實是橫排（和英文一樣），vertical是傳統中文的豎排
> 
> 完整的選項在這裡有：https://github.com/rime/squirrel/wiki/squirrel.yaml-%E9%85%8D%E7%BD%AE%E6%8C%87%E5%8D%97
> 
> 你想要的可能是candidate_layout: linear

感谢，加上了candidate_list_layout:  linear，变成横排了

**Comment by chanqii** [comment]
<img width="365" alt="image" src="https://github.com/user-attachments/assets/7f0e9b34-f7e8-4c26-adb4-f16ab8694d61">
为什么我的加了这个配置后这样显示candidate_list_layout: linear

**Comment by Tecon** [comment]
> <img alt="image" width="365" src="https://private-user-images.githubusercontent.com/9463120/357249930-7f0e9b34-f7e8-4c26-adb4-f16ab8694d61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMzI3MDIsIm5iZiI6MTczMTMzMjQwMiwicGF0aCI6Ii85NDYzMTIwLzM1NzI0OTkzMC03ZjBlOWIzNC1mN2U4LTRjMjYtYWRiNC1mMTZhYjg2OTRkNjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTFUMTM0MDAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGU1Y2NiODFiZGRkNmZjMDU5ZjQyYTNiNzQ0MGZhYmNkMjlhMjVkYTA4YzQwZThhMzU3YTg2NGI2NjczYjI4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.N_rYCQ1pegYVdpL7Lod244tq9rdVQFucEfZTVNTMJOM"> 为什么我的加了这个配置后这样显示candidate_list_layout: linear

你参考下上面发出来的配制说明，感觉和**text_orientation**这个配制项有关系

**Comment by mogocat** [comment]
> text_orientation: horizontal 確實是橫排（和英文一樣），vertical是傳統中文的豎排
> 
> 完整的選項在這裡有：https://github.com/rime/squirrel/wiki/squirrel.yaml-%E9%85%8D%E7%BD%AE%E6%8C%87%E5%8D%97
> 
> 你想要的可能是candidate_layout: linear

好用，感谢！
