### ISSUE TITLE
[Bug] 从苹果原生emoji面板切换后会无法使用，直到重新部署

### ISSUE THREAD

**Issue by ProudBenzene** [rime/squirrel#958]
**簡要描述 Bug：**

在输入框里，先按🌐+E，然后点击一个emoji输入，再然后输入法就会无法唤起，这时候点到其他输入框会显示正在重新部署，重新部署完成后才能继续使用。

 - 系統版本： (macOS 14.5)
 - 鼠鬚管版本： (1.0.2)
 - 方案： 雾凇拼音

**我試過：**

  - [x] 這是個新 Bug，以前真的沒有
  - [x] 在 Issues（包括已關閉的 Issue） 中未找到相關的報告

**Comment by LEOYoon-Tsaw** [comment]
確實，應該是切換後鼠鬚管進程就沒了（相當於切換了輸入法），點別的輸入框相當於重新打開鼠鬚管。

**Comment by jkhnfk** [comment]
我感觉我的更加频繁。都是只要切出去之后再切回来就有一定的几率触发，就得重新布署完才能再输入。也不知道什么原因。

**Comment by 0x2E** [comment]
Hi @ksqsf ，可以 release 这个修复吗？日常触发频率还挺高的
