### ISSUE TITLE
更新到1.02,存的皮肤都失效了怎么办？

### ISSUE THREAD

**Issue by zero-hugo** [rime/squirrel#959]
**簡要描述 Bug：**
刚升级到1.02,然后一开始皮肤还有的，但本来我说横向排列的，升级后变成了纵向，然后我根据网站上的信息，添加了一行candidate_list_layout: stack/linear，然后皮肤就调用不了了。

**預期行爲：**

**實際行爲：**

**環境**
 - 系統版本： (macOS 14.5)
 - 鼠鬚管版本： (1.0.2)

**Comment by ksqsf** [comment]
可能是修改的时候yaml格式改错了

**Comment by LEOYoon-Tsaw** [comment]
andidate_list_layout: stack/linear
stack和linear你得選一個吧，兩個都寫上怕是不太妥當
