### ISSUE TITLE
[Bug] 我其實沒有遇到Bug

### ISSUE THREAD

**Issue by paomian** [rime/squirrel#960]
**簡要描述 Bug：**
0.16.2 升级到 1.0.2 时，下载后显示
<img width="274" alt="image" src="https://github.com/rime/squirrel/assets/2999156/1c4fa285-28a0-4c5a-8553-e7a9c17ef712">

**預期行爲：**
升级成功
**實際行爲：**
升级失败
**環境**
 - 系統版本： (macOS 14.5)
 - 鼠鬚管版本： (0.16.2)
 - 方案： (如果你用的是自定義或第三方的方案，且該 Bug 可能與方案有關，請提供方案鏈接)
 - [ ] 使用了 Lua： (用了甚麼 Lua 腳本？)
 - [ ] 與其它 App 有關： (哪個 App？)

**我試過：**
  - [ ] 我換了內置的方案（如`朙月拼音`）後問題仍存在
  - [ ] 我找到了導致問題出現的具體設置： (何設置？)
  - [ ] 這是個新 Bug，以前真的沒有
  - [ ] 我對原因有一些猜想： (你的寳貴想法)
  - [x] 在 Issues（包括已關閉的 Issue） 中未找到相關的報告

**Comment by LEOYoon-Tsaw** [comment]
0.16不能自動升級，請手動安裝升級
