### ISSUE TITLE
build fail 编译失败

### ISSUE THREAD

**Issue by msxfXF** [rime/squirrel#962]
`** BUILD FAILED **

The following build commands failed:
	Copy /Users/xf/squirrel/build/Build/Products/Release/Squirrel.app/Contents/Frameworks/rime-plugins/librime-octagram.dylib /Users/xf/squirrel/lib/rime-plugins/librime-octagram.dylib (in target 'Squirrel' from project 'Squirrel')
	Copy /Users/xf/squirrel/build/Build/Products/Release/Squirrel.app/Contents/Frameworks/rime-plugins/librime-lua.dylib /Users/xf/squirrel/lib/rime-plugins/librime-lua.dylib (in target 'Squirrel' from project 'Squirrel')
	Copy /Users/xf/squirrel/build/Build/Products/Release/Squirrel.app/Contents/Frameworks/rime-plugins/librime-predict.dylib /Users/xf/squirrel/lib/rime-plugins/librime-predict.dylib (in target 'Squirrel' from project 'Squirrel')
(3 failures)
`

cmake version 3.30.0

**Comment by LEOYoon-Tsaw** [comment]
把這三個插件放進librime/plugin，或者去掉他們
