### ISSUE TITLE
[Bug] macOS 12.7.5安裝1.0.2失败

### ISSUE THREAD

**Issue by code-moritz** [rime/squirrel#964]
**簡要描述 Bug：**
~~我其實沒有遇到Bug~~
1.0.2的版本安裝時報錯，安裝不成功。

**預期行爲：**
可以正常安裝成功。

**實際行爲：**
<img width="624" alt="Screen Shot 2024-07-18 at 23 18 34" src="https://github.com/user-attachments/assets/4070f98e-6193-4375-b27b-d0375aa7e0b0">

**環境**
 - 系統版本： (macOS 12.7.5)
 - 鼠鬚管版本： (1.0.2)
 - 方案： 使用官方app安裝
 
**我試過：**
  - [ ] 我換了內置的方案（如`朙月拼音`）後問題仍存在
  - [ ] 我找到了導致問題出現的具體設置： (何設置？)
  - [x ] 這是個新 Bug，以前真的沒有
  - [ ] 我對原因有一些猜想： (你的寳貴想法)
  - [ ] 在 Issues（包括已關閉的 Issue） 中未找到相關的報告

**Comment by ksqsf** [comment]
https://github.com/rime/squirrel?tab=readme-ov-file#%E5%AE%89%E8%A3%9D%E8%BC%B8%E5%85%A5%E6%B3%95

現已不再支持 macOS <13 的版本
