### ISSUE TITLE
[优化] 建议增加一个按钮，用于选择要读取的用户目录路径

### ISSUE THREAD

**Issue by Dr-Octopus-dev** [rime/squirrel#967]

**Comment by lotem** [comment]
Squirrel.app 需要有個保存應用程序配置的文件夾，在 Mac 上就是這裏：`~/Library/Rime`。
假設用戶可以選擇不同的路徑，那麼也需要在一個固定的位置保存用戶選取的路徑，因此，不使用 `~/Library/Rime` 是做不到的。
至少 `~/Library/Rime` 也得是個符號鏈接。
