### ISSUE TITLE
怎么设置才能尽量与mac系统原来的使用习惯相近

### ISSUE THREAD

**Issue by Bedilatory** [rime/squirrel#968]
我习惯用Caps_Lock来切换ABC与中文输入法，并且切换大小写也习惯长按Caps_Lock，所以没有取消系统偏好【使用大写锁定键切换“ABC”输入法】，现在遇到的问题是当我在squirrel中文下输入英文时，此时按下Caps_Lock后切换到ABC，想要将刚刚输入的英文上屏，但是实际发生的是英文被清空了，我应该怎么配置才能生。
<img width="506" alt="image" src="https://github.com/user-attachments/assets/a5ca81de-fb01-4d95-a995-9ac275e7e600">
此外有没有啥配置可以阻止在squirrel中文的情况下按shift将squirrel变成英文模式，因为平常英文还是用ABC比较多，所以想禁止shift切换squirrel的中英文，squirrel始终用来输入中文

**Comment by lotem** [comment]
Rime 只能實現處理按鍵，並在 Rime 輸入法的各個狀態之間切換。ABC 是系統提供的另一個鍵盤。

僅當操作系統不處理 Caps Lock 鍵、交給輸入法處理時，纔會有如圖配置中定義的行爲。

**Comment by LEOYoon-Tsaw** [comment]
第二個如果不想在鼠鬚管中輸入英文，可以刪去ascii_translator

**Comment by Bedilatory** [comment]
> 第二個如果不想在鼠鬚管中輸入英文，可以自方案中刪去ascii_composer

所以就是我无法在切换ABC的时候保留待输入的英文，是这样理解的把。
那我如果将【使用大写锁定键切换“ABC”输入法】取消掉，然后全部的中英文都用Rime，能不能实现通过Caps_Lock实现中英文的切换，我尝试了一下使用Caps_Lock切换英文，Rime始终会将英文切换成大写，Caps_Lock长按的功能也无法使用。
刚刚查了一下长按功能似乎是mac硬件上的限制吧，所以Rime无法使用长按切换成大写。
所以总的来说，Rime在mac上的操作习惯更像Windows一样，Caps_Lock来切换大写，然后shift切换小写英文和中文，是我这样理解的吧

**Comment by LEOYoon-Tsaw** [comment]
Caps_Lock是個硬件，可以讀到它狀態改變，也許可以加計時器？你可以改改代碼試試

我自己只用Rime輸入中文，所以去掉了ascii_composer。英文通過按語言鍵切換到ABC輸入

**Comment by Bedilatory** [comment]
> Caps_Lock是個硬件，可以讀到它狀態改變，也許可以加計時器？你可以改改代碼試試
> 
> 我自己只用Rime輸入中文，所以去掉了ascii_composer。英文通過按語言鍵切換到ABC輸入

目前我也像你这样设置了，习惯了mac原来的操作方式，但是这样在Rime中文的情况下，输入英文单词不敲回车键的情况下，直接输入Caps_Lock切换成ABC，此时刚刚候选的英文单词就直接被清空，这种情况是不是就没有解决办法了

**Comment by LEOYoon-Tsaw** [comment]
換輸入法了，一般意味著之前的輸入無效，這沒毛病

**Comment by LEOYoon-Tsaw** [comment]
https://github.com/user-attachments/assets/ad298447-7551-4e11-9f60-66c5c9029cfa

我這邊是會直接上屏的，不知道你爲何不行

**Comment by Bedilatory** [comment]
> Screen.Recording.2024-08-01.at.22.05.31.mov 
> 我這邊是會直接上屏的，不知道你爲何不行

https://github.com/user-attachments/assets/e5584fa8-ba32-45de-8d3f-fbb8a1cca661

我这里就是这样的，很奇怪
![image](https://github.com/user-attachments/assets/c066b20f-c00f-4706-9d05-4202849b1982)
配置也是从别人那搬运过来的，我看了下似乎也不会影响我这个问题，是不是需要我重新安装一下，或者是我mac系统版本的问题？我把所有自定义的配置全部注释掉然后重新部署也是会出现清空的问题，或者是不是我用了【雾凇拼音】这个库的原因？
