### ISSUE TITLE
[Bug] PHPstorm 中英文输入法 会出现中文候选文字框

### ISSUE THREAD

**Issue by marunrun** [rime/squirrel#973]
**簡要描述 Bug：**

如视频所示，在phpstorm中 使用鼠须管英文输入法，输入英文的时候在左下角出现中文的候选文字框？

怀疑是代码提示导致的

但更换了JetBrains 家其他的ide， 例如 goland， idea 等都未复现， 只有PhpStorm中出现。

**預期行爲：**

**實際行爲：**

https://github.com/user-attachments/assets/a003c0ed-84ff-481d-bcb3-7756b1306417

**環境**
 - 系統版本： (macOS 14.5)
 - 鼠鬚管版本： (1.0.2)
 - 方案： 白霜拼音

**我試過：**
  - [ ] 我換了內置的方案（如`朙月拼音`）後問題仍存在
  - [ ] 我找到了導致問題出現的具體設置： (何設置？)
  - [ ] 這是個新 Bug，以前真的沒有
  - [ ] 我對原因有一些猜想： (你的寳貴想法)
  - [ ] 在 Issues（包括已關閉的 Issue） 中未找到相關的報告

**Comment by ksqsf** [comment]
> 但更换了JetBrains 家其他的ide， 例如 goland， idea 等都未复现， 只有PhpStorm中出现。

JetBrains 的 IDE 均是基于同一平台实现，因此可能是 PHPStorm 自身特有问题，请考虑检查配置或向 JetBrains 反馈。

**Comment by marunrun** [comment]
> > 但更换了JetBrains 家其他的ide， 例如 goland， idea 等都未复现， 只有PhpStorm中出现。
> 
> JetBrains 的 IDE 均是基于同一平台实现，因此可能是 PHPStorm 自身特有问题，请考虑检查配置或向 JetBrains 反馈。

ok 我重新安装PhpStorm就可以了。
