### ISSUE TITLE
[Bug] 无法在NotepadNext 软件里输入，连删除都不行

### ISSUE THREAD

**Issue by erdong01** [rime/squirrel#974]
**簡要描述 Bug：**
NotepadNext 版本：0.8
无法使用输入法

 

**環境**
 - 系統版本：macOs 15.0
 - 鼠鬚管版本： 1.0.2

**Comment by jiashie** [comment]
解决了吗？我也遇到同样的问题，
鼠须管 1.0.3
notepadNext 0.12
