### ISSUE TITLE
候选框在Google doc中不能随光标移到

### ISSUE THREAD

**Issue by Junbin6** [rime/squirrel#975]
**簡要描述 Bug：**
使用google doc的时候文字输入框在浏览器左上角，而不在网页内部。
**預期行爲：**
候选框跟随光标移到
**實際行爲：**
候选框固定在浏览器左上角
<img width="567" alt="image" src="https://github.com/user-attachments/assets/e3744dbe-80ea-4550-b0c7-8d0faaff5f6f">

**環境**
 - 系統版本： (macOS 13.5)
 - 鼠鬚管版本： (1.0.2)
 - 方案： (如果你用的是自定義或第三方的方案，且該 Bug 可能與方案有關，請提供方案鏈接)
 - [ ] 使用了 Lua： (用了甚麼 Lua 腳本？)
 - [ ] 與其它 App 有關： (哪個 App？)

**我試過：**
  - [ ] 我換了內置的方案（如`朙月拼音`）後問題仍存在
  - [ ] 我找到了導致問題出現的具體設置： (何設置？)
  - [ ] 這是個新 Bug，以前真的沒有
  - [ ] 我對原因有一些猜想： (你的寳貴想法)
  - [ ] 在 Issues（包括已關閉的 Issue） 中未找到相關的報告

**Comment by ksqsf** [comment]
duplicate of https://github.com/rime/squirrel/issues/345
