### ISSUE TITLE
鼠须管无法在tkinter控件中输入中文

### ISSUE THREAD

**Issue by etern** [rime/squirrel#976]
python的tkinter GUI库，弹出文本框。
切换到鼠须管，无法输入中文，只能输入英文。

我的中英文切换键是Shift_R: commit_code，在tkinter文本框中无效，在vscode中有效。

对比：切换到系统自带拼音输入法，在tkinter文本框中，可以输入中文

---
复现方法：用这一行代码可以弹出tkinter文本框：

`python -c 'import tkinter as tk; from tkinter import simpledialog; root = tk.Tk(); root.withdraw(); print(simpledialog.askstring("",""))'`

---
macos sonama 14.6.1
鼠须管1.0.2
使用配置 https://github.com/iDvel/rime-ice  快捷键稍有改动

**Comment by ksqsf** [comment]
（已迻动到鼠须管仓库）

macOS 14.6.1未能复现：

https://github.com/user-attachments/assets/a26e1496-a297-4369-8d4c-e98b67eda369

**Comment by etern** [comment]
我这边是无效的，切到输入框之后，Shift_R切换中英完全没反应。在vscode里，Shift_R切换中英就有个小图标。

https://github.com/user-attachments/assets/1deb14bf-1dbe-4ed1-9ba8-416e94e15717

有其他朋友看到，也请帮忙试试能否复现。

**Comment by ksqsf** [comment]
可能与 #977 是同一个问题

**Comment by etern** [comment]
确认了是同一个问题，更新到pre-release版本，问题解决了。
