### ISSUE TITLE
请问应如何使用`?`作为反查的引导符号？

### ISSUE THREAD

**Issue by yett1873** [rime/squirrel#978]
如图所示，因backtick太过常用，试换用`?`作为拼音反查的引导。实际使用中，如果使用这个pattern`^?[a-z]*$`则没有效果，按`?`直接上屏。如果使用这个pattern`^\?[a-z]*$`把问号escape掉，则部署失败。请问应如何实现想要的效果呢？望大佬指导🙇‍♀️
![image](https://github.com/user-attachments/assets/4cf327a4-1614-4bb4-bd82-fe6594422a2e)

**Comment by ksqsf** [comment]
> 部署失败

把双引号改成单引号，或者 \ 改成 \\ ?

**Comment by yett1873** [comment]
> 把双引号改成单引号，或者 `\` 改成 `\\` ?

改成`\\`就成功了，非常感谢！！🥰
