### ISSUE TITLE
编译源码的问题

### ISSUE THREAD

**Issue by songxing10000** [rime/squirrel#98]
已经照着说明做了，，到这一步

Build dependencies

Build librime, dependent third-party libraries and data files:

make deps

不知道怎么操作，在哪里输入make deps,直接在终端不对，求指教

**Comment by 1900forever** [comment]
要在终端下先cd到squirrel目录，再输入make deps

**Comment by songxing10000** [comment]
已经成功使用make deps ，原因是之前直接clone的，没有用git clone --recursive https://github.com/rime/squirrel.git

**Comment by amdth** [comment]
@songxing10000 请教一下该怎么编译，没有说明呢

**Comment by amdth** [comment]
可以使用debian来编译鼠须管吗？

**Comment by songxing10000** [comment]
@amdth 你跟着这个走，就能成功，https://github.com/rime/squirrel/blob/master/INSTALL.md
