### ISSUE TITLE
挂载搜狗用户自定义词库后, 输入单音节没有候选的问题

### ISSUE THREAD

**Issue by awaken233** [rime/squirrel#984]
将搜狗用户自定义词库导出, 深蓝转换导出后挂载该词库

导入的搜狗自定义词库选取部分如下,  大概有10w记录.

```
---
name: test1  # 词库名
version: "2023.11.09"  # 词库版本
sort: by_weight # 排序依据：按照权重
use_preset_vocabulary: true
...


吧啊	ba a	1
把把	ba ba	1
爸爸	ba ba	27
粑粑	ba ba	1
粑粑	ba ba	1
粑粑柑	ba ba gan	1
粑粑柑	ba ba gan	1
粑粑橘	ba ba ju	4
粑粑橘	ba ba ju	1
爸爸了然于心	ba ba liao ran yu xin	1
爸爸妈妈	ba ba ma ma	1
爸爸妈妈	ba ba ma ma	1
爸爸去哪儿	ba ba qu na er	1
爸爸去哪了	ba ba qu na le	1
爸爸一杀七	ba ba yi sha qi	1

```

挂载该词库后, 输入单音节, 没有出现预选, 我必须全音节输入才会出现候选, 如下:

![image](https://github.com/user-attachments/assets/2d0e9771-bbaf-4218-ba20-cf5049266c39)

取消挂载该词库, 输入单音节, 可以出现预选.

期望: 输入单音节, 可以出现预选

![image](https://github.com/user-attachments/assets/26831036-394f-4f59-bb9d-cdf1aad9b983)

我做出的尝试:
- use_preset_vocabulary 设置为 false, 不起作用

**Comment by lotem** [comment]
詞庫內容不正確。

**Comment by awaken233** [comment]
> 詞庫內容不正確。

请问大佬内容可能哪里出现问题呢？挂载这个词库仅仅是输入单音节不显示候选， 但是输入全拼还是有候选的。

词库项不能出现重复项吗？还是权重值范围有问题？
```
艾克	ai ke	1
艾克	ai ke	1
```


我是使用深蓝工具命令行导出的词库文件：

```
dotnet ImeWlConverterCmd.dll -i:sgpybin ./cibackup.bin -o:rime ./ci.txt
```

**Comment by lotem** [comment]
我看不到你的詞庫，你讓我怎麼告訴你哪裏出問題呢。

按道理，自然是輸入什麼編碼結果不對，就是那個編碼對應的數據有問題。
