### ISSUE TITLE
10.11.3, Xcode 7.2.1编译错误

### ISSUE THREAD

**Issue by 1900forever** [rime/squirrel#99]
按照https://github.com/rime/squirrel/blob/develop/INSTALL.md 的步骤，执行

> make deps

的时候报错如下：

`Undefined symbols for architecture x86_64:
  "snappy::RawCompress(char const*, unsigned long, char*, unsigned long*)", referenced from:
      leveldb::TableBuilder::WriteBlock(leveldb::BlockBuilder*, leveldb::BlockHandle*) in libleveldb.a(table_builder.o)
  "snappy::RawUncompress(char const*, unsigned long, char*)", referenced from:
      leveldb::ReadBlock(leveldb::RandomAccessFile*, leveldb::ReadOptions const&, leveldb::BlockHandle const&, leveldb::BlockContents*) in libleveldb.a(format.o)
  "snappy::MaxCompressedLength(unsigned long)", referenced from:
      leveldb::TableBuilder::WriteBlock(leveldb::BlockBuilder*, leveldb::BlockHandle*) in libleveldb.a(table_builder.o)
  "snappy::GetUncompressedLength(char const*, unsigned long, unsigned long*)", referenced from:
      leveldb::ReadBlock(leveldb::RandomAccessFile*, leveldb::ReadOptions const&, leveldb::BlockHandle const&, leveldb::BlockContents*) in libleveldb.a(format.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

cp -L librime/xbuild/lib/Release/librime.1.dylib lib/librime.1.dylib
cp: librime/xbuild/lib/Release/librime.1.dylib: No such file or directory
make: *** [librime] Error 1`

**Comment by jakwings** [comment]
是用的 homebrew 安裝的 boost 吗？可以試試：

```bash
brew unlink boost
brew install boost --cxx11
```

或者參考這裏手動編譯安裝 boost 的方法：
https://github.com/jakwings/librime/blob/travis-ci/.travis.yml#L27-L32

**Comment by 1900forever** [comment]
是用homebrew安装的boost，并且已经按照拟题痛得方法加了 -cxx11参数。同样是如下报错：

> 
ld: warning: directory not found for option '-L/Users/yan/src/squirrel/librime/thirdparty/lib/Release'
Undefined symbols for architecture x86_64:
  "snappy::RawCompress(char const*, unsigned long, char*, unsigned long*)", referenced from:
      leveldb::TableBuilder::WriteBlock(leveldb::BlockBuilder*, leveldb::BlockHandle*) in libleveldb.a(table_builder.o)
  "snappy::RawUncompress(char const*, unsigned long, char*)", referenced from:
      leveldb::ReadBlock(leveldb::RandomAccessFile*, leveldb::ReadOptions const&, leveldb::BlockHandle const&, leveldb::BlockContents*) in libleveldb.a(format.o)
  "snappy::MaxCompressedLength(unsigned long)", referenced from:
      leveldb::TableBuilder::WriteBlock(leveldb::BlockBuilder*, leveldb::BlockHandle*) in libleveldb.a(table_builder.o)
  "snappy::GetUncompressedLength(char const*, unsigned long, unsigned long*)", referenced from:
      leveldb::ReadBlock(leveldb::RandomAccessFile*, leveldb::ReadOptions const&, leveldb::BlockHandle const&, leveldb::BlockContents*) in libleveldb.a(format.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

cp -L librime/xbuild/lib/Release/librime.1.dylib lib/librime.1.dylib

**Comment by jakwings** [comment]
那自行編譯 boost 吧，上面給了方法了。

**Comment by lotem** [comment]
@jakwings 你確定跟 Boost 有關嘛？貼出的部分日誌顯示問題出在 leveldb。

感覺這裏有疑點
```
ld: warning: directory not found for option '-L/Users/yan/src/squirrel/librime/thirdparty/lib/Release'
```

**Comment by lotem** [comment]
如果不是 `brew install leveldb`，請排除 https://github.com/rime/squirrel/issues/98 這種情況。

**Comment by jakwings** [comment]
不太記得之前弄 Travis CI 時怎麼排查的了，好像是編譯選項不同導致的，關於 libc++ 和 libstdc++。
以前也有過同樣的求助 #72，聽說是重新編譯 boost 就好了，雖然不知是具體怎麼重新編譯。

**Comment by 1900forever** [comment]
升级到了Xcode7.3，报错内容还是一样。

我在另一台机器上全新安装了系统，homebrew和Xcode，按照INSTALL.md的步骤，可以完成正常编译，app大小仅有5MB左右。

不知道是哪里出了错。

**Comment by lotem** [comment]
請排除 #98 這種情況。

**Comment by jakwings** [comment]
剛在 Travis CI 試了下，應該不關 boost 的事。 :tongue:

**Comment by 1900forever** [comment]
并非 #98 的情况，我执行的命令是：

> 
git clone --recursive https://github.com/rime/squirrel.git
cd squirrel
make deps

**Comment by 1900forever** [comment]
尝试了直接编译librime，出现如下错误，应该与之前的错误相同：

> 
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/yan/src/squirrel/librime/xbuild
cd xbuild; xcodebuild -project rime.xcodeproj -configuration Release build | grep -v setenv | tee build.log
** BUILD FAILED **


The following build commands failed:
	Ld xbuild/lib/Release/librime.1.2.9.dylib normal x86_64
(1 failure)
=== BUILD AGGREGATE TARGET ZERO_CHECK OF PROJECT rime WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/yan/src/squirrel/librime/xbuild/rime.build/Release/ZERO_CHECK.build/Script-3A6A212246FA4A9E99974C82.sh
chmod 0755 /Users/yan/src/squirrel/librime/xbuild/rime.build/Release/ZERO_CHECK.build/Script-3A6A212246FA4A9E99974C82.sh

PhaseScriptExecution CMake\ Rules xbuild/rime.build/Release/ZERO_CHECK.build/Script-3A6A212246FA4A9E99974C82.sh
    cd /Users/yan/src/squirrel/librime
    /bin/sh -c /Users/yan/src/squirrel/librime/xbuild/rime.build/Release/ZERO_CHECK.build/Script-3A6A212246FA4A9E99974C82.sh
echo ""

make -f /Users/yan/src/squirrel/librime/xbuild/CMakeScripts/ReRunCMake.make
make[2]: `/Users/yan/src/squirrel/librime/xbuild/CMakeFiles/cmake.check_cache' is up to date.

=== BUILD TARGET rime OF PROJECT rime WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/yan/src/squirrel/librime/xbuild/src/rime.build/Release/rime.build/Script-4827FB65359444928199B1F7.sh
chmod 0755 /Users/yan/src/squirrel/librime/xbuild/src/rime.build/Release/rime.build/Script-4827FB65359444928199B1F7.sh

Ld xbuild/lib/Release/librime.1.2.9.dylib normal x86_64
    cd /Users/yan/src/squirrel/librime
    export MACOSX_DEPLOYMENT_TARGET=10.11
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -L/Users/yan/src/squirrel/librime/xbuild/lib/Release -L/usr/local/lib/Release -L/usr/local/lib -L/Users/yan/src/squirrel/librime/thirdparty/lib/Release -L/Users/yan/src/squirrel/librime/thirdparty/lib -F/Users/yan/src/squirrel/librime/xbuild/lib/Release -filelist /Users/yan/src/squirrel/librime/xbuild/src/rime.build/Release/rime.build/Objects-normal/x86_64/rime.1.2.9.LinkFileList -install_name /librime.1.2.9.dylib -mmacosx-version-min=10.11 -dynamiclib -Wl,-headerpad_max_install_names -install_name @rpath/librime.1.dylib /usr/local/lib/libboost_filesystem-mt.a /usr/local/lib/libboost_regex-mt.a /usr/local/lib/libboost_signals-mt.a /usr/local/lib/libboost_system-mt.a /usr/local/lib/libboost_locale-mt.a /Users/yan/src/squirrel/librime/thirdparty/lib/libglog.a /Users/yan/src/squirrel/librime/thirdparty/lib/libyaml-cpp.a /usr/local/lib/libgflags.dylib /usr/lib/libiconv.dylib /Users/yan/src/squirrel/librime/thirdparty/lib/libleveldb.a /Users/yan/src/squirrel/librime/thirdparty/lib/libmarisa.a /Users/yan/src/squirrel/librime/thirdparty/lib/libopencc.a -single_module -compatibility_version 1.0.0 -current_version 1.2.9 -Xlinker -dependency_info -Xlinker /Users/yan/src/squirrel/librime/xbuild/src/rime.build/Release/rime.build/Objects-normal/x86_64/rime.1.2.9_dependency_info.dat -o /Users/yan/src/squirrel/librime/xbuild/lib/Release/librime.1.2.9.dylib
ld: warning: directory not found for option '-L/Users/yan/src/squirrel/librime/thirdparty/lib/Release'
Undefined symbols for architecture x86_64:
  "snappy::RawCompress(char const*, unsigned long, char*, unsigned long*)", referenced from:
      leveldb::TableBuilder::WriteBlock(leveldb::BlockBuilder*, leveldb::BlockHandle*) in libleveldb.a(table_builder.o)
  "snappy::RawUncompress(char const*, unsigned long, char*)", referenced from:
      leveldb::ReadBlock(leveldb::RandomAccessFile*, leveldb::ReadOptions const&, leveldb::BlockHandle const&, leveldb::BlockContents*) in libleveldb.a(format.o)
  "snappy::MaxCompressedLength(unsigned long)", referenced from:
      leveldb::TableBuilder::WriteBlock(leveldb::BlockBuilder*, leveldb::BlockHandle*) in libleveldb.a(table_builder.o)
  "snappy::GetUncompressedLength(char const*, unsigned long, unsigned long*)", referenced from:
      leveldb::ReadBlock(leveldb::RandomAccessFile*, leveldb::ReadOptions const&, leveldb::BlockHandle const&, leveldb::BlockContents*) in libleveldb.a(format.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by lotem** [comment]
還是鏈接 leveldb 的問題。
貼出完整日誌看看。

**Comment by 1900forever** [comment]
22:17:41 $ make -f Makefile.xcode thirdparty/opencc
make -f Makefile.thirdparty opencc
cd thirdparty/src/opencc; mkdir -p build && \
	cd build && cmake \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DBUILD_SHARED_LIBS:BOOL=OFF \
	.. && \
	make
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/yan/src/squirrel/librime/thirdparty/src/opencc/build
[ 41%] Built target libopencc
[ 46%] Built target opencc_dict
[ 51%] Built target opencc_phrase_extract
[ 56%] Built target opencc
[100%] Built target Dictionaries
mkdir -p thirdparty/include/opencc
cp thirdparty/src/opencc/src/*.h* thirdparty/include/opencc/
cp thirdparty/src/opencc/build/src/libopencc.a thirdparty/lib/
mkdir -p thirdparty/data/opencc
cp thirdparty/src/opencc/data/config/*.json thirdparty/data/opencc/
cp thirdparty/src/opencc/build/data/*.ocd thirdparty/data/opencc/

yan at Yans-MacBook-Pro.local in [~/src/squirrel/librime]  on git:dc945bd ✔︎  (build) also clean t
22:17:43 $ make -f Makefile.xcode
mkdir -p xbuild
cd xbuild; cmake -G Xcode .. -DBUILD_STATIC=ON -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   filesystem
--   regex
--   signals
--   system
--   locale
-- Found gflags: /usr/local/lib/libgflags.dylib
-- Found glog: /Users/yan/src/squirrel/librime/thirdparty/lib/libglog.a
-- Found yaml-cpp: /Users/yan/src/squirrel/librime/thirdparty/lib/libyaml-cpp.a
-- Found leveldb: /Users/yan/src/squirrel/librime/thirdparty/lib/libleveldb.a
-- Found marisa: /Users/yan/src/squirrel/librime/thirdparty/lib/libmarisa.a
-- Found opencc: /Users/yan/src/squirrel/librime/thirdparty/lib/libopencc.a
-- Found X11/keysym.h at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Tk.framework/Headers/X11
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/yan/src/squirrel/librime/xbuild
cd xbuild; xcodebuild -project rime.xcodeproj -configuration Release build | grep -v setenv | tee build.log
** BUILD FAILED **


The following build commands failed:
	Ld xbuild/lib/Release/librime.1.2.9.dylib normal x86_64
(1 failure)
=== BUILD AGGREGATE TARGET ZERO_CHECK OF PROJECT rime WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/yan/src/squirrel/librime/xbuild/rime.build/Release/ZERO_CHECK.build/Script-3A6A212246FA4A9E99974C82.sh
chmod 0755 /Users/yan/src/squirrel/librime/xbuild/rime.build/Release/ZERO_CHECK.build/Script-3A6A212246FA4A9E99974C82.sh

PhaseScriptExecution CMake\ Rules xbuild/rime.build/Release/ZERO_CHECK.build/Script-3A6A212246FA4A9E99974C82.sh
    cd /Users/yan/src/squirrel/librime
    /bin/sh -c /Users/yan/src/squirrel/librime/xbuild/rime.build/Release/ZERO_CHECK.build/Script-3A6A212246FA4A9E99974C82.sh
echo ""

make -f /Users/yan/src/squirrel/librime/xbuild/CMakeScripts/ReRunCMake.make
make[2]: `/Users/yan/src/squirrel/librime/xbuild/CMakeFiles/cmake.check_cache' is up to date.

=== BUILD TARGET rime OF PROJECT rime WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/yan/src/squirrel/librime/xbuild/src/rime.build/Release/rime.build/Script-4827FB65359444928199B1F7.sh
chmod 0755 /Users/yan/src/squirrel/librime/xbuild/src/rime.build/Release/rime.build/Script-4827FB65359444928199B1F7.sh

Ld xbuild/lib/Release/librime.1.2.9.dylib normal x86_64
    cd /Users/yan/src/squirrel/librime
    export MACOSX_DEPLOYMENT_TARGET=10.11
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -L/Users/yan/src/squirrel/librime/xbuild/lib/Release -L/usr/local/lib/Release -L/usr/local/lib -L/Users/yan/src/squirrel/librime/thirdparty/lib/Release -L/Users/yan/src/squirrel/librime/thirdparty/lib -F/Users/yan/src/squirrel/librime/xbuild/lib/Release -filelist /Users/yan/src/squirrel/librime/xbuild/src/rime.build/Release/rime.build/Objects-normal/x86_64/rime.1.2.9.LinkFileList -install_name /librime.1.2.9.dylib -mmacosx-version-min=10.11 -dynamiclib -Wl,-headerpad_max_install_names -install_name @rpath/librime.1.dylib /usr/local/lib/libboost_filesystem-mt.a /usr/local/lib/libboost_regex-mt.a /usr/local/lib/libboost_signals-mt.a /usr/local/lib/libboost_system-mt.a /usr/local/lib/libboost_locale-mt.a /Users/yan/src/squirrel/librime/thirdparty/lib/libglog.a /Users/yan/src/squirrel/librime/thirdparty/lib/libyaml-cpp.a /usr/local/lib/libgflags.dylib /usr/lib/libiconv.dylib /Users/yan/src/squirrel/librime/thirdparty/lib/libleveldb.a /Users/yan/src/squirrel/librime/thirdparty/lib/libmarisa.a /Users/yan/src/squirrel/librime/thirdparty/lib/libopencc.a -single_module -compatibility_version 1.0.0 -current_version 1.2.9 -Xlinker -dependency_info -Xlinker /Users/yan/src/squirrel/librime/xbuild/src/rime.build/Release/rime.build/Objects-normal/x86_64/rime.1.2.9_dependency_info.dat -o /Users/yan/src/squirrel/librime/xbuild/lib/Release/librime.1.2.9.dylib
ld: warning: directory not found for option '-L/Users/yan/src/squirrel/librime/thirdparty/lib/Release'
Undefined symbols for architecture x86_64:
  "snappy::RawCompress(char const*, unsigned long, char*, unsigned long*)", referenced from:
      leveldb::TableBuilder::WriteBlock(leveldb::BlockBuilder*, leveldb::BlockHandle*) in libleveldb.a(table_builder.o)
  "snappy::RawUncompress(char const*, unsigned long, char*)", referenced from:
      leveldb::ReadBlock(leveldb::RandomAccessFile*, leveldb::ReadOptions const&, leveldb::BlockHandle const&, leveldb::BlockContents*) in libleveldb.a(format.o)
  "snappy::MaxCompressedLength(unsigned long)", referenced from:
      leveldb::TableBuilder::WriteBlock(leveldb::BlockBuilder*, leveldb::BlockHandle*) in libleveldb.a(table_builder.o)
  "snappy::GetUncompressedLength(char const*, unsigned long, unsigned long*)", referenced from:
      leveldb::ReadBlock(leveldb::RandomAccessFile*, leveldb::ReadOptions const&, leveldb::BlockHandle const&, leveldb::BlockContents*) in libleveldb.a(format.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by lotem** [comment]
有所發現。

`snappy::RawCompress` 的引用出自 https://github.com/rime/librime/blob/develop/thirdparty/src/leveldb/port/port_posix.h#L11
由 `SNAPPY` 開關選項控制條件編譯，

而 `SNAPPY` 選項在此設置
https://github.com/rime/librime/blob/develop/thirdparty/src/leveldb/build_detect_platform#L193
根據檢測頭文件 `<snappy.h>` 的結果打開了該編譯選項，說明該系統安裝了 snappy 壓縮算法庫，這是 leveldb 的一項可選依賴。
而鏈接錯誤表明系統中安裝的 snappy 庫其二進制文件是爲不同的編譯器/CPU 架構生成的。
這有可能通過其他軟件安裝上。比如 mongodb, leveldb （另行安裝的）等。

**Comment by osfans** [comment]
嗯，archlinux上leveldb中是默認打開snappy的。

**Comment by lotem** [comment]
用上 snappy 也可以。但需要二進制兼容。Squirrel 用的編譯選項 `clang++ -arch x86_64 -stdlib=libc++`。
我猜測該系統上的 snappy 庫是 gcc 編譯的？或是（@jakwings 提到）用的 `libstdc++`。

**Comment by 1900forever** [comment]
额，还需要我做什么吗……

**Comment by jakwings** [comment]
那樣的話，暫時 `brew unlink leveldb` 應該能解決，裝完後再 `brew link leveldb` 把文件鏈接回 `/usr/local`。

**Comment by jakwings** [comment]
好像說得不對，上面用的 leveldb.a 是在 thirdparty 文件夾的，應該是 `brew unlink snappy`？

**Comment by 1900forever** [comment]
删掉了193-202行之后，错误如下：

make -f Makefile.xcode
mkdir -p xbuild
cd xbuild; cmake -G Xcode .. -DBUILD_STATIC=ON -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   filesystem
--   regex
--   signals
--   system
--   locale
-- Found gflags: /usr/local/lib/libgflags.dylib
-- Found glog: /Users/yan/src/squirrel/librime/thirdparty/lib/libglog.a
-- Found yaml-cpp: /Users/yan/src/squirrel/librime/thirdparty/lib/libyaml-cpp.a
-- Found leveldb: /Users/yan/src/squirrel/librime/thirdparty/lib/libleveldb.a
-- Found marisa: /Users/yan/src/squirrel/librime/thirdparty/lib/libmarisa.a
-- Found opencc: /Users/yan/src/squirrel/librime/thirdparty/lib/libopencc.a
-- Found X11/keysym.h at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Tk.framework/Headers/X11
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/yan/src/squirrel/librime/xbuild
cd xbuild; xcodebuild -project rime.xcodeproj -configuration Release build | grep -v setenv | tee build.log
** BUILD FAILED **


The following build commands failed:
	Ld xbuild/lib/Release/librime.1.2.9.dylib normal x86_64
(1 failure)
=== BUILD AGGREGATE TARGET ZERO_CHECK OF PROJECT rime WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/yan/src/squirrel/librime/xbuild/rime.build/Release/ZERO_CHECK.build/Script-6C46FFBADFF0439694A24ECD.sh
chmod 0755 /Users/yan/src/squirrel/librime/xbuild/rime.build/Release/ZERO_CHECK.build/Script-6C46FFBADFF0439694A24ECD.sh

PhaseScriptExecution CMake\ Rules xbuild/rime.build/Release/ZERO_CHECK.build/Script-6C46FFBADFF0439694A24ECD.sh
    cd /Users/yan/src/squirrel/librime
    /bin/sh -c /Users/yan/src/squirrel/librime/xbuild/rime.build/Release/ZERO_CHECK.build/Script-6C46FFBADFF0439694A24ECD.sh
echo ""

make -f /Users/yan/src/squirrel/librime/xbuild/CMakeScripts/ReRunCMake.make
make[2]: `/Users/yan/src/squirrel/librime/xbuild/CMakeFiles/cmake.check_cache' is up to date.

=== BUILD TARGET rime OF PROJECT rime WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/yan/src/squirrel/librime/xbuild/src/rime.build/Release/rime.build/Script-C68E3B6DA2CB4958B89A5DF4.sh
chmod 0755 /Users/yan/src/squirrel/librime/xbuild/src/rime.build/Release/rime.build/Script-C68E3B6DA2CB4958B89A5DF4.sh

Ld xbuild/lib/Release/librime.1.2.9.dylib normal x86_64
    cd /Users/yan/src/squirrel/librime
    export MACOSX_DEPLOYMENT_TARGET=10.11
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -L/Users/yan/src/squirrel/librime/xbuild/lib/Release -L/usr/local/lib/Release -L/usr/local/lib -L/Users/yan/src/squirrel/librime/thirdparty/lib/Release -L/Users/yan/src/squirrel/librime/thirdparty/lib -F/Users/yan/src/squirrel/librime/xbuild/lib/Release -filelist /Users/yan/src/squirrel/librime/xbuild/src/rime.build/Release/rime.build/Objects-normal/x86_64/rime.1.2.9.LinkFileList -install_name /librime.1.2.9.dylib -mmacosx-version-min=10.11 -dynamiclib -Wl,-headerpad_max_install_names -install_name @rpath/librime.1.dylib /usr/local/lib/libboost_filesystem-mt.a /usr/local/lib/libboost_regex-mt.a /usr/local/lib/libboost_signals-mt.a /usr/local/lib/libboost_system-mt.a /usr/local/lib/libboost_locale-mt.a /Users/yan/src/squirrel/librime/thirdparty/lib/libglog.a /Users/yan/src/squirrel/librime/thirdparty/lib/libyaml-cpp.a /usr/local/lib/libgflags.dylib /usr/lib/libiconv.dylib /Users/yan/src/squirrel/librime/thirdparty/lib/libleveldb.a /Users/yan/src/squirrel/librime/thirdparty/lib/libmarisa.a /Users/yan/src/squirrel/librime/thirdparty/lib/libopencc.a -single_module -compatibility_version 1.0.0 -current_version 1.2.9 -Xlinker -dependency_info -Xlinker /Users/yan/src/squirrel/librime/xbuild/src/rime.build/Release/rime.build/Objects-normal/x86_64/rime.1.2.9_dependency_info.dat -o /Users/yan/src/squirrel/librime/xbuild/lib/Release/librime.1.2.9.dylib
ld: warning: directory not found for option '-L/Users/yan/src/squirrel/librime/thirdparty/lib/Release'
Undefined symbols for architecture x86_64:
  "snappy::RawCompress(char const*, unsigned long, char*, unsigned long*)", referenced from:
      leveldb::TableBuilder::WriteBlock(leveldb::BlockBuilder*, leveldb::BlockHandle*) in libleveldb.a(table_builder.o)
  "snappy::RawUncompress(char const*, unsigned long, char*)", referenced from:
      leveldb::ReadBlock(leveldb::RandomAccessFile*, leveldb::ReadOptions const&, leveldb::BlockHandle const&, leveldb::BlockContents*) in libleveldb.a(format.o)
  "snappy::MaxCompressedLength(unsigned long)", referenced from:
      leveldb::TableBuilder::WriteBlock(leveldb::BlockBuilder*, leveldb::BlockHandle*) in libleveldb.a(table_builder.o)
  "snappy::GetUncompressedLength(char const*, unsigned long, unsigned long*)", referenced from:
      leveldb::ReadBlock(leveldb::RandomAccessFile*, leveldb::ReadOptions const&, leveldb::BlockHandle const&, leveldb::BlockContents*) in libleveldb.a(format.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jakwings** [comment]
改完後你有 `make clean` 再 `make deps` 嗎？

**Comment by 1900forever** [comment]
有的

**Comment by jakwings** [comment]
奇怪啊。我用 Homebrew 的 snappy 能重現問題：
https://travis-ci.org/jakwings/squirrel/builds/119152446#L1551-L1571
然後修改 leveldb 的 build_detect_platform 搞定：
https://travis-ci.org/jakwings/squirrel/builds/119164788

你再查查日誌看編譯 leveldb 時有沒有出現 `-DSNAPPY` 或 `-lsnappy`，另外查清楚 snappy 哪來的，只要能排除掉它就好了。

**Comment by jakwings** [comment]
原來是 librime 的緩存沒清理乾淨，`rm librime/thirdparty/lib/*` 就好。

**Comment by qfdk** [comment]
好了，我找到了最简单的方法 应该是brew自动安装了一些奇怪的东西。
`brew uninstall snappy`
之后重新编译就好了。谢谢
