### ISSUE TITLE
反斜杠候选如何屏蔽，我期望直接上屏，如何配置

### ISSUE THREAD

**Issue by awaken233** [rime/squirrel#992]
![image](https://github.com/user-attachments/assets/91ec92c4-4cda-4ff0-9cf2-8611e14f09b0)

我期望直接上屏【

请教这个如何配置？

**Comment by ksqsf** [comment]
Rime 官方方案：修改 symbols.yaml。其他方案请咨询对应方案作者或查阅说明书。
