### ISSUE TITLE
[Bug] 升级到MacOS 15.1系统后，输入英文或数字会默认切换成全角输入方式。

### ISSUE THREAD

**Issue by ToutLee** [rime/squirrel#994]
场景1：输入英文单词点击回车或空格，上屏是全角字母。
场景2：输入数字，直接上屏全角数字。
背景：在不同的软件浏览器下都会出现这个场景，且仅在第一次输入的时候会遇到，手动切换了全半角格式后，不再触发。关掉页面重新打开后会复现。

**Comment by LEOYoon-Tsaw** [comment]
無法復現

**Comment by ToutLee** [comment]
卸载重装之后，输入法恢复正常了。
