### ISSUE TITLE
[Bug] 我其實沒有遇到Bug

### ISSUE THREAD

**Issue by lifei** [rime/squirrel#996]
**簡要描述 Bug：**
Neovide下无法输出中文标点符号：。；【】『』「」

**預期行爲：**

在Neovide App下输入中文表单。

**實際行爲：**

只能输入英文标点。

**環境**
 - 系統版本： (macOS 14.5)
 - 鼠鬚管版本： (1.0.0)
 - 方案： (如果你用的是自定義或第三方的方案，且該 Bug 可能與方案有關，請提供方案鏈接)
 - [ ] 使用了 Lua： (用了甚麼 Lua 腳本？)
 - [ ] 與其它 App 有關： (哪個 App？)

**我試過：**
  - [ ] 我換了內置的方案（如`朙月拼音`）後問題仍存在
  - [ ] 我找到了導致問題出現的具體設置： (何設置？)
  - [ ] 這是個新 Bug，以前真的沒有
  - [ ] 我對原因有一些猜想： (你的寳貴想法)
  - [ ] 在 Issues（包括已關閉的 Issue） 中未找到相關的報告

**Comment by ksqsf** [comment]
duplicate #827 #741 

上游问题

**Comment by lifei** [comment]
> duplicate [#827](https://github.com/rime/squirrel/issues/827) [#741](https://github.com/rime/squirrel/issues/741)
> 
> 上游问题


Tabby这个终端App，不是Rust写的，也不能输入中文标点，大概率就不是Rust的问题。

**Comment by lifei** [comment]
https://github.com/fcitx/fcitx5-macos/pull/348

**Comment by ksqsf** [comment]
> > duplicate [#827](https://github.com/rime/squirrel/issues/827) [#741](https://github.com/rime/squirrel/issues/741)
> > 上游问题
> 
> Tabby这个终端App，不是Rust写的，也不能输入中文标点，大概率就不是Rust的问题。

1. Upstream != Rust. 
2. Same behavior != same cause.
